/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFlashDiario.java
 *
 * Created on 25-mar-2014, 16:29:54
 */
package com.comerzzia.jpos.gui.flashventas;

import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.components.form.JTextFieldForm;
import com.comerzzia.jpos.gui.validation.IValidableForm;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorFecha;
import com.comerzzia.jpos.gui.validation.ValidadorHora;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.persistencia.flashventas.FlashVentasBean;
import com.comerzzia.jpos.servicios.flashventas.FlashVentasService;
import com.comerzzia.jpos.servicios.tickets.TicketException;
import es.mpsistemas.util.fechas.Fecha;
import es.mpsistemas.util.log.Logger;
import es.mpsistemas.util.numeros.Numero;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author SMLM
 */
public class JFlashDiario extends JVentanaDialogo implements IVista, IViewerValidationFormError {
    
    List<IValidableForm> formulario;
    private static Logger log = Logger.getMLogger(JFlashDiario.class);
    private JPrincipal ventana_padre = null; 

    /** Creates new form JFlashVendedor */
    public JFlashDiario() {
        super();
        try{
            formulario = new LinkedList<IValidableForm>();  
            initComponents();
            crearFormulario();
            registraEventoEnterBoton();
            
        } catch (Exception ex){           
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l_ventas = new javax.swing.JLabel();
        l_descuento = new javax.swing.JLabel();
        t_fecha = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_horaHasta = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_horaDesde = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_error = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l_nroClientes = new javax.swing.JLabel();
        l_nroFacturas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b_aceptar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setDisplayedMnemonic('F');
        jLabel2.setLabelFor(t_fecha);
        jLabel2.setText("Fecha:");

        jLabel3.setDisplayedMnemonic('D');
        jLabel3.setLabelFor(t_horaDesde);
        jLabel3.setText("Hora Desde:");

        jLabel4.setDisplayedMnemonic('H');
        jLabel4.setLabelFor(t_horaHasta);
        jLabel4.setText("Hora Hasta:");

        jLabel5.setText("Ventas:");

        jLabel6.setText("Descuento Promedio:");

        l_ventas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        l_descuento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        t_fecha.setNextFocusableComponent(t_horaDesde);
        t_fecha.setPreferredSize(new java.awt.Dimension(8, 27));
        t_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_fechaKeyTyped(evt);
            }
        });

        t_horaHasta.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_horaHasta.setNextFocusableComponent(b_aceptar);
        t_horaHasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_horaHastaKeyTyped(evt);
            }
        });

        t_horaDesde.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_horaDesde.setNextFocusableComponent(t_horaHasta);
        t_horaDesde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_horaDesdeKeyTyped(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(-3407872,true));

        jLabel7.setText("Nro Clientes:");

        l_nroClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        l_nroFacturas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel8.setText("Nro Facturas:");

        b_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_aceptar.setMnemonic('a');
        b_aceptar.setText("Aceptar");
        b_aceptar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_aceptar.setNextFocusableComponent(b_cancelar);
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_cancelar.setNextFocusableComponent(t_fecha);
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("FLASH DE VENTAS DIARIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(t_horaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t_horaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(l_descuento, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(l_nroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_nroFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(l_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_horaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(t_horaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(l_descuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(l_nroClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(l_nroFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_fechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_fechaKeyTyped
        accionIntro(evt);
    }//GEN-LAST:event_t_fechaKeyTyped

    private void t_horaDesdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_horaDesdeKeyTyped
        accionIntro(evt);
    }//GEN-LAST:event_t_horaDesdeKeyTyped

    private void t_horaHastaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_horaHastaKeyTyped
        accionIntro(evt);
    }//GEN-LAST:event_t_horaHastaKeyTyped

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        limpiarFormulario();        
        cerrarVentana(); 
}//GEN-LAST:event_b_cancelarActionPerformed

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
        accionAceptar();
}//GEN-LAST:event_b_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_aceptar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_descuento;
    private javax.swing.JLabel l_nroClientes;
    private javax.swing.JLabel l_nroFacturas;
    private javax.swing.JLabel l_ventas;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_fecha;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_horaDesde;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_horaHasta;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        try{
            lb_error.setText("");
            validarFormulario();
            String fechaDesde = t_fecha.getText() + " " + t_horaDesde.getText();
            Fecha fecha1 = new Fecha(fechaDesde, "dd-MMM-yyyy HH:mm");
            String fechaHasta = t_fecha.getText() + " " + t_horaHasta.getText();
            Fecha fecha2 = new Fecha(fechaHasta, "dd-MMM-yyyy HH:mm");
            
            if(fecha1.despues(fecha2)){
                lb_error.setText("La hora final no puede ser menor a la hora inicial");
                t_horaHasta.requestFocus();
                return;
            }
            
            FlashVentasBean flashVentas = FlashVentasService.consultarFlashDiario(fecha1, fecha2);
            
            l_ventas.setText("USD "+Numero.formatea(flashVentas.getImporteFinal(),2));
            l_descuento.setText(flashVentas.getDescuento().toString()+" %");
            l_nroClientes.setText(flashVentas.getNumClientes().toString());
            l_nroFacturas.setText(flashVentas.getNumFacturas().toString());
            
            
        } catch (ValidationFormException ex) {
            addError(ex);
        } catch (SQLException ex){   
            log.error("Error lanzando consulta de Flash Diario: " + ex.getMessage(), ex);
            JPrincipal.getInstance().crearError("Ocurrió un error consultando flash de ventas.");
        } catch (Exception ex){   
            log.error("Error lanzando consulta de Flash Diario: " + ex.getMessage(), ex);
            JPrincipal.getInstance().crearError("Ocurrió un error consultando flash de ventas.");
        }
    }

    @Override
    public void limpiarFormulario() {

        for (IValidableForm elem : formulario) {
            elem.setValidacionHabilitada(false);
        }

        for (IValidableForm elem : formulario) {
            elem.setText("");
        }
        
        this.t_fecha.requestFocus();

        for (IValidableForm elem : formulario) {
            elem.setValidacionHabilitada(true);
        }
        
        this.lb_error.setText("");        
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

    @Override
    public void iniciaVista() {
        lb_error.setText("");
        SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd-MMM-yyyy", new Locale("es","ES"));
        l_ventas.setText("");
        l_descuento.setText("");
        l_nroClientes.setText("");
        l_nroFacturas.setText("");  
        t_fecha.setText(formatoDeFecha.format(new Date()));
        t_horaDesde.setText("00:00");
        t_horaHasta.setText("23:59");
        t_fecha.addValidador(new ValidadorFecha(), this);
        t_horaDesde.addValidador(new ValidadorHora(), this);
        t_horaHasta.addValidador(new ValidadorHora(), this);
        t_fecha.addValidador(new ValidadorObligatoriedad(), this);
        t_horaDesde.addValidador(new ValidadorObligatoriedad(), this);
        t_horaHasta.addValidador(new ValidadorObligatoriedad(), this);
        
        t_fecha.requestFocus(true);
    }

    @Override
    public void iniciaFoco() {
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText("<html>"+e.getMessage()+"</html>");
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }
    
    private void accionIntro(KeyEvent ke) {
        if ((t_fecha.hasFocus() || t_horaDesde.hasFocus() || t_horaHasta.hasFocus()) && ke.getKeyChar() == '\n') {
            
            JTextFieldForm focoEn = null;
            
            if (ke.getComponent() instanceof JTextFieldForm){
                focoEn = (JTextFieldForm) ke.getComponent();
            }
            accionAceptar();
            
            focoEn.requestFocus();
        }
    }
    
    private void validarFormulario() throws ValidationFormException {
        for (IValidableForm e : formulario) {
            try {
                e.validar();
            }
            catch (ValidationFormException ex) {
                throw ex;
            }
        }
    }
    
    private void crearFormulario() {
        // Elementos del formulario susceptibles de validarse o resetearse 
        formulario.add(t_fecha);
        formulario.add(t_horaDesde);
        formulario.add(t_horaHasta);
    }
}
