/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.servicios.promociones.cupones.PromocionTipoCuponDescuentoAzar;
import com.comerzzia.util.imagenes.Imagenes;
import es.mpsistemas.util.log.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;

/**
 *
 * @author SMLM
 */
public class JAnimacion extends JVentanaDialogo {

    private static final Logger log = Logger.getMLogger(JAnimacion.class);
    private static URL urlImagenFondo = null;

    private final String nombreGif = "promocioncupon.gif";
    /**
     * Creates new form JAnimacion
     */
    public JAnimacion() {
        super();
        initComponents();
        addFunctionKeys();
        try{
            log.debug("iniciaVista() - Cargando gif de cupón de promociones");
            Imagenes.cambiarImagenArticuloTamanyo(jLabel1, nombreGif,1024, 768);        
            log.debug("iniciaVista() - Pantalla de animación inicializada.");
        }catch (Exception e){
            log.error("Error seteando Imagen de fondo en panel de animación ");
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setMaximumSize(new java.awt.Dimension(1024, 768));
        jLabel1.setMinimumSize(new java.awt.Dimension(1024, 768));
        jLabel1.setPreferredSize(new java.awt.Dimension(1024, 768));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
    
        private void addFunctionKeys() {
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCerrar();
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
        
        KeyStroke enter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        Action listenerenter = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCerrar();
            }
        };
        addHotKey(enter, "IdentCliententer", listenerenter);
         
    }
        
     private void accionCerrar(){
        PromocionTipoCuponDescuentoAzar.haEmitido=false;
        super.cerrarVentana();
     }
}
