/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JBloqueo.java
 *
 * Created on 19-sep-2011, 16:44:20
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.servicios.login.InvalidLoginException;
import com.comerzzia.jpos.servicios.login.LoginException;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.jpos.servicios.core.permisos.SinPermisosException;
import com.comerzzia.util.Contador;
import es.mpsistemas.util.log.Logger;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.KeyStroke;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import java.awt.Dialog.ModalExclusionType;
import java.io.IOException;

/**
 *
 * @author MGRI
 */
public class JBloqueo extends JVentanaDialogo {

    private static final Logger log = Logger.getMLogger(JBloqueo.class);
    private static URL urlImagenFondo = null;
    /** Creates new form JBloqueo */
    public JBloqueo() {
        // que no haga el super() o si en el futuro es necesario sobreescribir la función que hace aparecer este mismo panel
        initComponents();
        try {
                String prefijo = Variables.getVariable(Variables.POS_UI_SKIN); 
                //cggm 19092018 Quita la imagen de la empresa. Se remplaza por nuevos fondos creado por Marketing
//                urlImagenFondo = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_bloqueo.png");
                URL myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
            
                ImageIcon icon = new ImageIcon(myurl);
//                ImageIcon iconFondo = new ImageIcon(urlImagenFondo);
                v_solicitar_identificacion.setIconImage(icon.getImage());
                v_solicitar_identificacion.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
//                jLabel1.setIcon(iconFondo);
                jLabel1.setVisible(false);
            } catch (Exception ex) {
                log.error("Error seteando Imagen de fondo en panel de bloqueo ");
            }
            //URL myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
            
    }

    @Override
    public void registrarEventoBloqueoAplicacion(){
        // No hacer nada
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_solicitar_identificacion = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        l_error1 = new javax.swing.JLabel();
        l_mensaje = new javax.swing.JLabel();
        l_error3 = new javax.swing.JLabel();
        i_error = new javax.swing.JLabel();
        t_usuario = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        l_error2 = new javax.swing.JLabel();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        l_error = new javax.swing.JLabel();
        t_password = new com.comerzzia.jpos.gui.components.form.JPasswordFieldForm();
        jLabel1 = new javax.swing.JLabel();

        v_solicitar_identificacion.setAlwaysOnTop(true);
        v_solicitar_identificacion.setMinimumSize(new java.awt.Dimension(400, 424));
        v_solicitar_identificacion.setModal(true);
        v_solicitar_identificacion.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 320));

        l_error1.setBackground(new java.awt.Color(204, 255, 255));
        l_error1.setFont(new java.awt.Font("Comic Sans MS", 0, 14));
        l_error1.setText("Introduzca Usuario Autorizado :");

        l_mensaje.setBackground(new java.awt.Color(204, 255, 255));
        l_mensaje.setText("No tiene Permisos para realizar la operación");

        l_error3.setBackground(new java.awt.Color(204, 255, 255));
        l_error3.setDisplayedMnemonic('u');
        l_error3.setText("Usuario :");

        i_error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/mensajes/sinPermisos_p.png"))); // NOI18N

        t_usuario.setFont(new java.awt.Font("sansserif", 0, 14));
        t_usuario.setName("user"); // NOI18N
        t_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usuarioActionPerformed(evt);
            }
        });

        l_error2.setBackground(new java.awt.Color(204, 255, 255));
        l_error2.setDisplayedMnemonic('c');
        l_error2.setLabelFor(t_password);
        l_error2.setText("Contraseña :");

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });
        b_ok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b_okKeyPressed(evt);
            }
        });

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });
        b_cancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b_cancelarKeyPressed(evt);
            }
        });

        l_error.setForeground(new java.awt.Color(255, 51, 51));
        l_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_error.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        t_password.setPreferredSize(new java.awt.Dimension(8, 27));
        t_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_passwordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_error2)
                            .addComponent(l_error3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                    .addComponent(l_error1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(i_error, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(l_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(i_error, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(l_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(l_error1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_error3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_error2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_error, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout v_solicitar_identificacionLayout = new javax.swing.GroupLayout(v_solicitar_identificacion.getContentPane());
        v_solicitar_identificacion.getContentPane().setLayout(v_solicitar_identificacionLayout);
        v_solicitar_identificacionLayout.setHorizontalGroup(
            v_solicitar_identificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_solicitar_identificacionLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        v_solicitar_identificacionLayout.setVerticalGroup(
            v_solicitar_identificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_solicitar_identificacionLayout.createSequentialGroup()
                .addGap(0, 98, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel1)
                .addContainerGap(802, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(617, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(151, 151, 151))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usuarioActionPerformed
        b_okActionPerformed(evt);
}//GEN-LAST:event_t_usuarioActionPerformed

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        
        try {
            l_error.setText("");
            Sesion.desbloqueaOperacion(t_usuario.getText(), t_password.getText());            
            Contador.setBloqueado(false);
            v_solicitar_identificacion.setVisible(false);
            this.getContenedor().setVisible(false);
            t_usuario.setText("");
            t_password.setText("");
            
        }catch(NullPointerException ex){
            log.warn("Nulpointer en identificación para desbloqueo de la aplicación");
        }catch (InvalidLoginException ex) {
            log.debug("Login invalido para el desbloqueo de la aplicación");
            l_error.setText("Autenticación no valida");
        } catch (LoginException ex) {
            log.error("Error al realizar el login para desbloquear la aplicación: "+ ex.getMessage(), ex);
            l_error.setText("No se pudo realizar la autenticación");
        } catch (SinPermisosException ex) {
            log.debug("El usuario no tiene permisos para desbloquear la aplicación");
            l_error.setText("<html>El usuario logueado no tiene permisos <P>para realizar la operación</html>");
        }
    }//GEN-LAST:event_b_okActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.listenerList = null;
        l_error.setText("");
        t_usuario.setText("");
        t_password.setText("");        
        v_solicitar_identificacion.setVisible(false);
}//GEN-LAST:event_b_cancelarActionPerformed

    private void t_passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_passwordKeyTyped
        if (evt.getKeyChar() == '\n')
            b_okActionPerformed(null);
    }//GEN-LAST:event_t_passwordKeyTyped

private void b_okKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_okKeyPressed
    if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        b_okActionPerformed(null);
}//GEN-LAST:event_b_okKeyPressed

private void b_cancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b_cancelarKeyPressed
    if (evt.getKeyChar() == '\n')
        b_cancelarActionPerformed(null);
}//GEN-LAST:event_b_cancelarKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyStroke.getKeyStroke(KeyEvent.VK_F4, InputEvent.ALT_DOWN_MASK).getKeyCode()){
            log.debug("Se previene el evento ALT+F4 en la pantalla de bloqueo"); 
             // No hacemos nada ante un ALT+F4
        }
    }//GEN-LAST:event_formKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel i_error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_error;
    private javax.swing.JLabel l_error1;
    private javax.swing.JLabel l_error2;
    private javax.swing.JLabel l_error3;
    private javax.swing.JLabel l_mensaje;
    private com.comerzzia.jpos.gui.components.form.JPasswordFieldForm t_password;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_usuario;
    private javax.swing.JDialog v_solicitar_identificacion;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        
    }
    
    @Override
    public void accionCancelar() {
            JPrincipal.getInstance().mostrarPantallaDesbloqueo(this.getContenedor());
        //v_solicitar_identificacion.setLocationRelativeTo(null);
        //v_solicitar_identificacion.setVisible(true);
    }

    @Override
    public void limpiarFormulario() {
        
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
}
