/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JArticulos.java
 *
 * Created on 07-jul-2011, 9:33:44
 */
package com.comerzzia.jpos.gui;

//import com.comerzzia.jpos.entity.Articulos;
import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.gui.components.form.JTextFieldForm;
import com.comerzzia.jpos.gui.devoluciones.JDevolucionVentas;
import com.comerzzia.jpos.gui.modelos.NoEditableTableModel;
import com.comerzzia.jpos.gui.reservaciones.JReservacionesVentas;
import com.comerzzia.jpos.servicios.articulos.ArticulosServices;
import com.comerzzia.jpos.servicios.articulos.ArticuloNotFoundException;
import com.comerzzia.jpos.servicios.articulos.ArticuloLimitExceededException;
import com.comerzzia.jpos.servicios.articulos.ArticulosParamBuscar;
import com.comerzzia.jpos.servicios.core.permisos.Operaciones;
import com.comerzzia.jpos.servicios.logs.logsacceso.ServicioLogAcceso;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.util.swing.acciones.Acciones;
import java.awt.Color;
import es.mpsistemas.util.log.Logger;
import java.awt.Dialog;
import java.awt.Dialog.ModalExclusionType;
import java.awt.Dialog.ModalityType;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.net.URL;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author MGRI
 */
public class JBuscar extends JPanelImagenFondo implements IVista, KeyListener {

    private static final Logger log = Logger.getMLogger(JBuscar.class);
    public IVista ventana_padre = null;
    private JDialog contenedor = null;
    ArticulosServices as = ArticulosServices.getInstance();
    Vector header; //Cabecera fija de la tabla de articulos
    Vector articulos = null;
    JTextFieldForm focoEn = null;
    //List<Articulos> lstart; 

    /**
     * Creates new form JArticulos
     */
    public JBuscar() {
        super();
        initComponents();
    }

    public JBuscar(JLogin ventana_padre) {
        super();
        this.ventana_padre = ventana_padre;
        //iniciamos los componentes
        initComponents();
        iniciaVentanas();
        inicializaEventoDeFoco();
        //iniciaVista();
        Set<KeyStroke> strokes = new HashSet<KeyStroke>(Arrays.asList(KeyStroke.getKeyStroke("pressed TAB")));
        tb_listaArticulos.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, strokes);
        strokes = new HashSet<KeyStroke>(Arrays.asList(KeyStroke.getKeyStroke("shift pressed TAB")));
        tb_listaArticulos.setFocusTraversalKeys(KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS, strokes);

    }

    public void liberarMemoria() {
        inicia();
        articulos = null;
    }

    public JBuscar(IVista ventana_padre) {
        super();
        this.ventana_padre = ventana_padre;
        //iniciamos los componentes
        initComponents();
        iniciaVentanas();
        inicializaEventoDeFoco();

    }

    private void inicia() {
        tb_listaArticulos.scrollRectToVisible(tb_listaArticulos.getCellRect(0, 0, true));
        
        Vector listaarticulos = new Vector(new Vector());
        header = new Vector();
        header.add("CÓDIGO"); //0
        header.add("DESCRIPCIÓN"); //1
        header.add("MARCA"); //2
        header.add("CÓDIGO BARRAS"); //3
        header.add("PVP"); //4
        header.add("DESCONT"); //5
        header.add("EXISTENCIAS"); //6
        header.add("S.L"); //7
        header.add("G.O."); //8
        header.add("G.E."); //9
        header.add("SECCIÓN"); //10
        header.add("SUBSECCIÓN"); //11
        header.add("S.CD"); //12    
        header.add("MODELO"); //13    
        header.add("U. MANEJO"); //13    

        NoEditableTableModel tableModel = new NoEditableTableModel(listaarticulos, header);
        tb_listaArticulos.setModel(tableModel);

        refrescaTabla();

        t_descripcion.addKeyListener(this);
        t_marca.addKeyListener(this);
        t_modelo.addKeyListener(this);
        t_codigo_bar.addKeyListener(this);
        addFunctionKeys();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_consulta_stock = new javax.swing.JDialog();
        p_consulta_stock = new com.comerzzia.jpos.gui.stock.JStock();
        v_editar_cantidad = new javax.swing.JDialog();
        p_editar_cantidad = new com.comerzzia.jpos.gui.devoluciones.JIntroducirCantidad();
        v_consulta_promocion = new javax.swing.JDialog();
        p_consulta_promocion = new com.comerzzia.jpos.gui.promocion.JPromocion();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_listaArticulos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_descripcion = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_marca = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_modelo = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_codigo_bar = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t_codigo_art = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_seccion = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_subseccion = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel9 = new javax.swing.JLabel();
        b_aceptar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        v_consulta_stock.setAlwaysOnTop(true);
        v_consulta_stock.setMinimumSize(new java.awt.Dimension(678, 397));
        v_consulta_stock.setModal(true);
        v_consulta_stock.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        javax.swing.GroupLayout v_consulta_stockLayout = new javax.swing.GroupLayout(v_consulta_stock.getContentPane());
        v_consulta_stock.getContentPane().setLayout(v_consulta_stockLayout);
        v_consulta_stockLayout.setHorizontalGroup(
            v_consulta_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(v_consulta_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(v_consulta_stockLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p_consulta_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        v_consulta_stockLayout.setVerticalGroup(
            v_consulta_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(v_consulta_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(v_consulta_stockLayout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(p_consulta_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        v_editar_cantidad.setAlwaysOnTop(true);
        v_editar_cantidad.setMinimumSize(new java.awt.Dimension(445, 215));

        javax.swing.GroupLayout v_editar_cantidadLayout = new javax.swing.GroupLayout(v_editar_cantidad.getContentPane());
        v_editar_cantidad.getContentPane().setLayout(v_editar_cantidadLayout);
        v_editar_cantidadLayout.setHorizontalGroup(
            v_editar_cantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_editar_cantidadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_editar_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        v_editar_cantidadLayout.setVerticalGroup(
            v_editar_cantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_editar_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        v_consulta_promocion.setAlwaysOnTop(true);
        v_consulta_promocion.setMinimumSize(new java.awt.Dimension(678, 397));
        v_consulta_promocion.setModal(true);

        javax.swing.GroupLayout v_consulta_promocionLayout = new javax.swing.GroupLayout(v_consulta_promocion.getContentPane());
        v_consulta_promocion.getContentPane().setLayout(v_consulta_promocionLayout);
        v_consulta_promocionLayout.setHorizontalGroup(
            v_consulta_promocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_consulta_promocionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_consulta_promocion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        v_consulta_promocionLayout.setVerticalGroup(
            v_consulta_promocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_consulta_promocionLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(p_consulta_promocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setMaximumSize(new java.awt.Dimension(1010, 630));
        setMinimumSize(new java.awt.Dimension(1010, 630));
        setPreferredSize(new java.awt.Dimension(1010, 520));
        setRepintarImagenFondo(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Búsqueda de Artículos");
        jLabel1.setFocusable(false);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 380, -1));

        tb_listaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_listaArticulos.setNextFocusableComponent(t_codigo_art);
        tb_listaArticulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_listaArticulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_listaArticulosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_listaArticulos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 960, 310));

        jLabel2.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("atajosTeclado").getString("tpv.busquedaArticulos.descripcion").charAt(0));
        jLabel2.setLabelFor(t_descripcion);
        jLabel2.setText("Descripción");

        jLabel4.setDisplayedMnemonic(java.util.ResourceBundle.getBundle("atajosTeclado").getString("tpv.busquedaArticulos.marca").charAt(0));
        jLabel4.setLabelFor(t_marca);
        jLabel4.setText("Marca");

        t_descripcion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_descripcion.setNextFocusableComponent(t_seccion);
        t_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_descripcionKeyTyped(evt);
            }
        });

        t_marca.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_marca.setNextFocusableComponent(t_descripcion);
        t_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_marcaKeyTyped(evt);
            }
        });

        t_modelo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_modelo.setNextFocusableComponent(t_codigo_bar);
        t_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_modeloActionPerformed(evt);
            }
        });
        t_modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_modeloKeyTyped(evt);
            }
        });

        t_codigo_bar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_codigo_bar.setNextFocusableComponent(t_marca);
        t_codigo_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_codigo_barKeyTyped(evt);
            }
        });

        jLabel5.setDisplayedMnemonic('b');
        jLabel5.setLabelFor(t_codigo_bar);
        jLabel5.setText("Código Barras");

        jLabel6.setDisplayedMnemonic('r');
        jLabel6.setLabelFor(t_modelo);
        jLabel6.setText("Modelo/referencia");

        t_codigo_art.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_codigo_art.setNextFocusableComponent(t_modelo);
        t_codigo_art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_codigo_artActionPerformed(evt);
            }
        });
        t_codigo_art.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_codigo_artKeyTyped(evt);
            }
        });

        jLabel7.setDisplayedMnemonic('i');
        jLabel7.setLabelFor(t_codigo_art);
        jLabel7.setText("Código Interno");

        jLabel8.setDisplayedMnemonic('s');
        jLabel8.setLabelFor(t_seccion);
        jLabel8.setText("Sección");

        t_seccion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_seccion.setNextFocusableComponent(t_subseccion);
        t_seccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_seccionKeyTyped(evt);
            }
        });

        t_subseccion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        t_subseccion.setNextFocusableComponent(t_codigo_art);
        t_subseccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_subseccionKeyTyped(evt);
            }
        });

        jLabel9.setDisplayedMnemonic('u');
        jLabel9.setLabelFor(t_subseccion);
        jLabel9.setText("SubSección");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_codigo_art, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_codigo_bar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_subseccion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(t_codigo_art, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_codigo_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t_seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t_subseccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 850, 170));

        b_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_aceptar.setMnemonic(java.util.ResourceBundle.getBundle("atajosTeclado").getString("tpv.busquedaArticulos.aceptar").charAt(0));
        b_aceptar.setText("Aceptar");
        b_aceptar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });
        add(b_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, -1, -1));

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });
        add(b_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
    this.getContenedor().setVisible(false);
    try{
        if (ventana_padre instanceof IBusquedasArticulos) {
            String codigo = "";
            int fila = tb_listaArticulos.getSelectedRow();
            if (fila >= 0 && tb_listaArticulos.getModel().getRowCount() > 0) {
                    codigo = (String) tb_listaArticulos.getModel().getValueAt(fila, 3);
            }
            ServicioLogAcceso.crearAccesoLogBusquedaArticulo(codigo);
            ((IBusquedasArticulos) ventana_padre).setCodigoArticulo(codigo);
        }
        else if (ventana_padre instanceof JLogin) {
        }
    } catch (ArrayIndexOutOfBoundsException e) {
        // Ha presionado aceptar sin seleccionar un artículo
    }
}//GEN-LAST:event_b_aceptarActionPerformed

private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
    // Cerramos el Jdialog
    this.getContenedor().setVisible(false);
}//GEN-LAST:event_b_cancelarActionPerformed

private void t_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_modeloActionPerformed
}//GEN-LAST:event_t_modeloActionPerformed

private void tb_listaArticulosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_listaArticulosKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        b_aceptarActionPerformed(null);
    }
    else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
        t_codigo_art.requestFocus();
    }
}//GEN-LAST:event_tb_listaArticulosKeyPressed

private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
}//GEN-LAST:event_formFocusGained

private void t_descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_descripcionKeyTyped
    if (evt.getKeyChar() == '\n') {
        guardaFoco(evt);
        buscar();
    }
}//GEN-LAST:event_t_descripcionKeyTyped

private void t_modeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_modeloKeyTyped
    if (evt.getKeyChar() == '\n') {
        guardaFoco(evt);
        buscar();
    }
}//GEN-LAST:event_t_modeloKeyTyped

private void t_codigo_barKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_codigo_barKeyTyped
    if (evt.getKeyChar() == '\n') {
        guardaFoco(evt);
        buscar();
    }
}//GEN-LAST:event_t_codigo_barKeyTyped

private void t_marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_marcaKeyTyped
    if (evt.getKeyChar() == '\n') {
        guardaFoco(evt);
        buscar();
    }
}//GEN-LAST:event_t_marcaKeyTyped

    private void t_codigo_artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_codigo_artActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_codigo_artActionPerformed

    private void t_codigo_artKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_codigo_artKeyTyped
        if (evt.getKeyChar() == '\n') {
            guardaFoco(evt);
            buscar();
        }
    }//GEN-LAST:event_t_codigo_artKeyTyped

    private void t_seccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_seccionKeyTyped
        if (evt.getKeyChar() == '\n') {
            guardaFoco(evt);
            buscar();
        }
    }//GEN-LAST:event_t_seccionKeyTyped

    private void t_subseccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_subseccionKeyTyped
        if (evt.getKeyChar() == '\n') {
            guardaFoco(evt);
            buscar();
        }
    }//GEN-LAST:event_t_subseccionKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_aceptar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.comerzzia.jpos.gui.promocion.JPromocion p_consulta_promocion;
    private com.comerzzia.jpos.gui.stock.JStock p_consulta_stock;
    private com.comerzzia.jpos.gui.devoluciones.JIntroducirCantidad p_editar_cantidad;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_codigo_art;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_codigo_bar;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_descripcion;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_marca;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_modelo;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_seccion;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_subseccion;
    private javax.swing.JTable tb_listaArticulos;
    private javax.swing.JDialog v_consulta_promocion;
    private javax.swing.JDialog v_consulta_stock;
    private javax.swing.JDialog v_editar_cantidad;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciaVista() {
        inicia();
        t_descripcion.setText("");
        t_marca.setText("");
        t_modelo.setText("");
        t_codigo_bar.setText("");
        t_codigo_art.setText("");
        t_seccion.setText("");
        t_subseccion.setText("");
        t_codigo_art.requestFocus();
    }

    public void iniciaVista(String codigoArticulo) {
        inicia();
        t_descripcion.setText("");
        t_marca.setText("");
        t_codigo_bar.setText("");
        t_descripcion.setBackground(Color.WHITE);        
        t_seccion.setText("");
        t_subseccion.setText("");
        t_modelo.setText("");
        t_codigo_art.setText(codigoArticulo);
        buscar();
    }

    public void establecerFoco() {
        if (articulos != null && !articulos.isEmpty() && articulos.size() > 0 && !t_modelo.getText().isEmpty()) {
            log.debug("foco establecido en la tabla");
            tb_listaArticulos.requestFocus();
            t_modelo.setBackground(Color.WHITE);
            t_descripcion.setBackground(Color.WHITE);
        }
        else if (focoEn != null) {
            t_codigo_art.requestFocus();
        }
        else {
            log.debug("foco establecido en código de artículo");
            t_codigo_art.requestFocus();
        }
    }

    @Override
    public void keyTyped(KeyEvent ke) {
    }

    private void buscar() {
        try {            
            // Preparamos la clase para buscar
            ArticulosParamBuscar parametrosBuscar = new ArticulosParamBuscar();
            parametrosBuscar.setDescripcion(t_descripcion.getText().trim());
            parametrosBuscar.setProveedor("");
            parametrosBuscar.setMarca(t_marca.getText().trim());
            parametrosBuscar.setCodigo(t_codigo_art.getText().trim());
            parametrosBuscar.setCodigoBarras(t_codigo_bar.getText().trim());
            parametrosBuscar.setSeccion(t_seccion.getText().trim());
            parametrosBuscar.setSubseccion(t_subseccion.getText().trim());
            parametrosBuscar.setModelo(t_modelo.getText().trim());
            
            if(parametrosBuscar.isFiltroVacio()) {
                crearAdvertencia("No se han indicado filtros de búsqueda");
                return;
            }
            
            // Para el código de sukasa había un tratamiento especial que ya no se va a usar
            //Cadena.completaconCeros(codigos[0], 4) + "." + Cadena.completaconCeros(codigos[1], 4);
            
            articulos = as.getArticulosAsVector(parametrosBuscar, Variables.getVariable(Variables.POS_CONFIG_MAXIMOS_RESULTADOS_ARTICULOS));
            if (articulos.isEmpty()) {
                crearAdvertencia("No se han encontrado artículos con los filtros indicados.");
                return;
            }
            NoEditableTableModel tableModel = new NoEditableTableModel(articulos, header);
            tb_listaArticulos.setModel(tableModel);

            refrescaTabla();
            
            JTableHeader header1 = tb_listaArticulos.getTableHeader();
            header1.updateUI();
            header1.addMouseListener(tableModel.new ColumnListener(tb_listaArticulos));
            header1.setReorderingAllowed(true);
            tb_listaArticulos.requestFocus();
                if (tb_listaArticulos.getRowCount() >= 0) {
                    ListSelectionModel selectionModel = tb_listaArticulos.getSelectionModel();
                    selectionModel.setSelectionInterval(0, 0);
                    tb_listaArticulos.requestFocus();
                }
                else {
                    if (focoEn != null) {
                        focoEn.requestFocus();
                    }
                }
            }
        catch (ArticuloLimitExceededException ex) {
            articulos = new Vector();
            log.debug("Limite de artículos en consulta superado");
            crearAdvertencia(" Se ha superado el limite de " + Variables.getVariable(Variables.POS_CONFIG_MAXIMOS_RESULTADOS_ARTICULOS) + " resultados.  Por favor precise la búsqueda ");
            if (focoEn != null) {
                focoEn.requestFocus();
            }
        }
        catch (ArticuloNotFoundException e) {
            crearAdvertencia(e.getMessage());
            if (focoEn != null) {
                focoEn.requestFocus();
            }
        }
        catch (Exception ex) {
            log.debug("Error consultando Artículos", ex);
            crearAdvertencia("Error consultando Artículos");
            if (focoEn != null) {
                focoEn.requestFocus();
            }
        }
    }

    private void crearAdvertencia(String msg) {
        if (ventana_padre instanceof JVentas) {
            ((JVentas) ventana_padre).ventana_padre.crearAdvertencia(msg);
        }
        else if (ventana_padre instanceof JReservacionesVentas) {
            ((JReservacionesVentas) ventana_padre).getVentanaPadre().crearAdvertencia(msg);
        }
        else if (ventana_padre instanceof JLogin) {
            ((JLogin) ventana_padre).ventana_padre.crearAdvertencia(msg);
        }
        else if (ventana_padre instanceof JDevolucionVentas) {
            ((JDevolucionVentas) ventana_padre).getVentana_padre().crearAdvertencia(msg);
        }
        else  {
            JPrincipal.getInstance().crearAdvertencia(msg);
        }
    }

    @Override
    public void keyPressed(KeyEvent ke) {
    }

    @Override
    public void keyReleased(KeyEvent ke) {
    }

    @Override
    protected void addHotKey(KeyStroke keyStroke, String inputActionKey, Action listener) {
        ActionMap actionMap = this.getActionMap();
        InputMap inputMap = this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(keyStroke, inputActionKey);
        actionMap.put(inputActionKey, listener);
    }

    private void addFunctionKeys() {
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_cancelarActionPerformed(ae);
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);

        KeyStroke altmast = KeyStroke.getKeyStroke(KeyEvent.VK_T, KeyEvent.VK_ALT);
        Action listeneraltmast = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                tb_listaArticulos.setColumnSelectionInterval(0, 0);
                tb_listaArticulos.setRowSelectionInterval(0, 0);
                tb_listaArticulos.requestFocus();
            }
        };
        addHotKey(altmast, "IdentClientaltmast", listeneraltmast);

        KeyStroke alt1 = KeyStroke.getKeyStroke(KeyEvent.VK_1, KeyEvent.ALT_DOWN_MASK);
        KeyStroke alt2 = KeyStroke.getKeyStroke(KeyEvent.VK_2, KeyEvent.ALT_DOWN_MASK);
        KeyStroke alt3 = KeyStroke.getKeyStroke(KeyEvent.VK_3, KeyEvent.ALT_DOWN_MASK);
        KeyStroke alt4 = KeyStroke.getKeyStroke(KeyEvent.VK_4, KeyEvent.ALT_DOWN_MASK);
        KeyStroke alt5 = KeyStroke.getKeyStroke(KeyEvent.VK_5, KeyEvent.ALT_DOWN_MASK);
        KeyStroke alt6 = KeyStroke.getKeyStroke(KeyEvent.VK_6, KeyEvent.ALT_DOWN_MASK);
        KeyStroke ctrlS = KeyStroke.getKeyStroke(KeyEvent.VK_S, KeyEvent.CTRL_DOWN_MASK);
        KeyStroke ctrlP = KeyStroke.getKeyStroke(KeyEvent.VK_P, KeyEvent.CTRL_DOWN_MASK);
        KeyStroke ctrlM = KeyStroke.getKeyStroke(KeyEvent.VK_M, KeyEvent.CTRL_DOWN_MASK);

        Action listenerAlt1 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                ((NoEditableTableModel) tb_listaArticulos.getModel()).ordenarColumna(0, tb_listaArticulos);
            }
        };
        Action listenerAlt2 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                ((NoEditableTableModel) tb_listaArticulos.getModel()).ordenarColumna(1, tb_listaArticulos);
            }
        };
        Action listenerAlt3 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                ((NoEditableTableModel) tb_listaArticulos.getModel()).ordenarColumna(2, tb_listaArticulos);
            }
        };
        Action listenerAlt4 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                ((NoEditableTableModel) tb_listaArticulos.getModel()).ordenarColumna(3, tb_listaArticulos);
            }
        };
        Action listenerAlt5 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                ((NoEditableTableModel) tb_listaArticulos.getModel()).ordenarColumna(4, tb_listaArticulos);
            }
        };
        Action listenerAlt6 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                ((NoEditableTableModel) tb_listaArticulos.getModel()).ordenarColumna(5, tb_listaArticulos);
            }
        };

        Action listenerCtrlS = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                JBuscar.this.accionAbrirVentanaStock();
            }
        };
        
        Action listenerCtrlP = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                JBuscar.this.accionAbrirVentanaCantidad();
            }
        };
        
         Action listenerCtrlM = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                JBuscar.this.accionAbrirVentanaPromocion();
            }
        };

        addHotKey(alt1, "OrdenarAlt1", listenerAlt1);
        addHotKey(alt2, "OrdenarAlt2", listenerAlt2);
        addHotKey(alt3, "OrdenarAlt3", listenerAlt3);
        addHotKey(alt4, "OrdenarAlt4", listenerAlt4);
        addHotKey(alt5, "OrdenarAlt5", listenerAlt5);
        addHotKey(alt6, "OrdenarAlt6", listenerAlt6);
        addHotKey(ctrlS, "OrdenarCtrlS", listenerCtrlS);
        addHotKey(ctrlP, "OrdenarCtrlP", listenerCtrlP);
        addHotKey(ctrlM, "OrdenarCtrlM", listenerCtrlM);

        // Acción de acceso a Tabla
        Acciones.crearAccionFocoTabla(this, tb_listaArticulos);
    }

    public IVista getVentana_padre() {
        return ventana_padre;
    }

    public void setVentana_padre(JLogin ventana_padre) {
        this.ventana_padre = ventana_padre;
    }

    public void setVentana_padre(IVista ventana_padre) {
        this.ventana_padre = ventana_padre;
    }

    public JDialog getContenedor() {
        return contenedor;
    }

    public void setContenedor(JDialog contenedor) {
        this.contenedor = contenedor;
    }

    void setVentana_padre(JVentas ventana_padre) {
        this.ventana_padre = ventana_padre;
    }

    private void inicializaEventoDeFoco() {
    }

    @Override
    public void iniciaFoco() {
        log.info("Iniciando Foco");
        t_codigo_art.requestFocus();

    }

    private void guardaFoco(KeyEvent evt) {
        if (evt.getComponent() instanceof JTextFieldForm) {
            focoEn = (JTextFieldForm) evt.getComponent();
        }
        else {
            focoEn = null;
        }
    }

    private void refrescaTabla() {
        tb_listaArticulos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tb_listaArticulos.getColumnModel().getColumn(0).setPreferredWidth(80); // 0-Código
        tb_listaArticulos.getColumnModel().getColumn(1).setPreferredWidth(300); // 1-Descripcion
        tb_listaArticulos.getColumnModel().getColumn(2).setPreferredWidth(100); // 2-Marca
        tb_listaArticulos.getColumnModel().getColumn(3).setPreferredWidth(130); // 3-Codigo Barras
        tb_listaArticulos.getColumnModel().getColumn(4).setPreferredWidth(80); // 4-PVP           
        tb_listaArticulos.getColumnModel().getColumn(5).setPreferredWidth(70); // 5-Descontinuado
        tb_listaArticulos.getColumnModel().getColumn(6).setPreferredWidth(60); // 6-Existencia
        tb_listaArticulos.getColumnModel().getColumn(7).setPreferredWidth(55); // 7-Stock Local
        tb_listaArticulos.getColumnModel().getColumn(8).setPreferredWidth(35); // 8-Garantia
        tb_listaArticulos.getColumnModel().getColumn(9).setPreferredWidth(35); // 9-Garantia Extendida
        tb_listaArticulos.getColumnModel().getColumn(10).setPreferredWidth(95); // 10-Seccion
        tb_listaArticulos.getColumnModel().getColumn(11).setPreferredWidth(95); // 11-Subseccion
        tb_listaArticulos.getColumnModel().getColumn(12).setPreferredWidth(60); // 12-Stock CD
        tb_listaArticulos.getColumnModel().getColumn(13).setPreferredWidth(150); // 13-Modelo
        tb_listaArticulos.getColumnModel().getColumn(14).setPreferredWidth(70); // 14-Unidad de manejo      
    }

    private void iniciaVentanas() {

        articulos = null;

        // Imagen para als ventanas
        URL myurl;
        myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
        ImageIcon icon = new ImageIcon(myurl);

        // Búsqueda de Stocks
        v_consulta_stock.setLocationRelativeTo(null);
        v_consulta_stock.setIconImage(icon.getImage());
        p_consulta_stock.setContenedor(v_consulta_stock);
        p_consulta_stock.setVentana_padre(JPrincipal.getInstance());
        
        // Insertar cantidad
        v_editar_cantidad.setLocationRelativeTo(null);
        v_editar_cantidad.setIconImage(icon.getImage());
        p_editar_cantidad.setContenedor(v_editar_cantidad);
        p_editar_cantidad.setVentana_padre(JPrincipal.getInstance());
        
          // Búsqueda de Stocks
        v_consulta_promocion.setLocationRelativeTo(null);
        v_consulta_promocion.setIconImage(icon.getImage());
        p_consulta_promocion.setContenedor(v_consulta_promocion);
        p_consulta_promocion.setVentana_padre(JPrincipal.getInstance());
          
    }

    private void accionAbrirVentanaStock() {

        if (Variables.getVariableAsBoolean(Variables.FUNCIONALIDAD_CONSULTA_STOCK) || Variables.getVariableAsBoolean(Variables.FUNCIONALIDAD_KARDEX_POS)) {
            // Si hay un elemento                
            if (articulos != null && tb_listaArticulos.getRowCount() > 0) {
                // Si hay solo un elemento, abro este elemento
                if (articulos.size() == 1) {
                    p_consulta_stock.setArticuloBuscado((Vector) articulos.get(0));
                    p_consulta_stock.iniciaVista();
                    v_consulta_stock.setModalityType(ModalityType.TOOLKIT_MODAL);
                    v_consulta_stock.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
                    v_consulta_stock.setVisible(true);
                }
                else {
                    // Si hay mas abro el seleccionado si hay seleccionado
                    int linea = tb_listaArticulos.getSelectedRow();
                    p_consulta_stock.setArticuloBuscado((Vector) articulos.get(linea));
                    p_consulta_stock.iniciaVista();   
                    v_consulta_stock.setModalityType(ModalityType.TOOLKIT_MODAL);
                    v_consulta_stock.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);                    
                    v_consulta_stock.setVisible(true);
                }
            }
        }
    }
    
    private void accionAbrirVentanaPromocion() {
        // Si hay un elemento                
        if (articulos != null && tb_listaArticulos.getRowCount() > 0) {
            // Si hay solo un elemento, abro este elemento
            if (articulos.size() == 1) {
                p_consulta_promocion.setArticuloBuscado((Vector) articulos.get(0));
                p_consulta_promocion.iniciaVista();
                v_consulta_promocion.setModalityType(ModalityType.TOOLKIT_MODAL);
                v_consulta_promocion.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
                v_consulta_promocion.setVisible(true);
            }
            else {
                // Si hay mas abro el seleccionado si hay seleccionado
                int linea = tb_listaArticulos.getSelectedRow();
                p_consulta_promocion.setArticuloBuscado((Vector) articulos.get(linea));
                p_consulta_promocion.iniciaVista();   
                v_consulta_promocion.setModalityType(ModalityType.TOOLKIT_MODAL);
                v_consulta_promocion.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);                    
                v_consulta_promocion.setVisible(true);
            }
        }
    }
    private void accionAbrirVentanaCantidad() {
        
        //Controlamos que no se abra la pantalla desde la ventana de login y comprobamos los permisos
        if (Sesion.permisos != null && Sesion.permisos.isPuede(Operaciones.PERMITE_FACTURAR) && ventana_padre instanceof JVentas) {
            log.debug("El usuario tiene permisos para ejecutar la acción");
            
            if (tb_listaArticulos.getRowCount() > 0) { //Comprobamos que se haya seleccionado algún artículo
                
                //TODO: Controlar cuando se cancela la ventana
                
                v_editar_cantidad.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
                v_editar_cantidad.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);  
                p_editar_cantidad.iniciaFoco();
                v_editar_cantidad.setVisible(true);  

                int nuevaCantidad = p_editar_cantidad.getCantidad();
                
                if(nuevaCantidad > 0){
                    String codigo = "";
                    int fila = tb_listaArticulos.getSelectedRow();
                    if (fila >= 0 && tb_listaArticulos.getModel().getRowCount() > 0) {
                            codigo = (String) tb_listaArticulos.getModel().getValueAt(fila, 3);
                    }
                    ((JVentas) ventana_padre).setCantidadArticulo(nuevaCantidad);
                    ((JVentas) ventana_padre).setFacturarArticulo(Boolean.TRUE);
                    ((IBusquedasArticulos) ventana_padre).setCodigoArticulo(codigo);
                    
                    p_editar_cantidad.setCantidad(0);
                }
            }
        }
        
    }
}
