/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JConfirmacion.java
 *
 * Created on 29-agosto-2011, 10:34:11
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;

/**
 * Clase para tratar los errores de la aplicación. Puede contener la lógica para registrar diferentes actividades que el cliente desee monitorizar
 * @author MGRI
 */
public class JInformacion extends JPanelImagenFondo {

    //Constantes
    public static final int ANCHO_DEFECTO = 650; 
    public static final int ALTO_DEFECTO = 180; 
    private int aumentoAlto;
    
    private JDialog contenedor;
    private String desError;
    private boolean aceptado = false;

    /** Creates new form JConfirmacion */
    public JInformacion() {
        super();
        inicio();
        initComponents();
        addFunctionKeys();
        registraEventoEnterBoton();
    }

    public JInformacion(JDialog contenedor, String desError) {
        super();
        inicio();
        initComponents();
        this.contenedor = contenedor;
        registraEventoEnterBoton();

        if (desError == null || desError.isEmpty()) {
            desError = " Se ha producido un error en la aplicación ";
        }
        
        l_error.setText(desError);
    }

    public void iniciaVista(){
        b_ok.requestFocus();
    }
    
    private void inicio() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        i_error = new javax.swing.JLabel();
        l_error = new com.comerzzia.jpos.gui.components.JMultilineLabel();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        i_error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/mensajes/interrogacion_p.png"))); // NOI18N

        l_error.setBackground(new java.awt.Color(204, 255, 255));
        l_error.setFont(l_error.getFont().deriveFont(l_error.getFont().getSize()+2f));
        l_error.setMaximumSize(null);

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18));
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(i_error, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(l_error, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(i_error)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_error, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
    }//GEN-LAST:event_formKeyTyped

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed

        accionAceptar();
}//GEN-LAST:event_b_okActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        accionCancelar();
}//GEN-LAST:event_b_cancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel i_error;
    private com.comerzzia.jpos.gui.components.JMultilineLabel l_error;
    // End of variables declaration//GEN-END:variables

    public JDialog getContenedor() {
        return contenedor;
    }

    public void setContenedor(JDialog contenedor) {
        this.contenedor = contenedor;
    }

    public String getDesError() {
        return desError;
    }

    /** Establece el mensaje de confirmación
     * 
     * @param desError 
     */
    public void setDesError(String desError,int altoTexto) {
        this.aceptado = false;
        if (desError == null || desError.isEmpty()) {
            desError = " Se ha producido un error en la aplicación ";
        }
       
        this.desError = desError;
        
        //Ajuste de altura
        l_error.setText(desError);
       
    }



    @Override
    protected void addHotKey(KeyStroke keyStroke, String inputActionKey, Action listener) {
        ActionMap actionMap = this.getActionMap();
        InputMap inputMap = this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(keyStroke, inputActionKey);
        actionMap.put(inputActionKey, listener);
    }

    private void addFunctionKeys() {
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
    }

    public boolean isAceptado() {
        return aceptado;
    }

    public void setAceptado(boolean aceptado) {
        this.aceptado = aceptado;
    }

    /** Accion de aceptar
     */
    private void accionAceptar() {
        aceptado = true;
        contenedor.setVisible(false);
    }

    /** Accion de cancelar
     */
    private void accionCancelar() {
        aceptado = false;
        contenedor.setVisible(false);
    }

    public void cambiaTextoBotones(String textoConfirmacion, String textoCancelacion) {
        b_ok.setText(textoConfirmacion);
        b_cancelar.setText(textoCancelacion);
    }
    
    public void ocultarBotones(){
        b_cancelar.setVisible(false);
        b_ok.setVisible(false);
    }
   

    public int getAumentoAlto() {
        return aumentoAlto;
    }

    public void setAumentoAlto(int aumentoAlto) {
        this.aumentoAlto = aumentoAlto;
    }
}
