/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JIngresarValor.java
 *
 * Created on 20-nov-2012, 10:20:47
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.entity.db.Usuarios;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorDecimal;
import com.comerzzia.jpos.gui.validation.ValidadorEntero;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.persistencia.core.usuarios.UsuariosDao;
import es.mpsistemas.util.log.Logger;
import java.math.BigDecimal;
import java.util.logging.Level;

/**
 *
 * @author MGRI
 */
public class JIngresarPromocion extends JVentanaDialogo implements IViewerValidationFormError {

    private static final Logger log = Logger.getMLogger(JIngresarPromocion.class);
    
    public static int TIPO_CADENA = 0; // cadenas
    public static int TIPO_NUMERICO = 1; // enteros
    public static int TIPO_DECIMAL = 2; // decimales mayores a 0 con 2 decimales. Se puede establecer valor máximo
    private static final long serialVersionUID = 1L;
    
    private int tipoValor;
    private String valorS;
    private BigDecimal valor;
    private BigDecimal valorMaximo;
    private Usuarios usuario=new Usuarios();

    /** Creates new form JIngresarValor */
    public JIngresarPromocion() {
        initComponents();
        registraEventoEnterBoton();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        t_valor = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_mensaje = new javax.swing.JLabel();
        lb_error = new javax.swing.JLabel();

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        t_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_valorActionPerformed(evt);
            }
        });
        t_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_valorKeyTyped(evt);
            }
        });

        lb_mensaje.setFont(lb_mensaje.getFont().deriveFont(lb_mensaje.getFont().getStyle() | java.awt.Font.BOLD));
        lb_mensaje.setText("Texto que describe el campo");

        lb_error.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lb_error.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        accionCancelar();
}//GEN-LAST:event_b_cancelarActionPerformed

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed

        accionAceptar();
}//GEN-LAST:event_b_okActionPerformed

    private void t_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_valorActionPerformed
    }//GEN-LAST:event_t_valorActionPerformed

    private void t_valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_valorKeyTyped
        if (evt.getKeyChar() == '\n'){
            accionAceptar();
        }
    }//GEN-LAST:event_t_valorKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel lb_error;
    private javax.swing.JLabel lb_mensaje;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_valor;
    // End of variables declaration//GEN-END:variables

      @Override
  public void accionAceptar() {
      boolean novalidad=false;
        try {
            t_valor.validar();
        } catch (ValidationFormException ex) {
            java.util.logging.Logger.getLogger(JIngresarPromocion.class.getName()).log(Level.SEVERE, null, ex);
            novalidad=true;
        }
        if (!t_valor.getText().isEmpty()) {
            if (getTipoValor() == TIPO_CADENA) {
                valorS = t_valor.getText();
                
//                usuario = UsuariosDao.obtenerUsuarioporNumero(valorS);
                
            } else if (getTipoValor() == TIPO_NUMERICO || getTipoValor() == TIPO_DECIMAL) {
                valor = new BigDecimal(t_valor.getText());
            }
            if (valor != null) {
                if(!novalidad){
                contenedor.setVisible(false);
                }
            } else {
                lb_error.setText("Ingrese un valor");
            }
        } else {
            valor=null;
            lb_error.setText("Debe ingresar un valor");
        }
    }

    @Override
    public void limpiarFormulario() {
        setTipoValor(TIPO_CADENA);
        valor = new BigDecimal(-1);
        valorS = null;
        valorMaximo = null;
        lb_error.setText("");
        t_valor.setText("");
        lb_mensaje.setText("");
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

    public int getTipoValor() {
        return tipoValor;
    }

    public void setTipoValor(int tipoValor) {
        this.tipoValor = tipoValor;
        t_valor.removeValidadores();
        if (tipoValor == TIPO_NUMERICO) {
            t_valor.addValidador(new ValidadorEntero(0, valorMaximo.intValue()), this);
        }
        else if (tipoValor == TIPO_DECIMAL) {
            t_valor.addValidador(new ValidadorDecimal(valorMaximo, BigDecimal.ZERO, 2), this);
        }

    }

    public void setMensaje(String texto) {
        lb_mensaje.setText(texto);
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }

    public void iniciaVista() {
        limpiarFormulario();
    }

    public void iniciaFoco() {
        t_valor.requestFocus();
    }

     public Integer getValor() {
         Integer respuesta=0;
        if(valor!=null){
              respuesta =Integer.parseInt(valor.toString());
        }else{
            respuesta=null;
        }
            return respuesta ;
        
    }

    public void setValorMaximo(BigDecimal valorMaximo) {
        this.valorMaximo = valorMaximo;
    }
    
    
}
