/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JIngresarCodigoOtp.java
 *
 * Created on 12/10/2022, 13:00:47
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.pagos.credito.PagoCredito;
import com.comerzzia.jpos.servicios.pagos.credito.ServicioCodigoOTP;
import com.comerzzia.jpos.util.enums.EnumEstadosValidacionOtp;
import com.comerzzia.jpos.util.exception.ValidacionOTPException;
import es.mpsistemas.util.log.Logger;

/**
 *
 * @author Gabriel Simbania
 */
public class JIngresarCodigoOtp extends JVentanaDialogo implements IViewerValidationFormError {

    private static final Logger LOG_POS = Logger.getMLogger(JIngresarCodigoOtp.class);

    public static int TIPO_CADENA = 0; // cadenas
    public static int TIPO_NUMERICO = 1; // enteros
    public static int TIPO_DECIMAL = 2; // decimales mayores a 0 con 2 decimales. Se puede establecer valor máximo
    private static final long serialVersionUID = 1L;

    private int tipoValor;
    private String uidTicket;
    private boolean otpValido;
    private EnumEstadosValidacionOtp estadoValido;
    private PagoCredito pagoCredito;

    public JIngresarCodigoOtp() {
        estadoValido = EnumEstadosValidacionOtp.NO_VALIDO;
        initComponents();
        registraEventoEnterBoton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        t_valor = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_mensaje = new javax.swing.JLabel();
        lb_error = new javax.swing.JLabel();
        b_autorizacion = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        t_valor.setColumns(7);
        t_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_valorActionPerformed(evt);
            }
        });
        t_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_valorKeyTyped(evt);
            }
        });

        lb_mensaje.setFont(lb_mensaje.getFont().deriveFont(lb_mensaje.getFont().getStyle() | java.awt.Font.BOLD));
        lb_mensaje.setText("Texto que describe el campo");

        lb_error.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        lb_error.setForeground(new java.awt.Color(255, 0, 0));

        b_autorizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aviso.gif"))); // NOI18N
        b_autorizacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        b_autorizacion.setLabel("Autorización");
        b_autorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_autorizacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_autorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(t_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_autorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        estadoValido = EnumEstadosValidacionOtp.NO_VALIDO;
        accionCancelar();
}//GEN-LAST:event_b_cancelarActionPerformed

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed

        accionAceptar();
}//GEN-LAST:event_b_okActionPerformed

    private void t_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_valorActionPerformed
    }//GEN-LAST:event_t_valorActionPerformed

    private void t_valorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_valorKeyTyped
        if (evt.getKeyChar() == '\n') {
            accionAceptar();
        }
    }//GEN-LAST:event_t_valorKeyTyped

    private void b_autorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_autorizacionActionPerformed
        estadoValido = EnumEstadosValidacionOtp.NO_VALIDO;
        validarAutorizacion();
    }//GEN-LAST:event_b_autorizacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_autorizacion;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel lb_error;
    private javax.swing.JLabel lb_mensaje;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_valor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        try {
            t_valor.validar();

            if (!t_valor.getText().isEmpty()) {
                otpValido = ServicioCodigoOTP.validarOTP(Long.parseLong(t_valor.getText()), uidTicket);
                if (otpValido) {
                    estadoValido = EnumEstadosValidacionOtp.VALIDO;
                }
                contenedor.setVisible(false);
            } else {
                otpValido = Boolean.FALSE;
                estadoValido = EnumEstadosValidacionOtp.NO_VALIDO;
                lb_error.setText("Debe ingresar un valor");
            }
        } catch (ValidacionOTPException ex) {
            String mensaje = ex.getMessage();
            lb_error.setText(mensaje);
            LOG_POS.error(mensaje, ex);
        } catch (Exception ex) {
            String mensaje = "Error :" + ex.getMessage();
            lb_error.setText(mensaje);
            LOG_POS.error(mensaje, ex);
        }
    }

    public void validarAutorizacion() {

        try {
            otpValido = ServicioCodigoOTP.validarTiempoExpiracion(uidTicket);

            if (otpValido) {
                estadoValido = EnumEstadosValidacionOtp.AUTORIZACION_MANUAL;
                limpiarFormulario();
                cerrarVentana();
            }

        } catch (ValidacionOTPException ex) {
            String mensaje = ex.getMessage();
            lb_error.setText(mensaje);
            LOG_POS.error(mensaje, ex);
        } catch (Exception ex) {
            String mensaje = "Error :" + ex.getMessage();
            lb_error.setText(mensaje);
            LOG_POS.error(mensaje, ex);
        }

    }

    @Override
    public void limpiarFormulario() {
        setTipoValor(TIPO_CADENA);
        lb_error.setText("");
        t_valor.setText("");
        lb_mensaje.setText("");
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

    public int getTipoValor() {
        return tipoValor;
    }

    public void setTipoValor(int tipoValor) {
        this.tipoValor = tipoValor;
        t_valor.removeValidadores();

    }

    public void setMensaje(String texto) {
        lb_mensaje.setText(texto);
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }

    public void iniciaVista() {
        limpiarFormulario();
    }

    public void iniciaFoco() {
        t_valor.requestFocus();
    }

    public boolean getValor() {
        return otpValido;
    }

    public String getUidTicket() {
        return uidTicket;
    }

    public void setUidTicket(String uidTicket) {
        this.uidTicket = uidTicket;
    }

    public PagoCredito getPagoCredito() {
        return pagoCredito;
    }

    public void setPagoCredito(PagoCredito pagoCredito) {
        this.pagoCredito = pagoCredito;
    }

    public EnumEstadosValidacionOtp getEstadoValido() {
        return estadoValido;
    }

    public void setEstadoValido(EnumEstadosValidacionOtp estadoValido) {
        this.estadoValido = estadoValido;
    }

}
