/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JInicioPC.java
 *
 * Created on 27-jun-2011, 12:37:51
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.servicios.login.Sesion;
import es.mpsistemas.util.log.Logger;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import javax.swing.JFrame;
import java.awt.BorderLayout;
import java.net.URL;
import javax.swing.ImageIcon;


/**
 *
 * @author MGRI
 */
public class JInicioPC extends javax.swing.JFrame {

    private static final Logger log = Logger.getMLogger(JInicioPC.class);
    private JPrincipal p_principal;

    /** Creates new form JInicioPC */
    public JInicioPC() {

        if (Sesion.getDatosConfiguracion().isModoDesarrollo()) {
            setUndecorated(false);
            setResizable(true);
        }
        else {
            setUndecorated(true);
            setResizable(true);
            setLocationRelativeTo(null);
        }


        log.info("LLamada a initComponets de JInicioPC");
        initComponents();
        
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        // Imagen en blanco
        URL myurl;
        
        myurl= this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
        ImageIcon icon=new ImageIcon(myurl);
        v_contadores.setIconImage(icon.getImage());
        
        p_contadores.setContenedor(v_contadores);
        v_contadores.setLocationRelativeTo(null); 
        
        
        p_principal = new JPrincipal();
        p_principal.setMinimumSize(new Dimension(768, 1024));

        add(p_principal, BorderLayout.CENTER);

    }

    public void initFrame() {

        if (Sesion.getDatosConfiguracion().isModoReserva()){
            p_contadores.iniciaVista();
            v_contadores.setVisible(true);
        }
        // Mostrar la aplicación
        p_principal = new JPrincipal();
        add(p_principal, BorderLayout.CENTER);


        setTitle("Comerzzia JPOS");

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0, 0, d.width, d.height);
        setVisible(true);
        p_principal.iniciaVistaActiva();
        

    }

    public void restoreWindow() throws RemoteException {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                if (getExtendedState() == JFrame.ICONIFIED) {
                    setExtendedState(JFrame.NORMAL);
                }
                requestFocus();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_contadores = new javax.swing.JDialog();
        p_contadores = new com.comerzzia.jpos.gui.respaldo.JContadores();

        v_contadores.setTitle("Introducción de contadores");
        v_contadores.setAlwaysOnTop(true);
        v_contadores.setMinimumSize(new java.awt.Dimension(435, 300));
        v_contadores.setModal(true);
        v_contadores.setName("v_contadores"); // NOI18N
        v_contadores.setResizable(false);
        v_contadores.getContentPane().add(p_contadores, java.awt.BorderLayout.CENTER);

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         p_principal.tryToClose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       System.exit(0);
        if (Sesion.getEmf()!=null){
            try{
                Sesion.getEmf().close();
                log.debug("Conexion a la Base de datos cerrada correctamente");
            }
            catch (Exception e){
                log.error("Error cerrando la conexión con la base de datos al cerrar la aplicación");
            }
        }
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.respaldo.JContadores p_contadores;
    private javax.swing.JDialog v_contadores;
    // End of variables declaration//GEN-END:variables



}
