/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPagosBonos.java
 *
 * Created on 22-nov-2011, 16:42:14
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.entity.codigosBarra.NotAValidBarCodeException;
import com.comerzzia.jpos.entity.db.Bono;
import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.servicios.bonos.BonoException;
import com.comerzzia.jpos.servicios.bonos.BonoInvalidException;
import com.comerzzia.jpos.servicios.bonos.BonosServices;
import es.mpsistemas.util.log.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.persistence.NoResultException;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JDialog;
import javax.swing.KeyStroke;

/**
 *
 * @author MGRI
 */
public class JPagosBonos extends JPanelImagenFondo {
   
    
    private static Logger log = Logger.getMLogger(JPagosBonos.class);
    //private JPagos ventanaPadre;
    private JPrincipal ventana_padre;
    private JDialog contenedor;
    private Bono bono = null;
    private boolean desdeReservaciones = false;
    private String tipoBonoALeer = "";
    
    /** Creates new form JPagosBonos */
    public JPagosBonos() {       
        
        super();
        initComponents();
        super.registraEventoEnterBoton();

        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                getContenedor().setVisible(false);
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_bono = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        t_bono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_bono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_bonoKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/codigoBarras.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lea o escriba el código del bono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_bono, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_bono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_bonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_bonoKeyPressed
        if (evt.getKeyChar()=='\n'){
            accionAceptar();        
        }
    }//GEN-LAST:event_t_bonoKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_bono;
    // End of variables declaration//GEN-END:variables

    
    private void accionAceptar(){
        try {
            if (tipoBonoALeer.isEmpty()){
                tipoBonoALeer = BonosServices.BONOEFECTIVO;
            }
            Bono consulta= BonosServices.consultaBono(t_bono.getText(), tipoBonoALeer);
            this.setBono(consulta);
            this.getContenedor().setVisible(false);
            // Al final de la lectura ponemos el tipo de bono de lectura a vacío. Esto es un reset
            tipoBonoALeer="";
        }
        catch (NoResultException ex) {
            log.debug("No se encontro un bono con el código de barras");
            this.getContenedor().setVisible(false);
            ventana_padre.crearAdvertencia("No se encontró el bono");
            
        }
        catch (BonoInvalidException ex){
            log.debug(ex.getMessage());
            this.getContenedor().setVisible(false);
            ventana_padre.crearAdvertencia(ex.getMessage());
        }
        catch (NotAValidBarCodeException ex){
            log.debug("Error de formato en el código leido");
            this.getContenedor().setVisible(false);
            ventana_padre.crearAdvertencia("Error de formato en el código leido");
        }        
        catch (BonoException ex) {
            // Aqui hay que cerrar y mostrar el mensaje de la excepción
            this.getContenedor().setVisible(false);
            ventana_padre.crearAdvertencia(ex.getMessage());
        }
        catch (Exception ex) {
            // cerrar y mostrar ventana de error generico
            this.getContenedor().setVisible(false);
            ventana_padre.crearError("No se pudo agregar el medio de pago.");
        }

        
    }
    
    /**
     * @return the desdeReservaciones
     */
    public boolean isDesdeReservaciones() {
        return desdeReservaciones;
    }

    /**
     * @param desdeReservaciones the desdeReservaciones to set
     */
    public void setDesdeReservaciones(boolean desdeReservaciones) {
        this.desdeReservaciones = desdeReservaciones;
    }

    public JPrincipal getVentana_padre() {
        return ventana_padre;
    }

    public void setVentana_padre(JPrincipal lanzadorErrores) {
        this.ventana_padre = lanzadorErrores;
    }

    public JDialog getContenedor() {
        return contenedor;
    }

    public void setContenedor(JDialog contenedor) {
        this.contenedor = contenedor;
    }

    public Bono getBono() {
        return bono;
    }

    public void setBono(Bono bono) {
        this.bono = bono;
    }

    public void resetearDatos() {
        tipoBonoALeer="";
        bono = null;
        t_bono.setText("");
        
    }

    public String getTipoBonoALeer() {
        return tipoBonoALeer;
    }

    public void setTipoBonoALeer(String tipoBonoAleer) {
        this.tipoBonoALeer = tipoBonoAleer;
    }
}
