/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JPie.java
 *
 * Created on 27-jun-2011, 15:51:50
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import com.comerzzia.util.Contador;
import es.mpsistemas.util.log.Logger;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 *
 * @author MGRI
 */
public class JPie extends JPanelImagenFondo implements IVista {

    private String cajero;
    private String cajero_nombre;
    private String caja;
    private static Timer timerBloqueo = null;
    private static Logger log = Logger.getMLogger(JPie.class);

    /**
     * Creates new form JPie
     */
    public JPie() {
        //super();
        initComponents();

        if (timerBloqueo == null) {
            timerBloqueo = new Timer(10000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    if (!Contador.isBloqueado()) {
                        if (!(JPrincipal.getVistaActual() instanceof JLogin) && !JPrincipal.isRecuentoVisible()) {
                            Contador.setContador(Contador.getContador() + 1);
                            if(Contador.getContador()>(Sesion.getDatosConfiguracion().getTiempoBloqueo()*6) &&!Contador.isBloqueado()){                           
                                Contador.setBloqueado(true);
                                log.debug("actionPerformed() - Se ha alcanzado tiempo de bloqueo (" + (Sesion.getDatosConfiguracion().getTiempoBloqueo()) + " minutos. Bloqueando POS...");
//                                JDialog v_bloqueo = creaPanelDeBloqueo();
//                                v_bloqueo.setVisible(true);
                                log.debug("Hacemos logout");
                                Sesion.cerrarSesion();
                                JPrincipal.getInstance().showView("login");
                                Contador.setContador(0);

                            }
                        }

                    }
                }
            });
            timerBloqueo.start();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_cajero_nombre = new javax.swing.JLabel();
        jLabelRelojAnalogico1 = new com.comerzzia.jpos.gui.components.JLabelRelojAnalogico();
        l_caja_nombre1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1025, 45));
        setMinimumSize(new java.awt.Dimension(1025, 45));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1025, 45));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_cajero_nombre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        l_cajero_nombre.setForeground(new java.awt.Color(0, 149, 227));
        l_cajero_nombre.setText(getCajero_nombre());
        add(l_cajero_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 11, 214, 23));

        jLabelRelojAnalogico1.setForeground(new java.awt.Color(0, 149, 227));
        add(jLabelRelojAnalogico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 14, 152, -1));

        l_caja_nombre1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        l_caja_nombre1.setForeground(new java.awt.Color(0, 149, 227));
        l_caja_nombre1.setText("CAJA");
        add(l_caja_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, 170, 23));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.JLabelRelojAnalogico jLabelRelojAnalogico1;
    private javax.swing.JLabel l_caja_nombre1;
    private javax.swing.JLabel l_cajero_nombre;
    // End of variables declaration//GEN-END:variables

    public String getCajero() {
        return cajero;
    }

    public void setCajero(String cajero) {
        this.cajero = cajero;
    }

    public void inicializaImagenFondo() {
        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_app_pie.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
        } catch (IOException ex) {
        }
    }

    public String getCajero_nombre() {
        if (Sesion.getUsuario() != null) {
            cajero_nombre = Sesion.getUsuario().getDesUsuario();
            return cajero_nombre;
        }
        return "";
    }

    public void setCajero_nombre(String cajero_nombre) {
        this.cajero_nombre = cajero_nombre;
    }

    public String getCaja() {
        return caja;
    }

    public void setCaja(String caja) {
        this.caja = caja;
    }

    void setDatosAutenticacion() {
        l_cajero_nombre.setText(getCajero_nombre());
    }

    @Override
    public void iniciaVista() {
        if (this.getImagenFondo() == null) {
            inicializaImagenFondo();
        }
        if (Sesion.getUsuario() != null) {
            l_cajero_nombre.setText(Sesion.getUsuario().getDesUsuario());
        } else {
            l_cajero_nombre.setText("");

        }
        l_caja_nombre1.setText("CAJA " + Sesion.getDatosConfiguracion().getCodcaja());
    }

    @Override
    public void iniciaFoco() {

    }
}
