/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JSolicitarAutorizacionVentana.java
 *
 * Created on 12-ago-2011, 12:55:30
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.servicios.core.permisos.SinPermisosException;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 *
 * @author MGRI
 */
public class JSolicitarAutorizacionVentana extends JDialog {
    
    private static final long serialVersionUID = 1L;

    public static String MENSAJE_AUTORIZACION_TARJETA = "<html>La tarjeta requiere autorización <br> para su uso.</html>";
    public static String MENSAJE_AUTORIZACION_LECTURA_MANUAL = "<html>La tarjeta requiere autorización <br> para su lectura manual.</html>";
    public static String MENSAJE_AUTORIZACION_RESERVA_CADUCADA = "<html>El usuario no tiene permisos para ingresar a una reservación caducada.</html>";

    
    
    public JSolicitarAutorizacionVentana() {
        super();
        initComponents();
        URL myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
        ImageIcon con=new ImageIcon(myurl);
        this.setIconImage(con.getImage());
        this.p_solicitar_permiso.setContenedor(this);
        this.addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent we) {
            }

            @Override
            public void windowClosing(WindowEvent we) {
                p_solicitar_permiso.b_cancelar(null);
                
            }

            @Override
            public void windowClosed(WindowEvent we) {
                
            }

            @Override
            public void windowIconified(WindowEvent we) {
            }

            @Override
            public void windowDeiconified(WindowEvent we) {
            }

            @Override
            public void windowActivated(WindowEvent we) {
            }

            @Override
            public void windowDeactivated(WindowEvent we) {
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_solicitar_permiso = new com.comerzzia.jpos.gui.JSolicitarInformaciónPanel();

        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(343, 331));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_solicitar_permiso.setMaximumSize(new java.awt.Dimension(350, 331));
        p_solicitar_permiso.setName(""); // NOI18N
        getContentPane().add(p_solicitar_permiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 333, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.JSolicitarInformaciónPanel p_solicitar_permiso;
    // End of variables declaration//GEN-END:variables

    public void setOperacionAAutorizar(Byte operacion) {

        p_solicitar_permiso.setOperacionAAutorizar(operacion);
    }

    public String autenticacionExitosa() throws SinPermisosException {
        if (!p_solicitar_permiso.isResultado()){
            throw new SinPermisosException();
        }
        return p_solicitar_permiso.getUsuarioAutorizador();
    }
    
    public void setFocoInicial(){
        p_solicitar_permiso.setFocoInicial();
    }

    void setMensajeDefault() {
        p_solicitar_permiso.setMensajeDefault();
    }

    void setMensaje(String mensaje) {
        p_solicitar_permiso.setMensaje(mensaje);
    }

}



