/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JTicketsAparcados.java
 *
 * Created on 29-ago-2011, 13:37:42
 */
package com.comerzzia.jpos.gui;

import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.gui.modelos.TicketsAparcadosCellRenderer;
import com.comerzzia.jpos.gui.modelos.TicketsAparcadosTableModel;
import com.comerzzia.jpos.servicios.core.contadores.ContadorException;
import com.comerzzia.jpos.servicios.tickets.TicketException;
import com.comerzzia.jpos.servicios.login.Sesion;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.KeyStroke;

/**
 *
 * @author Admin
 */
public class JTicketsAparcados extends JPanelImagenFondo {

    private JMenu ventana_padre=null;
    private JDialog contenedor=null;
    private TicketsAparcadosTableModel ticketsAparcadosTableModel;
    

    
    public JTicketsAparcados(){
        super();
        initComponents();
    }
    public JTicketsAparcados(JMenu ventana_padre) {
        super();
        this.ventana_padre=ventana_padre;
        initComponents();
        t_tickets.setDefaultRenderer(Object.class, new TicketsAparcadosCellRenderer());
        addFunctionKeys();
    



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        t_tickets = new javax.swing.JTable();
        jb_cancel1 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        jb_ok1 = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        setMaximumSize(new java.awt.Dimension(450, 220));
        setMinimumSize(new java.awt.Dimension(450, 220));
        setPreferredSize(new java.awt.Dimension(450, 220));

        t_tickets.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_tickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        t_tickets.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_ticketsKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(t_tickets);

        jb_cancel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jb_cancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        jb_cancel1.setText("Cancelar");
        jb_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancel1ActionPerformed(evt);
            }
        });

        jb_ok1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jb_ok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        jb_ok1.setMnemonic('a');
        jb_ok1.setText("Aceptar");
        jb_ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ok1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jb_ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_ok1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jb_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancel1ActionPerformed
    contenedor.setVisible(false);
}//GEN-LAST:event_jb_cancel1ActionPerformed

private void jb_ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ok1ActionPerformed
        try {
            contenedor.setVisible(false);
            Sesion.recuperaTicket(Sesion.getTicketsAparcados().get(t_tickets.getSelectedRow()));
            ventana_padre.getContenedor().setVisible(false);            
            ventana_padre.getVentana_padre().showView("ventas");
        }
        catch(ArrayIndexOutOfBoundsException ex){
            ventana_padre.getVentana_padre().crearInformacion("No ha seleccionado ningún ticket.");
        }
        catch (ContadorException ex) {
            ventana_padre.getVentana_padre().crearError("Error al recuperar nuevo contador de Factura.");
        }
}//GEN-LAST:event_jb_ok1ActionPerformed

private void t_ticketsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_ticketsKeyPressed
    if(evt.getKeyChar() == '\n'){
        jb_ok1ActionPerformed(null);
    }
}//GEN-LAST:event_t_ticketsKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.comerzzia.jpos.gui.components.form.JButtonForm jb_cancel1;
    private com.comerzzia.jpos.gui.components.form.JButtonForm jb_ok1;
    private javax.swing.JTable t_tickets;
    // End of variables declaration//GEN-END:variables
 public void inicializar() {
        
        ticketsAparcadosTableModel = new TicketsAparcadosTableModel();

        refrescarTablaPlanes();
        t_tickets.setColumnSelectionInterval(0,0);
        t_tickets.setRowSelectionInterval(0,0);
        t_tickets.requestFocus();
    }

    public void refrescarTablaPlanes() {
        t_tickets.setModel(ticketsAparcadosTableModel);
  

        t_tickets.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        t_tickets.getColumnModel().getColumn(0).setPreferredWidth(150);
        t_tickets.getColumnModel().getColumn(1).setPreferredWidth(272);
        
    }

    

    @Override
    protected void addHotKey(KeyStroke keyStroke, String inputActionKey, Action listener) {
        ActionMap actionMap = this.getActionMap();
        InputMap inputMap = this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(keyStroke, inputActionKey);
        actionMap.put(inputActionKey, listener);
    }

    private void addFunctionKeys() {
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                contenedor.setVisible(false);
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
        
        KeyStroke altmast=KeyStroke.getKeyStroke(KeyEvent.VK_T,KeyEvent.VK_ALT);
        Action listeneraltmast = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                t_tickets.setColumnSelectionInterval(0,0);
                t_tickets.setRowSelectionInterval(0,0);
                t_tickets.requestFocus();
            }
        };
        addHotKey(altmast, "IdentClientaltmast", listeneraltmast);
    }
    public void setContenedor(JDialog contenedor){
        this.contenedor=contenedor;
    }
}
