/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JErrorValidacionTarjeta.java
 *
 * Created on 03-sep-2012, 18:13:56
 */
package com.comerzzia.jpos.gui.ventas;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import com.comerzzia.jpos.servicios.pagos.Pago;
import com.comerzzia.jpos.servicios.pagos.credito.PagoCredito;
import es.mpsistemas.util.log.Logger;
import java.math.BigDecimal;
import javax.swing.JDialog;

/**
 *
 * @author MGRI
 */
public class JErrorValidacionTarjeta extends JVentanaDialogo {

   public static int RESP_CANCELADO = 0;
   public static int RESP_AUTORIZACION_MANUAL = 1;
   public static int RESP_REINTENTAR = 2;
    
    
   private static final Logger log = Logger.getMLogger(JErrorValidacionTarjeta.class);
   private JDialog contenedor = null;    
   private int respuesta;
           
           
    /** Creates new form JErrorValidacionTarjeta */
    public JErrorValidacionTarjeta() {
        initComponents();
        registraEventoEnterBoton();
    }
    
    public void iniciaVista(){
        this.setRespuesta(RESP_CANCELADO);
        b_autorizacion_manual.setVisible(true);
        b_autorizacion_manual.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        i_error = new javax.swing.JLabel();
        lb_error = new javax.swing.JLabel();
        b_autorizacion_manual = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_anular = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_reintentar = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        i_error.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/mensajes/informacion_p.png"))); // NOI18N

        lb_error.setFont(lb_error.getFont().deriveFont(lb_error.getFont().getSize()+2f));
        lb_error.setText("<html>El pago con la tarjeta no ha sido autorizado. <br> ¿Que desea hacer?</html>");

        b_autorizacion_manual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_autorizacion_manual.setMnemonic('m');
        b_autorizacion_manual.setText("Autorización Manual");
        b_autorizacion_manual.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_autorizacion_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_autorizacion_manualActionPerformed(evt);
            }
        });

        b_anular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_anular.setMnemonic('t');
        b_anular.setText("Anular Todos Los Pagos");
        b_anular.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anularActionPerformed(evt);
            }
        });

        b_reintentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_reintentar.setMnemonic('r');
        b_reintentar.setText("Reintentar");
        b_reintentar.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_reintentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_reintentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(i_error, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_autorizacion_manual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_reintentar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_anular, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(i_error, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_anular, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_autorizacion_manual, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addComponent(b_reintentar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_autorizacion_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_autorizacion_manualActionPerformed
        this.setRespuesta(RESP_AUTORIZACION_MANUAL);
        cerrarVentana();
    }//GEN-LAST:event_b_autorizacion_manualActionPerformed

    private void b_anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anularActionPerformed
        this.setRespuesta(RESP_CANCELADO);
        cerrarVentana();
}//GEN-LAST:event_b_anularActionPerformed

    private void b_reintentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_reintentarActionPerformed
        this.setRespuesta(RESP_REINTENTAR);
        cerrarVentana();
    }//GEN-LAST:event_b_reintentarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_anular;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_autorizacion_manual;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_reintentar;
    private javax.swing.JLabel i_error;
    private javax.swing.JLabel lb_error;
    // End of variables declaration//GEN-END:variables

    public JDialog getContenedor() {
        return contenedor;
    }

    public void setContenedor(JDialog contenedor) {
        this.contenedor = contenedor;       
    }

    public int getRespuesta() {
        return respuesta;
    }

    public void setRespuesta(int respuesta) {
        this.respuesta = respuesta;
    }

    @Override
    public void cerrarVentana() {
        this.contenedor.setVisible(false);
    }
    /**
     *  Inicia el texto del cuadro de diálog mediante los valores que insertamos en una plantilla
     * @param importe
     * @param tarjeta 
     */
    public void iniciaTexto(Pago pago, String motivo) {
        String plantilla = Variables.getVariable(Variables.SWITCH_TARJETAS_MSG_ERROR);
        plantilla = plantilla.replace("#I", pago.getUstedPagaConIntereses().toString());
        plantilla = plantilla.replace("#T", pago.getMedioPagoActivo().getDesMedioPago());
        plantilla = plantilla.replace("#R", motivo != null ? motivo : "");

        lb_error.setText(plantilla);
        if (pago.isPagoTarjeta()){
            if (!((PagoCredito) pago).isAdmiteAutorizacionManual()){
                b_autorizacion_manual.setVisible(false);
            }
        }
    }

       /**
     *  Inicia el texto del cuadro de diálog mediante los valores que insertamos en una plantilla
     * @param importe
     * @param tarjeta 
     */
    //Texto creado con el nuevo Valor 
    public void iniciaTexto2(Pago pago, String motivo,String valor) {
        String plantilla = Variables.getVariable(Variables.SWITCH_TARJETAS_MSG_ERROR);
        plantilla = plantilla.replace("#I", valor);
        plantilla = plantilla.replace("#T", pago.getMedioPagoActivo().getDesMedioPago());
        plantilla = plantilla.replace("#R", motivo != null ? motivo : "");

        lb_error.setText(plantilla);
        if (pago.isPagoTarjeta()){
            if (!((PagoCredito) pago).isAdmiteAutorizacionManual()){
                b_autorizacion_manual.setVisible(false);
            }
        }
    }
    
    @Override
    public void accionAceptar() {
        
    }

    @Override
    public void limpiarFormulario() {
        
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
}
