/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JStock.java
 *
 * Created on 28-nov-2012, 16:55:32
 */
package com.comerzzia.jpos.gui.promocion;

import com.comerzzia.jpos.entity.db.Articulos;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.promocion.modelos.PromocionCellRenderer;
import com.comerzzia.jpos.gui.promocion.modelos.PromocionManager;
import com.comerzzia.jpos.gui.promocion.modelos.PromocionTableModel;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.jpos.servicios.promociones.Promocion;
import com.comerzzia.jpos.servicios.promociones.articulos.ArticuloEnPromocion;
import com.comerzzia.jpos.servicios.promociones.articulos.ArticulosEnPromocion;
import com.comerzzia.jpos.servicios.promociones.detalles.DetallePromocionDto;
import com.comerzzia.jpos.servicios.promociones.tipos.PromocionTipoDescuentoCombinado;
import com.comerzzia.jpos.servicios.tickets.componentes.PromocionLineaTicket;
import es.mpsistemas.util.log.Logger;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.ListSelectionModel;

/**
 *
 * @author MGRI
 */
public class JPromocion extends JVentanaDialogo {

    private static final Logger log = Logger.getMLogger(JVentanaDialogo.class);
    PromocionManager manejador = new PromocionManager();
    /** Creates new form JStock */
    public JPromocion() {
        initComponents(); 
        manejador = PromocionManager.getInstance();     
        tb_listaPromo.setDefaultRenderer(Object.class,new PromocionCellRenderer());        
        crearAccionFocoTabla(this, tb_listaPromo, KeyEvent.VK_T, InputEvent.CTRL_MASK);   
        registraEventoEnterBoton();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_articulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_listaPromo = new javax.swing.JTable();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        lb_error = new javax.swing.JLabel();

        lb_articulo.setFont(lb_articulo.getFont().deriveFont(lb_articulo.getFont().getStyle() | java.awt.Font.BOLD, lb_articulo.getFont().getSize()+2));
        lb_articulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_articulo.setText("Articulo");

        tb_listaPromo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tb_listaPromoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_listaPromoFocusLost(evt);
            }
        });
        tb_listaPromo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_listaPromoKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_listaPromo);

        b_cancelar.setMnemonic('c');
        b_cancelar.setText("Cancelar");
        b_cancelar.setActionCommand("Cerrar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(255, 0, 0));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_error.setText("Mensaje de error al consultar stock");
        lb_error.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(lb_articulo, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_articulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_listaPromoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaPromoFocusGained
        if (tb_listaPromo.getRowCount() >= 0) {
            ListSelectionModel selectionModel = tb_listaPromo.getSelectionModel();
            selectionModel.setSelectionInterval(0, 0);
        }
}//GEN-LAST:event_tb_listaPromoFocusGained

    private void tb_listaPromoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaPromoFocusLost
        
}//GEN-LAST:event_tb_listaPromoFocusLost

    private void tb_listaPromoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_listaPromoKeyPressed
        if (evt.getKeyChar() == '\n') {
            
        }
    }//GEN-LAST:event_tb_listaPromoKeyPressed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
       accionCancelar();
}//GEN-LAST:event_b_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_articulo;
    private javax.swing.JLabel lb_error;
    private javax.swing.JTable tb_listaPromo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
        lb_error.setText("");
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
    
    public void iniciaVista(){    
        limpiarFormulario();  
        List<PromocionLineaTicket> promociones = new ArrayList<PromocionLineaTicket>();
        ArticuloEnPromocion articuloEnPromocion = ArticulosEnPromocion.getInstance().get(manejador.getArticuloBuscado().getCodart());
        if(articuloEnPromocion != null){
            DetallePromocionDto detallePromocionDto = (DetallePromocionDto)(articuloEnPromocion.getPromociones().get(0).getDetalle());           
            PromocionLineaTicket lineaTicket = new PromocionLineaTicket(articuloEnPromocion.getPromociones().get(0).getPromocion(), PromocionLineaTicket.PROMO_LINEA_MULTIPLE);
            lineaTicket.setDescuento(BigDecimal.valueOf(detallePromocionDto.getDescuento()));
            promociones.add(lineaTicket);
        }
        List<PromocionTipoDescuentoCombinado> promocionesParaPruducto = new ArrayList<PromocionTipoDescuentoCombinado>();
        for (Promocion promocion : Sesion.promociones) {
            if (promocion.isAplicableArticulo(manejador.getArticuloBuscado())
                    && promocion.isAplicableAFecha()) {
                PromocionTipoDescuentoCombinado objeto = null;

                try {
                    if(promocion instanceof PromocionTipoDescuentoCombinado){
                        objeto = (PromocionTipoDescuentoCombinado) promocion;
                    }else{
                        System.out.print("Tipo Diferente a PromocionTipoDescuentoCombinado ");
                    }

                } catch (Exception ex) {
                    System.out.print("Tipo Diferente a PromocionTipoDescuentoCombinado ");
                }
                if (objeto != null) {
                    promocionesParaPruducto.add(objeto);
                } else {
                   // promocion.aplicaLineasMultiple(lineas);
                }
            }
        }
          
         PromocionTipoDescuentoCombinado promoultima = null;
         for(int j=0;j<promocionesParaPruducto.size();j++){
            if(!promocionesParaPruducto.get(j).isTieneFiltroPagosTarjetaSukasa()){
                promoultima = promocionesParaPruducto.get(j);
                PromocionLineaTicket pl = new PromocionLineaTicket(promoultima, PromocionLineaTicket.PROMO_LINEA_MULTIPLE);
                pl.setDescuento(BigDecimal.valueOf(promoultima.getDescuento()));
                promociones.add(pl);
                promocionesParaPruducto.remove(j);
                j--;
            }
        }
       
        lb_articulo.setText(manejador.getNombreArticulo());
        manejador.setListaPromocion(promociones);
        refrescaTabla();
    }

    private void refrescaTabla() {
        System.out.print("Mostrando tabla ");
//           t_table.setDefaultRenderer(Object.class, new BonoClientesCellRenderer());
        tb_listaPromo.setModel(new PromocionTableModel(manejador.getListaPromocion()));
        tb_listaPromo.getColumnModel().getColumn(0).setPreferredWidth(100);
        tb_listaPromo.getColumnModel().getColumn(1).setPreferredWidth(300);
        tb_listaPromo.getColumnModel().getColumn(2).setPreferredWidth(100);
    }

    public void setArticuloBuscado(Articulos articulo) {
        manejador.setArticuloBuscado(articulo);
    }

    public void setArticuloBuscado(Vector vectorArt) {
        log.debug("setArticuloBuscado() - establecemos el articulo buscado");
        Articulos art = new Articulos();
        art.setCodart((String)vectorArt.get(0));
        art.setDesart((String)vectorArt.get(1));
        manejador.setArticuloBuscado(art);
    }
}
