/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JOperacionesTarjeta.java
 *
 * Created on 02-oct-2012, 10:31:50
 */
package com.comerzzia.jpos.gui.credito;

import com.comerzzia.jpos.servicios.credito.CreditoDirectoBean;
import com.comerzzia.jpos.gui.IManejadorErrores;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.servicios.letras.LetraCambioManager;
import es.mpsistemas.util.log.Logger;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author MGRI
 */
public class JOperacionesTarjeta extends JVentanaDialogo {

    private static final Logger log = Logger.getMLogger(JOperacionesTarjeta.class);
    
    
    
    private static JOperacionesTarjeta instancia;
    
    public static JOperacionesTarjeta getInstance(){
        if (instancia == null){
            instancia = new JOperacionesTarjeta();
        }
        return instancia;
    }
   

    /** Creates new form JOperacionesTarjeta */
    public JOperacionesTarjeta() {
        try {
            initComponents();

            // Imagen para als ventanas
            URL myurl;
            myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
            ImageIcon icon = new ImageIcon(myurl);

            // Búsqueda de Letras
            v_buscar_letras.setLocationRelativeTo(null);
            v_buscar_letras.setIconImage(icon.getImage());
            p_buscar_letras.setContenedor(v_buscar_letras);

            // Consulta de Crédito directo
            v_consulta_credito_directo.setLocationRelativeTo(null);
            v_consulta_credito_directo.setIconImage(icon.getImage());
            p_consulta_credito_directo.setContenedor(v_consulta_credito_directo);

            // Pago de credito directo
            v_pagar_credito_directo.setLocationRelativeTo(null);
            v_pagar_credito_directo.setIconImage(icon.getImage());
            p_pagar_credito_directo.setContenedor(v_pagar_credito_directo);

            // Consulta de letras de factura
            v_consulta_letras_factura.setLocationRelativeTo(null);
            v_consulta_letras_factura.setIconImage(icon.getImage());
            p_consulta_letras_factura.setContenedor(v_consulta_letras_factura);

            // Consulta de facturas
            v_consulta_facturas.setLocationRelativeTo(null);
            v_consulta_facturas.setIconImage(icon.getImage());
            p_consulta_facturas.setContenedor(v_consulta_facturas);

            registraEventoEnterBoton();
        }
        catch (Exception e) {
            log.error("Error incicializando ventana JOperacionesTarjeta :" + e.getMessage(), e);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_buscar_letras = new javax.swing.JDialog();
        p_buscar_letras = new com.comerzzia.jpos.gui.credito.letras.JBuscarLetrasCambio();
        v_consulta_credito_directo = new javax.swing.JDialog();
        p_consulta_credito_directo = new com.comerzzia.jpos.gui.credito.tarjeta.JConsultaCreditoDirecto();
        v_pagar_credito_directo = new javax.swing.JDialog();
        p_pagar_credito_directo = new com.comerzzia.jpos.gui.credito.tarjeta.JPagarCreditoDirecto();
        v_consulta_letras_factura = new javax.swing.JDialog();
        p_consulta_letras_factura = new com.comerzzia.jpos.gui.credito.letras.JConsultaLetrasFacturaCambio();
        v_consulta_facturas = new javax.swing.JDialog();
        p_consulta_facturas = new com.comerzzia.jpos.gui.credito.letras.JConsultaFacturasLC();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        b_consulta_saldo_credito = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_consulta_letras = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_salir = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        v_buscar_letras.setAlwaysOnTop(true);
        v_buscar_letras.setMinimumSize(new java.awt.Dimension(748, 495));
        v_buscar_letras.setModal(true);
        v_buscar_letras.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        javax.swing.GroupLayout v_buscar_letrasLayout = new javax.swing.GroupLayout(v_buscar_letras.getContentPane());
        v_buscar_letras.getContentPane().setLayout(v_buscar_letrasLayout);
        v_buscar_letrasLayout.setHorizontalGroup(
            v_buscar_letrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_buscar_letrasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_buscar_letras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        v_buscar_letrasLayout.setVerticalGroup(
            v_buscar_letrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_buscar_letrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_buscar_letras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        v_consulta_credito_directo.setAlwaysOnTop(true);
        v_consulta_credito_directo.setMinimumSize(new java.awt.Dimension(581, 530));
        v_consulta_credito_directo.setModal(true);
        v_consulta_credito_directo.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        v_consulta_credito_directo.setPreferredSize(new java.awt.Dimension(589, 530));

        p_consulta_credito_directo.setMinimumSize(new java.awt.Dimension(580, 481));
        p_consulta_credito_directo.setPreferredSize(new java.awt.Dimension(589, 461));

        javax.swing.GroupLayout v_consulta_credito_directoLayout = new javax.swing.GroupLayout(v_consulta_credito_directo.getContentPane());
        v_consulta_credito_directo.getContentPane().setLayout(v_consulta_credito_directoLayout);
        v_consulta_credito_directoLayout.setHorizontalGroup(
            v_consulta_credito_directoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_consulta_credito_directoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_consulta_credito_directo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        v_consulta_credito_directoLayout.setVerticalGroup(
            v_consulta_credito_directoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_consulta_credito_directoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_consulta_credito_directo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        v_pagar_credito_directo.setAlwaysOnTop(true);
        v_pagar_credito_directo.setMinimumSize(new java.awt.Dimension(710, 545));
        v_pagar_credito_directo.setModal(true);
        v_pagar_credito_directo.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        javax.swing.GroupLayout v_pagar_credito_directoLayout = new javax.swing.GroupLayout(v_pagar_credito_directo.getContentPane());
        v_pagar_credito_directo.getContentPane().setLayout(v_pagar_credito_directoLayout);
        v_pagar_credito_directoLayout.setHorizontalGroup(
            v_pagar_credito_directoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_pagar_credito_directoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_pagar_credito_directo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        v_pagar_credito_directoLayout.setVerticalGroup(
            v_pagar_credito_directoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_pagar_credito_directoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_pagar_credito_directo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        v_consulta_letras_factura.setAlwaysOnTop(true);
        v_consulta_letras_factura.setMinimumSize(new java.awt.Dimension(838, 720));
        v_consulta_letras_factura.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        v_consulta_letras_factura.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                v_consulta_letras_facturaWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        javax.swing.GroupLayout v_consulta_letras_facturaLayout = new javax.swing.GroupLayout(v_consulta_letras_factura.getContentPane());
        v_consulta_letras_factura.getContentPane().setLayout(v_consulta_letras_facturaLayout);
        v_consulta_letras_facturaLayout.setHorizontalGroup(
            v_consulta_letras_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_consulta_letras_facturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_consulta_letras_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_consulta_letras_facturaLayout.setVerticalGroup(
            v_consulta_letras_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_consulta_letras_facturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_consulta_letras_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        v_consulta_facturas.setAlwaysOnTop(true);
        v_consulta_facturas.setMinimumSize(new java.awt.Dimension(817, 400));
        v_consulta_facturas.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        v_consulta_facturas.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        javax.swing.GroupLayout v_consulta_facturasLayout = new javax.swing.GroupLayout(v_consulta_facturas.getContentPane());
        v_consulta_facturas.getContentPane().setLayout(v_consulta_facturasLayout);
        v_consulta_facturasLayout.setHorizontalGroup(
            v_consulta_facturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_consulta_facturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_consulta_facturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_consulta_facturasLayout.setVerticalGroup(
            v_consulta_facturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_consulta_facturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_consulta_facturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+7));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OPERACIONES CON TARJETA");

        b_consulta_saldo_credito.setMnemonic('c');
        b_consulta_saldo_credito.setText("CONSULTA DE SALDO DE CRÉDITO DIRECTO");
        b_consulta_saldo_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_consulta_saldo_creditoActionPerformed(evt);
            }
        });

        b_consulta_letras.setMnemonic('l');
        b_consulta_letras.setText("CONSULTA DE CRÉDITO TEMPORAL");
        b_consulta_letras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_consulta_letrasActionPerformed(evt);
            }
        });

        b_salir.setMnemonic('s');
        b_salir.setText("SALIR");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(b_consulta_saldo_credito, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(b_consulta_letras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(b_consulta_saldo_credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_consulta_letras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(b_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_consulta_saldo_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_consulta_saldo_creditoActionPerformed
        if (b_consulta_saldo_credito.isEnabled()) {
            cerrarVentana();
            crearVentanaConsultaCreditoDirecto();
        }
}//GEN-LAST:event_b_consulta_saldo_creditoActionPerformed

    private void b_consulta_letrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_consulta_letrasActionPerformed
        if (b_consulta_letras.isEnabled()) {
            cerrarVentana();
            crearVentanaBuscarLetras();
        }
    }//GEN-LAST:event_b_consulta_letrasActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        if (b_consulta_saldo_credito.isEnabled()) {
            cerrarVentana();
        }
    }//GEN-LAST:event_b_salirActionPerformed

    private void v_consulta_letras_facturaWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_v_consulta_letras_facturaWindowGainedFocus
       p_consulta_letras_factura.establecerFoco();
    }//GEN-LAST:event_v_consulta_letras_facturaWindowGainedFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_consulta_letras;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_consulta_saldo_credito;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.comerzzia.jpos.gui.credito.letras.JBuscarLetrasCambio p_buscar_letras;
    private com.comerzzia.jpos.gui.credito.tarjeta.JConsultaCreditoDirecto p_consulta_credito_directo;
    private com.comerzzia.jpos.gui.credito.letras.JConsultaFacturasLC p_consulta_facturas;
    private static com.comerzzia.jpos.gui.credito.letras.JConsultaLetrasFacturaCambio p_consulta_letras_factura;
    private static com.comerzzia.jpos.gui.credito.tarjeta.JPagarCreditoDirecto p_pagar_credito_directo;
    private javax.swing.JDialog v_buscar_letras;
    private javax.swing.JDialog v_consulta_credito_directo;
    private javax.swing.JDialog v_consulta_facturas;
    private static javax.swing.JDialog v_consulta_letras_factura;
    private static javax.swing.JDialog v_pagar_credito_directo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        this.cerrarVentana();
    }

    @Override
    public void limpiarFormulario() {
    }

    @Override
    public void setVentana_padre(IManejadorErrores ventana_padre) {
        super.setVentana_padre(ventana_padre);
        p_buscar_letras.setVentana_padre(ventana_padre);
        p_consulta_credito_directo.setVentana_padre(ventana_padre);
        p_pagar_credito_directo.setVentana_padre(ventana_padre);
        p_consulta_letras_factura.setVentana_padre(ventana_padre);
        p_consulta_facturas.setVentana_padre(ventana_padre);
    }
    
    public void iniciaVista() {
        b_consulta_saldo_credito.requestFocus();
    }

    public void crearVentanaMenuTarjetas() {
        p_buscar_letras.iniciaVista();
        v_buscar_letras.setVisible(true);
    }

    public void crearVentanaConsultaCreditoDirecto() {
        p_consulta_credito_directo.iniciaVista();
        v_consulta_credito_directo.setVisible(true);
    }

    // Vuelve a la pantalla de búsquedas de credito directo
     public void crearVentanaConsultaCreditoDirecto(CreditoDirectoBean datosCredito) {         
        p_consulta_credito_directo.iniciaVista();
        p_consulta_credito_directo.consultaPorCredito(datosCredito);
        v_consulta_credito_directo.setVisible(true);
        
    }
    
    public static void crearVentanaPagarCreditoDirecto(CreditoDirectoBean credito) {
        p_pagar_credito_directo.iniciaVista();
        p_pagar_credito_directo.setDatosCredito(credito);
        p_pagar_credito_directo.mostrarFormulario();
        v_pagar_credito_directo.setVisible(true);
    }

    public static void crearVentanaPagarLetra() {
        p_consulta_letras_factura.iniciaVista();
        v_consulta_letras_factura.setVisible(true);
    }

    public void crearVentanaConsultaLetrasFactura() {
        p_consulta_letras_factura.iniciaVista();
        v_consulta_letras_factura.setVisible(true);
    }

    public void crearVenntanaConsultaFacturas() {
        p_consulta_facturas.iniciaVista();
        v_consulta_facturas.setVisible(true);
    }

    public void crearVentanaBuscarLetras() {
        p_buscar_letras.iniciaVista();
        v_buscar_letras.setVisible(true);
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

    public void volverAConsultaLetrasFactura( ) {
        p_buscar_letras.recuperaVista();
        v_buscar_letras.setVisible(true);
    }
}
