/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JAnadirInvitado.java
 *
 * Created on 27-sep-2011, 13:36:52
 */
package com.comerzzia.jpos.gui.reservaciones;

import com.comerzzia.jpos.entity.db.Cliente;
import com.comerzzia.jpos.entity.services.reservaciones.Reservacion;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.validation.IValidableForm;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorEmail;
import com.comerzzia.jpos.gui.validation.ValidadorEntero;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidadorTelefono;
import com.comerzzia.jpos.gui.validation.ValidadorTexto;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.persistencia.reservaciones.reservainvitados.ReservaInvitadoBean;
import com.comerzzia.jpos.servicios.reservaciones.ReservacionesServicios;
import es.mpsistemas.util.log.Logger;
import java.awt.Dialog.ModalExclusionType;
import java.awt.Dialog.ModalityType;
import java.math.BigInteger;
import java.net.URL;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 *
 * @author Admin
 */
public class JAnadirInvitado extends JVentanaDialogo implements IVista, IViewerValidationFormError {

    private static final Logger log = Logger.getMLogger(JAnadirInvitado.class);
    private JDialog contenedor;
    private JSeleccionarInvitado ventana_padre;
    private Reservacion reserva;
    private Cliente clienteDefecto = null;
    private List<IValidableForm> formulario;

    /** Creates new form JAnadirInvitado */
    public JAnadirInvitado() {
        initComponents();
    }

    public JAnadirInvitado(Reservacion reserva, JSeleccionarInvitado ventana_padre) {
        super();
        initComponents();
        this.reserva = reserva;
        this.ventana_padre = ventana_padre;
        formulario = new LinkedList<IValidableForm>();
        inicializaValidacion();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_titulo = new javax.swing.JLabel();
        lv_invitado_nombre = new javax.swing.JLabel();
        lb_invitado_apellidos = new javax.swing.JLabel();
        lb_invitado_email = new javax.swing.JLabel();
        lb_invitado_telefono = new javax.swing.JLabel();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        t_invitado_nombre = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_invitado_apellidos = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_invitado_email = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_invitado_telefono = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_error = new javax.swing.JLabel();

        lb_titulo.setFont(lb_titulo.getFont().deriveFont((float)18));
        lb_titulo.setText("Alta de Invitado");

        lv_invitado_nombre.setDisplayedMnemonic('n');
        lv_invitado_nombre.setLabelFor(t_invitado_nombre);
        lv_invitado_nombre.setText("Nombre:");

        lb_invitado_apellidos.setDisplayedMnemonic('p');
        lb_invitado_apellidos.setLabelFor(t_invitado_apellidos);
        lb_invitado_apellidos.setText("Apellidos:");

        lb_invitado_email.setDisplayedMnemonic('e');
        lb_invitado_email.setLabelFor(t_invitado_email);
        lb_invitado_email.setText("Email:");

        lb_invitado_telefono.setDisplayedMnemonic('t');
        lb_invitado_telefono.setLabelFor(t_invitado_telefono);
        lb_invitado_telefono.setText("Teléfono:");

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(b_cancelar.getFont().deriveFont((float)15));
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(b_ok.getFont().deriveFont((float)15));
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        t_invitado_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_invitado_nombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(80, Short.MAX_VALUE)
                        .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_invitado_apellidos)
                            .addComponent(lv_invitado_nombre)
                            .addComponent(lb_invitado_email)
                            .addComponent(lb_invitado_telefono))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_invitado_email, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(t_invitado_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(t_invitado_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(t_invitado_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addGap(63, 63, 63)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(lb_titulo)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lv_invitado_nombre)
                    .addComponent(t_invitado_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_invitado_apellidos)
                    .addComponent(t_invitado_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_invitado_email)
                    .addComponent(t_invitado_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_invitado_telefono)
                    .addComponent(t_invitado_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
    contenedor.setVisible(false);
    ventana_padre.getContenedor().setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
    ventana_padre.getContenedor().setModalityType(ModalityType.TOOLKIT_MODAL);
}//GEN-LAST:event_b_cancelarActionPerformed

private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
    try {


        for (IValidableForm iv : formulario) {
            iv.validar();
        }

        BigInteger idInvitado = new BigInteger(ReservacionesServicios.consultaSiguienteIdInvitado(reserva.getReservacion().getUidReservacion()).toString());
        ReservaInvitadoBean invitado = new ReservaInvitadoBean(reserva.getReservacion().getUidReservacion(), idInvitado.longValue());
        invitado.setNombre(t_invitado_nombre.getText());
        invitado.setApellido(t_invitado_apellidos.getText());
        invitado.setEmail(t_invitado_email.getText());
        invitado.setTelefono(t_invitado_telefono.getText());
        invitado.setReserva(reserva.getReservacion());
        invitado.setProcesadoTienda(false);

        reserva.setInvitadoSeleccionado(invitado);
        reserva.getReservacion().getReservaInvitadoList().add(invitado);
        ReservacionesServicios.crearInvitado(invitado);
        contenedor.setVisible(false);
        ventana_padre.getContenedor().setVisible(false);


    }
    catch (ValidationFormException e){
        // El error ya se debe pintar en pantalla
    }
    catch (IndexOutOfBoundsException e) {
        ventana_padre.getVentana_padre().crearAdvertencia("Debe seleccionar un invitado para aceptar. ");
    }
    catch (Exception e) {
        log.error(e);
        ventana_padre.getVentana_padre().crearError(e.getMessage());
    }
}//GEN-LAST:event_b_okActionPerformed

private void t_invitado_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_invitado_nombreActionPerformed

}//GEN-LAST:event_t_invitado_nombreActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel lb_error;
    private javax.swing.JLabel lb_invitado_apellidos;
    private javax.swing.JLabel lb_invitado_email;
    private javax.swing.JLabel lb_invitado_telefono;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lv_invitado_nombre;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_invitado_apellidos;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_invitado_email;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_invitado_nombre;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_invitado_telefono;
    // End of variables declaration//GEN-END:variables
    private void inicializaValidacion() {

        // APELLIDOS: CAMPO OBLIGATORIO: 1 a 100
        t_invitado_apellidos.setFormatearTexto(true);
        t_invitado_apellidos.addValidador(new ValidadorObligatoriedad(), this);
        t_invitado_apellidos.addValidador(new ValidadorTexto(30), this);
        formulario.add(t_invitado_apellidos);
        // NOMBRES: CAMPO OBLIGATORIO:
        t_invitado_nombre.setFormatearTexto(true);
        t_invitado_nombre.addValidador(new ValidadorObligatoriedad(), this);
        t_invitado_nombre.addValidador(new ValidadorTexto(20), this);
        formulario.add(t_invitado_nombre);
        // EMAIL:
        t_invitado_email.addValidador(new ValidadorEmail(), this);
        t_invitado_email.addValidador(new ValidadorTexto(new Integer(0), new Integer(100)), this);
        formulario.add(t_invitado_email);
        // TELEFONO PARTICULAR
        t_invitado_telefono.addValidador(new ValidadorObligatoriedad(), this);
        t_invitado_telefono.addValidador(new ValidadorEntero(), this);
        t_invitado_telefono.addValidador(new ValidadorTelefono(), this);
        
        formulario.add(t_invitado_telefono);
    }

    @Override
    public void iniciaVista() {

        for (IValidableForm iv : formulario) {
            iv.setValidacionHabilitada(false);
        }

        if (clienteDefecto != null) {
            t_invitado_nombre.setText(clienteDefecto.getNombre());
            t_invitado_nombre.requestFocus();
            t_invitado_apellidos.setText(clienteDefecto.getApellido());
            t_invitado_email.setText(clienteDefecto.getEmail());
            
        }
        else {
            t_invitado_nombre.setText("");
            t_invitado_nombre.requestFocus();
            t_invitado_apellidos.setText("");
            t_invitado_email.setText("");
        }

        for (IValidableForm iv : formulario) {
            iv.setValidacionHabilitada(true);
        }

        clearError();
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
        URL myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/error.gif");
        lb_error.setIcon(new ImageIcon(myurl));
    }

    @Override
    public void clearError() {
        lb_error.setText("");
        lb_error.setIcon(null);
    }

    @Override
    public JDialog getContenedor() {
        return contenedor;
    }

    @Override
    public void setContenedor(JDialog contenedor) {
        this.contenedor = contenedor;
    }

    @Override
    public void iniciaFoco() {
        t_invitado_nombre.requestFocus();
    }

    void setClienteDefecto(Cliente invitadoActivo) {
        this.clienteDefecto = invitadoActivo;
    }

    public Cliente getClienteDefecto() {
        return clienteDefecto;
    }

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
    }

    @Override
    public void cerrarVentana() {
        limpiarFormulario();
        contenedor.setVisible(false);
    }
    
        
    @Override
    public void accionLeerTarjetaVD() {
    }

}
