/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDetalleArticulo.java
 *
 * Created on 20-mar-2012, 8:35:35
 */
package com.comerzzia.jpos.gui.reservaciones;

import com.comerzzia.jpos.entity.gui.reservaciones.ArticuloReservado;
import com.comerzzia.jpos.entity.services.reservaciones.Reservacion;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.reservaciones.modelos.MostrarDetalleArticuloCellRenderer;
import com.comerzzia.jpos.gui.reservaciones.modelos.MostrarDetalleArticuloTableModel;
import com.comerzzia.jpos.servicios.core.permisos.Operaciones;
import com.comerzzia.jpos.servicios.core.permisos.SinPermisosException;
import es.mpsistemas.util.log.Logger;
import java.awt.event.KeyEvent;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MGRI
 */
public class JDetalleArticulo extends JVentanaDialogo implements IVista {

    private ArticuloReservado articuloReservado;
    private Reservacion reservacion;
    private JPrincipal ventana_padre;
    private static Logger log = Logger.getMLogger(JVentanaDialogo.class);

    /** Creates new form JDetalleArticulo */
    public JDetalleArticulo() {
        initComponents();
        tb_articulos.setDefaultRenderer(Object.class, new MostrarDetalleArticuloCellRenderer());
        Border empty = new EmptyBorder(0, 0, 0, 0);
        jScrollPane1.setViewportBorder(empty);
        tb_articulos.setBorder(empty);
        jScrollPane1.getViewport().setOpaque(false);
        
        v_valor.setLocationRelativeTo(this);
        p_valor.setVentana_padre(getVentana_padre());
        p_valor.setContenedor(v_valor);
        
    }

    public JDetalleArticulo(ArticuloReservado articuloR) {
        initComponents();
        articuloReservado = articuloR;

        if (articuloReservado != null) {

            actualizaArticuloReservado();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_valor = new javax.swing.JDialog();
        p_valor = new com.comerzzia.jpos.gui.reservaciones.JCantidad();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_articulos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_descripcion = new javax.swing.JLabel();
        lb_codbarras = new javax.swing.JLabel();
        lb_estado = new javax.swing.JLabel();
        lb_cantidad_reservada = new javax.swing.JLabel();
        lb_cantidad_comprada = new javax.swing.JLabel();

        v_valor.setMinimumSize(new java.awt.Dimension(380, 140));
        v_valor.setModal(true);

        javax.swing.GroupLayout v_valorLayout = new javax.swing.GroupLayout(v_valor.getContentPane());
        v_valor.getContentPane().setLayout(v_valorLayout);
        v_valorLayout.setHorizontalGroup(
            v_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_valorLayout.createSequentialGroup()
                .addComponent(p_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_valorLayout.setVerticalGroup(
            v_valorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_valorLayout.createSequentialGroup()
                .addComponent(p_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb_articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_articulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_articulosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_articulos);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código de Barras:");
        jPanel1.add(jLabel1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Comprada:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Estado:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Reservada:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Descripción:");

        lb_descripcion.setForeground(new java.awt.Color(0, 102, 255));
        lb_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_descripcion.setText("DESCRIPCION");

        lb_codbarras.setForeground(new java.awt.Color(0, 102, 255));
        lb_codbarras.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_codbarras.setText("CODBARRAS");

        lb_estado.setForeground(new java.awt.Color(0, 102, 255));
        lb_estado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_estado.setText("ESTADO");

        lb_cantidad_reservada.setForeground(new java.awt.Color(0, 102, 255));
        lb_cantidad_reservada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_cantidad_reservada.setText("RESERVADA");

        lb_cantidad_comprada.setForeground(new java.awt.Color(0, 102, 255));
        lb_cantidad_comprada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_cantidad_comprada.setText("COMPRADA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb_codbarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lb_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_cantidad_reservada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_cantidad_comprada, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_codbarras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_descripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_cantidad_reservada)
                    .addComponent(lb_cantidad_comprada)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lb_estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tb_articulosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_articulosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_TAB && evt.isShiftDown()) {
            tb_articulos.transferFocusBackward();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            tb_articulos.transferFocus();
        }
    }//GEN-LAST:event_tb_articulosKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_cantidad_comprada;
    private javax.swing.JLabel lb_cantidad_reservada;
    private javax.swing.JLabel lb_codbarras;
    private javax.swing.JLabel lb_descripcion;
    private javax.swing.JLabel lb_estado;
    private com.comerzzia.jpos.gui.reservaciones.JCantidad p_valor;
    private javax.swing.JTable tb_articulos;
    private javax.swing.JDialog v_valor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
    }

    @Override
    public void iniciaVista() {
        actualizaArticuloReservado();
    }

    @Override
    public void iniciaFoco() {
        p_valor.iniciaFoco();
    }      

    public ArticuloReservado getArticuloReservado() {
        return articuloReservado;
    }

    
    public void setArticuloReservado(ArticuloReservado articuloReservado,boolean propResYresActiva) {
        this.articuloReservado = articuloReservado;
        if (propResYresActiva && this.articuloReservado.getCantidadReservados()>this.articuloReservado.getCantidadComprados()){
            
        }
        else{
            
        }
        actualizaArticuloReservado();
    }

    private void actualizaArticuloReservado() {
        lb_cantidad_comprada.setText(String.valueOf(articuloReservado.getCantidadComprados()));
        lb_cantidad_reservada.setText(String.valueOf(articuloReservado.getCantidadReservados()));
        lb_codbarras.setText(articuloReservado.getArticulo().getCodbarras());
        lb_descripcion.setText(articuloReservado.getArticulo().getDesart());
        if ((articuloReservado.getCantidadReservados() - articuloReservado.getCantidadComprados()) > 0) {
            lb_estado.setText("DISPONIBLE");
        }
        else {
            lb_estado.setText("COMPRADO");
        }
        refrescaTabla();
    }

    private void refrescaTabla() {

        MostrarDetalleArticuloTableModel modelo = new MostrarDetalleArticuloTableModel(articuloReservado.getCompradores());
        tb_articulos.setModel(modelo);
    }

   

    public Reservacion getReservacion() {
        return reservacion;
    }

    public void setReservacion(Reservacion reservacion) {
        this.reservacion = reservacion;
    }

    public JPrincipal getVentana_padre() {
        return ventana_padre;
    }

    public void setVentana_padre(JPrincipal ventana_padre) {
        this.ventana_padre = ventana_padre;
    }
    
        
    @Override
    public void accionLeerTarjetaVD() {
    }

    
}
