/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JReservacionListaAbonos.java
 *
 * Created on 09-nov-2011, 1:57:42
 */
package com.comerzzia.jpos.gui.reservaciones;

import com.comerzzia.jpos.entity.services.reservaciones.Reservacion;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.reservaciones.modelos.ListadoAbonosCellRenderer;
import com.comerzzia.jpos.gui.reservaciones.modelos.ListadoAbonosTableModel;
import com.comerzzia.jpos.persistencia.reservaciones.reservaabono.ReservaAbonoBean;
import es.mpsistemas.util.log.Logger;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Administrador
 */
public class JReservacionListaAbonos extends JVentanaDialogo {
    
    private static Logger log = Logger.getMLogger(JReservacionListaAbonos.class);
    private List<ReservaAbonoBean> listaAbonos;
    /** Creates new form JReservacionListaAbonos */
    public JReservacionListaAbonos() {
        initComponents();
    }
    
    public JReservacionListaAbonos(Reservacion reserva) {
        
        
        listaAbonos= reserva.getReservacion().getReservaAbonoList();
        for(ReservaAbonoBean abono:listaAbonos){
            abono.setReserva(reserva.getReservacion());
        }
        initComponents();
        super.registraEventoEnterBoton();
        tb_abonos.setDefaultRenderer(Object.class, new ListadoAbonosCellRenderer());
        //lb_reserva.setText(reserva.getReservacion().getUidReservacion());
        lb_autor.setText(reserva.getReservacion().getCliente().getNombre() + " " + reserva.getReservacion().getCliente().getApellido());                
        
        // transparencia
        Border empty = new EmptyBorder(0, 0, 0, 0);
        js_tb_abonos.setViewportBorder(empty);
        tb_abonos.setBorder(empty);
        js_tb_abonos.getViewport().setOpaque(false);
        
        // Establecimiento de ancho de las columnas
        tb_abonos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tb_abonos.getColumnModel().getColumn(0).setPreferredWidth(120);
        tb_abonos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tb_abonos.getColumnModel().getColumn(2).setPreferredWidth(210);
        tb_abonos.getColumnModel().getColumn(3).setPreferredWidth(113);
        tb_abonos.getColumnModel().getColumn(4).setPreferredWidth(113);
        iniciaFoco();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lb_autor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        js_tb_abonos = new javax.swing.JScrollPane();
        tb_abonos = new javax.swing.JTable();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("Reserva realizada por:");

        lb_autor.setText("Autor");

        jLabel5.setFont(jLabel5.getFont().deriveFont((float)18));
        jLabel5.setText("Listado de Abonos");

        tb_abonos.setModel(new ListadoAbonosTableModel(listaAbonos));
        tb_abonos.setMinimumSize(new java.awt.Dimension(0, 660));
        tb_abonos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_abonosKeyPressed(evt);
            }
        });
        js_tb_abonos.setViewportView(tb_abonos);

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(b_ok.getFont().deriveFont((float)15));
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(js_tb_abonos, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_autor))
                .addGap(32, 32, 32)
                .addComponent(js_tb_abonos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        accionAceptar();
}//GEN-LAST:event_b_okActionPerformed

    private void tb_abonosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_abonosKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_TAB && evt.isShiftDown()) {
        tb_abonos.transferFocusBackward();
    }
    else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
        tb_abonos.transferFocus();
    }
    }//GEN-LAST:event_tb_abonosKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane js_tb_abonos;
    private javax.swing.JLabel lb_autor;
    private javax.swing.JTable tb_abonos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        log.info("Accion Aceptar");
        this.getContenedor().setVisible(false);
    }

    @Override
    public void limpiarFormulario() {
        
    }
    
    public void iniciaFoco(){
        log.info("iniciando foco");
        b_ok.requestFocus();
    }
    
    
    @Override
    public void accionLeerTarjetaVD() {
    }

}
