/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JReservacionesTipo.java
 *
 * Created on 21-sep-2011, 12:40:26
 */
package com.comerzzia.jpos.gui.reservaciones;

import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.persistencia.reservaciones.reservatipos.ReservaTiposBean;
import com.comerzzia.jpos.servicios.core.permisos.Operaciones;
import com.comerzzia.jpos.servicios.core.permisos.SinPermisosException;
import com.comerzzia.jpos.servicios.login.Sesion;
import es.mpsistemas.util.log.Logger;
import java.awt.Dialog;
import java.util.LinkedList;
import java.util.logging.Level;

/**
 *
 * @author MGRI
 */
public class JReservacionesTipo extends JVentanaDialogo {

    private static final Logger log = Logger.getMLogger(JReservacionesPagosTarjetas.class);
    private ReservaTiposBean reservacionSeleccionada = null;
    private JPrincipal ventana_padre;

    /**
     * Creates new form JReservacionesTipo
     */
    public JReservacionesTipo() {
        super();
//        this.ventana_padre = ventana_padre;
        initComponents();
        registraEventoEnterBoton();
        //reservacionSeleccionada=(Reservacion)l_tipoReserva.getSelectedItem();
    }

    public JPrincipal getVentana_padre() {
        return ventana_padre;
    }

    public void setVentana_padre(JPrincipal ventana_padre) {
        this.ventana_padre = ventana_padre;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        listaTiposReservaciones = new com.comerzzia.jpos.entity.services.reservaciones.ListaTiposReservaciones();
        tiposReservacionesListRenderer = new com.comerzzia.jpos.gui.reservaciones.modelos.TiposReservacionesListRenderer();
        l_tipoReserva = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        b_aceptar = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        listaTiposReservaciones.setListaTiposReservaciones(Sesion.getTiposReservacionesFiltroSeleccion()!=null ? Sesion.getTiposReservacionesFiltroSeleccion() : new LinkedList());

        tiposReservacionesListRenderer.setText("tiposReservacionesListRenderer1");

        l_tipoReserva.setRenderer(tiposReservacionesListRenderer);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaTiposReservaciones}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, listaTiposReservaciones, eLProperty, l_tipoReserva);
        bindingGroup.addBinding(jComboBoxBinding);

        l_tipoReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_tipoReservaActionPerformed(evt);
            }
        });
        l_tipoReserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                l_tipoReservaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18));
        jLabel1.setText("Tipo de Reservación :");

        b_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_aceptar.setMnemonic('a');
        b_aceptar.setText("Aceptar");
        b_aceptar.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(b_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_tipoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(l_tipoReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(b_aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void l_tipoReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_tipoReservaActionPerformed

}//GEN-LAST:event_l_tipoReservaActionPerformed

    private void l_tipoReservaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l_tipoReservaKeyPressed
        if (evt.getKeyChar() == '\n') {
            accionAceptar();
        }
}//GEN-LAST:event_l_tipoReservaKeyPressed

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
        accionAceptar();

    }//GEN-LAST:event_b_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox l_tipoReserva;
    private com.comerzzia.jpos.entity.services.reservaciones.ListaTiposReservaciones listaTiposReservaciones;
    private com.comerzzia.jpos.gui.reservaciones.modelos.TiposReservacionesListRenderer tiposReservacionesListRenderer;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        log.info("Acción Aceptar");
        setReservacionSeleccionada((ReservaTiposBean) l_tipoReserva.getSelectedItem());
        log.info("Plan seleccionado " + ((ReservaTiposBean) l_tipoReserva.getSelectedItem()).getCodTipo());
        if ((((ReservaTiposBean) l_tipoReserva.getSelectedItem()).getCodTipo()).equals("01")) {
            try {
                String autorizador = JPrincipal.getInstance().compruebaAutorizacionReserva(Operaciones.AUTORIZA_RESERVACION_SEPARACION);
                Sesion.setAutorizadorReservacion(autorizador);
                cerrarVentana();
            } catch (SinPermisosException ex) {
                java.util.logging.Logger.getLogger(JReservacionesTipo.class.getName()).log(Level.SEVERE, null, ex);
                cerrarVentana();
                 ventana_padre.showViewMenuVentas();                

            }
        } else {
            cerrarVentana();

        }
   }

    @Override
    public void limpiarFormulario() {

    }

    @Override
    public void accionCancelar() {
        //cerrarVentana();
    }

    public ReservaTiposBean getReservacionSeleccionada() {
        return reservacionSeleccionada;
    }

    public void setReservacionSeleccionada(ReservaTiposBean reservacionSeleccionada) {
        this.reservacionSeleccionada = reservacionSeleccionada;
    }

    public void iniciaVista() {
        l_tipoReserva.requestFocus();
    }

    protected void setTeclasNavegacionPorDefecto() {
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
}
