/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JReservacionesImportePago.java
 *
 * Created on 27-sep-2011, 15:46:57
 */
package com.comerzzia.jpos.gui.reservaciones;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorDecimal;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import es.mpsistemas.util.log.Logger;
import java.math.BigDecimal;

/**
 *
 * @author MGRI
 */
public class JReservacionesImportePago extends JVentanaDialogo implements IViewerValidationFormError {

    private static final Logger log = Logger.getMLogger(JReservacionesImportePago.class);
    private BigDecimal valorMinimo;
    private BigDecimal valorMaximo;
    private BigDecimal importeAAbonar;
    private IPagoImporteCall pasarelaAPagos; // Clase que contiene el método para llamar a la ventana de pagos

    /** Constructor por defecto */
    public JReservacionesImportePago() {
        initComponents();
        registraEventoEnterBoton();
        t_importe.addValidador(new ValidadorDecimal(), this);
    }

    public JReservacionesImportePago(BigDecimal valorMinimoE, BigDecimal valorMaximoE) {
        log.info("CONSTRUCTOR DE IMPORTE DE PAGOS");
        log.info("Valor Mínimo "+ valorMinimoE.toString());
        log.info("Valor Máximo "+ valorMaximoE.toString());
        
        this.valorMinimo = valorMinimoE;
        this.valorMaximo = valorMaximoE;
        initComponents();
        registraEventoEnterBoton();
        t_importe.addValidador(new ValidadorObligatoriedad(), this);
        if (valorMinimo == null && valorMaximo == null) {
            t_importe.addValidador(new ValidadorDecimal(), this);
            lb_cantidad_maxima.setText("");
            lb_cantidad_minima.setText("");
        }
        else if (valorMinimo != null && valorMaximo == null) {
            t_importe.addValidador(new ValidadorDecimal(null, valorMinimo, 2), this);
            lb_cantidad_maxima.setText("");
            lb_cantidad_minima.setText("Abono mínimo  $ "+valorMinimo.toString());
        }
        else if (valorMinimo == null && valorMaximo != null) {
            t_importe.addValidador(new ValidadorDecimal(valorMaximo, BigDecimal.ZERO, 2), this);
            lb_cantidad_maxima.setText("Abono máximo  $ "+valorMaximo.toString());
            lb_cantidad_minima.setText("");
        }
        else {
            t_importe.addValidador(new ValidadorDecimal(valorMaximo, valorMinimo, 2), this);
            lb_cantidad_maxima.setText("Abono máximo  $ "+valorMaximo.toString());
            lb_cantidad_minima.setText("Abono mínimo  $ "+valorMinimo.toString());
            
        }

        clearError();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb_cantidad_minima = new javax.swing.JLabel();
        lb_cantidad_maxima = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_aceptar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        t_importe = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_error = new javax.swing.JLabel();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
        jLabel1.setText("Introduzca el importe que desea abonar:");

        lb_cantidad_minima.setText("Abono mínimo  $ CANTIDAD");

        lb_cantidad_maxima.setText("Abono máximo  $ CANTIDAD");

        jLabel8.setText("$");

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_aceptar.setMnemonic('a');
        b_aceptar.setText("Aceptar");
        b_aceptar.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });

        t_importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_importeKeyTyped(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(255, 51, 51));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(60, 60, 60)
                .add(b_aceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 91, Short.MAX_VALUE)
                .add(b_cancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(62, 62, 62))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .add(187, 187, 187))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lb_cantidad_minima, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .add(lb_cantidad_maxima))
                .add(99, 99, 99))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(lb_error, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .add(17, 17, 17))
            .add(layout.createSequentialGroup()
                .add(176, 176, 176)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(t_importe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_cantidad_minima)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lb_cantidad_maxima)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(lb_error, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(t_importe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(b_aceptar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(b_cancelar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        accionCancelar();

}//GEN-LAST:event_b_cancelarActionPerformed

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
        accionAceptar();
    }//GEN-LAST:event_b_aceptarActionPerformed

    private void t_importeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_importeKeyTyped
       if (evt.getKeyChar() == '\n'){
           accionAceptar();
       }
    }//GEN-LAST:event_t_importeKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_aceptar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lb_cantidad_maxima;
    private javax.swing.JLabel lb_cantidad_minima;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_importe;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        log.info("Acción Aceptar");
        try {          
            validaFormulario();
            this.getContenedor().setVisible(false);
            //this.pasarelaAPagos.crearVentanaPagos(new BigDecimal(t_importe.getText())); No usamos la ventana
            importeAAbonar= new BigDecimal(t_importe.getText());
            log.debug("Importe seleccionado para abonar: "+importeAAbonar.toString());                    
        }
        catch (ValidationFormException ex) {
            // No hace falta mostrar el mensaje puesto que el validador ya lo saca a a etiqueta de errores
            log.debug("El importe introducido " + t_importe.getText() + "No ha superado la validación");
        }
    }

    @Override
    public void limpiarFormulario() {
    }

    private void validaFormulario() throws ValidationFormException {
        t_importe.validar();
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }

    public IPagoImporteCall getPasarelaAPagos() {
        return pasarelaAPagos;
    }

    public void setPasarelaAPagos(IPagoImporteCall pasarelaAPagos) {
        this.pasarelaAPagos = pasarelaAPagos;
    }

    BigDecimal getImporteAAbonar() {
        return importeAAbonar;
    }

    public void setImporteAAbonar(BigDecimal importeAAbonar) {
        this.importeAAbonar = importeAAbonar;
    }
    
    @Override
    public void accionLeerTarjetaVD() {
    }

}
