/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JSeleccionarInvitado.java
 *
 * Created on 27-sep-2011, 12:47:27
 */
package com.comerzzia.jpos.gui.reservaciones;

import com.comerzzia.jpos.entity.services.reservaciones.Reservacion;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.reservaciones.modelos.SeleccionarInvitadoCellRenderer;
import com.comerzzia.jpos.gui.reservaciones.modelos.SeleccionarInvitadoTableModel;
import com.comerzzia.jpos.persistencia.reservaciones.reservainvitados.ReservaInvitadoBean;
import com.comerzzia.jpos.servicios.login.Sesion;
import es.mpsistemas.util.log.Logger;
import java.awt.Dialog.ModalExclusionType;
import java.awt.Dialog.ModalityType;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Admin
 */
public class JSeleccionarInvitado extends JVentanaDialogo implements IVista {

    private static final Logger log = Logger.getMLogger(JReservacionesVentas.class);
    private JPrincipal ventana_padre;
    private JDialog contenedor;
    private Reservacion reserva;
    

    /** Creates new form JSeleccionarInvitado */
    public JSeleccionarInvitado() {
        initComponents();

    }

    public JSeleccionarInvitado(JMostrarReservacion ventana_padre, Reservacion reserva) {
        this(reserva);
        this.ventana_padre = ventana_padre.getVentana_padre();
    }

    public JSeleccionarInvitado(JPrincipal ventana_padre, Reservacion reserva) {
        this(reserva);
        this.ventana_padre = ventana_padre;
    }
    
    public JSeleccionarInvitado(Reservacion reserva) {
        this.reserva = reserva;
        
        initComponents();
        URL myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
        ImageIcon icon = new ImageIcon(myurl);
        v_anadir_invitado.setIconImage(icon.getImage());
        b_anadirInvitado.setVisible(!reserva.isCanastilla());
        v_anadir_invitado.setLocationRelativeTo(null);
        p_anadir_invitado.setContenedor(v_anadir_invitado);
                    
        List<ReservaInvitadoBean> invitados = reserva.getReservacion().getReservaInvitadoList();
        SeleccionarInvitadoTableModel modelo = new SeleccionarInvitadoTableModel(invitados);
        tb_invitados.setDefaultRenderer(Object.class, new SeleccionarInvitadoCellRenderer());
        tb_invitados.setModel(modelo);
        
        if (!invitados.isEmpty()){
            tb_invitados.requestFocus();            
        }
        else{
            b_anadirInvitado.requestFocus();
        }

        crearAccionFocoTabla(this, tb_invitados, KeyEvent.VK_T, InputEvent.CTRL_MASK);
        
        addFunctionKeys();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_anadir_invitado = new javax.swing.JDialog();
        p_anadir_invitado = new com.comerzzia.jpos.gui.reservaciones.JAnadirInvitado(reserva, this);
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_invitados = new javax.swing.JTable();
        b_cancelar5 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_anadirInvitado = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        v_anadir_invitado.setAlwaysOnTop(true);
        v_anadir_invitado.setMinimumSize(new java.awt.Dimension(430, 350));
        v_anadir_invitado.setModal(true);
        v_anadir_invitado.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        javax.swing.GroupLayout v_anadir_invitadoLayout = new javax.swing.GroupLayout(v_anadir_invitado.getContentPane());
        v_anadir_invitado.getContentPane().setLayout(v_anadir_invitadoLayout);
        v_anadir_invitadoLayout.setHorizontalGroup(
            v_anadir_invitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_anadir_invitadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_anadir_invitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        v_anadir_invitadoLayout.setVerticalGroup(
            v_anadir_invitadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_anadir_invitadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_anadir_invitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 18));
        jLabel1.setText("Lista de Invitados");

        tb_invitados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_invitados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_invitadosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_invitados);

        b_cancelar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar5.setText("Cancelar");
        b_cancelar5.setFont(b_cancelar5.getFont().deriveFont((float)15));
        b_cancelar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelar5ActionPerformed(evt);
            }
        });

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(b_ok.getFont().deriveFont((float)15));
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        b_anadirInvitado.setMnemonic('n');
        b_anadirInvitado.setText("Añadir Invitado");
        b_anadirInvitado.setActionCommand("");
        b_anadirInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anadirInvitadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_anadirInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_cancelar5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_cancelar5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b_anadirInvitado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

private void b_cancelar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelar5ActionPerformed
    log.info("Accion Cancelar");
    contenedor.setVisible(false);
}//GEN-LAST:event_b_cancelar5ActionPerformed

private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
    log.info("Accion Aceptar");
    try {
        reserva.setInvitadoSeleccionado(reserva.getReservacion().getReservaInvitadoList().get(tb_invitados.getSelectedRow()));
        contenedor.setVisible(false);
    }
    catch (IndexOutOfBoundsException e) {
        log.debug("Se ha de seleccionar un invitado para aceptar");
        ventana_padre.crearAdvertencia("Debe seleccionar un invitado para aceptar. ");
    }
    catch (Exception e) {
        log.error(e);
        ventana_padre.crearError(null);
    }
}//GEN-LAST:event_b_okActionPerformed

private void tb_invitadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_invitadosKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        b_okActionPerformed(null);
    }
    else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
        b_cancelar5.requestFocus();
    }
}//GEN-LAST:event_tb_invitadosKeyPressed

private void b_anadirInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anadirInvitadoActionPerformed
    accionAnadirInvitado();
}//GEN-LAST:event_b_anadirInvitadoActionPerformed

    public JDialog getContenedor() {
        return contenedor;
    }

    public void setContenedor(JDialog contenedor) {
        this.contenedor = contenedor;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_anadirInvitado;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar5;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.comerzzia.jpos.gui.reservaciones.JAnadirInvitado p_anadir_invitado;
    private javax.swing.JTable tb_invitados;
    private javax.swing.JDialog v_anadir_invitado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciaVista() {
        log.info("Inicia Vista");
        contenedor.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
        contenedor.setModalityType(ModalityType.APPLICATION_MODAL);
        refrescaTabla();
        
        if (!reserva.getReservacion().getReservaInvitadoList().isEmpty()){
            if (tb_invitados.getRowCount() >= 0) {
                    ListSelectionModel selectionModel = tb_invitados.getSelectionModel();
                    selectionModel.setSelectionInterval(0, 0);
                    tb_invitados.requestFocus();
                }
            tb_invitados.requestFocus();
            
        }
        else{
            b_cancelar5.requestFocus();
        }
        
        if(!reserva.getReservacion().getCodalm().equals(Sesion.getTienda().getCodalm())){
            b_anadirInvitado.setEnabled(false);
        }
    }

    public JPrincipal getVentana_padre() {
        return ventana_padre;
    }

    private void refrescaTabla() {
        log.info("Refresca Tabla");
        List<ReservaInvitadoBean> invitados = reserva.getReservacion().getReservaInvitadoList();
        SeleccionarInvitadoTableModel modelo = new SeleccionarInvitadoTableModel(invitados);
        tb_invitados.setDefaultRenderer(Object.class, new SeleccionarInvitadoCellRenderer());
        tb_invitados.setModel(modelo);
    }
    @Override
    public void iniciaFoco() {
        log.info("Iniciando Foco");
        b_cancelar5.requestFocus();
    }
    
    
    /* EVENTOS*/
    private void addFunctionKeys() {
    // ENTER EN LOS BOTONES
        addHotKey(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "EnterBotones", listenerEnter);
    }

    @Override
    public void accionAceptar() {
        
    }

    @Override
    public void limpiarFormulario() {
        
    }
    
    @Override
    public void cerrarVentana() {
        limpiarFormulario();
        getContenedor().setVisible(false);
    }

    private void accionAnadirInvitado() {
        p_anadir_invitado.iniciaVista();
        v_anadir_invitado.setVisible(true);
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
}
