/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JGiftCard.java
 *
 * Created on 28-jun-2012, 13:05:41
 */
package com.comerzzia.jpos.gui.bonos;

import com.comerzzia.jpos.entity.db.Cliente;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorDecimal;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.persistencia.giftcard.GiftCardBean;
import com.comerzzia.jpos.persistencia.mediospagos.MedioPagoBean;
import com.comerzzia.jpos.persistencia.mediospagos.VencimientoBean;
import com.comerzzia.jpos.servicios.giftcard.GiftCardException;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.jpos.servicios.mediospago.MediosPago;
import com.comerzzia.jpos.servicios.core.permisos.Operaciones;
import com.comerzzia.jpos.servicios.core.permisos.SinPermisosException;
import com.comerzzia.jpos.servicios.tramas.ParserTramaException;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import com.comerzzia.jpos.servicios.mediospago.tarjetas.TarjetaCredito;
import com.comerzzia.jpos.servicios.pagos.Pago;
import com.comerzzia.jpos.servicios.pagos.credito.PagoBonoSuperMaxiNavidad;
import com.comerzzia.jpos.servicios.tramas.TramaBonoSupermaxi;
import es.mpsistemas.util.log.Logger;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.KeyStroke;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author MGRI
 */
public class JConsultaBonosSupermaxi extends JPanelImagenFondo implements IVista, IViewerValidationFormError {

    private static Logger log = Logger.getMLogger(JConsultaBonosSupermaxi.class);
    private static int ESTADO_INICIAL = 0;
    private static int ESTADO_TARJETA_NUEVA_LEIDA = 1;
    private static int ESTADO_TARJETA_LEIDA = 2;
    // Variables
    private JPrincipal ventana_padre = null;
    private TramaBonoSupermaxi tramaBonoSupermaxi = null;
    private GiftCardBean tarjetaGiftCard = null;
    private int estado;
    private boolean estaEnPasoRecarga = false;
    private Cliente cliente; // cliente seleccionado en la pantalla de clientes
    private Pago p;

    /**
     * Creates new form JGiftCard
     */
    public JConsultaBonosSupermaxi() {
        initComponents();
    }

    public JConsultaBonosSupermaxi(JPrincipal ventana_padre) {
        super();
        this.ventana_padre = ventana_padre;

        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_reservas_canastillabbsh.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
        } catch (IOException ex) {
        }
        initComponents();

        URL iconurl;

        iconurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
        ImageIcon icon = new ImageIcon(iconurl);

        // Lectura de Tarjeta
        v_lectura_tarjeta.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        v_lectura_tarjeta.setResizable(false);
        v_lectura_tarjeta.setIconImage(icon.getImage());
        v_lectura_tarjeta.setLocationRelativeTo(null);
        p_lectura_tarjeta.setVentana_padre(ventana_padre);
        p_lectura_tarjeta.setContenedor(v_lectura_tarjeta);

        // Eventos
        registrarEventoLeerTarjeta();
        addFuntionKeysBotonesMenu();

        // validadores
        t_carga.addValidador(new ValidadorDecimal(new BigDecimal(1000000), BigDecimal.ONE, 2), null);
        t_carga.addValidador(new ValidadorObligatoriedad(), this);

        //Visibilidad
        ocultarCampos();
        // limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_lectura_tarjeta = new javax.swing.JDialog();
        p_lectura_tarjeta = new com.comerzzia.jpos.gui.JLecturaTarjeta();
        v_pagos = new javax.swing.JDialog();
        p_pagos = new com.comerzzia.jpos.gui.reservaciones.JReservacionesPagosV();
        l_texto_inicio = new javax.swing.JLabel();
        p_saldo = new javax.swing.JPanel();
        l_saldo = new javax.swing.JLabel();
        l_texto_saldo1 = new javax.swing.JLabel();
        l_texto_dolar_saldo1 = new javax.swing.JLabel();
        l_texto_dolar_saldo2 = new javax.swing.JLabel();
        b_volver = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        lb_error = new javax.swing.JLabel();
        l_estado_tarjeta = new javax.swing.JLabel();
        p_carga = new javax.swing.JPanel();
        l_texto_saldo2 = new javax.swing.JLabel();
        t_carga = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        l_texto_dolar_saldo = new javax.swing.JLabel();
        b_lectura_manual = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        l_introducir_gift = new javax.swing.JLabel();
        t_introducir_gift = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        p_saldo2 = new javax.swing.JPanel();
        l_saldoContado = new javax.swing.JLabel();
        l_texto_saldo3 = new javax.swing.JLabel();
        l_texto_dolar_saldo3 = new javax.swing.JLabel();
        l_texto_dolar_saldo4 = new javax.swing.JLabel();
        p_saldo3 = new javax.swing.JPanel();
        l_saldoCredito = new javax.swing.JLabel();
        l_texto_saldo4 = new javax.swing.JLabel();
        l_texto_dolar_saldo5 = new javax.swing.JLabel();
        l_texto_dolar_saldo6 = new javax.swing.JLabel();
        p_saldo4 = new javax.swing.JPanel();
        l_saldoPrepago = new javax.swing.JLabel();
        l_texto_saldo5 = new javax.swing.JLabel();
        l_texto_dolar_saldo7 = new javax.swing.JLabel();
        l_texto_dolar_saldo8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        l_saldoDiferido = new javax.swing.JLabel();
        l_texto_dolar_saldo9 = new javax.swing.JLabel();
        l_texto_saldo6 = new javax.swing.JLabel();

        v_lectura_tarjeta.setAlwaysOnTop(true);
        v_lectura_tarjeta.setMinimumSize(new java.awt.Dimension(354, 100));
        v_lectura_tarjeta.setModal(true);
        v_lectura_tarjeta.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        v_lectura_tarjeta.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                v_lectura_tarjetaWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        javax.swing.GroupLayout v_lectura_tarjetaLayout = new javax.swing.GroupLayout(v_lectura_tarjeta.getContentPane());
        v_lectura_tarjeta.getContentPane().setLayout(v_lectura_tarjetaLayout);
        v_lectura_tarjetaLayout.setHorizontalGroup(
            v_lectura_tarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_lectura_tarjetaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_lectura_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        v_lectura_tarjetaLayout.setVerticalGroup(
            v_lectura_tarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_lectura_tarjetaLayout.createSequentialGroup()
                .addComponent(p_lectura_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        v_pagos.setAlwaysOnTop(true);
        v_pagos.setMinimumSize(new java.awt.Dimension(1024, 660));
        v_pagos.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        v_pagos.setLocationRelativeTo(null);
        v_pagos.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                v_pagosWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout v_pagosLayout = new javax.swing.GroupLayout(v_pagos.getContentPane());
        v_pagos.getContentPane().setLayout(v_pagosLayout);
        v_pagosLayout.setHorizontalGroup(
            v_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_pagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_pagosLayout.setVerticalGroup(
            v_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_pagosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1024, 734));
        setMinimumSize(new java.awt.Dimension(1024, 734));
        setPreferredSize(new java.awt.Dimension(1024, 734));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l_texto_inicio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        l_texto_inicio.setText("Consulta de Saldo de la tarjeta Bono Supermaxi");
        l_texto_inicio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_inicio.setFocusable(false);
        add(l_texto_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 161, 764, -1));

        p_saldo.setOpaque(false);

        l_saldo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_saldo.setForeground(new java.awt.Color(0, 0, 204));
        l_saldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_saldo.setText("0");
        l_saldo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_saldo.setFocusable(false);

        l_texto_saldo1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_saldo1.setText("Saldo:");
        l_texto_saldo1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_saldo1.setFocusable(false);

        l_texto_dolar_saldo1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo1.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo1.setText("$");
        l_texto_dolar_saldo1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo1.setFocusable(false);

        l_texto_dolar_saldo2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo2.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo2.setText("$");
        l_texto_dolar_saldo2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo2.setFocusable(false);

        javax.swing.GroupLayout p_saldoLayout = new javax.swing.GroupLayout(p_saldo);
        p_saldo.setLayout(p_saldoLayout);
        p_saldoLayout.setHorizontalGroup(
            p_saldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_saldoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(l_texto_saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_texto_dolar_saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(p_saldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_saldoLayout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(l_texto_dolar_saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );
        p_saldoLayout.setVerticalGroup(
            p_saldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_saldoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_saldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(l_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_texto_dolar_saldo1)
                    .addComponent(l_texto_saldo1))
                .addGap(128, 128, 128))
            .addGroup(p_saldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_saldoLayout.createSequentialGroup()
                    .addContainerGap(127, Short.MAX_VALUE)
                    .addComponent(l_texto_dolar_saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        add(p_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, 50));

        b_volver.setText("<html><center>Volver<br/>F2</center></html>");
        b_volver.setActionCommand("<html><center> Cancelar <br>F2</center></html>");
        b_volver.setAlignmentY(0.0F);
        b_volver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_volver.setMargin(new java.awt.Insets(2, 0, 2, 0));
        b_volver.setMaximumSize(new java.awt.Dimension(76, 48));
        b_volver.setMinimumSize(new java.awt.Dimension(76, 48));
        b_volver.setNextFocusableComponent(b_lectura_manual);
        b_volver.setPreferredSize(new java.awt.Dimension(114, 48));
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });
        add(b_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 634, -1, 56));

        lb_error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lb_error.setForeground(new java.awt.Color(255, 51, 0));
        add(lb_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 585, 20));

        l_estado_tarjeta.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        l_estado_tarjeta.setForeground(new java.awt.Color(0, 0, 204));
        l_estado_tarjeta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_estado_tarjeta.setFocusable(false);
        add(l_estado_tarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 720, 30));

        p_carga.setOpaque(false);

        l_texto_saldo2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_saldo2.setLabelFor(t_carga);
        l_texto_saldo2.setText("Carga:");
        l_texto_saldo2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_saldo2.setFocusable(false);

        t_carga.setText("jTextFieldForm1");
        t_carga.setNextFocusableComponent(b_volver);

        l_texto_dolar_saldo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo.setText("$");
        l_texto_dolar_saldo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo.setFocusable(false);

        javax.swing.GroupLayout p_cargaLayout = new javax.swing.GroupLayout(p_carga);
        p_carga.setLayout(p_cargaLayout);
        p_cargaLayout.setHorizontalGroup(
            p_cargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_cargaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(l_texto_saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_texto_dolar_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_carga, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        p_cargaLayout.setVerticalGroup(
            p_cargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_cargaLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(p_cargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(t_carga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_texto_dolar_saldo)
                    .addComponent(l_texto_saldo2))
                .addGap(22, 22, 22))
        );

        add(p_carga, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, -1, -1));

        b_lectura_manual.setLabel("<html><center>Lectura<br>Manual<br>F8</center></html>");
        b_lectura_manual.setMargin(new java.awt.Insets(2, 0, 2, 0));
        b_lectura_manual.setMaximumSize(new java.awt.Dimension(76, 48));
        b_lectura_manual.setMinimumSize(new java.awt.Dimension(76, 48));
        b_lectura_manual.setPreferredSize(new java.awt.Dimension(76, 48));
        b_lectura_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_lectura_manualActionPerformed(evt);
            }
        });
        add(b_lectura_manual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 634, 108, 56));

        l_introducir_gift.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        l_introducir_gift.setLabelFor(t_introducir_gift);
        l_introducir_gift.setText("Nº Bono Supermaxi:");
        l_introducir_gift.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_introducir_gift.setFocusable(false);
        add(l_introducir_gift, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 140, -1));

        t_introducir_gift.setNextFocusableComponent(b_volver);
        t_introducir_gift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_introducir_giftActionPerformed(evt);
            }
        });
        t_introducir_gift.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_introducir_giftKeyPressed(evt);
            }
        });
        add(t_introducir_gift, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 330, 35));

        p_saldo2.setOpaque(false);

        l_saldoContado.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_saldoContado.setForeground(new java.awt.Color(0, 0, 204));
        l_saldoContado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_saldoContado.setText("0");
        l_saldoContado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_saldoContado.setFocusable(false);

        l_texto_saldo3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_saldo3.setText("Saldo Contado:");
        l_texto_saldo3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_saldo3.setFocusable(false);

        l_texto_dolar_saldo3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo3.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo3.setText("$");
        l_texto_dolar_saldo3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo3.setFocusable(false);

        l_texto_dolar_saldo4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo4.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo4.setText("$");
        l_texto_dolar_saldo4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo4.setFocusable(false);

        javax.swing.GroupLayout p_saldo2Layout = new javax.swing.GroupLayout(p_saldo2);
        p_saldo2.setLayout(p_saldo2Layout);
        p_saldo2Layout.setHorizontalGroup(
            p_saldo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_saldo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_texto_saldo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_texto_dolar_saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_saldoContado, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(p_saldo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_saldo2Layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(l_texto_dolar_saldo4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(293, Short.MAX_VALUE)))
        );
        p_saldo2Layout.setVerticalGroup(
            p_saldo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_saldo2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_saldo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(l_saldoContado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_texto_dolar_saldo3)
                    .addComponent(l_texto_saldo3))
                .addGap(113, 113, 113))
            .addGroup(p_saldo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_saldo2Layout.createSequentialGroup()
                    .addContainerGap(112, Short.MAX_VALUE)
                    .addComponent(l_texto_dolar_saldo4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        add(p_saldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, 60));

        p_saldo3.setOpaque(false);

        l_saldoCredito.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_saldoCredito.setForeground(new java.awt.Color(0, 0, 204));
        l_saldoCredito.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_saldoCredito.setText("0");
        l_saldoCredito.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_saldoCredito.setFocusable(false);

        l_texto_saldo4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_saldo4.setText("Saldo Credito:");
        l_texto_saldo4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_saldo4.setFocusable(false);

        l_texto_dolar_saldo5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo5.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo5.setText("$");
        l_texto_dolar_saldo5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo5.setFocusable(false);

        l_texto_dolar_saldo6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo6.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo6.setText("$");
        l_texto_dolar_saldo6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo6.setFocusable(false);

        javax.swing.GroupLayout p_saldo3Layout = new javax.swing.GroupLayout(p_saldo3);
        p_saldo3.setLayout(p_saldo3Layout);
        p_saldo3Layout.setHorizontalGroup(
            p_saldo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_saldo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_texto_saldo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_texto_dolar_saldo5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_saldoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(p_saldo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_saldo3Layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(l_texto_dolar_saldo6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );
        p_saldo3Layout.setVerticalGroup(
            p_saldo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_saldo3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_saldo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(l_saldoCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_texto_dolar_saldo5)
                    .addComponent(l_texto_saldo4))
                .addGap(113, 113, 113))
            .addGroup(p_saldo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_saldo3Layout.createSequentialGroup()
                    .addContainerGap(112, Short.MAX_VALUE)
                    .addComponent(l_texto_dolar_saldo6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        add(p_saldo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, 60));

        p_saldo4.setOpaque(false);

        l_saldoPrepago.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_saldoPrepago.setForeground(new java.awt.Color(0, 0, 204));
        l_saldoPrepago.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_saldoPrepago.setText("0");
        l_saldoPrepago.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_saldoPrepago.setFocusable(false);

        l_texto_saldo5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_saldo5.setText("Saldo Prepago:");
        l_texto_saldo5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_saldo5.setFocusable(false);

        l_texto_dolar_saldo7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo7.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo7.setText("$");
        l_texto_dolar_saldo7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo7.setFocusable(false);

        l_texto_dolar_saldo8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo8.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo8.setText("$");
        l_texto_dolar_saldo8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo8.setFocusable(false);

        javax.swing.GroupLayout p_saldo4Layout = new javax.swing.GroupLayout(p_saldo4);
        p_saldo4.setLayout(p_saldo4Layout);
        p_saldo4Layout.setHorizontalGroup(
            p_saldo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_saldo4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_texto_saldo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_texto_dolar_saldo7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_saldoPrepago, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(p_saldo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_saldo4Layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(l_texto_dolar_saldo8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(279, Short.MAX_VALUE)))
        );
        p_saldo4Layout.setVerticalGroup(
            p_saldo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_saldo4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_saldo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(l_saldoPrepago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_texto_dolar_saldo7)
                    .addComponent(l_texto_saldo5))
                .addGap(113, 113, 113))
            .addGroup(p_saldo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_saldo4Layout.createSequentialGroup()
                    .addContainerGap(112, Short.MAX_VALUE)
                    .addComponent(l_texto_dolar_saldo8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        add(p_saldo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 490, 60));

        jPanel1.setOpaque(false);

        l_saldoDiferido.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_saldoDiferido.setForeground(new java.awt.Color(0, 0, 204));
        l_saldoDiferido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_saldoDiferido.setText("0");
        l_saldoDiferido.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_saldoDiferido.setFocusable(false);

        l_texto_dolar_saldo9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_dolar_saldo9.setForeground(new java.awt.Color(0, 0, 204));
        l_texto_dolar_saldo9.setText("$");
        l_texto_dolar_saldo9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_dolar_saldo9.setFocusable(false);

        l_texto_saldo6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        l_texto_saldo6.setText("Saldo Diferido:");
        l_texto_saldo6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        l_texto_saldo6.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(l_texto_saldo6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(l_texto_dolar_saldo9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(l_saldoDiferido, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(l_saldoDiferido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_texto_dolar_saldo9)
                        .addComponent(l_texto_saldo6))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 470, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        accionVolver();
}//GEN-LAST:event_b_volverActionPerformed

    private void v_lectura_tarjetaWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_v_lectura_tarjetaWindowGainedFocus
        p_lectura_tarjeta.iniciaFoco();
}//GEN-LAST:event_v_lectura_tarjetaWindowGainedFocus

    private void v_pagosWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_v_pagosWindowOpened
        p_pagos.iniciaFoco();
}//GEN-LAST:event_v_pagosWindowOpened

    private void b_lectura_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_lectura_manualActionPerformed
        accionLecturaManual();
    }//GEN-LAST:event_b_lectura_manualActionPerformed

    private void t_introducir_giftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_introducir_giftKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                if (t_introducir_gift.getText().length() == 16) {
                    eventoLecturaTarjetaBonoSupermaxi(t_introducir_gift.getText());
                } else {
                    lb_error.setText("La longitud de la tarjeta debe ser de 16 dígitos");
                }

            } catch (ParserTramaException ex) {
                log.debug("Error parseando la trama de la tarjeta");
                lb_error.setText("El número de tarjeta no es válido");
            }
        }
    }//GEN-LAST:event_t_introducir_giftKeyPressed

    private void t_introducir_giftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_introducir_giftActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_t_introducir_giftActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_lectura_manual;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_estado_tarjeta;
    private javax.swing.JLabel l_introducir_gift;
    private javax.swing.JLabel l_saldo;
    private javax.swing.JLabel l_saldoContado;
    private javax.swing.JLabel l_saldoCredito;
    private javax.swing.JLabel l_saldoDiferido;
    private javax.swing.JLabel l_saldoPrepago;
    private javax.swing.JLabel l_texto_dolar_saldo;
    private javax.swing.JLabel l_texto_dolar_saldo1;
    private javax.swing.JLabel l_texto_dolar_saldo2;
    private javax.swing.JLabel l_texto_dolar_saldo3;
    private javax.swing.JLabel l_texto_dolar_saldo4;
    private javax.swing.JLabel l_texto_dolar_saldo5;
    private javax.swing.JLabel l_texto_dolar_saldo6;
    private javax.swing.JLabel l_texto_dolar_saldo7;
    private javax.swing.JLabel l_texto_dolar_saldo8;
    private javax.swing.JLabel l_texto_dolar_saldo9;
    private javax.swing.JLabel l_texto_inicio;
    private javax.swing.JLabel l_texto_saldo1;
    private javax.swing.JLabel l_texto_saldo2;
    private javax.swing.JLabel l_texto_saldo3;
    private javax.swing.JLabel l_texto_saldo4;
    private javax.swing.JLabel l_texto_saldo5;
    private javax.swing.JLabel l_texto_saldo6;
    private javax.swing.JLabel lb_error;
    private javax.swing.JPanel p_carga;
    private com.comerzzia.jpos.gui.JLecturaTarjeta p_lectura_tarjeta;
    private com.comerzzia.jpos.gui.reservaciones.JReservacionesPagosV p_pagos;
    private javax.swing.JPanel p_saldo;
    private javax.swing.JPanel p_saldo2;
    private javax.swing.JPanel p_saldo3;
    private javax.swing.JPanel p_saldo4;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_carga;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_introducir_gift;
    private javax.swing.JDialog v_lectura_tarjeta;
    private javax.swing.JDialog v_pagos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciaVista() {
        l_texto_inicio.setText("Consulta de Saldo de la tarjeta Bono Supermaxi ");
        resetearFormulario();
        iniciaFoco();
        ocultarCampos();
    }

    @Override
    public void iniciaFoco() {
        b_volver.requestFocus();
    }

    private void accionLeerTarjetaBonoSupermaxi() {
        if (JPrincipal.getVistaActualS().equals(JPrincipal.VISTA_BONOSUPER)) {
            if (Sesion.getDatosConfiguracion().isModoDesarrollo()) {
                // Hacemos aparecer el input de introducción de bandas de la tarjeta
                //v_lectura_tarjeta.setSize(400, 400);
                v_lectura_tarjeta.setMinimumSize(new Dimension(550, 330));
                p_lectura_tarjeta.setMinimumSize(new Dimension(520, 310));
            }
            p_lectura_tarjeta.iniciaVista();
            v_lectura_tarjeta.setVisible(true);
            try {
                if (p_lectura_tarjeta.getBine() != null && !p_lectura_tarjeta.getBine().isEmpty()) {
                    ocultarCampos();
                    eventoLecturaTarjetaBonoSupermaxi(p_lectura_tarjeta.getBine());
                }
            } catch (ParserTramaException e) {
                log.debug("Error parseando la trama de la tarjeta");
                lb_error.setText("Error leyendo la banda de la tarjeta");
            }
        }
    }
    public Action listenerTarjeta = new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent act) {
            accionLeerTarjetaBonoSupermaxi();
        }
    };

    public void registrarEventoLeerTarjeta() {
        KeyStroke keyEnter = KeyStroke.getKeyStroke(KeyEvent.VK_5, InputEvent.SHIFT_DOWN_MASK); //% es SHIFT + 5
        addHotKey(keyEnter, "LecturaTarjetaGiftCard", listenerTarjeta);
    }

    private void eventoLecturaTarjetaBonoSupermaxi(String tarjetaLeida) throws ParserTramaException {

        // Ocultar datos de tarjeta leida previamente            
        resetearFormulario();

        // LEER LA TARJETA
        //Buscamos los bines por si es GiftCard de Sukasa
        MedioPagoBean medPag = TarjetaCredito.getBINMedioPagoBanda(tarjetaLeida);
        TramaBonoSupermaxi tident;
        if (medPag != null && (medPag.isBonoSuperMaxiNavidad() || medPag.isCreditoFilial())) {
            tident = new TramaBonoSupermaxi(tarjetaLeida, medPag.getCodMedioPago());
            accionLecturaTarjeta(tident);
        } else {
            lb_error.setText("La tarjeta deslizada no es un bono supermaxi o crédito de temporada");
        }

    }

    private void accionLecturaTarjeta(TramaBonoSupermaxi tident) {
        try {
            String respuesta;
            String trama;
            String saldoBonoSuper;
            String saldoBonoSuperD;
            log.debug("accionLecturaTarjeta()");
            lb_error.setText("");

            p = new PagoBonoSuperMaxiNavidad(null, null, null, null);
            String tarjeta = "239";
            if (Variables.getVariable(Variables.ACTIVO_SERVICIO_WEB_SUPERMAXI).equals("S")) {
                respuesta = p.consultarSaldoWeb(tident.getidBonoSuper());
                if (tident.getCodMedioPago() == null ? tarjeta == null : tident.getCodMedioPago().equals(tarjeta)) {
                    trama = ignorarComienzoRespuestaCfavoritaSWeb(respuesta);
                } else {
                    trama = ignorarComienzoRespuestaSWeb(respuesta);
                }
            } else {
                respuesta = p.consultarSaldo(tident.getidBonoSuper());
                if (tident.getCodMedioPago() == null ? tarjeta == null : tident.getCodMedioPago().equals(tarjeta)) {
                    trama = ignorarComienzoRespuestaCfavorita(respuesta);
                } else {
                    trama = ignorarComienzoRespuesta(respuesta);
                }
            }

            if (!tident.getCodMedioPago().equals(tarjeta)) {
                if (trama != null) {
                    saldoBonoSuper = trama.substring(0, 8);
                    int saldo = Integer.parseInt(saldoBonoSuper);
                    String saldoT = String.valueOf(saldo);
                    saldoBonoSuperD = trama.substring(8, 10);
                    log.debug("Se ha encontrado la Gift Card registrada en BD.");
                    this.estado = JConsultaBonosSupermaxi.ESTADO_TARJETA_LEIDA;
                    t_introducir_gift.setText(tident.getidBonoSuper());
                    t_introducir_gift.setVisible(true);
                    t_introducir_gift.setEditable(false);
                    l_saldo.setText(saldoT + "," + saldoBonoSuperD);
                    p_saldo.setVisible(true);
                } else {
                    this.estado = JConsultaBonosSupermaxi.ESTADO_TARJETA_LEIDA;
                    t_introducir_gift.setText(tident.getidBonoSuper());
                    t_introducir_gift.setVisible(true);
                    t_introducir_gift.setEditable(false);
                    if (PagoBonoSuperMaxiNavidad.ERROR_TIMEOUT.equals(respuesta)) {
                        l_estado_tarjeta.setText(PagoBonoSuperMaxiNavidad.ERROR_TIMEOUT_OBSERVACION);
                    } else {
                        l_estado_tarjeta.setText(PagoBonoSuperMaxiNavidad.ERROR_TARJETA_NO_VALIDA);
                    }

                    l_saldo.setText(StringUtils.EMPTY);
                    p_saldo.setVisible(true);
                }

            } else {
                if (trama != null) {
                    saldoBonoSuper = trama.substring(0, 8);
                    int saldo = Integer.parseInt(saldoBonoSuper);
                    String saldoT = String.valueOf(saldo);
                    saldoBonoSuperD = trama.substring(8, 10);
                    String saldoCredito = trama.substring(10, 18);
                    int sCredito = Integer.parseInt(saldoCredito);
                    String saldoT1 = String.valueOf(sCredito);
                    String saldoCreditoD = trama.substring(18, 20);
                    String saldoPrepago = trama.substring(20, 28);
                    int sPrepago = Integer.parseInt(saldoPrepago);
                    String saPrepago = String.valueOf(sPrepago);
                    String saldoPrepagoD = trama.substring(28, 30);
                    String saldoDiferido = trama.substring(30, 38);
                    int sDiferido = Integer.parseInt(saldoDiferido);
                    String saDiferido = String.valueOf(sDiferido);
                    String saldoDiferidoD = trama.substring(38, 40);
                    log.debug("Se ha encontrado la Gift Card registrada en BD.");
                    this.estado = JConsultaBonosSupermaxi.ESTADO_TARJETA_LEIDA;
                    t_introducir_gift.setText(tident.getidBonoSuper());
                    t_introducir_gift.setVisible(true);
                    t_introducir_gift.setEditable(false);
                    l_saldoContado.setText(saldoT + "," + saldoBonoSuperD);
                    l_saldoCredito.setText(saldoT1 + "," + saldoCreditoD);
                    l_saldoDiferido.setText(saDiferido + "," + saldoDiferidoD);
                    l_saldoPrepago.setText(saPrepago + "," + saldoPrepagoD);
                    p_saldo2.setVisible(true);
                    p_saldo3.setVisible(true);
                    p_saldo4.setVisible(true);
                    jPanel1.setVisible(true);
                } else {
                    this.estado = JConsultaBonosSupermaxi.ESTADO_TARJETA_LEIDA;
                    t_introducir_gift.setText(tident.getidBonoSuper());
                    t_introducir_gift.setVisible(true);
                    t_introducir_gift.setEditable(false);
                    l_estado_tarjeta.setText(PagoBonoSuperMaxiNavidad.ERROR_TARJETA_NO_VALIDA);
                    l_saldo.setText(StringUtils.EMPTY);
                    p_saldo.setVisible(true);
                }
            }

        } catch (Exception e) {
            log.debug("No se ha encontrado la Gift Card registrada en BD. Nueva Gift Card");
            this.estado = JConsultaBonosSupermaxi.ESTADO_TARJETA_NUEVA_LEIDA;
            t_introducir_gift.setText(tident.getidBonoSuper());
            t_introducir_gift.setVisible(true);
            t_introducir_gift.setEditable(false);
            l_estado_tarjeta.setText("Tarjeta no Activa");
        }
    }

    protected String ignorarComienzoRespuesta(String trama) {
        //Si la trama empieza con %B, estamos leyendo la banda magnética y lo ignoramos
        if (trama.contains("APROBADO") || trama.contains("MAXIBONO")) {
            trama = trama.substring(151);
        } else {
            return null;
        }

        return trama;
    }

    protected String ignorarComienzoRespuestaSWeb(String trama) {
        //Si la trama empieza con %B, estamos leyendo la banda magnética y lo ignoramos
        if (trama.contains("APROBADO") || trama.contains("MAXIBONO")) {
//            trama = trama.substring(151);
            trama = trama.substring(157);
        } else {
            return null;
        }

        return trama;
    }

    protected String ignorarComienzoRespuestaCfavorita(String trama) {
        //Si la trama empieza con %B, estamos leyendo la banda magnética y lo ignoramos
        if (trama != null) {
            trama = trama.substring(131);
        } else {
            return null;
        }
        return trama;
    }

    protected String ignorarComienzoRespuestaCfavoritaSWeb(String trama) {
        //Si la trama empieza con %B, estamos leyendo la banda magnética y lo ignoramos
        if (trama != null) {
//            trama = trama.substring(131);
            trama = trama.substring(137);
        } else {
            return null;
        }
        return trama;
    }

    private void resetearFormulario() {

        estaEnPasoRecarga = false;
//        b_carga.setText("");
//        b_carga.setEnabled(false);
        cliente = null;

        this.tramaBonoSupermaxi = null;
        this.tarjetaGiftCard = null;
        lb_error.setText("");
        p_saldo.setVisible(false);
        p_saldo2.setVisible(false);
        p_saldo3.setVisible(false);
        p_saldo4.setVisible(false);
        jPanel1.setVisible(false);
        p_carga.setVisible(false);
        l_estado_tarjeta.setText("");
        t_carga.setText("");
        t_carga.setEnabled(false);
        b_volver.requestFocus();
        t_carga.setValidacionHabilitada(false);

    }

    private void accionCargar() {

        try {
            // Comprobamos que la tarjeta es de un descuento que podemos recargar
            if (this.tarjetaGiftCard != null || this.tramaBonoSupermaxi != null) {
                VencimientoBean venEfectiSocio = MediosPago.getInstancia().getPagoEfectivo().getVencimientoDefault();
                String codigoMedioPago;
                if (this.tarjetaGiftCard != null) {
                    codigoMedioPago = tarjetaGiftCard.getCodMedioPago();
                } else {
                    codigoMedioPago = tramaBonoSupermaxi.getCodMedioPago();
                }
                MedioPagoBean medioPagotGiftCard = MediosPago.getInstancia().getMedioPago(codigoMedioPago);

                if (medioPagotGiftCard == null) {
                    log.error("Medio de pago no encontrado: " + codigoMedioPago);
                    throw new GiftCardException("No se encontró el medio de pago asociado a la tarjeta ");
                }

                VencimientoBean venTarjeta = medioPagotGiftCard.getVencimientoDefault();

                /*
                if (venTarjeta.getDescuentoNoAfiliados().compareTo(venEfectiSocio.getDescuentoAfiliados())>0){
                    throw new GiftCardException("No es posible recargar esta tarjeta en el Terminal de Venta");
                }
                 *  // TODO: GIFTCARD: Con nuevos medios de pago: calcular descuentos GIFTCARD
                 */
            }
            String autorizador = ventana_padre.compruebaAutorizacion(Operaciones.CARGAR_GIFTCARD);

        } catch (SinPermisosException e) {
            log.debug("No se tiene permisos para realizar la operación sobre la Gift Card");
            ventana_padre.crearError("No tiene permisos para realizar la operación");
        } catch (GiftCardException e) {
            log.debug(e.getMessage());
            ventana_padre.crearError(e.getMessage());

        } catch (Exception e) {
            log.debug("Se produjo un error al realizar la operación", e);
            ventana_padre.crearError("Se produjo un error al realizar la operación");

        }
    }

    private void accionVolver() {
        ventana_padre.showView(JPrincipal.VISTA_INICIO);
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }

    // ACCIONES
    private void addFuntionKeysBotonesMenu() {

        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionVolver();
            }

        };
        addHotKey(f2, "IdentClientF2", listenerf2);

        KeyStroke f9 = KeyStroke.getKeyStroke(KeyEvent.VK_F9, 0);
        Action listenerf9 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCargar();
            }
        };
        addHotKey(f9, "IdentClientF9", listenerf9);

        KeyStroke f8 = KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0);
        Action listenerf8 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionLecturaManual();
            }
        };
        addHotKey(f8, "IdentClientF8", listenerf8);

    }

    public void setCliente(Cliente cliente) {
        log.debug("setCliente() establecemos el cliente ");
        this.cliente = cliente;
        estaEnPasoRecarga = true;
        if (cliente != null) {
            t_carga.setValidacionHabilitada(true);
            p_carga.setVisible(true);
            t_carga.requestFocus();
            t_carga.setEnabled(true);
        }
    }

    private void accionLecturaManual() {
        try {
            String autorizador = ventana_padre.compruebaAutorizacion(Operaciones.LECTURA_GIFTCARD, "<html>La tarjeta requiere autorización<br> para su lectura manual</html>");
            l_introducir_gift.setVisible(true);
            t_introducir_gift.setVisible(true);
            t_introducir_gift.setText("");
            t_introducir_gift.setEditable(true);
            // Ocultar datos de trajeta leida previamente            
            resetearFormulario();
            t_introducir_gift.requestFocus();
        } catch (SinPermisosException ex) {
            log.debug("No se tiene permisos para realizar la lectura manual de la Gift Card");
            ventana_padre.crearError("No tiene permisos para realizar la operación");
        }
    }

    private void ocultarCampos() {
        /* t_introducir_gift.setVisible(false);
        l_introducir_gift.setVisible(false);
        t_introducir_gift.setText("");*/
        //   b_lectura_manual.setVisible(false);
        t_introducir_gift.setText("");
        t_introducir_gift.requestFocus();
    }

    private void limpiarCampos() {
        /* t_introducir_gift.setVisible(false);
        l_introducir_gift.setVisible(false);
        t_introducir_gift.setText("");*/
        //   b_lectura_manual.setVisible(false);
        l_introducir_gift.setVisible(true);
        t_introducir_gift.setVisible(true);
        t_introducir_gift.setText("");
        t_introducir_gift.setEditable(true);
        // Ocultar datos de trajeta leida previamente            
        resetearFormulario();
        t_introducir_gift.requestFocus();
    }
}
