/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.comerzzia.jpos.gui.cajas.anulaciones;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.servicios.anulaciones.AnulacionesServices;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import es.mpsistemas.util.log.Logger;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;

/**
 *
 * @author SMLM
 */
public class JAnulaciones extends JVentanaDialogo{

    private static Logger log = Logger.getMLogger(JAnulaciones.class);
    /**
     * Creates new form JAnulaciones
     */
    public JAnulaciones() {
        super();
        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_menu.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
        }
        catch (Exception e) {
        }        
        initComponents();
        addFunctionKeys();
        
        // Anulación de Documentos
        v_anulacion_documento.setLocationRelativeTo(null);
        p_anulacion_documento.setContenedor(v_anulacion_documento);
        
        // Anulación de Documentos con Abono
        v_anulacion_documento_abono.setLocationRelativeTo(null);
        p_anulacion_documento_abono.setContenedor(v_anulacion_documento_abono);
        
        // Anulación de Documentos con Recibo
        v_anulacion_documento_recibo.setLocationRelativeTo(null);
        p_anulacion_documento_recibo.setContenedor(v_anulacion_documento_recibo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_anulacion_documento = new javax.swing.JDialog();
        p_anulacion_documento = new com.comerzzia.jpos.gui.cajas.anulaciones.JAnulacionDocumento();
        v_anulacion_documento_abono = new javax.swing.JDialog();
        p_anulacion_documento_abono = new com.comerzzia.jpos.gui.cajas.anulaciones.JAnulacionDocumentoConAbono();
        v_anulacion_documento_recibo = new javax.swing.JDialog();
        p_anulacion_documento_recibo = new com.comerzzia.jpos.gui.cajas.anulaciones.JAnulacionDocumentoRecibo();
        b_boton3 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_boton4 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        l_titulo = new javax.swing.JLabel();
        b_boton5 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_boton6 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_boton7 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_boton8 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_boton9 = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        v_anulacion_documento.setAlwaysOnTop(true);
        v_anulacion_documento.setMinimumSize(new java.awt.Dimension(520,400));

        javax.swing.GroupLayout v_anulacion_documentoLayout = new javax.swing.GroupLayout(v_anulacion_documento.getContentPane());
        v_anulacion_documento.getContentPane().setLayout(v_anulacion_documentoLayout);
        v_anulacion_documentoLayout.setHorizontalGroup(
            v_anulacion_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_anulacion_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        v_anulacion_documentoLayout.setVerticalGroup(
            v_anulacion_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_anulacion_documento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        v_anulacion_documento_abono.setAlwaysOnTop(true);
        v_anulacion_documento_abono.setMinimumSize(new java.awt.Dimension(520,470));

        javax.swing.GroupLayout v_anulacion_documento_abonoLayout = new javax.swing.GroupLayout(v_anulacion_documento_abono.getContentPane());
        v_anulacion_documento_abono.getContentPane().setLayout(v_anulacion_documento_abonoLayout);
        v_anulacion_documento_abonoLayout.setHorizontalGroup(
            v_anulacion_documento_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_anulacion_documento_abonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_anulacion_documento_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_anulacion_documento_abonoLayout.setVerticalGroup(
            v_anulacion_documento_abonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_anulacion_documento_abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        v_anulacion_documento_recibo.setAlwaysOnTop(true);
        v_anulacion_documento_recibo.setMinimumSize(new java.awt.Dimension(520,390));

        p_anulacion_documento_recibo.setRequestFocusEnabled(false);

        javax.swing.GroupLayout v_anulacion_documento_reciboLayout = new javax.swing.GroupLayout(v_anulacion_documento_recibo.getContentPane());
        v_anulacion_documento_recibo.getContentPane().setLayout(v_anulacion_documento_reciboLayout);
        v_anulacion_documento_reciboLayout.setHorizontalGroup(
            v_anulacion_documento_reciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_anulacion_documento_reciboLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_anulacion_documento_recibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        v_anulacion_documento_reciboLayout.setVerticalGroup(
            v_anulacion_documento_reciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_anulacion_documento_reciboLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_anulacion_documento_recibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        b_boton3.setMnemonic('D');
        b_boton3.setText("Anular Pago Credito Directo");
        b_boton3.setAlignmentY(0.2F);
        b_boton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton3ActionPerformed(evt);
            }
        });

        b_boton4.setMnemonic('G');
        b_boton4.setText("Anular Compra GiftCard");
        b_boton4.setAlignmentY(0.2F);
        b_boton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton4ActionPerformed(evt);
            }
        });

        l_titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        l_titulo.setForeground(new java.awt.Color(-4144960,true));
        l_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_titulo.setText("MENÚ DE ANULACIONES");

        b_boton5.setMnemonic('R');
        b_boton5.setText("Anular Recarga GiftCard");
        b_boton5.setAlignmentY(0.2F);
        b_boton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton5ActionPerformed(evt);
            }
        });

        b_boton6.setMnemonic('T');
        b_boton6.setText("Anular Pago Credito Temporal");
        b_boton6.setAlignmentY(0.2F);
        b_boton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton6ActionPerformed(evt);
            }
        });

        b_boton7.setMnemonic('v');
        b_boton7.setText("Anular Recibo Abono Reservacion");
        b_boton7.setAlignmentY(0.2F);
        b_boton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton7ActionPerformed(evt);
            }
        });

        b_boton8.setMnemonic('P');
        b_boton8.setText("Anular Recibo Abono Plan Novio");
        b_boton8.setAlignmentY(0.2F);
        b_boton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton8ActionPerformed(evt);
            }
        });

        b_boton9.setMnemonic('B');
        b_boton9.setText("Anular Bono Anulacion Reservacion");
        b_boton9.setAlignmentY(0.2F);
        b_boton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_boton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_boton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_boton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_boton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_boton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_boton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_boton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_boton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_boton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_boton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_boton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton3ActionPerformed
        crearVentanaAnulacion(AnulacionesServices.CREDITO_ABONO);
    }//GEN-LAST:event_b_boton3ActionPerformed

    private void b_boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton4ActionPerformed
        crearVentanaAnulacion(AnulacionesServices.COMP_GIFTCARD);
    }//GEN-LAST:event_b_boton4ActionPerformed

    private void b_boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton5ActionPerformed
        crearVentanaAnulacion(AnulacionesServices.RECA_GIFTCARD);
    }//GEN-LAST:event_b_boton5ActionPerformed

    private void b_boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton6ActionPerformed
        crearVentanaAnulacion(AnulacionesServices.LETRA_ABONO);
    }//GEN-LAST:event_b_boton6ActionPerformed

    private void b_boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton7ActionPerformed
        crearVentanaAnulacionConAbono(AnulacionesServices.ABONO_RESERVA);
    }//GEN-LAST:event_b_boton7ActionPerformed

    private void b_boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton8ActionPerformed
        crearVentanaAnulacionConAbono(AnulacionesServices.ABONO_PLAN_NOVIO);
    }//GEN-LAST:event_b_boton8ActionPerformed

    private void b_boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton9ActionPerformed
        crearVentanaAnulacionConRecibo(AnulacionesServices.BONO_RESERVA);
    }//GEN-LAST:event_b_boton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton3;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton4;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton5;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton6;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton7;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton8;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton9;
    private javax.swing.JLabel l_titulo;
    private com.comerzzia.jpos.gui.cajas.anulaciones.JAnulacionDocumento p_anulacion_documento;
    private com.comerzzia.jpos.gui.cajas.anulaciones.JAnulacionDocumentoConAbono p_anulacion_documento_abono;
    private com.comerzzia.jpos.gui.cajas.anulaciones.JAnulacionDocumentoRecibo p_anulacion_documento_recibo;
    private javax.swing.JDialog v_anulacion_documento;
    private javax.swing.JDialog v_anulacion_documento_abono;
    private javax.swing.JDialog v_anulacion_documento_recibo;
    // End of variables declaration//GEN-END:variables

    private void crearVentanaAnulacion(String tipo) {
        cerrarVentana();
        p_anulacion_documento.setTipo(tipo);
        v_anulacion_documento.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        v_anulacion_documento.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);        
        p_anulacion_documento.iniciaVista();
        v_anulacion_documento.setVisible(true);  
    }    
    
    private void crearVentanaAnulacionConAbono(String tipo) {
        cerrarVentana();
        p_anulacion_documento_abono.setTipo(tipo);
        v_anulacion_documento_abono.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        v_anulacion_documento_abono.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);        
        p_anulacion_documento_abono.iniciaVista();
        v_anulacion_documento_abono.setVisible(true);          
    }
    
    private void crearVentanaAnulacionConRecibo(String tipo) {
        cerrarVentana();
        p_anulacion_documento_recibo.setTipo(tipo);
        v_anulacion_documento_recibo.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        v_anulacion_documento_recibo.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);        
        p_anulacion_documento_recibo.iniciaVista();
        v_anulacion_documento_recibo.setVisible(true);          
    }    
    
    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
    
    public void iniciaVista(){
        l_titulo.setText("MENU DE ANULACIONES");
        b_boton3.requestFocus();
    }
    
    private void addFunctionKeys() {
        // ENTER EN LOS BOTONES
        addHotKey(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "EnterBotones", listenerEnter);

        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
    }
    
}
