/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPagarCreditoDirecto.java
 *
 * Created on 02-oct-2012, 12:34:12
 */
package com.comerzzia.jpos.gui.credito.tarjeta;

import com.comerzzia.jpos.servicios.credito.CreditoDirectoBean;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.credito.JOperacionesTarjeta;
import com.comerzzia.jpos.gui.reservaciones.JReservacionesPagosV;
import com.comerzzia.jpos.servicios.tickets.TicketS;
import es.mpsistemas.util.log.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.net.URL;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.KeyStroke;

/**
 *
 * @author MGRI
 */
public class JPagarCreditoDirecto extends JVentanaDialogo {

    private CreditoDirectoBean datosCredito;
    private static Logger log = Logger.getMLogger(JPagarCreditoDirecto.class);

    /** Creates new form JPagarCreditoDirecto */
    public JPagarCreditoDirecto() {

        try {
            initComponents();
            
            registrarEventoLeerTarjeta();
            mostrarFormulario();
            registraEventoEnterBoton();
            addFunctionKeys();

            URL myurl;
            myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
            ImageIcon icon = new ImageIcon(myurl);

            v_pagos.setLocationRelativeTo(null);
            v_pagos.setIconImage(icon.getImage());
            p_pagos.setContenedor(v_pagos);
        }
        catch (Exception e) {
            log.error("Error incicializando ventana JPagarCreditoDirecto :" + e.getMessage(), e);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_pagos = new javax.swing.JDialog();
        p_pagos = new com.comerzzia.jpos.gui.reservaciones.JReservacionesPagosV();
        sesion1 = new com.comerzzia.jpos.servicios.login.Sesion();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l_total_a_pagar = new javax.swing.JLabel();
        l_cupo_disponible = new javax.swing.JLabel();
        l_fecha_de_corte = new javax.swing.JLabel();
        l_nombre = new javax.swing.JLabel();
        lb_error = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_cantidad_abonar = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_observaciones = new com.comerzzia.jpos.gui.components.form.JTextAreaForm();
        b_m_menu_principal = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_menu_principal1 = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        v_pagos.setMinimumSize(new java.awt.Dimension(1024, 660));
        v_pagos.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        v_pagos.setLocationRelativeTo(null);
        v_pagos.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                v_pagosWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout v_pagosLayout = new javax.swing.GroupLayout(v_pagos.getContentPane());
        v_pagos.getContentPane().setLayout(v_pagosLayout);
        v_pagosLayout.setHorizontalGroup(
            v_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_pagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_pagosLayout.setVerticalGroup(
            v_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_pagosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+7));
        jLabel1.setText("PAGAR CRÉDITO DIRECTO");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD, jLabel6.getFont().getSize()+7));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Total a Pagar:");

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()+7f));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Cupo Disponible:");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()+2f));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Fecha de corte:");

        l_total_a_pagar.setFont(l_total_a_pagar.getFont().deriveFont(l_total_a_pagar.getFont().getStyle() | java.awt.Font.BOLD, l_total_a_pagar.getFont().getSize()+7));
        l_total_a_pagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_total_a_pagar.setText("$ 19.90");

        l_cupo_disponible.setFont(l_cupo_disponible.getFont().deriveFont(l_cupo_disponible.getFont().getSize()+7f));
        l_cupo_disponible.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_cupo_disponible.setText("$ 680.10");

        l_fecha_de_corte.setFont(l_fecha_de_corte.getFont().deriveFont(l_fecha_de_corte.getFont().getSize()+2f));
        l_fecha_de_corte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_fecha_de_corte.setText("30 de cada mes");

        l_nombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_nombre.setText("Gabriela Gavilanes");

        lb_error.setForeground(new java.awt.Color(255, 0, 0));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_error.setText("Tarjeta de identificación incorrecta");
        lb_error.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Nombre:");

        jLabel10.setDisplayedMnemonic('a');
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setLabelFor(t_cantidad_abonar);
        jLabel10.setText("Cantidad que desea abonar:");

        t_cantidad_abonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cantidad_abonarActionPerformed(evt);
            }
        });

        jLabel11.setDisplayedMnemonic('o');
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setLabelFor(t_observaciones);
        jLabel11.setText("Observaciones:");

        t_observaciones.setColumns(20);
        t_observaciones.setRows(5);
        jScrollPane1.setViewportView(t_observaciones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(l_cupo_disponible, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l_total_a_pagar, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addComponent(l_fecha_de_corte, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_cantidad_abonar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(115, 115, 115)))
                .addGap(343, 343, 343))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(l_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(l_fecha_de_corte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(l_total_a_pagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(l_cupo_disponible))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(t_cantidad_abonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        b_m_menu_principal.setText("<html><center>Volver <br/>F2</center></html>");
        b_m_menu_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_menu_principalActionPerformed(evt);
            }
        });

        b_m_menu_principal1.setText("<html><center>Pagos <br/>F9</center></html>");
        b_m_menu_principal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_menu_principal1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(b_m_menu_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_m_menu_principal1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_m_menu_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_m_menu_principal1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_m_menu_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_menu_principalActionPerformed
        if (b_m_menu_principal.isEnabled()) {
            cerrarVentana();
            JOperacionesTarjeta.getInstance().crearVentanaConsultaCreditoDirecto(datosCredito);            
            datosCredito = null;
            //super.getVentanaPadreJPrincipal().crearVentanaMenuTarjetas();
        }
}//GEN-LAST:event_b_m_menu_principalActionPerformed

    private void b_m_menu_principal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_menu_principal1ActionPerformed

        lb_error.setText("");

        BigDecimal importeIntroducido = null;;
        try {
            importeIntroducido = new BigDecimal(t_cantidad_abonar.getText());
            if (importeIntroducido.compareTo(BigDecimal.ZERO) <= 0) {
                importeIntroducido = null;
                throw new NumberFormatException();
            }
//            if (datosCredito.getTotalAPagar()!=null &&  importeIntroducido.compareTo(datosCredito.getTotalAPagar()) > 0) {
//                importeIntroducido = null;
//                throw new NumberFormatException();
//            };

        }
        catch (NumberFormatException e) {
            log.debug("La cantidad introducida no es un importe válido");
            lb_error.setText("La cantidad introducida no es un importe válido");
        }
        if (t_observaciones.getText().length() > 400){
            lb_error.setText("El tamaño máximo de observaciones son 400 caracteres.");
            return;
        }
        
        // Accedemos a pago
        if (importeIntroducido != null) {
            contenedor.setVisible(false);
            crearVentanaPagos(datosCredito, importeIntroducido);
            limpiarFormulario();
        }

}//GEN-LAST:event_b_m_menu_principal1ActionPerformed

    private void t_cantidad_abonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cantidad_abonarActionPerformed
    }//GEN-LAST:event_t_cantidad_abonarActionPerformed

    private void v_pagosWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_v_pagosWindowOpened
        p_pagos.iniciaFoco();
}//GEN-LAST:event_v_pagosWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_menu_principal;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_menu_principal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_cupo_disponible;
    private javax.swing.JLabel l_fecha_de_corte;
    private javax.swing.JLabel l_nombre;
    private javax.swing.JLabel l_total_a_pagar;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.gui.reservaciones.JReservacionesPagosV p_pagos;
    private com.comerzzia.jpos.servicios.login.Sesion sesion1;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_cantidad_abonar;
    private com.comerzzia.jpos.gui.components.form.JTextAreaForm t_observaciones;
    private javax.swing.JDialog v_pagos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
        //datosCredito = null;
        t_cantidad_abonar.setText("");
        t_observaciones.setText("");
        l_cupo_disponible.setText("");
        l_fecha_de_corte.setText("");
        l_nombre.setText("");
        l_total_a_pagar.setText("");
        lb_error.setText("");

    }

    public void iniciaVista() {
        limpiarFormulario();
        iniciaFoco();
    }

    void iniciaFoco() {
        t_cantidad_abonar.requestFocus();
    }

    @Override
    public void accionLeerTarjetaVD() {
        // Esta ventana de dialogo tiene implementada la opción de lectura de tarjeta
        if (getTramaTarjeta() != null) {
            this.getVentana_padre().crearInformacion(getTramaTarjeta());
        }
        else {
            this.getVentana_padre().crearError("no se pudo leer la trama");
        }
    }

    public void mostrarFormulario() {
        if (datosCredito != null) {
            
            if (datosCredito.getFechaDeCorte() > 0  ){
                l_fecha_de_corte.setText("" + datosCredito.getFechaDeCorte() + " de cada mes");}
            else{
                l_fecha_de_corte.setText("---");
            }
            
            l_cupo_disponible.setText("$ " + datosCredito.getPlastico().getCupo().getCupo());
            
            if (datosCredito.getTotalAPagar() != null){
                l_total_a_pagar.setText("$ " + datosCredito.getTotalAPagar().toString());
            }
            else{
                l_total_a_pagar.setText("---");
            }
            l_nombre.setText(datosCredito.getPlastico().getCliente().getNombreYApellidos());
        }
    }

    public CreditoDirectoBean getDatosCredito() {
        return datosCredito;
    }

    public void setDatosCredito(CreditoDirectoBean datosCredito) {
        this.datosCredito = datosCredito;
    }
    
    private String parseaXML(String sIn){
        String res = sIn;
        res = res.replaceAll("&", "&amp;");
        res = res.replaceAll("<","&lt;");
        res = res.replaceAll(">","&gt;");
        return res;
    }    

    public void crearVentanaPagos(CreditoDirectoBean credito, BigDecimal importe) {
        log.debug("creción de la ventana de pagos");
        v_pagos.getContentPane().removeAll();

        TicketS ticket = new TicketS();
        ticket.setCliente(credito.getPlastico().getCliente());
        ticket.inicializaTotales(importe);
        ticket.setObservaciones(parseaXML(t_observaciones.getText()));
        p_pagos = new JReservacionesPagosV(credito, ticket);
        javax.swing.GroupLayout v_pagosLayout = new javax.swing.GroupLayout(v_pagos.getContentPane());
        v_pagos.getContentPane().setLayout(v_pagosLayout);
        v_pagosLayout.setHorizontalGroup(
                v_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(v_pagosLayout.createSequentialGroup().addContainerGap().addComponent(p_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        v_pagosLayout.setVerticalGroup(
                v_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_pagosLayout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(p_pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        p_pagos.setContenedor(v_pagos);
        v_pagos.getContentPane().add(p_pagos);
        v_pagos.requestFocus();
        p_pagos.iniciaVista();
        v_pagos.setVisible(true);
    }

    private void addFunctionKeys() {
        KeyStroke f9 = KeyStroke.getKeyStroke(KeyEvent.VK_F9, 0);
        Action listenerf9 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {

                b_m_menu_principal1ActionPerformed(ae);
            }
        };
        addHotKey(f9, "IdentClientF4", listenerf9);

        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {

                b_m_menu_principalActionPerformed(ae);
            }
        };
        addHotKey(f2, "IdentClientF2", listenerf2);
    }
    
    
}
