/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JGestionCajas.java
 *
 * Created on 08-ago-2011, 14:35:03
 */
package com.comerzzia.jpos.gui.cajas;

import com.comerzzia.jpos.gui.IManejadorErrores;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.gui.cajas.modelos.MovimientosTableCellRenderer;
import com.comerzzia.jpos.gui.cajas.modelos.MovimientosTableModel;
import com.comerzzia.jpos.servicios.core.permisos.Operaciones;
import com.comerzzia.jpos.servicios.core.permisos.SinPermisosException;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import es.mpsistemas.util.log.Logger;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Dialog.ModalExclusionType;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author MGRI
 */
public class JGestionCajas extends JPanelImagenFondo implements IVista {

    private static Logger log = Logger.getMLogger(JGestionCajas.class);
    private JPrincipal ventana_padre = null;

    /** Creates new form JGestionCajas */
    public JGestionCajas() {
        super();
        initComponents();
        addFunctionKeys();
    }

    public JGestionCajas(JPrincipal ventana_padre) {
        super();
        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_gest-caja.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
        }
        catch (IOException ex) {
            log.error("Error cargando la imagen de fondo.");
        }
        this.ventana_padre = ventana_padre;

        initComponents();
        
        URL myurl;
        
            myurl= this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
        ImageIcon icon=new ImageIcon(myurl);
        v_abrir_caja.setIconImage(icon.getImage());
        v_abrir_caja.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
        v_anulaciones.setIconImage(icon.getImage());
        v_anulaciones.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
        v_prestamos.setIconImage(icon.getImage());
        
        // Iniciamos la ventana de insertar apunte
        p_anulaciones.setVentana_padre(this.ventana_padre);
        p_anulaciones.setContenedor(v_anulaciones);
        
       // Iniciamos la ventana de prestamos
        p_prestamos.setVentana_padre(this.ventana_padre);
        p_prestamos.setContenedor(v_prestamos);
        
        // Iniciamos la ventana de Abrir Caja
        p_apertura_caja.setVentana_padre((IManejadorErrores) this.ventana_padre);
        p_apertura_caja.setContenedor(v_abrir_caja);

        // Borde vacio ara tablas, Viewports y scrollpanels
        Border empty = new EmptyBorder(0, 0, 0, 0);
        // Iniciamos la tabla de movimientos        
        tb_movimientos.setDefaultRenderer(Object.class, new MovimientosTableCellRenderer());

        js_tb_movimientos.setViewportBorder(empty);
        tb_movimientos.setBorder(empty);
        js_tb_movimientos.getViewport().setOpaque(false);

        //Iniciamos la tabla de ventas
        tb_ventas.setDefaultRenderer(Object.class, new MovimientosTableCellRenderer());

        js_tb_ventas.setViewportBorder(empty);
        tb_ventas.setBorder(empty);
        js_tb_ventas.getViewport().setOpaque(false);
        addFunctionKeys();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_abrir_caja = new javax.swing.JDialog();
        new JAperturaCaja(this.ventana_padre,v_abrir_caja);
        p_apertura_caja = new com.comerzzia.jpos.gui.cajas.JAperturaCaja();
        v_prestamos = new javax.swing.JDialog();
        p_prestamos = new com.comerzzia.jpos.gui.cajas.JPrestamos();
        v_anulaciones = new javax.swing.JDialog();
        p_anulaciones = new com.comerzzia.jpos.gui.cajas.anulaciones.JAnulaciones();
        m_ventas = new javax.swing.JPanel();
        b_cerrar_caja = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_insertar_apunte = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_menu_ppal = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_prestamos = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        tp_panel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        js_tb_movimientos = new javax.swing.JScrollPane();
        tb_movimientos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        js_tb_ventas = new javax.swing.JScrollPane();
        tb_ventas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lb_estado_caja = new javax.swing.JLabel();

        v_abrir_caja.setAlwaysOnTop(true);
        v_abrir_caja.setMinimumSize(new java.awt.Dimension(494, 198));
        v_abrir_caja.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        javax.swing.GroupLayout v_abrir_cajaLayout = new javax.swing.GroupLayout(v_abrir_caja.getContentPane());
        v_abrir_caja.getContentPane().setLayout(v_abrir_cajaLayout);
        v_abrir_cajaLayout.setHorizontalGroup(
            v_abrir_cajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_abrir_cajaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_apertura_caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_abrir_cajaLayout.setVerticalGroup(
            v_abrir_cajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_abrir_cajaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_apertura_caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        v_prestamos.setAlwaysOnTop(true);
        v_prestamos.setMinimumSize(new java.awt.Dimension(568, 340));
        v_prestamos.setModal(true);
        v_prestamos.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        v_prestamos.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                v_prestamosWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        javax.swing.GroupLayout v_prestamosLayout = new javax.swing.GroupLayout(v_prestamos.getContentPane());
        v_prestamos.getContentPane().setLayout(v_prestamosLayout);
        v_prestamosLayout.setHorizontalGroup(
            v_prestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_prestamosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        v_prestamosLayout.setVerticalGroup(
            v_prestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_prestamosLayout.createSequentialGroup()
                .addComponent(p_prestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        v_anulaciones.setAlwaysOnTop(true);
        v_anulaciones.setMinimumSize(new java.awt.Dimension(335, 550));

        p_anulaciones.setMinimumSize(new java.awt.Dimension(335, 540));
        p_anulaciones.setPreferredSize(new java.awt.Dimension(331, 550));

        javax.swing.GroupLayout v_anulacionesLayout = new javax.swing.GroupLayout(v_anulaciones.getContentPane());
        v_anulaciones.getContentPane().setLayout(v_anulacionesLayout);
        v_anulacionesLayout.setHorizontalGroup(
            v_anulacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_anulaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        v_anulacionesLayout.setVerticalGroup(
            v_anulacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_anulaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1024, 723));
        setMinimumSize(new java.awt.Dimension(1024, 723));
        setPreferredSize(new java.awt.Dimension(1024, 723));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m_ventas.setBackground(new java.awt.Color(255, 255, 255));
        m_ventas.setOpaque(false);
        m_ventas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_cerrar_caja.setText("<html><center> Arqueo de Caja<br/>F3</center></html>");
        b_cerrar_caja.setActionCommand("Identificar Cliente F3");
        b_cerrar_caja.setMargin(new java.awt.Insets(2, 9, 2, 9));
        b_cerrar_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cerrar_cajaActionPerformed(evt);
            }
        });
        m_ventas.add(b_cerrar_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 57));

        b_insertar_apunte.setText("<html><center>Anulaciones <br/>F4</center></html>");
        b_insertar_apunte.setMargin(new java.awt.Insets(2, 5, 2, 5));
        b_insertar_apunte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_insertar_apunteActionPerformed(evt);
            }
        });
        m_ventas.add(b_insertar_apunte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 57));

        b_menu_ppal.setText("<html><center>Menú Principal <br/>F12</center></html>");
        b_menu_ppal.setMargin(new java.awt.Insets(2, 9, 2, 9));
        b_menu_ppal.setNextFocusableComponent(b_insertar_apunte);
        b_menu_ppal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_menu_ppalActionPerformed(evt);
            }
        });
        m_ventas.add(b_menu_ppal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, 57));

        b_prestamos.setText("<html><center>Préstamos <br/>F5</center></html>");
        b_prestamos.setMargin(new java.awt.Insets(2, 5, 2, 5));
        b_prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_prestamosActionPerformed(evt);
            }
        });
        m_ventas.add(b_prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 57));

        add(m_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 410, -1));

        jPanel1.setOpaque(false);

        js_tb_movimientos.setBorder(null);

        tb_movimientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Entradas", "Salidas", "Documento", "Concepto", "F. Pago"
            }
        ));
        tb_movimientos.setOpaque(false);
        js_tb_movimientos.setViewportView(tb_movimientos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_tb_movimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_tb_movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_panel.addTab("<html><u>M</u>OVIMIENTOS</html>", jPanel1);

        jPanel2.setOpaque(false);

        js_tb_ventas.setBorder(null);

        tb_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Entradas", "Salidas", "Documento", "Concepto", "F. Pago"
            }
        ));
        tb_ventas.setOpaque(false);
        js_tb_ventas.setViewportView(tb_ventas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_tb_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_tb_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp_panel.addTab("<html><u>V</u>ENTAS</html>", jPanel2);

        add(tp_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 980, 470));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("GESTIÓN DE CAJAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 317, -1));

        lb_estado_caja.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lb_estado_caja.setForeground(new java.awt.Color(0, 0, 255));
        lb_estado_caja.setText("Caja Abierta desde el ");
        add(lb_estado_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 410, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void b_cerrar_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cerrar_cajaActionPerformed
        accionCerrarCaja();
}//GEN-LAST:event_b_cerrar_cajaActionPerformed

    private void b_insertar_apunteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_insertar_apunteActionPerformed

        accionInsertarApunte();
        }//GEN-LAST:event_b_insertar_apunteActionPerformed

    private void b_menu_ppalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_menu_ppalActionPerformed
        accionMenu();
}//GEN-LAST:event_b_menu_ppalActionPerformed

    private void b_prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_prestamosActionPerformed
        accionPrestamos();
    }//GEN-LAST:event_b_prestamosActionPerformed

    private void v_prestamosWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_v_prestamosWindowGainedFocus
        p_prestamos.iniciaFoco();
    }//GEN-LAST:event_v_prestamosWindowGainedFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cerrar_caja;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_insertar_apunte;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_menu_ppal;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_prestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane js_tb_movimientos;
    private javax.swing.JScrollPane js_tb_ventas;
    private javax.swing.JLabel lb_estado_caja;
    private javax.swing.JPanel m_ventas;
    private com.comerzzia.jpos.gui.cajas.anulaciones.JAnulaciones p_anulaciones;
    private com.comerzzia.jpos.gui.cajas.JAperturaCaja p_apertura_caja;
    private com.comerzzia.jpos.gui.cajas.JPrestamos p_prestamos;
    private javax.swing.JTable tb_movimientos;
    private javax.swing.JTable tb_ventas;
    private javax.swing.JTabbedPane tp_panel;
    private javax.swing.JDialog v_abrir_caja;
    private javax.swing.JDialog v_anulaciones;
    private javax.swing.JDialog v_prestamos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciaVista() {
        refrescaVista();
        JPrincipal.setPanelActivo(this);
        if (b_insertar_apunte.isEnabled()) {
            b_insertar_apunte.requestFocus();
        }
        else {
            b_menu_ppal.requestFocus();
        }
    }

    private void refrescaVista() {
        try {
            tb_movimientos.setModel(new MovimientosTableModel(Sesion.getCajaActual().consultaMovimientos()));
            tb_ventas.setModel(new MovimientosTableModel(Sesion.getCajaActual().consultaVentas()));
            resfrescaNavegación();
        }
        catch (Exception e) {
            log.error("Error refrescando vista");
            ventana_padre.crearError("Error refrescando vista");
        }
    }

    private void resfrescaNavegación() {
        if (Sesion.getCajaActual().isCajaAbierta()) {
            if (Sesion.getCajaActual().isCajaParcialAbierta()) {
                b_insertar_apunte.setEnabled(true);
            }
            else {
                b_insertar_apunte.setEnabled(false);
            }

            b_cerrar_caja.setEnabled(true);
            lb_estado_caja.setText("Caja Abierta desde el " + formateadorFecha.format((Sesion.getCajaActual().getCajaActual().getFechaApertura())));
            lb_estado_caja.setForeground(Color.blue);

        }
        else {

            //b_cerrar_caja.setEnabled(false);
            b_insertar_apunte.setEnabled(false);
            lb_estado_caja.setText("La caja esta Cerrada");
            lb_estado_caja.setForeground(Color.red);
        }
    }

    /* EVENTOS*/
    private void addFunctionKeys() {

        // ENTER EN LOS BOTONES
        addHotKey(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "EnterBotones", listenerEnter);

        KeyStroke f3 = KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0);
        Action listenerf3 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCerrarCaja();

            }
        };
        addHotKey(f3, "CCajaF3", listenerf3);

        KeyStroke f4 = KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0);
        Action listenerf4 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionInsertarApunte();
            }
        };
        addHotKey(f4, "CCajaF4", listenerf4);

        KeyStroke f5 = KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0);
        Action listenerf5 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionPrestamos();
            }
        };
        addHotKey(f5, "CCajaF5", listenerf5);

        KeyStroke f12 = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        Action listenerf12 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionMenu();
            }
        };
        addHotKey(f12, "MenuF12", listenerf12);

        // ALT+M
        KeyStroke altm = KeyStroke.getKeyStroke(KeyEvent.VK_M, InputEvent.ALT_MASK);
        Action listeneraltm = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                tp_panel.setSelectedIndex(0);
            }
        };
        addHotKey(altm, "IdentClientalt7", listeneraltm);

        // ALT+V
        KeyStroke altv = KeyStroke.getKeyStroke(KeyEvent.VK_V, InputEvent.ALT_MASK);
        Action listeneraltv = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                tp_panel.setSelectedIndex(1);
            }
        };
        addHotKey(altv, "IdentClientaltv", listeneraltv);

    }

    public void addHotKey(KeyStroke keyStroke, String inputActionKey, Action listener) {
        ActionMap actionMap = this.getActionMap();
        InputMap inputMap = this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(keyStroke, inputActionKey);
        actionMap.put(inputActionKey, listener);
    }

    /* ACCIONES */
    private void accionAbrirCaja() {
        if (!Sesion.getCajaActual().isCajaAbierta()) {
            try {
                v_abrir_caja.setLocationRelativeTo(null);
                v_abrir_caja.setVisible(true);
                refrescaVista();
            }
            catch (Exception e) {
                ventana_padre.crearError(null);
            }
        }
    }

    private void accionCerrarCaja() {
        log.info("ACCION CERRAR CAJA");
        try {
            ventana_padre.addCierreCajaView();
            ventana_padre.showView("cierre_caja");
        }
        catch (Exception e) {
            log.error ("Error Cerrando la Caja :"+e.getMessage(),e);
            ventana_padre.crearError(null);
        }

    }

    private void accionInsertarApunte() {
        log.debug("ACCION ANULACIONES");
        if (Sesion.getCajaActual().isCajaAbierta()) {            
            try {
                String autorizador = ventana_padre.compruebaAutorizacion(Operaciones.ANULAR_DOCUMENTOS);
                Sesion.setAutorizadorAnulacion(autorizador);
                v_anulaciones.setLocationRelativeTo(null);
                v_anulaciones.setResizable(false);
                v_anulaciones.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
                v_anulaciones.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);      
                p_anulaciones.setVentana_padre(JPrincipal.getInstance());             
                if(!v_anulaciones.isUndecorated()){
                    v_anulaciones.setUndecorated(true);
                }      
                v_anulaciones.setVisible(true);
                p_anulaciones.iniciaVista();
            }
            catch(SinPermisosException e){
                log.debug("El usuario no tiene permisos para anular documentos");           
            }
            catch (Exception e) {
                log.error ("Error Insertando el apunte :"+e.getMessage(),e);
                ventana_padre.crearError("Se produjo un error al insertar el apunte de movimiento");
            }
            refrescaVista();
        }
    }

    private void accionMovimientos() {
        log.info("ACCION MOVIMIENTOS");
        try {
            ventana_padre.showView("movimientos");
        }
        catch (Exception e) {
            log.error ("Error  :"+e.getMessage(),e);
            ventana_padre.crearError(null);
        }
    }

    private void accionMenu() {
        log.info("ACCION MENÚ");
        try {
            ventana_padre.mostrarMenu();
        }
        catch (Exception e) {
            log.error ("Error  :"+e.getMessage(),e);
            ventana_padre.crearError(null);
        }
    }
        @Override
    public void iniciaFoco() {
        log.info("Iniciando Foco");
        b_cerrar_caja.requestFocus();
    }

    private void accionPrestamos() {
        log.info("ACCION PRESTAMO");
        if (Sesion.getCajaActual().isCajaAbierta()) {            
            try {
                
                p_prestamos.iniciaVista();
                v_prestamos.setLocationRelativeTo(null);
                v_prestamos.setVisible(true);
                if (p_prestamos.isInsertado()) {
                    ventana_padre.crearInformacion("Se ha realizado el préstamo");
                    p_prestamos.setInsertado(false);
                }
            }

            catch (Exception e) {
                log.error ("Error Insertando el apunte :"+e.getMessage(),e);
                ventana_padre.crearError("Se produjo un error al insertar el apunte de movimiento");
            }
            refrescaVista();
        }
    }
}
