/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JRecuentoCaja.java
 *
 * Created on 09-ago-2011, 8:18:20
 */
package com.comerzzia.jpos.gui.cajas;

import es.mpsistemas.util.log.Logger;
import com.comerzzia.jpos.entity.db.MedioPagoCaja;
import com.comerzzia.jpos.entity.db.RecuentoCajaDet;
import com.comerzzia.jpos.gui.IVentanaDialogo;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.cajas.modelos.RecuentoCajaTableCellRenderer;
import com.comerzzia.jpos.gui.cajas.modelos.RecuentoCajaTableModel;
import com.comerzzia.jpos.servicios.login.Sesion;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import com.comerzzia.jpos.gui.components.form.JButtonForm;
import com.comerzzia.jpos.persistencia.mediospagos.MedioPagoBean;
import com.comerzzia.jpos.servicios.mediospago.MediosPago;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import java.math.BigInteger;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MGRI
 */
public class JRecuentoCaja extends JVentanaDialogo implements IVista, IVentanaDialogo {

    private static final Logger log = Logger.getMLogger(JRecuentoCaja.class);
    private static final long serialVersionUID = 1L;
    private JPanel panel_pagos_activo = null;
    private RecuentoCajaDet lineaRecuento = null;
    private int lineaSelecionada;
    private RecuentoCajaTableCellRenderer tbRecuentosCellRenderer;
    private int paginaPagoTarjeta = 1;

    /** Creates new form JRecuentoCaja */
    public JRecuentoCaja() {
       super();
       initComponents();
    }

    public JRecuentoCaja(JPrincipal ventana_padre) {
        super();
        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_recuento-caja.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
        }
        catch (IOException ex) {
        }
        this.setVentana_padre(ventana_padre);
        initComponents();
        URL myurl;

        myurl = this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
        ImageIcon icon = new ImageIcon(myurl);
        v_modificar_importe.setIconImage(icon.getImage());

        inicializaPanel();
    }


     
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_modificar_importe = new javax.swing.JDialog();
        p_modificar_importe = new com.comerzzia.jpos.gui.components.JValor();
        p_principal = new com.comerzzia.jpos.gui.components.JPanelImagenFondo(true);
        js_tb_recuento_caja = new javax.swing.JScrollPane();
        tb_recuento_caja = new javax.swing.JTable();
        m_tipos_pagos = new javax.swing.JPanel();
        b_pago_efectivo = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_pago_contado = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_pago_tarjeta = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_pago_otros = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        m_edicion_pagos = new javax.swing.JPanel();
        b_m_borrar_linea_recuento = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        panel_superior = new javax.swing.JPanel();
        t_pagos_total = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        l_pagos_total = new javax.swing.JLabel();
        l_pagos_total1 = new javax.swing.JLabel();
        p_pago_contenedor = new javax.swing.JLayeredPane();
        p_pago_efectivo = new javax.swing.JPanel();
        t_pago_efectivo_total = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        l_pagos_efectivo_total = new javax.swing.JLabel();
        lb_tipo_recuento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t_denominacion_efectivo = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_simbolo_dolar = new javax.swing.JLabel();
        lb_cantidad = new javax.swing.JLabel();
        lb_denominacion = new javax.swing.JLabel();
        p_pago_tarjeta = new javax.swing.JPanel();
        p_pago_tarjeta_interno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p_pago_otros = new javax.swing.JPanel();
        p_pago_otros_interno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        p_pago_contado = new javax.swing.JPanel();
        p_pago_contado_interno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        v_modificar_importe.setAlwaysOnTop(true);
        v_modificar_importe.setMinimumSize(new java.awt.Dimension(400, 60));
        v_modificar_importe.setModal(true);

        javax.swing.GroupLayout v_modificar_importeLayout = new javax.swing.GroupLayout(v_modificar_importe.getContentPane());
        v_modificar_importe.getContentPane().setLayout(v_modificar_importeLayout);
        v_modificar_importeLayout.setHorizontalGroup(
            v_modificar_importeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_modificar_importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        v_modificar_importeLayout.setVerticalGroup(
            v_modificar_importeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_modificar_importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_principal.setMaximumSize(new java.awt.Dimension(840, 660));
        p_principal.setMinimumSize(new java.awt.Dimension(840, 660));
        p_principal.setOpaque(false);
        p_principal.setPreferredSize(new java.awt.Dimension(840, 660));
        p_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_recuento_caja.setModel(new com.comerzzia.jpos.gui.cajas.modelos.RecuentoCajaTableModel());
        tb_recuento_caja.setFocusCycleRoot(true);
        tb_recuento_caja.setGridColor(new java.awt.Color(153, 204, 255));
        tb_recuento_caja.setNextFocusableComponent(b_m_borrar_linea_recuento);
        tb_recuento_caja.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        js_tb_recuento_caja.setViewportView(tb_recuento_caja);

        p_principal.add(js_tb_recuento_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 650, 250));

        m_tipos_pagos.setOpaque(false);

        b_pago_efectivo.setText("<html><center> EFECTIVO  &nbsp;  ( F5 )</center></html>");
        b_pago_efectivo.setActionCommand("");
        b_pago_efectivo.setNextFocusableComponent(b_pago_contado);
        b_pago_efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pago_efectivoActionPerformed(evt);
            }
        });

        b_pago_contado.setText("<html><center> CONTADO &nbsp; ( F6 )</center></html>");
        b_pago_contado.setActionCommand("");
        b_pago_contado.setNextFocusableComponent(b_pago_tarjeta);
        b_pago_contado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pago_contadoActionPerformed(evt);
            }
        });

        b_pago_tarjeta.setText("<html><center> TARJETA  &nbsp; ( F7 )</center></html>");
        b_pago_tarjeta.setActionCommand("");
        b_pago_tarjeta.setNextFocusableComponent(b_pago_otros);
        b_pago_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pago_tarjetaActionPerformed(evt);
            }
        });

        b_pago_otros.setText("<html><center> OTROS  &nbsp; ( F8 )</center></html>");
        b_pago_otros.setActionCommand("");
        b_pago_otros.setNextFocusableComponent(t_pago_efectivo_total);
        b_pago_otros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pago_otrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout m_tipos_pagosLayout = new javax.swing.GroupLayout(m_tipos_pagos);
        m_tipos_pagos.setLayout(m_tipos_pagosLayout);
        m_tipos_pagosLayout.setHorizontalGroup(
            m_tipos_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_tipos_pagosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(m_tipos_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_pago_otros, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_pago_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_pago_contado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_pago_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        m_tipos_pagosLayout.setVerticalGroup(
            m_tipos_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_tipos_pagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_pago_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_pago_contado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_pago_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_pago_otros, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        p_principal.add(m_tipos_pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 240, 190));

        m_edicion_pagos.setOpaque(false);
        m_edicion_pagos.setPreferredSize(new java.awt.Dimension(490, 80));
        m_edicion_pagos.setRequestFocusEnabled(false);

        b_m_borrar_linea_recuento.setText("<html><center>Borrar Línea de Recuento <br/>F3</center></html>");
        b_m_borrar_linea_recuento.setNextFocusableComponent(b_pago_efectivo);
        b_m_borrar_linea_recuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_borrar_linea_recuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout m_edicion_pagosLayout = new javax.swing.GroupLayout(m_edicion_pagos);
        m_edicion_pagos.setLayout(m_edicion_pagosLayout);
        m_edicion_pagosLayout.setHorizontalGroup(
            m_edicion_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_edicion_pagosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_m_borrar_linea_recuento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        m_edicion_pagosLayout.setVerticalGroup(
            m_edicion_pagosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_edicion_pagosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(b_m_borrar_linea_recuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        p_principal.add(m_edicion_pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 120, 250));

        panel_superior.setOpaque(false);

        t_pagos_total.setEditable(false);
        t_pagos_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        l_pagos_total.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        l_pagos_total.setForeground(new java.awt.Color(0, 102, 255));
        l_pagos_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pagos_total.setText("$");

        l_pagos_total1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        l_pagos_total1.setForeground(new java.awt.Color(0, 102, 255));
        l_pagos_total1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_pagos_total1.setText("Total:");

        javax.swing.GroupLayout panel_superiorLayout = new javax.swing.GroupLayout(panel_superior);
        panel_superior.setLayout(panel_superiorLayout);
        panel_superiorLayout.setHorizontalGroup(
            panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_superiorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(l_pagos_total1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_pagos_total, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t_pagos_total, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_superiorLayout.setVerticalGroup(
            panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_superiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(t_pagos_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_pagos_total)
                    .addComponent(l_pagos_total1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_principal.add(panel_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 290, 40));

        p_pago_efectivo.setMaximumSize(new java.awt.Dimension(550, 180));
        p_pago_efectivo.setMinimumSize(new java.awt.Dimension(550, 180));
        p_pago_efectivo.setOpaque(false);

        t_pago_efectivo_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_pago_efectivo_total.setName("total"); // NOI18N
        t_pago_efectivo_total.setNextFocusableComponent(t_denominacion_efectivo);
        t_pago_efectivo_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_pago_efectivo_totalActionPerformed(evt);
            }
        });
        t_pago_efectivo_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_pago_efectivo_totalKeyTyped(evt);
            }
        });

        l_pagos_efectivo_total.setDisplayedMnemonic('r');
        l_pagos_efectivo_total.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        l_pagos_efectivo_total.setLabelFor(t_pago_efectivo_total);
        l_pagos_efectivo_total.setText("Recuento:");

        lb_tipo_recuento.setText("EFECTIVO:");

        jLabel1.setText("RECUENTO PARA ");

        t_denominacion_efectivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t_denominacion_efectivo.setName("total"); // NOI18N
        t_denominacion_efectivo.setNextFocusableComponent(b_ok);
        t_denominacion_efectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_pago_efectivo_totalActionPerformed(evt);
            }
        });
        t_denominacion_efectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_pago_efectivo_totalKeyTyped(evt);
            }
        });

        lb_simbolo_dolar.setFont(new java.awt.Font("Dialog", 0, 14));
        lb_simbolo_dolar.setText("$");
        lb_simbolo_dolar.setToolTipText("");

        lb_cantidad.setDisplayedMnemonic('r');
        lb_cantidad.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lb_cantidad.setLabelFor(t_pago_efectivo_total);
        lb_cantidad.setText("CANTIDAD");

        lb_denominacion.setDisplayedMnemonic('r');
        lb_denominacion.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lb_denominacion.setLabelFor(t_pago_efectivo_total);
        lb_denominacion.setText("DENOMINACIÓN");

        javax.swing.GroupLayout p_pago_efectivoLayout = new javax.swing.GroupLayout(p_pago_efectivo);
        p_pago_efectivo.setLayout(p_pago_efectivoLayout);
        p_pago_efectivoLayout.setHorizontalGroup(
            p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pago_efectivoLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_pago_efectivoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_tipo_recuento, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_pago_efectivoLayout.createSequentialGroup()
                        .addComponent(l_pagos_efectivo_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addGroup(p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_pago_efectivo_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_cantidad))
                        .addGap(18, 18, 18)
                        .addGroup(p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_pago_efectivoLayout.createSequentialGroup()
                                .addComponent(lb_simbolo_dolar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_denominacion_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188))
                            .addComponent(lb_denominacion))))
                .addGap(0, 0, 0))
        );
        p_pago_efectivoLayout.setVerticalGroup(
            p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pago_efectivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_tipo_recuento))
                .addGap(45, 45, 45)
                .addGroup(p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_pago_efectivo_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_pagos_efectivo_total))
                    .addGroup(p_pago_efectivoLayout.createSequentialGroup()
                        .addGroup(p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_denominacion)
                            .addComponent(lb_cantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p_pago_efectivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_simbolo_dolar)
                            .addComponent(t_denominacion_efectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        lb_cantidad.getAccessibleContext().setAccessibleName("Cantidad");

        p_pago_contenedor.add(p_pago_efectivo);
        p_pago_efectivo.setBounds(0, 10, 560, 180);

        p_pago_tarjeta.setMaximumSize(new java.awt.Dimension(550, 180));
        p_pago_tarjeta.setMinimumSize(new java.awt.Dimension(550, 180));
        p_pago_tarjeta.setOpaque(false);

        p_pago_tarjeta_interno.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/flecha_nav.png"))); // NOI18N

        javax.swing.GroupLayout p_pago_tarjetaLayout = new javax.swing.GroupLayout(p_pago_tarjeta);
        p_pago_tarjeta.setLayout(p_pago_tarjetaLayout);
        p_pago_tarjetaLayout.setHorizontalGroup(
            p_pago_tarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_pago_tarjetaLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_pago_tarjeta_interno, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_pago_tarjetaLayout.setVerticalGroup(
            p_pago_tarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_pago_tarjeta_interno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_pago_tarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        p_pago_contenedor.add(p_pago_tarjeta);
        p_pago_tarjeta.setBounds(0, 0, 553, 170);

        p_pago_otros.setMaximumSize(new java.awt.Dimension(550, 180));
        p_pago_otros.setMinimumSize(new java.awt.Dimension(550, 180));
        p_pago_otros.setOpaque(false);

        p_pago_otros_interno.setOpaque(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/flecha_nav.png"))); // NOI18N

        javax.swing.GroupLayout p_pago_otrosLayout = new javax.swing.GroupLayout(p_pago_otros);
        p_pago_otros.setLayout(p_pago_otrosLayout);
        p_pago_otrosLayout.setHorizontalGroup(
            p_pago_otrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_pago_otrosLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_pago_otros_interno, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_pago_otrosLayout.setVerticalGroup(
            p_pago_otrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_pago_otros_interno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_pago_otrosLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_pago_contenedor.add(p_pago_otros);
        p_pago_otros.setBounds(0, 0, 554, 170);

        p_pago_contado.setMinimumSize(new java.awt.Dimension(550, 180));
        p_pago_contado.setOpaque(false);

        p_pago_contado_interno.setOpaque(false);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/flecha_nav.png"))); // NOI18N

        javax.swing.GroupLayout p_pago_contadoLayout = new javax.swing.GroupLayout(p_pago_contado);
        p_pago_contado.setLayout(p_pago_contadoLayout);
        p_pago_contadoLayout.setHorizontalGroup(
            p_pago_contadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_pago_contadoLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(p_pago_contado_interno, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_pago_contadoLayout.setVerticalGroup(
            p_pago_contadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pago_contadoLayout.createSequentialGroup()
                .addGroup(p_pago_contadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_pago_contadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(p_pago_contado_interno, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(p_pago_contadoLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        p_pago_contado_interno.getAccessibleContext().setAccessibleName("pcontado");

        p_pago_contenedor.add(p_pago_contado);
        p_pago_contado.setBounds(0, 0, 550, 170);

        p_principal.add(p_pago_contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 550, 180));

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_ok.setMaximumSize(null);
        b_ok.setMinimumSize(null);
        b_ok.setNextFocusableComponent(b_cancelar);
        b_ok.setPreferredSize(null);
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });
        p_principal.add(b_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 140, -1));

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_cancelar.setMaximumSize(null);
        b_cancelar.setMinimumSize(null);
        b_cancelar.setNextFocusableComponent(b_m_borrar_linea_recuento);
        b_cancelar.setPreferredSize(null);
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });
        p_principal.add(b_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 140, -1));

        add(p_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void b_pago_efectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pago_efectivoActionPerformed
        b_pago_otros.setNextFocusableComponent(t_pago_efectivo_total);
        lineaRecuento.setMedioPago(MediosPago.getInstancia().getPagoEfectivo());
        lb_tipo_recuento.setText("EFECTIVO");
        cambiaPanelPago(p_pago_efectivo);
        t_denominacion_efectivo.setVisible(true);
        lb_denominacion.setVisible(true);
        lb_simbolo_dolar.setVisible(true);
        lb_cantidad.setVisible(true);
        
        t_pago_efectivo_total.setSize(new Dimension(600, 60));
        
        t_pago_efectivo_total.requestFocus();
    }//GEN-LAST:event_b_pago_efectivoActionPerformed

    private void b_pago_contadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pago_contadoActionPerformed

        cambiaPanelPago(p_pago_contado);
        t_denominacion_efectivo.setVisible(false);
        lb_denominacion.setVisible(false);
        lb_simbolo_dolar.setVisible(false);
        lb_cantidad.setVisible(false);
        if (p_pago_contado_interno.getComponents().length != 0) {
            b_pago_otros.setNextFocusableComponent(p_pago_contado_interno.getComponent(0));
            ((JButtonForm) p_pago_contado_interno.getComponent(p_pago_contado_interno.getComponents().length - 1)).setNextFocusableComponent(b_pago_efectivo);
            p_pago_contado_interno.getComponent(0).requestFocus();
        }
        else {
            b_pago_otros.setNextFocusableComponent(b_ok);
        }

    }//GEN-LAST:event_b_pago_contadoActionPerformed

    private void b_pago_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pago_tarjetaActionPerformed

        pintaBotonesMedioPago(1);
        paginaPagoTarjeta = 1;

        refrescaPagosTarjeta();
    }//GEN-LAST:event_b_pago_tarjetaActionPerformed

    private void pintaBotonesMedioPago(int pagina) {
        int TAMANO_PAGINA = 18;
        int desde = 0;
        int hasta = 0;
        boolean pintaSiguiente = false;
        boolean pintaAnterior = false;

        List<MedioPagoBean> listaPagos = MediosPago.getInstancia().getListaMediosPago(MedioPagoBean.TIPO_TARJETAS);


        if (listaPagos.size() <= TAMANO_PAGINA) {
            // solo hay 1 página posible
            desde = 0;
            if (listaPagos.size() < 18) {
                hasta = listaPagos.size() - 1;
            }
            else {
                hasta = 17;
            }
            pintaSiguiente = false;
            pintaAnterior = false;

        }
        else if (listaPagos.size() > TAMANO_PAGINA && pagina == 1) {
            desde = 0;
            hasta = 16;
            pintaSiguiente = true;
            pintaAnterior = false;
        }
        else if (listaPagos.size() > TAMANO_PAGINA && pagina > 1) {
            desde = 17;
            if (listaPagos.size() < 34) {
                hasta = listaPagos.size() - 1;
            }
            else {
                hasta = 32;
            }
            pintaSiguiente = false;
            pintaAnterior = true;
        }

        ((JPanel) p_pago_tarjeta.getComponent(1)).removeAll();
        p_pago_tarjeta.repaint();

        if (pintaAnterior) {
            addButtonAnterior(p_pago_tarjeta);
        }
        // INICIO DE PINTADO DE BOTÓN DE PAGO   

        for (int i = desde; i <= hasta; i++) {

            final MedioPagoBean entrada = listaPagos.get(i);
            JButtonForm button = new JButtonForm();
            Action ac = new AbstractAction(entrada.getCodMedioPago()) {

                @Override
                public void actionPerformed(ActionEvent ae) {
                    String codPagoActivo = (String) this.getValue(Action.NAME);
                    MedioPagoBean mpEncontrado = MediosPago.getInstancia().getMedioPago(codPagoActivo);
                    lineaRecuento.setMedioPago(mpEncontrado);
                    
                    cambiaPanelPago(p_pago_efectivo);
                    t_denominacion_efectivo.setVisible(false);
                    lb_denominacion.setVisible(false);
                    lb_simbolo_dolar.setVisible(false);
                    lb_cantidad.setVisible(false);
                    
                    t_pago_efectivo_total.requestFocus();
                    b_pago_otros.setNextFocusableComponent(t_pago_efectivo_total);
                    //t_pago_efectivo_total.setNextFocusableComponent(b_pago_efectivo);
                    lb_tipo_recuento.setText(mpEncontrado.getDesMedioPago());
                }
            };
            button.setAction(ac);
            button.setText(entrada.getDesMedioPago());
            button.setToolTipText(entrada.getDesMedioPago());
            button.setPreferredSize(new Dimension(150, 22));
            p_pago_tarjeta_interno.add(button);


        }


        // FIN DE PINTADO DE BOTONES DE PAGO
        if (pintaSiguiente) {
            addButtonSiguiente(p_pago_tarjeta);
        }

    }

    private void b_pago_otrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pago_otrosActionPerformed

        cambiaPanelPago(p_pago_otros);
        t_denominacion_efectivo.setVisible(false);
        lb_denominacion.setVisible(false);
        lb_simbolo_dolar.setVisible(false);
        lb_cantidad.setVisible(false);
        if (p_pago_otros_interno.getComponents().length != 0) {
            b_pago_otros.setNextFocusableComponent(p_pago_otros_interno.getComponent(0));
            ((JButtonForm) p_pago_otros_interno.getComponent(p_pago_otros_interno.getComponents().length - 1)).setNextFocusableComponent(b_pago_efectivo);
            p_pago_otros_interno.getComponent(0).requestFocus();
        }
        else {
            b_pago_otros.setNextFocusableComponent(b_ok);
        }
    }//GEN-LAST:event_b_pago_otrosActionPerformed

    private void b_m_borrar_linea_recuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_borrar_linea_recuentoActionPerformed
        accionBorrarPago();
}//GEN-LAST:event_b_m_borrar_linea_recuentoActionPerformed

    private void t_pago_efectivo_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_pago_efectivo_totalActionPerformed
}//GEN-LAST:event_t_pago_efectivo_totalActionPerformed

    private void t_pago_efectivo_totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_pago_efectivo_totalKeyTyped
        if (evt.getKeyChar() == '\n') {
            accionIntroducirRecuento();
        }

    }//GEN-LAST:event_t_pago_efectivo_totalKeyTyped

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed

        accionAceptar();

}//GEN-LAST:event_b_okActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        accionCancelar();
}//GEN-LAST:event_b_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_borrar_linea_recuento;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_pago_contado;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_pago_efectivo;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_pago_otros;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_pago_tarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane js_tb_recuento_caja;
    private javax.swing.JLabel l_pagos_efectivo_total;
    private javax.swing.JLabel l_pagos_total;
    private javax.swing.JLabel l_pagos_total1;
    private javax.swing.JLabel lb_cantidad;
    private javax.swing.JLabel lb_denominacion;
    private javax.swing.JLabel lb_simbolo_dolar;
    private javax.swing.JLabel lb_tipo_recuento;
    private javax.swing.JPanel m_edicion_pagos;
    private javax.swing.JPanel m_tipos_pagos;
    private com.comerzzia.jpos.gui.components.JValor p_modificar_importe;
    private javax.swing.JPanel p_pago_contado;
    private javax.swing.JPanel p_pago_contado_interno;
    private javax.swing.JLayeredPane p_pago_contenedor;
    private javax.swing.JPanel p_pago_efectivo;
    private javax.swing.JPanel p_pago_otros;
    private javax.swing.JPanel p_pago_otros_interno;
    private javax.swing.JPanel p_pago_tarjeta;
    private javax.swing.JPanel p_pago_tarjeta_interno;
    private com.comerzzia.jpos.gui.components.JPanelImagenFondo p_principal;
    private javax.swing.JPanel panel_superior;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_denominacion_efectivo;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_pago_efectivo_total;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_pagos_total;
    private javax.swing.JTable tb_recuento_caja;
    private javax.swing.JDialog v_modificar_importe;
    // End of variables declaration//GEN-END:variables

    /**
     * Cambia el panel de pago que se muestra en pantalla: Efectivo, tarjeta...
     * @param pamostrar 
     */
    protected void cambiaPanelPago(JPanel pamostrar) {
        if (panel_pagos_activo != null) {
            panel_pagos_activo.setVisible(false);
        }
        panel_pagos_activo = pamostrar;
        panel_pagos_activo.setVisible(true);
    }

    private void addFunctionKeys() {
        // ENTER EN LOS BOTONES
        addHotKey(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "EnterBotones", listenerEnter);

        KeyStroke f5 = KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0);
        Action listenerf5 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_pago_efectivoActionPerformed(ae);
            }
        };
        addHotKey(f5, "IdentClientF5", listenerf5);

        KeyStroke f6 = KeyStroke.getKeyStroke(KeyEvent.VK_F6, 0);
        Action listenerf6 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_pago_contadoActionPerformed(ae);
            }
        };
        addHotKey(f6, "IdentClientF6", listenerf6);

        KeyStroke f7 = KeyStroke.getKeyStroke(KeyEvent.VK_F7, 0);
        Action listenerf7 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_pago_tarjetaActionPerformed(ae);

            }
        };
        addHotKey(f7, "IdentClientF7", listenerf7);

        KeyStroke f8 = KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0);
        Action listenerf8 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_pago_otrosActionPerformed(ae);

            }
        };
        addHotKey(f8, "IdentClientF8", listenerf8);

        // F3 BORRAR RECUENTO
        KeyStroke f3 = KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0);
        KeyStroke ctrolMenos = KeyStroke.getKeyStroke(KeyEvent.VK_MINUS, InputEvent.CTRL_DOWN_MASK);
        Action listenerf3 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {

                accionBorrarPago();
            }
        };
        addHotKey(f3, "IdentClientF3", listenerf3);
        addHotKey(ctrolMenos, "ControlMenos", listenerf3);

        // F9 INTRODUCIR RECUENTO
        KeyStroke f9 = KeyStroke.getKeyStroke(KeyEvent.VK_F9, 0);
        Action listenerf9 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionIntroducirRecuento();
            }
        };
        addHotKey(f9, "IdentClientF9", listenerf9);
        // Cambiar Pagina
        KeyStroke f10 = KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0);
        Action listenerf10 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCambiaPaginaPagoTarjeta();
            }
        };
        addHotKey(f10, "IdentClientF10", listenerf10);
    }

    @Override
    public void iniciaVista() {
        t_pago_efectivo_total.requestFocus();
        lineaRecuento = new RecuentoCajaDet();
        refrescaVista();
        t_pago_efectivo_total.setText("");
        t_pago_efectivo_total.requestFocus();
    }

    private void refrescaVista() {
        tb_recuento_caja.setModel(new RecuentoCajaTableModel(Sesion.getCajaActual().getRecuento().getRecuento()));
        t_pagos_total.setText(Sesion.getCajaActual().getRecuento().getTotalRecuento().toString());
        t_pago_efectivo_total.setText("");
        t_denominacion_efectivo.setText("");
        setTamanosTabla();
    }

    private void setTamanosTabla() {        
        tb_recuento_caja.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tb_recuento_caja.getColumnModel().getColumn(0).setPreferredWidth(160);
        tb_recuento_caja.getColumnModel().getColumn(1).setPreferredWidth(160);
        tb_recuento_caja.getColumnModel().getColumn(2).setPreferredWidth(160);
        tb_recuento_caja.getColumnModel().getColumn(3).setPreferredWidth(164);
        Rectangle recta = tb_recuento_caja.getCellRect(tb_recuento_caja.getRowCount(), 1, true);
        recta.height = recta.height + 30;
        js_tb_recuento_caja.getViewport().scrollRectToVisible(recta);
    }

    void setVentana_padre(JPrincipal ventana_padre) {
        super.setVentana_padre(ventana_padre);
    }

    public void inicializaPanel() {
        p_modificar_importe.setContenedor(v_modificar_importe);
        p_modificar_importe.setVentana_padre(this.getVentana_padre());

        p_pago_contado.setVisible(false);
        p_pago_efectivo.setVisible(true);
        p_pago_otros.setVisible(false);
        p_pago_tarjeta.setVisible(false);
        panel_pagos_activo = p_pago_efectivo;

        //Transparencia y ausencia de bordes en la tabla
        Border empty = new EmptyBorder(0, 0, 0, 0);
        js_tb_recuento_caja.setViewportBorder(empty);
        tb_recuento_caja.setBorder(empty);
        js_tb_recuento_caja.getViewport().setOpaque(false);

        addFunctionKeys();

        // Generar botones mediosPago
        MedioPagoBean entrada;
        for (Object mp : MediosPago.getInstancia().getListaMediosPago(MedioPagoBean.TIPO_TARJETAS)) {
            entrada = (MedioPagoBean) mp;
            JButtonForm button = new JButtonForm();
            Action ac = new AbstractAction(entrada.getCodMedioPago()) {

                @Override
                public void actionPerformed(ActionEvent ae) {
                    String codPagoActivo = (String) this.getValue(Action.NAME);
                    MedioPagoBean mpEncontrado = MediosPago.getInstancia().getMedioPago(codPagoActivo);
                    lineaRecuento.setMedioPago(mpEncontrado);
                    cambiaPanelPago(p_pago_efectivo);
                    t_pago_efectivo_total.requestFocus();
                    b_pago_otros.setNextFocusableComponent(t_pago_efectivo_total);
                    lb_tipo_recuento.setText(mpEncontrado.getDesMedioPago());
                }
            };
            button.setAction(ac);
            button.setText(entrada.getDesMedioPago());
            button.setToolTipText(entrada.getDesMedioPago());
            button.setPreferredSize(new Dimension(150, 22));
            p_pago_tarjeta_interno.add(button);


        }
        for (Object mp : MediosPago.getInstancia().getListaMediosPago(MedioPagoBean.TIPO_CONTADO)) {
            entrada = (MedioPagoBean) mp;
            JButtonForm button = new JButtonForm(entrada.getDesMedioPago());
            Action ac = new AbstractAction(entrada.getCodMedioPago()) {

                @Override
                public void actionPerformed(ActionEvent ae) {
                    String codPagoActivo = (String) this.getValue(Action.NAME);
                    MedioPagoBean mpEncontrado = MediosPago.getInstancia().getMedioPago(codPagoActivo);
                    lineaRecuento.setMedioPago(mpEncontrado);
                    cambiaPanelPago(p_pago_efectivo);
                    t_pago_efectivo_total.requestFocus();
                    b_pago_otros.setNextFocusableComponent(t_pago_efectivo_total);
                    lb_tipo_recuento.setText(mpEncontrado.getDesMedioPago());
                }
            };
            button.setAction(ac);
            button.setText(entrada.getDesMedioPago());
            button.setPreferredSize(new Dimension(150, 22));
            p_pago_contado_interno.add(button);

        }

        for (Object mp : MediosPago.getInstancia().getListaMediosPago(MedioPagoBean.TIPO_OTROS)) {
            entrada = (MedioPagoBean) mp;
            JButtonForm button = new JButtonForm(entrada.getDesMedioPago());
            Action ac = new AbstractAction(entrada.getCodMedioPago()) {

                @Override
                public void actionPerformed(ActionEvent ae) {
                    String codPagoActivo = (String) this.getValue(Action.NAME);
                    MedioPagoBean mpEncontrado = MediosPago.getInstancia().getMedioPago(codPagoActivo);
                    lineaRecuento.setMedioPago(mpEncontrado);
                    cambiaPanelPago(p_pago_efectivo);
                    t_pago_efectivo_total.requestFocus();
                    b_pago_otros.setNextFocusableComponent(t_pago_efectivo_total);
                    lb_tipo_recuento.setText(mpEncontrado.getDesMedioPago());
                }
            };
            button.setAction(ac);
            button.setText(entrada.getDesMedioPago());
            button.setPreferredSize(new Dimension(150, 22));
            p_pago_otros_interno.add(button);

        }
        log.debug("consulta de la tabla recuentos");
        tbRecuentosCellRenderer = new RecuentoCajaTableCellRenderer();
        tb_recuento_caja.setDefaultRenderer(Object.class, tbRecuentosCellRenderer);
        crearAccionFocoTabla(this, tb_recuento_caja, KeyEvent.VK_T, InputEvent.CTRL_MASK);
    }

    @Override
    protected void addHotKey(KeyStroke keyStroke, String inputActionKey, Action listener) {
        ActionMap actionMap = this.getActionMap();
        InputMap inputMap = this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(keyStroke, inputActionKey);
        actionMap.put(inputActionKey, listener);
    }

    //sobreescribimos la accion Aceptar
    @Override
    public void accionAceptar() {
        accionGuardarRecuento();
        cerrarVentana();
    }

    //sobreescribimos la accion Cancelar
    @Override
    public void accionCancelar() {
        super.accionCancelar();
    }

    private void accionGuardarRecuento() {
        try {
            Sesion.getCajaActual().guardarRecuento();
            this.getVentana_padre().crearConfirmacion("Se guardó el recuento");
        }
        catch (Exception e) {
            this.getVentana_padre().crearError(e.getMessage());
        }
    }

    private void accionIntroducirRecuento() {
        try {
            MedioPagoCaja mpaux;
            if (lineaRecuento.getCodmedpag() == null) {
                lineaRecuento.setMedioPago(MediosPago.getInstancia().getPagoEfectivo());
            }
            BigDecimal subValor;
            if(lineaRecuento.getCodmedpag().getCodmedpag().equals(MediosPago.getInstancia().getPagoEfectivo().getCodMedioPago())){
                Integer cantidad = new Integer(t_pago_efectivo_total.getText());
                subValor = new BigDecimal(t_denominacion_efectivo.getText());
                if(cantidad != null  &&  cantidad>0 && subValor != null ){
                    lineaRecuento.setSubvalor(subValor);
                    lineaRecuento.setCantidad(cantidad);
                    lineaRecuento.setValor(subValor.multiply(new BigDecimal(cantidad)));
                    t_pago_efectivo_total.requestFocus();
                }
                else{
                     throw  new NumberFormatException();
                }
            }
            else{
                subValor = new BigDecimal(t_pago_efectivo_total.getText());
                if(subValor != null ){
                    lineaRecuento.setSubvalor(subValor);
                    lineaRecuento.setCantidad(1);
                    lineaRecuento.setValor(subValor);
                }
                else{
                    throw  new NumberFormatException();
                }
            }
            Sesion.getCajaActual().getRecuento().crearLineaRecuento(lineaRecuento);
            mpaux = lineaRecuento.getCodmedpag();
            lineaRecuento = new RecuentoCajaDet();
            lineaRecuento.setCodmedpag(mpaux);
            refrescaVista();
        }
        catch (NumberFormatException ex) {
            this.getVentana_padre().crearError("Debe introducir un valor numérico en cantidad y denominación");
        }
        catch (Exception ex) {
            this.getVentana_padre().crearError(ex.getMessage());
        }
    }

    private void accionBorrarPago() {
        lineaSelecionada = tb_recuento_caja.getSelectedRow();
        if (lineaSelecionada >= 0) {
            Sesion.getCajaActual().getRecuento().eliminarLineaRecuento(lineaSelecionada);
        }
        else {
            Sesion.getCajaActual().getRecuento().eliminarLineaRecuento();
        }
        refrescaVista();
    }

    @Override
    public void limpiarFormulario() {
        t_pago_efectivo_total.setText("");
        b_pago_efectivoActionPerformed(null);
    }

    @Override
    public void iniciaFoco() {
        log.info("Iniciando Foco");
        t_pago_efectivo_total.requestFocus();
    }

    private void accionPaginaAnterior() {
        pintaBotonesMedioPago(1);
        paginaPagoTarjeta = 1;
        refrescaPagosTarjeta();
    }

    private void accionPaginaSiguiente() {
        pintaBotonesMedioPago(2);
        paginaPagoTarjeta = 2;
        refrescaPagosTarjeta();
    }

    private void accionCambiaPaginaPagoTarjeta() {
        if (panel_pagos_activo != null && panel_pagos_activo.equals(p_pago_tarjeta)) {
            if (this.paginaPagoTarjeta == 1) {
                accionPaginaSiguiente();
            }
            else {
                accionPaginaAnterior();
            }
        }
    }

    private void refrescaPagosTarjeta() {
        cambiaPanelPago(p_pago_tarjeta);
        if (p_pago_tarjeta_interno.getComponents().length != 0) {
            b_pago_otros.setNextFocusableComponent(p_pago_tarjeta_interno.getComponent(0));
            ((JButtonForm) p_pago_tarjeta_interno.getComponent(p_pago_tarjeta_interno.getComponents().length - 1)).setNextFocusableComponent(b_pago_efectivo);
            p_pago_tarjeta_interno.getComponent(0).requestFocus();
        }
        else {
            b_pago_otros.setNextFocusableComponent(b_ok);
        }
    }

    private void addButtonAnterior(JPanel panel) {
        JButtonForm button = new JButtonForm(" << (F10)");
        Action ac = new AbstractAction(" << (F10)") {

            @Override
            public void actionPerformed(ActionEvent ae) {
                JRecuentoCaja.this.accionPaginaAnterior();
            }
        };
        button.setAction(ac);
        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/arrow_left.png")));
        button.setText("   (F10)");
        button.setPreferredSize(new Dimension(150, 22));
        ((JPanel) panel.getComponent(1)).add(button);

    }

    private void addButtonSiguiente(JPanel panel) {
        JButtonForm button = new JButtonForm(" >> (F10)");
        Action ac = new AbstractAction(" >> (F10)") {

            @Override
            public void actionPerformed(ActionEvent ae) {
                JRecuentoCaja.this.accionPaginaSiguiente();
            }
        };
        button.setAction(ac);
        button.setText("   (F10)");
        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/arrow_right.png")));
        button.setPreferredSize(new Dimension(150, 22));
        ((JPanel) panel.getComponent(1)).add(button);

    }

    @Override
    public void accionLeerTarjetaVD() {
    }
}
