/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JReimpresionFactura.java
 *
 * Created on 11-mar-2014, 16:47:03
 */
package com.comerzzia.jpos.gui.reimpresion.tipos;

import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.validation.IValidableForm;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidadorTexto;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.persistencia.print.documentos.DocumentosBean;
import com.comerzzia.jpos.servicios.bonos.BonosServices;
import com.comerzzia.jpos.servicios.core.contadores.ContadorException;
import com.comerzzia.jpos.servicios.core.contadores.ServicioContadores;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import com.comerzzia.jpos.servicios.core.variables.VariablesAlm;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.jpos.servicios.print.PrintServices;
import com.comerzzia.jpos.servicios.print.documentos.DocumentoException;
import com.comerzzia.jpos.servicios.print.documentos.DocumentosService;
import com.comerzzia.jpos.servicios.reservaciones.plannovio.PlanNovioServices;
import es.mpsistemas.util.log.Logger;
import java.math.BigInteger;
import java.util.Calendar;
import java.util.Formatter;
import java.util.GregorianCalendar;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;

/**
 *
 * @author SMLM
 */
public class JReimpresionDocumentoRecibo extends JVentanaDialogo implements IViewerValidationFormError {

    private static Logger log = Logger.getMLogger(JReimpresionDocumentoRecibo.class);
    List<IValidableForm> formulario;
    String tipo = null;

    /**
     * Creates new form JReimpresionFactura
     */
    public JReimpresionDocumentoRecibo() {
        super();

        try {
            formulario = new LinkedList<IValidableForm>();
            initComponents();

            //creamos la validación
            inicializaValidacion();
            //creamos el formulario
            crearFormulario();

            t_factura1.setText(VariablesAlm.getVariable(VariablesAlm.COD_ALMACEN));
            registraEventoEnterBoton();
        } catch (Exception e) {

        }
    }

    /**
     * Creates new form JReimpresionFactura
     */
    public JReimpresionDocumentoRecibo(String tipo) {
        super();
        this.tipo = tipo;
        try {
            formulario = new LinkedList<IValidableForm>();
            initComponents();

            //creamos la validación
            inicializaValidacion();
            //creamos el formulario
            crearFormulario();

            if (tipo.equals(DocumentosBean.LIQUIDACION_RE)) {
                l_documento.setText("Resumen Liquidación/Anulación: ");
                l_documento.setDisplayedMnemonic('R');
            }
            if (tipo.equals(DocumentosBean.LIQUIDACION_PN)) {
                l_documento.setText("Recibo Liquidación: ");
                l_documento.setDisplayedMnemonic('R');
            }
            if (tipo.equals(DocumentosBean.BONO_RESERVA)) {
                l_documento.setText("Número Reservacion: ");
                l_documento.setDisplayedMnemonic('R');
            }
            if (tipo.equals(DocumentosBean.RESERVACION)) {
                l_documento.setText("Reservación: ");
                l_documento.setDisplayedMnemonic('R');
            }
            if (tipo.equals(DocumentosBean.PLAN_NOVIO)) {
                l_documento.setText("Plan Novio: ");
                l_documento.setDisplayedMnemonic('P');
            }
            if (tipo.equals(DocumentosBean.BONO)) {
                l_documento.setText("Bono Efectivo: ");
                l_documento.setDisplayedMnemonic('B');
            }
            t_factura1.setText(VariablesAlm.getVariable(VariablesAlm.COD_ALMACEN));
            //t_factura2.setText(Sesion.getCajaActual().getCajaActual().getCodcaja());
            registraEventoEnterBoton();
        } catch (Exception e) {

        }
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sesion1 = new com.comerzzia.jpos.servicios.login.Sesion();
        l_documento = new javax.swing.JLabel();
        t_factura1 = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_factura3 = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_previsualizar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        lb_error = new javax.swing.JLabel();
        b_aceptar1 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        l_factura_cabecera1 = new javax.swing.JLabel();
        factura = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t_factura2 = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();

        setPreferredSize(new java.awt.Dimension(570, 248));

        l_documento.setDisplayedMnemonic('f');
        l_documento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l_documento.setLabelFor(t_factura3);
        l_documento.setAlignmentY(0.0F);

        t_factura1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_factura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_factura1ActionPerformed(evt);
            }
        });

        t_factura3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_factura3.setNextFocusableComponent(b_previsualizar);

        jLabel4.setText("-");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel6.setText("REIMPRESIÓN");

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_cancelar.setNextFocusableComponent(t_factura1);
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_previsualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_previsualizar.setMnemonic('P');
        b_previsualizar.setText("Previsualizar");
        b_previsualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_previsualizar.setNextFocusableComponent(b_aceptar1);
        b_previsualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_previsualizarActionPerformed(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(204, 0, 0));

        b_aceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_aceptar1.setMnemonic('a');
        b_aceptar1.setText("Aceptar");
        b_aceptar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_aceptar1.setNextFocusableComponent(b_cancelar);
        b_aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptar1ActionPerformed(evt);
            }
        });

        l_factura_cabecera1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        l_factura_cabecera1.setText("Última Documento:");
        l_factura_cabecera1.setFocusable(false);

        factura.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        factura.setForeground(new java.awt.Color(0, 0, 204));
        factura.setText("ID");
        factura.setFocusable(false);

        jLabel1.setText("-");

        t_factura2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_factura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_factura2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(l_factura_cabecera1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 78, Short.MAX_VALUE)
                                .addComponent(b_previsualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_aceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(l_documento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_factura1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(t_factura2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_factura3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_factura_cabecera1)
                    .addComponent(factura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(t_factura3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(t_factura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(t_factura2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(l_documento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_aceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_previsualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        accionCancelar();
}//GEN-LAST:event_b_cancelarActionPerformed

    private void b_previsualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_previsualizarActionPerformed
        accionPrevisualizar();
}//GEN-LAST:event_b_previsualizarActionPerformed

    private void b_aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptar1ActionPerformed
        accionAceptar();
    }//GEN-LAST:event_b_aceptar1ActionPerformed

    private void t_factura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_factura1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_t_factura1ActionPerformed

    private void t_factura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_factura2ActionPerformed
        // TODO add your handling code here:
        String texto = t_factura2.getText();
        String textoFormateado = "";
        if (!texto.equals("")) {
            Formatter fmt = new Formatter();
            textoFormateado = fmt.format("%03d", Integer.parseInt(texto.trim())).toString();
            t_factura2.setText(textoFormateado);

            String result = getIdPN(textoFormateado);

            this.factura.setText(result);
            if (result != "-") {
                t_factura2.setNextFocusableComponent(t_factura3);
                t_factura3.setText(result.split("-")[2]);
            }

        }
    }//GEN-LAST:event_t_factura2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_aceptar1;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_previsualizar;
    private javax.swing.JLabel factura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel l_documento;
    private javax.swing.JLabel l_factura_cabecera1;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.servicios.login.Sesion sesion1;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_factura1;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_factura2;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_factura3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        try {
            validarFormulario();
            DocumentosBean documentoBean;
            Calendar calFecha = new GregorianCalendar();
            Calendar calendarSys = Calendar.getInstance();
            if (tipo.equals(DocumentosBean.BONO)) {
                documentoBean = DocumentosService.consultarBonoByUniqueKey(t_factura1.getText(), DocumentosBean.CODCAJA, t_factura3.getText());
            } else {
                documentoBean = DocumentosService.consultarDocByUniqueKey(this.tipo, t_factura1.getText(), DocumentosBean.CODCAJA, t_factura3.getText());
            }
            calFecha.setTime(documentoBean.getFecha().getDate());
            int difHoras = (calendarSys.get(Calendar.HOUR_OF_DAY) - calFecha.get(Calendar.HOUR_OF_DAY));
            int difMinutos = (calendarSys.get(Calendar.MINUTE) - calFecha.get(Calendar.MINUTE));
            int minutos = (difHoras * 60) + difMinutos;
            String variablesNCR = Variables.getVariable(Variables.VARIABLES_TIEMPO_REIMPRESION_BONO);
            if (documentoBean != null) {
                if (tipo.equals(DocumentosBean.RESERVACION) || tipo.equals(DocumentosBean.PLAN_NOVIO)) {
                    PrintServices.getInstance().reimpresionReservacion(documentoBean, false);
                } else if ((minutos > 0 && minutos <= Integer.valueOf(variablesNCR)) || Variables.getVariable(Variables.ACTIVO_TIEMPO_REIMPRESION).equals("N")) {
//                    if (Variables.getVariable(Variables.ACTIVO_TIEMPO_REIMPRESION).equals("S")) {
                    if (tipo.equals(DocumentosBean.LIQUIDACION_PN)) {
                        PrintServices.getInstance().reimpresionLiquidaPN(documentoBean, false);
                    }
                    if (tipo.equals(DocumentosBean.LIQUIDACION_RE)) {
                        PrintServices.getInstance().reimpresionLiquidaRE(documentoBean, false);
                    }
                    if (tipo.equals(DocumentosBean.BONO_RESERVA) || tipo.equals(DocumentosBean.BONO)) {
                        PrintServices.getInstance().reimpresionBonoReserva(documentoBean, false);
                    }
                    accionCancelar();
                } else {
                    JPrincipal.getInstance().crearAdvertencia("No se puede realizar la reimpresión ya paso el tiempo determinado " + variablesNCR + " min.");
                }
//                }
            } else {
                this.contenedor.setVisible(false);
                JPrincipal.getInstance().crearAdvertencia("No se han encontrado tickets para los datos introducidos.");
                this.contenedor.setVisible(true);
            }
            accionCancelar();
        } catch (ValidationFormException ex) {
            addError(ex);
        } catch (DocumentoException ex) {
            addError(ex);
        }
    }

    public void accionPrevisualizar() {
        try {
            validarFormulario();
            DocumentosBean documentoBean;
            if (tipo.equals(DocumentosBean.BONO)) {
                documentoBean = DocumentosService.consultarBonoByUniqueKey(t_factura1.getText(), DocumentosBean.CODCAJA, t_factura3.getText());
            } else {
                documentoBean = DocumentosService.consultarDocByUniqueKey(this.tipo, t_factura1.getText(), DocumentosBean.CODCAJA, t_factura3.getText());
            }
            if (documentoBean != null) {
                if (tipo.equals(DocumentosBean.LIQUIDACION_PN)) {
                    PrintServices.getInstance().reimpresionLiquidaPN(documentoBean, true);
                }
                if (tipo.equals(DocumentosBean.LIQUIDACION_RE)) {
                    PrintServices.getInstance().reimpresionLiquidaRE(documentoBean, true);
                }
                if (tipo.equals(DocumentosBean.BONO_RESERVA) || tipo.equals(DocumentosBean.BONO)) {
                    PrintServices.getInstance().reimpresionBonoReserva(documentoBean, true);
                }
                if (tipo.equals(DocumentosBean.RESERVACION) || tipo.equals(DocumentosBean.PLAN_NOVIO)) {
                    PrintServices.getInstance().reimpresionReservacion(documentoBean, true);
                }
            } else {
                this.contenedor.setVisible(false);
                JPrincipal.getInstance().crearAdvertencia("No se han encontrado tickets para los datos introducidos.");
                this.contenedor.setVisible(true);
            }
        } catch (ValidationFormException ex) {
            addError(ex);
        } catch (DocumentoException ex) {
            addError(ex);
        }
    }

    @Override
    public void limpiarFormulario() {

        for (IValidableForm elem : formulario) {
            elem.setValidacionHabilitada(false);
        }

        for (IValidableForm elem : formulario) {
            elem.setText("");
        }

        this.t_factura3.requestFocus();

        for (IValidableForm elem : formulario) {
            elem.setValidacionHabilitada(true);
        }

        this.lb_error.setText("");
    }

    private void crearFormulario() {
        // Elementos del formulario susceptibles de validarse o resetearse 
        formulario.add(t_factura3);
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    public void addError(DocumentoException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }

    private void inicializaValidacion() {
        t_factura1.addValidador(new ValidadorObligatoriedad(), this);
        t_factura1.addValidador(new ValidadorTexto(3, true), this);
        t_factura3.addValidador(new ValidadorObligatoriedad(), this);

    }

    private void validarFormulario() throws ValidationFormException {
        for (IValidableForm e : formulario) {
            try {
                e.validar();
            } catch (ValidationFormException ex) {
                throw ex;
            }
        }
    }

    public String getIdPN(String codCaja) {
        String result = Sesion.getTienda().getCodalm() + "-" + codCaja + "-";
        try {
            if (PlanNovioServices.maximoIDPorCaja(codCaja) == new BigInteger("0")) {
                result = "-";
            } else {
                result += String.valueOf(PlanNovioServices.maximoIDPorCaja(codCaja));
            }

        } catch (Exception e) {
        }
        return result;
    }

    public void iniciaVista() {
        limpiarFormulario();
        t_factura3.requestFocus();

        if (tipo.equals(DocumentosBean.LIQUIDACION_RE)) {
            l_documento.setText("Resumen Liquidación/Anulación: ");
            l_documento.setDisplayedMnemonic('R');
        }
        if (tipo.equals(DocumentosBean.LIQUIDACION_PN)) {
            l_documento.setText("Recibo Liquidación: ");
            l_documento.setDisplayedMnemonic('R');

            factura.setText("");
        }
        if (tipo.equals(DocumentosBean.BONO_RESERVA)) {
            l_documento.setText("Número Reservacion: ");
            l_documento.setDisplayedMnemonic('R');
        }
        if (tipo.equals(DocumentosBean.RESERVACION)) {
            try {
                l_documento.setText("Reservación: ");
                l_documento.setDisplayedMnemonic('R');
                factura.setText(getIdReserva());
            } catch (ContadorException ex) {
                java.util.logging.Logger.getLogger(JReimpresionDocumentoRecibo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (tipo.equals(DocumentosBean.PLAN_NOVIO)) {
            String result = "";
            if (Sesion.getCajaActual().getCajaActual() != null) {
                result = getIdPN(Sesion.getCajaActual().getCajaActual().getCodcaja());
                factura.setText(result);
            }
            if (result != "-") {
                t_factura2.setNextFocusableComponent(t_factura3);
                t_factura3.setText(result.split("-")[2]);
            }
            l_documento.setText("Plan Novio: ");
            l_documento.setDisplayedMnemonic('P');
        }
        if (tipo.equals(DocumentosBean.BONO)) {
            l_documento.setText("Bono Efectivo: ");
            l_documento.setDisplayedMnemonic('B');
            Long valor = ServicioContadores.obtenercontadorReimpresion(ServicioContadores.CONTADOR_BONO);
            valor = valor - 1;
            Number respuesta = BonosServices.consultaBonoPorId(VariablesAlm.getVariable(VariablesAlm.COD_ALMACEN), valor);
            factura.setText(VariablesAlm.getVariable(VariablesAlm.COD_ALMACEN) + "-" + respuesta);
        }
        t_factura1.setText(VariablesAlm.getVariable(VariablesAlm.COD_ALMACEN));
        if (Sesion.getCajaActual().getCajaActual() != null) {
            t_factura2.setText(Sesion.getCajaActual().getCajaActual().getCodcaja());
        }

        b_previsualizar.setVisible(false);
    }

    public String getIdReserva() throws ContadorException {
        Long valor = ServicioContadores.obtenercontadorReimpresion(ServicioContadores.CONTADOR_RESERVA);
        if (valor != null) {
//             Long numeroanterior = valor-1;
            Long numeroanterior = valor;
            String idvalor = numeroanterior.toString();
            String a = new Long(idvalor).toString();
            String b = new Long(idvalor).toString();
//        for (int i = a.length(); i < 9; i++) {
//            b = "0" + b;
//        }
//        
            return Sesion.getTienda().getCodalm() + "-" + b;
        } else {
            return "";
        }
    }

    /*
    public String getIdPN() throws ContadorException
    {
        Long valor = ServicioContadores.obtenercontadorReimpresion(ServicioContadores.CONTADOR_PN);
        if(valor!=null)
        {
            return  valor.toString();
        }
        else
        {
            return "";
        }
    }
     */
    public String getIBonoEfectivo() throws ContadorException {
        Long valor = ServicioContadores.obtenercontadorReimpresion(ServicioContadores.CONTADOR_BONO);
        if (valor != null) {
//             Long numeroanterior = valor-1;
            Long numeroanterior = valor;
            String idvalor = numeroanterior.toString();
            String a = new Long(idvalor).toString();
            String b = new Long(idvalor).toString();
//        for (int i = a.length(); i < 9; i++) {
//            b = "0" + b;
//        }
//        
            return Sesion.getTienda().getCodalm() + "-" + b;
        } else {
            return "";
        }
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

}
