/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JBuscarLetrasCambio.java
 *
 * Created on 02-oct-2012, 13:08:05
 */
package com.comerzzia.jpos.gui.sukupo;

import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.credito.JOperacionesTarjeta;
import com.comerzzia.jpos.gui.sukupon.modelos.SukuponCambioCellRenderer;
import com.comerzzia.jpos.gui.sukupon.modelos.SukuponCambioTableModel;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.persistencia.sukupon.SukuponBean;
import com.comerzzia.jpos.servicios.sukupon.SukuponCambioException;
import com.comerzzia.jpos.servicios.sukupon.SukuponManager;
import com.comerzzia.jpos.servicios.sukupon.SukuponServices;
import es.mpsistemas.util.log.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MGRI
 */
public class JConsultaSukupon extends JVentanaDialogo implements IVista, IViewerValidationFormError {

    protected static Logger log = Logger.getMLogger(JConsultaSukupon.class);
    public static SukuponManager manejador;
    private static final long serialVersionUID = 1L;
    private JPrincipal ventana_padre = null;
    private SukuponBean sukuponBean = new SukuponBean();
    List<SukuponBean> lista;

    public JConsultaSukupon(JPrincipal ventana_padre) {
        super();
        this.ventana_padre = ventana_padre;
        addFuntionKeysBotonesMenu();
        initComponents();
        lista = new ArrayList<SukuponBean>();
        registraEventoEnterBoton();
        crearAccionFocoTabla(this, tb_listaFacturas, KeyEvent.VK_T, InputEvent.CTRL_MASK);
        manejador = SukuponManager.getInstance();

//        tb_listaFacturas.setDefaultRenderer(Object.class, new SukuponCambioCellRenderer());
//        addFunctionsKeys();
//        inicia();
        iniciaVista();
        addFunctionsKeys();

    }

    public JConsultaSukupon() {

    }

    private void inicia() {

        // Borde vacio ara tablas, Viewports y scrollpanels
        Border empty = new EmptyBorder(0, 0, 0, 0);
        tb_listaFacturas.setDefaultRenderer(Object.class, new SukuponCambioCellRenderer());
        refrescarTablaSukupon(new SukuponCambioTableModel(lista));

        jScrollPane2.setViewportBorder(empty);
        tb_listaFacturas.setBorder(empty);
        jScrollPane2.getViewport().setOpaque(false);
        //   t_numero_cedula.addKeyListener(this);
//        t_numero_fidelizado.addKeyListener(this);
//        t_documento.addKeyListener(this);
//        t_fecha_desde.addKeyListener(this);
//        t_fecha_hasta.addKeyListener(this);
//        t_nombre_org.addKeyListener(this);
//        t_apellidos_org.addKeyListener(this);

    }

    // ACCIONES
    private void addFuntionKeysBotonesMenu() {

        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionVolver();
            }

        };
        addHotKey(f2, "IdentClientF2", listenerf2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        t_numero_cedula = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_error = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_numero_cupon = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_listaFacturas = new javax.swing.JTable();
        b_volver1 = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+7));
        jLabel1.setText("CONSULTA DE SUKUPON");

        jLabel4.setDisplayedMnemonic('c');
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setLabelFor(t_numero_cedula);
        jLabel4.setText("Nro. Cédula:");

        t_numero_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_numero_cedulaActionPerformed(evt);
            }
        });
        t_numero_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_cedulaKeyTyped(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(255, 0, 0));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_error.setText("Cedula Invalida");
        lb_error.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setDisplayedMnemonic('c');
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setLabelFor(t_numero_cedula);
        jLabel5.setText("Nro. Sukupón/Billetón:");

        t_numero_cupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_numero_cuponActionPerformed(evt);
            }
        });
        t_numero_cupon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_cuponKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_numero_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(t_numero_cupon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(308, 308, 308))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_numero_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_error))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_numero_cupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        tb_listaFacturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_listaFacturas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tb_listaFacturasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_listaFacturasFocusLost(evt);
            }
        });
        tb_listaFacturas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_listaFacturasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_listaFacturas);

        b_volver1.setText("<html><center>Volver<br/>F2</center></html>");
        b_volver1.setActionCommand("<html><center> Cancelar <br>F2</center></html>");
        b_volver1.setAlignmentY(0.0F);
        b_volver1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_volver1.setMargin(new java.awt.Insets(2, 0, 2, 0));
        b_volver1.setMaximumSize(new java.awt.Dimension(76, 48));
        b_volver1.setMinimumSize(new java.awt.Dimension(76, 48));
        b_volver1.setPreferredSize(new java.awt.Dimension(114, 48));
        b_volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(b_volver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_volver1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

//GEN-FIRST:event_tb_listaArticulosKeyPressed
 
//GEN-LAST:event_tb_listaArticulosKeyPressed
////
    private void tb_listaFacturasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_listaFacturasKeyPressed

    }//GEN-LAST:event_tb_listaFacturasKeyPressed

    private void tb_listaFacturasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaFacturasFocusLost
        eliminaSeleccionTabla();
    }//GEN-LAST:event_tb_listaFacturasFocusLost

    private void tb_listaFacturasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaFacturasFocusGained
        if (tb_listaFacturas.getRowCount() >= 0) {
            ListSelectionModel selectionModel = tb_listaFacturas.getSelectionModel();
            selectionModel.setSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_tb_listaFacturasFocusGained

    private void t_numero_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_cedulaKeyTyped
        if (evt.getKeyChar() == '\n') {
            accionBuscarCedula();
        }
    }//GEN-LAST:event_t_numero_cedulaKeyTyped

    private void t_numero_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_numero_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_numero_cedulaActionPerformed

    private void b_volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volver1ActionPerformed
        accionCancelar();
    }//GEN-LAST:event_b_volver1ActionPerformed

    private void t_numero_cuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_numero_cuponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_numero_cuponActionPerformed

    private void t_numero_cuponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_cuponKeyTyped
        if (evt.getKeyChar() == '\n') {
            accionBuscarIdCupon();
        }
    }//GEN-LAST:event_t_numero_cuponKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_volver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_cedula;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_cupon;
    private javax.swing.JTable tb_listaFacturas;
    // End of variables declaration//GEN-END:variables

    public void accionAceptar() {
    }

    public void limpiarFormulario() {
        t_numero_cedula.setText("");
        t_numero_cupon.setText("");
        eliminaSeleccionTabla();
        lb_error.setText("");
    }

    public void iniciaVista() {
        iniciaVista(null);
    }

    public void iniciaVista(JPrincipal ventana_padre) {
        manejador.inicia();
        limpiarFormulario();
        inicializaValidacion();
        refrescarTabla();
        iniciaFoco();
    }

    public void recuperaVista() {
        refrescarTabla();
        lb_error.setText("");
        inicializaValidacion();
        iniciaFoco();
    }

    public void iniciaFoco() {
        t_numero_cedula.requestFocus();
    }

    public void accionLeerTarjetaVD() {
    }

    private void mostrarResultados(List<SukuponBean> lista) throws SukuponCambioException {
        //refrescarTabla();
        tb_listaFacturas.setDefaultRenderer(Object.class, new SukuponCambioCellRenderer());
        tb_listaFacturas.setModel(new SukuponCambioTableModel(manejador.getSukupon()));
        refrescarTablaSukupon(new SukuponCambioTableModel(lista));

    }

    private void accionVolver() {
        ventana_padre.showView(JPrincipal.VISTA_INICIO);
    }

    private void accionBuscarCedula() {
        lb_error.setText("");
        t_numero_cupon.setText("");

        if (t_numero_cedula.getText().isEmpty()) {
            lb_error.setText("Debe ingresar una Cedula");
            return;
        }
        try {
            try {
                // manejador.accionBuscarCedula(t_numero_cedula.getText());
                lista = SukuponServices.consultarLetrasPorCliente(t_numero_cedula.getText());

            } catch (SukuponCambioException ex) {
                java.util.logging.Logger.getLogger(JConsultaSukupon.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrarResultados(lista);
        } catch (SukuponCambioException e) {
            lb_error.setText(e.getMessage());
        }
    }

    private void accionBuscarIdCupon() {
        lb_error.setText("");
        t_numero_cedula.setText("");

        if (t_numero_cupon.getText().isEmpty()) {
            lb_error.setText("Debe ingresar el número de Cupón");
            return;
        }
        try {
            // manejador.accionBuscarCedula(t_numero_cedula.getText());
            lista = SukuponServices.consultarIdCupon(Long.parseLong(t_numero_cupon.getText()));
//            for (SukuponDetalle cupon : listaDetalle) {
//                sukuponBean.setIdCupon(Long.toString(cupon.getIdCupon()));
//                sukuponBean.setCodBarras(cupon.getUidNotaCredito());
//                lista.add(sukuponBean);
//            }

            mostrarResultados(lista);
        } catch (SukuponCambioException e) {
            lb_error.setText(e.getMessage());
        }
    }

    private void refrescarTabla() {
        // inicia();
        lista = new ArrayList<SukuponBean>();
        tb_listaFacturas.setDefaultRenderer(Object.class, new SukuponCambioCellRenderer());
        refrescarTablaSukupon(new SukuponCambioTableModel(lista));
        //tb_listaFacturas.setModel(new SukuponCambioTableModel(manejador.getSukupon()));

        //  tb_listaFacturas.setModel(new SukuponCambioTableModel(manejador.getSukupon()));
    }

    private void refrescarTablaSukupon(SukuponCambioTableModel table) {
        tb_listaFacturas.setModel(table);
        tb_listaFacturas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tb_listaFacturas.getColumnModel().getColumn(0).setPreferredWidth(30);
        tb_listaFacturas.getColumnModel().getColumn(1).setPreferredWidth(70);
        tb_listaFacturas.getColumnModel().getColumn(2).setPreferredWidth(165);
        tb_listaFacturas.getColumnModel().getColumn(3).setPreferredWidth(80);
        tb_listaFacturas.getColumnModel().getColumn(4).setPreferredWidth(80);
        tb_listaFacturas.getColumnModel().getColumn(5).setPreferredWidth(50);
        tb_listaFacturas.getColumnModel().getColumn(6).setPreferredWidth(50);
        tb_listaFacturas.getColumnModel().getColumn(7).setPreferredWidth(50);
        tb_listaFacturas.getColumnModel().getColumn(8).setPreferredWidth(50);
        tb_listaFacturas.getColumnModel().getColumn(9).setPreferredWidth(100);
        tb_listaFacturas.getColumnModel().getColumn(10).setPreferredWidth(100);
    }

    private void accionIrADetalleDeFactura() {
        this.contenedor.setVisible(false);
        JOperacionesTarjeta.crearVentanaPagarLetra();
        limpiarFormulario();

    }

    private void addFunctionsKeys() {
        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }

        };
        addHotKey(f2, "IdentClientF2", listenerf2);
    }

    private void eliminaSeleccionTabla() {
        ListSelectionModel selectionModel = tb_listaFacturas.getSelectionModel();
        selectionModel.clearSelection();
    }

    private void accionIrAtras() {
        // cerrarVentana();
        // JPrincipal.getPanelActivo();
    }

    private void inicializaValidacion() {
        //     t_numero_factura.addValidador(new ValidadorTexto(3, true), this);
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }
}
