/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JBuscarPlanNovios.java
 *
 * Created on 04-oct-2012, 12:59:21
 */
package com.comerzzia.jpos.gui.reservaciones.plannovios;

import com.comerzzia.jpos.entity.db.Almacen;
import com.comerzzia.jpos.entity.db.PlanNovio;
import com.comerzzia.jpos.entity.services.reservaciones.plannovio.PlanNovioBuscar;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.gui.components.form.JTextFieldForm;
import com.comerzzia.jpos.gui.reservaciones.plannovios.modelos.BusquedaPlanesNoviosCellRenderer;
import com.comerzzia.jpos.gui.reservaciones.plannovios.modelos.BusquedaPlanesNoviosTableModel;
import com.comerzzia.jpos.gui.validation.IValidableForm;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorFecha;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.core.tiendas.TiendasException;
import com.comerzzia.jpos.servicios.core.tiendas.TiendasServices;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.util.swing.acciones.Acciones;
import es.mpsistemas.util.log.Logger;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MGRI
 */
public class JBuscarPlanNovios extends JPanelImagenFondo implements IVista, IViewerValidationFormError {

    // log
    private static Logger log = Logger.getMLogger(JBuscarPlanNovios.class);
    private static PlanNovioBuscar manejador;
    private JPrincipal ventana_padre;
    private List<IValidableForm> formularioBusqueda;

    /** Creates new form JBuscarPlanNovios */
    public JBuscarPlanNovios() {

        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_buscar_plan_novios.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
        }
        catch (IOException ex) {
            log.error("No se pudo cargar la imagen de fondo de cBúsqueda de reservaciones");
        }
        catch (Exception e) {
            log.error("No se pudo cargar la imagen de fondo de cBúsqueda de reservaciones: " + e.getMessage(), e);
        }


        initComponents();
        PlanNovioBuscar.inicia();
        ventana_padre = JPrincipal.getInstance();
        formularioBusqueda = new LinkedList<IValidableForm>();
        tb_listaReservaciones.setDefaultRenderer(Object.class, new BusquedaPlanesNoviosCellRenderer());

        PlanNovioBuscar.setTablaResultadoPlanes(tb_listaReservaciones);
        // Inicilización de las tabla de búsqueda
        Border empty = new EmptyBorder(0, 0, 0, 0);
        jScrollPane1.setViewportBorder(empty);
        tb_listaReservaciones.setBorder(empty);
        jScrollPane1.getViewport().setOpaque(false);
        
        t_fecha_desde.addValidador(new ValidadorFecha(), this);
        t_fecha_hasta.addValidador(new ValidadorFecha(), this);
        try {
            l_tienda.addItem(Sesion.getTienda().getAlmacen());
            
            for(Almacen almacen: TiendasServices.consultarListaTiendas()){
                if(!almacen.equals(Sesion.getTienda().getAlmacen())){
                    l_tienda.addItem(almacen);                                                    
                }
            }            
           } catch (TiendasException e) {
            log.error("No se pudo cargar los almacenes: "+ e.getMessage());
        }
        inicializaFormulario();
        addFunctionKeys();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tiendasKeySelectionManager1 = new com.comerzzia.jpos.gui.modelos.TiendasKeySelectionManager();
        tiendasListRenderer1 = new com.comerzzia.jpos.gui.modelos.TiendasListRenderer();
        sesion1 = new com.comerzzia.jpos.servicios.login.Sesion();
        sesion1.listaTiendas = new ArrayList();
        sesion1.listaTiendas.add(Sesion.getTienda().getAlmacen());
        tiendasServices1 = new com.comerzzia.jpos.servicios.core.tiendas.TiendasServices();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_numero_reserva = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_documento_novia = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel5 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        t_apellido_novio = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel6 = new javax.swing.JLabel();
        l_estado = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        t_nombre_novia = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel8 = new javax.swing.JLabel();
        t_nombre_novio = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_fecha_desde = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_fecha_hasta = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t_apellido_novia = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_boda = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_documento_novio = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel12 = new javax.swing.JLabel();
        t_id_sukasa = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel4 = new javax.swing.JLabel();
        l_tienda = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        b_menu_ppal = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_listaReservaciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        b_nuevo_plan = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        lb_error = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jLabel2.setDisplayedMnemonic('m');
        jLabel2.setLabelFor(t_numero_reserva);
        jLabel2.setText("Número de Reserva:");

        jLabel3.setDisplayedMnemonic('b');
        jLabel3.setLabelFor(t_boda);
        jLabel3.setText("Boda:");

        t_numero_reserva.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_numero_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_numero_reservaActionPerformed(evt);
            }
        });
        t_numero_reserva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_reservaKeyTyped(evt);
            }
        });

        t_documento_novia.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_documento_novia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_documento_noviaKeyTyped(evt);
            }
        });

        jLabel5.setDisplayedMnemonic('d');
        jLabel5.setLabelFor(t_documento_novia);
        jLabel5.setText("Documento Novia:");

        jLabel36.setDisplayedMnemonic('p');
        jLabel36.setLabelFor(t_apellido_novio);
        jLabel36.setText("Apellidos Novio:");

        t_apellido_novio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        t_apellido_novio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_apellido_novioActionPerformed(evt);
            }
        });
        t_apellido_novio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_apellido_novioKeyTyped(evt);
            }
        });

        jLabel6.setDisplayedMnemonic('e');
        jLabel6.setLabelFor(l_estado);
        jLabel6.setText("Estado del Plan:");

        l_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Abierto", "Liquidado", "Caducado" }));
        l_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_estadoActionPerformed(evt);
            }
        });
        l_estado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                l_estadoKeyPressed(evt);
            }
        });

        jLabel7.setDisplayedMnemonic('n');
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setLabelFor(t_nombre_novia);
        jLabel7.setText("Nombres Novia:");

        t_nombre_novia.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_nombre_novia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nombre_noviaKeyTyped(evt);
            }
        });

        jLabel8.setDisplayedMnemonic('r');
        jLabel8.setLabelFor(t_nombre_novio);
        jLabel8.setText("Nombres de Novio:");

        t_nombre_novio.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_nombre_novio.setInputVerifier(null);
        t_nombre_novio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_nombre_novioKeyTyped(evt);
            }
        });

        t_fecha_desde.setPreferredSize(new java.awt.Dimension(8, 27));
        t_fecha_desde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_fecha_desdeKeyTyped(evt);
            }
        });

        t_fecha_hasta.setPreferredSize(new java.awt.Dimension(8, 27));
        t_fecha_hasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_fecha_hastaKeyTyped(evt);
            }
        });

        jLabel9.setDisplayedMnemonic('s');
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setLabelFor(t_fecha_desde);
        jLabel9.setText("Desde:");

        jLabel10.setDisplayedMnemonic('h');
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setLabelFor(t_fecha_hasta);
        jLabel10.setText("Hasta:");

        jLabel11.setDisplayedMnemonic('v');
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setLabelFor(t_apellido_novia);
        jLabel11.setText("Apellidos Novia:");

        t_apellido_novia.setPreferredSize(new java.awt.Dimension(8, 27));
        t_apellido_novia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_apellido_noviaKeyTyped(evt);
            }
        });

        t_boda.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_boda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_bodaKeyTyped(evt);
            }
        });

        t_documento_novio.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_documento_novio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_documento_novioKeyTyped(evt);
            }
        });

        jLabel12.setDisplayedMnemonic('c');
        jLabel12.setLabelFor(t_documento_novio);
        jLabel12.setText("Documento Novio:");

        t_id_sukasa.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        t_id_sukasa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_id_sukasaKeyTyped(evt);
            }
        });

        jLabel4.setDisplayedMnemonic('i');
        jLabel4.setLabelFor(t_id_sukasa);
        jLabel4.setText("Identificador Plan SUKASA:");

        l_tienda.setKeySelectionManager(tiendasKeySelectionManager1);
        l_tienda.setRenderer(tiendasListRenderer1);
        l_tienda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                l_tiendaKeyTyped(evt);
            }
        });

        jLabel13.setDisplayedMnemonic('L');
        jLabel13.setLabelFor(l_tienda);
        jLabel13.setText("Lugar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_fecha_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_apellido_novia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_nombre_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_numero_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_documento_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(t_id_sukasa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_apellido_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_fecha_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_documento_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_nombre_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_boda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(t_numero_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(l_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(l_tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(t_id_sukasa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(t_boda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(t_documento_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(t_documento_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(t_nombre_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(t_nombre_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(t_apellido_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(t_apellido_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(t_fecha_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(t_fecha_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        b_menu_ppal.setText("<html><center>Menú Principal <br/>F12</center></html>");
        b_menu_ppal.setMargin(new java.awt.Insets(2, 9, 2, 9));
        b_menu_ppal.setNextFocusableComponent(t_numero_reserva);
        b_menu_ppal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_menu_ppalActionPerformed(evt);
            }
        });

        tb_listaReservaciones.setOpaque(false);
        tb_listaReservaciones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_listaReservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_listaReservacionesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_listaReservaciones);

        jLabel1.setFont(jLabel1.getFont().deriveFont((float)18));
        jLabel1.setText("Gestión De Plan Novios");
        jLabel1.setFocusable(false);

        b_nuevo_plan.setText("<html><center>Nuevo Plan <br/>F1</center></html>");
        b_nuevo_plan.setMargin(new java.awt.Insets(2, 9, 2, 9));
        b_nuevo_plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nuevo_planActionPerformed(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b_nuevo_plan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_menu_ppal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_menu_ppal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_nuevo_plan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_numero_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_numero_reservaActionPerformed
}//GEN-LAST:event_t_numero_reservaActionPerformed

    private void t_numero_reservaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_reservaKeyTyped
        accionIntro(evt);
}//GEN-LAST:event_t_numero_reservaKeyTyped

    private void t_documento_noviaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_documento_noviaKeyTyped
        accionIntro(evt);
}//GEN-LAST:event_t_documento_noviaKeyTyped

    private void t_apellido_novioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_apellido_novioActionPerformed
}//GEN-LAST:event_t_apellido_novioActionPerformed

    private void t_apellido_novioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_apellido_novioKeyTyped
        accionIntro(evt);
}//GEN-LAST:event_t_apellido_novioKeyTyped

    private void l_estadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l_estadoKeyPressed
        accionIntro(evt);
}//GEN-LAST:event_l_estadoKeyPressed

    private void t_nombre_noviaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nombre_noviaKeyTyped
        accionIntro(evt);
}//GEN-LAST:event_t_nombre_noviaKeyTyped

    private void t_nombre_novioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nombre_novioKeyTyped
        accionIntro(evt);
}//GEN-LAST:event_t_nombre_novioKeyTyped

    private void t_fecha_desdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_fecha_desdeKeyTyped
        accionIntro(evt);
}//GEN-LAST:event_t_fecha_desdeKeyTyped

    private void t_fecha_hastaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_fecha_hastaKeyTyped
        accionIntro(evt);
}//GEN-LAST:event_t_fecha_hastaKeyTyped

    private void t_apellido_noviaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_apellido_noviaKeyTyped
        accionIntro(evt);
}//GEN-LAST:event_t_apellido_noviaKeyTyped

    private void b_menu_ppalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_menu_ppalActionPerformed
        if (b_menu_ppal.isEnabled()) {
            log.info("MENÚ PRINCIPAL");
            ventana_padre.mostrarMenu();
        }
}//GEN-LAST:event_b_menu_ppalActionPerformed

    private void tb_listaReservacionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_listaReservacionesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                manejador.setTablaResultadoPlanes(tb_listaReservaciones);
                manejador.seleccionaPlan(tb_listaReservaciones.getSelectedRow());
                ventana_padre.irMostrarPlanNovio();
            }
            catch (IndexOutOfBoundsException e) {
                ventana_padre.crearError("Debe de realizar una búsqueda antes de seleccionar una reservación. ");
            }
            catch (Exception e) {
                log.error(e.getMessage(), e);
                ventana_padre.crearError(null);
            }
        }
        else if (evt.getKeyCode() == KeyEvent.VK_TAB && evt.isShiftDown()) {
            tb_listaReservaciones.transferFocusBackward();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            tb_listaReservaciones.transferFocus();
        }
}//GEN-LAST:event_tb_listaReservacionesKeyPressed

    private void b_nuevo_planActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nuevo_planActionPerformed
        accionNuevoPlan();
    }//GEN-LAST:event_b_nuevo_planActionPerformed

    private void t_bodaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_bodaKeyTyped
        accionIntro(evt);
    }//GEN-LAST:event_t_bodaKeyTyped

    private void t_documento_novioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_documento_novioKeyTyped
        accionIntro(evt);
    }//GEN-LAST:event_t_documento_novioKeyTyped

    private void l_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_estadoActionPerformed
    }//GEN-LAST:event_l_estadoActionPerformed

    private void t_id_sukasaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_id_sukasaKeyTyped
        accionIntro(evt);
    }//GEN-LAST:event_t_id_sukasaKeyTyped

    private void l_tiendaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_l_tiendaKeyTyped
         accionIntro(evt);
    }//GEN-LAST:event_l_tiendaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_menu_ppal;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_nuevo_plan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox l_estado;
    private javax.swing.JComboBox l_tienda;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.servicios.login.Sesion sesion1;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_apellido_novia;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_apellido_novio;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_boda;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_documento_novia;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_documento_novio;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_fecha_desde;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_fecha_hasta;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_id_sukasa;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_nombre_novia;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_nombre_novio;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_reserva;
    private javax.swing.JTable tb_listaReservaciones;
    private com.comerzzia.jpos.gui.modelos.TiendasKeySelectionManager tiendasKeySelectionManager1;
    private com.comerzzia.jpos.gui.modelos.TiendasListRenderer tiendasListRenderer1;
    private com.comerzzia.jpos.servicios.core.tiendas.TiendasServices tiendasServices1;
    // End of variables declaration//GEN-END:variables

    private void accionBuscar() {
        try {
            // pasar parametros de búsqueda como un mapa
            t_fecha_desde.validar();
            t_fecha_hasta.validar();
            //pasar otro parametro para el combox
            manejador.estableceParametrosBusqueda(formularioBusqueda, l_estado, l_tienda);
            manejador.buscarPlanNovio();
            refrescaTablaPlanes();
        }
        catch (ValidationFormException ex) {
            addError(ex);
        }
    }

    private void accionLimpiarFormulario() {
        t_apellido_novia.setText("");
        t_apellido_novio.setText("");
        t_nombre_novia.setText("");
        t_nombre_novio.setText("");
        t_boda.setText("");
        t_fecha_desde.setText("");
        t_fecha_hasta.setText("");
        t_id_sukasa.setText("");
        t_documento_novia.setText("");
        t_documento_novio.setText("");
        t_numero_reserva.setText("");
        l_estado.setSelectedIndex(0);
        l_tienda.setSelectedIndex(0);
        lb_error.setText("");
    }

    private void accionNuevoPlan() {
        log.debug("ACCION NUEVO PLAN");
        manejador.setOperacion(PlanNovioBuscar.OPERACION_NUEVO_PLAN);
        ventana_padre.addIdentificaClienteReservacionView(manejador.getPlanNovio());
    }

    private void inicializaFormulario() {
        // El orden importa y ha de corresponderse con el orden en que se leen los resulados en 
        // el objeto paraetrosBuscar del Plan novios
        formularioBusqueda.add(t_numero_reserva);
        formularioBusqueda.add(t_boda);
        formularioBusqueda.add(t_documento_novia);
        formularioBusqueda.add(t_documento_novio);
        formularioBusqueda.add(t_nombre_novia);
        formularioBusqueda.add(t_nombre_novio);
        formularioBusqueda.add(t_apellido_novia);
        formularioBusqueda.add(t_apellido_novio);
        formularioBusqueda.add(t_fecha_desde);
        formularioBusqueda.add(t_fecha_hasta);
        formularioBusqueda.add(t_id_sukasa);
    }

    @Override
    public void iniciaVista() {
        log.debug("iniciamos el manejador de la pantalla");
        manejador = PlanNovioBuscar.inicia();
        manejador.setManejadorErrores(this);
        refrescaTablaPlanes();
        accionLimpiarFormulario();
        iniciaFoco();
        l_estado.setSelectedIndex(1);
    }

    public void refrescaTablaPlanes() {
        log.debug("refrescaTablaPlanes() ");
        if (PlanNovioBuscar.getListaPlanesBusqueda() == null) {
            log.debug("Se refrescó la tabla de planes sin resultados en la tabla");
            PlanNovioBuscar.setListaPlanesBusqueda((List<PlanNovio>) new LinkedList());
        }
        tb_listaReservaciones.setModel(new BusquedaPlanesNoviosTableModel(PlanNovioBuscar.getListaPlanesBusqueda()));
        tb_listaReservaciones.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        int i = 0;
        for (int tam : PlanNovioBuscar.getAnchosColumnasTablaResultadoPlanes()) {
            tb_listaReservaciones.getColumnModel().getColumn(i).setPreferredWidth(tam);
            i++;
        }
    }

    @Override
    public void iniciaFoco() {
        t_numero_reserva.requestFocus();
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }

    private void addFunctionKeys() {

        log.info("Función de acciones de teclado");
        KeyStroke f1 = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0);
        Action listenerf1 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionNuevoPlan();

            }
        };
        addHotKey(f1, "IdentClientF1", listenerf1);

        KeyStroke f12 = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        Action listenerf12 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_menu_ppalActionPerformed(ae);
            }
        };
        addHotKey(f12, "IdentClientF12", listenerf12);

        Acciones.crearAccionFocoTabla(this, tb_listaReservaciones);
    }

    private void accionIntro(KeyEvent evt) {

        if (evt.getKeyChar() == '\n') {

            JTextFieldForm focoEn = null;

            if (evt.getComponent() instanceof JTextFieldForm) {
                focoEn = (JTextFieldForm) evt.getComponent();
            }
            accionBuscar();

            if (tb_listaReservaciones.getRowCount() < 1 && focoEn != null) {
                focoEn.requestFocus();
            }

            if (tb_listaReservaciones.getRowCount() >= 0) {
                ListSelectionModel selectionModel = tb_listaReservaciones.getSelectionModel();
                selectionModel.setSelectionInterval(0, 0);
                tb_listaReservaciones.requestFocus();
            }
        }
    }
}
