/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDatosPlanNovio.java
 *
 * Created on 04-oct-2012, 13:39:38
 */
package com.comerzzia.jpos.gui.reservaciones.plannovios;

import com.comerzzia.jpos.entity.services.reservaciones.plannovio.PlanNovioDatosAdicionales;
import com.comerzzia.jpos.entity.services.reservaciones.plannovio.PlanNovioOBJ;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.gui.validation.IValidableForm;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorBigInteger;
import com.comerzzia.jpos.gui.validation.ValidadorEmail;
import com.comerzzia.jpos.gui.validation.ValidadorFecha2;
import com.comerzzia.jpos.gui.validation.ValidadorFechaHora;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidadorTelefono;
import com.comerzzia.jpos.gui.validation.ValidadorTexto;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.reservaciones.plannovio.PlanNovioException;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import es.mpsistemas.util.log.Logger;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.LinkedList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;

/**
 *
 * @author MGRI
 */
public class JDatosPlanNovio extends JPanelImagenFondo implements IVista, IViewerValidationFormError {

    private static Logger log = Logger.getMLogger(JDatosPlanNovio.class);
    private static PlanNovioDatosAdicionales manejador = null;
    private JPrincipal ventana_padre;
    private List<IValidableForm> formulario;

    /** Creates new form JDatosPlanNovio */
    public JDatosPlanNovio() {
        
        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_datos_plan_novios.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
        }
        catch (IOException ex) {
            log.error("No se pudo cargar la imagen de fondo de cBúsqueda de reservaciones");
        }
        catch (Exception e){
            log.error("No se pudo cargar la imagen de fondo de cBúsqueda de reservaciones: "+e.getMessage(),e);
        }
        
        initComponents();

        ventana_padre = JPrincipal.getInstance();

        inicializarValidacion();
        inicializarFormulario();
        addFunctionsKeys();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_boda = new javax.swing.JLabel();
        menu_navegacion = new javax.swing.JPanel();
        b_m_editar_cliente = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_facturar_otro_cliente = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_informacion_extra = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_confirmar_cliente = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_menu_principal = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_salvar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        l_nombre_novia = new javax.swing.JLabel();
        l_apellidos_novia = new javax.swing.JLabel();
        l_cedula_novia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        l_cedula_novio = new javax.swing.JLabel();
        l_apellidos_novio = new javax.swing.JLabel();
        l_nombre_novio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        t_fecha_hora_boda = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_lugar_boda = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        t_fecha_contacto_invitados = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel16 = new javax.swing.JLabel();
        t_telefono = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel18 = new javax.swing.JLabel();
        t_email = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_error = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lb_boda.setFont(lb_boda.getFont().deriveFont(lb_boda.getFont().getStyle() | java.awt.Font.BOLD, lb_boda.getFont().getSize()+2));
        lb_boda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menu_navegacion.setBackground(new java.awt.Color(255, 255, 255));
        menu_navegacion.setOpaque(false);
        menu_navegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_m_editar_cliente.setEnabled(false);
        b_m_editar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_editar_clienteActionPerformed(evt);
            }
        });
        menu_navegacion.add(b_m_editar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 7, 85, 85));

        b_m_facturar_otro_cliente.setEnabled(false);
        b_m_facturar_otro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_facturar_otro_clienteActionPerformed(evt);
            }
        });
        menu_navegacion.add(b_m_facturar_otro_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 7, 85, 85));

        b_m_cancelar.setAlignmentX(1.0F);
        b_m_cancelar.setEnabled(false);
        b_m_cancelar.setMargin(new java.awt.Insets(0, -5, 0, 0));
        b_m_cancelar.setMinimumSize(new java.awt.Dimension(90, 87));
        b_m_cancelar.setPreferredSize(new java.awt.Dimension(90, 87));
        b_m_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_cancelarActionPerformed(evt);
            }
        });
        menu_navegacion.add(b_m_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 85, 85));

        b_m_informacion_extra.setEnabled(false);
        b_m_informacion_extra.setMargin(new java.awt.Insets(0, -3, 0, 0));
        b_m_informacion_extra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_informacion_extraActionPerformed(evt);
            }
        });
        menu_navegacion.add(b_m_informacion_extra, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 7, 85, 85));

        b_m_confirmar_cliente.setEnabled(false);
        b_m_confirmar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_confirmar_clienteActionPerformed(evt);
            }
        });
        menu_navegacion.add(b_m_confirmar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 7, 85, 85));

        b_m_menu_principal.setText("<html><center>Menú Principal <br/>F12</center></html>");
        b_m_menu_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_menu_principalActionPerformed(evt);
            }
        });
        menu_navegacion.add(b_m_menu_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 7, 85, 85));

        b_m_salvar.setText("<html><center>Reservar <br/> F2</center></html>");
        b_m_salvar.setActionCommand("Identificar Cliente F3");
        b_m_salvar.setMargin(new java.awt.Insets(0, -3, 0, 0));
        b_m_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_salvarActionPerformed(evt);
            }
        });
        menu_navegacion.add(b_m_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 85, 85));

        jPanel1.setOpaque(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombres:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Apellidos:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Cédula:");

        l_nombre_novia.setFont(l_nombre_novia.getFont().deriveFont(l_nombre_novia.getFont().getSize()+2f));
        l_nombre_novia.setForeground(new java.awt.Color(51, 153, 255));

        l_apellidos_novia.setFont(l_apellidos_novia.getFont().deriveFont(l_apellidos_novia.getFont().getSize()+2f));
        l_apellidos_novia.setForeground(new java.awt.Color(51, 153, 255));

        l_cedula_novia.setFont(l_cedula_novia.getFont().deriveFont(l_cedula_novia.getFont().getSize()+2f));
        l_cedula_novia.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(l_apellidos_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_nombre_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_cedula_novia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_nombre_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_apellidos_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_cedula_novia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(451, 126));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Cédula:");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Apellidos:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Nombres:");

        l_cedula_novio.setFont(l_cedula_novio.getFont().deriveFont(l_cedula_novio.getFont().getSize()+2f));
        l_cedula_novio.setForeground(new java.awt.Color(51, 153, 255));

        l_apellidos_novio.setFont(l_apellidos_novio.getFont().deriveFont(l_apellidos_novio.getFont().getSize()+2f));
        l_apellidos_novio.setForeground(new java.awt.Color(51, 153, 255));

        l_nombre_novio.setFont(l_nombre_novio.getFont().deriveFont(l_nombre_novio.getFont().getSize()+2f));
        l_nombre_novio.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(l_apellidos_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_nombre_novio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_cedula_novio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_nombre_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_apellidos_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_cedula_novio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS DE LA NOVIA");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DATOS DEL NOVIO");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel4.setOpaque(false);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DATOS DE LA BODA");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel3.setOpaque(false);

        t_fecha_hora_boda.setToolTipText("dd/MM/yyyy - HH:mm");

        jLabel6.setDisplayedMnemonic('l');
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setLabelFor(t_lugar_boda);
        jLabel6.setText(" * Lugar de la Boda:");

        jLabel14.setDisplayedMnemonic('f');
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setLabelFor(t_fecha_hora_boda);
        jLabel14.setText("* Fecha y Hora de la Boda:");

        jLabel16.setDisplayedMnemonic('i');
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setLabelFor(t_fecha_contacto_invitados);
        jLabel16.setText("Fecha para contactar Invitados:");

        t_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_telefonoActionPerformed(evt);
            }
        });

        jLabel18.setDisplayedMnemonic('t');
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setLabelFor(t_telefono);
        jLabel18.setText("Telefono");

        jLabel19.setDisplayedMnemonic('e');
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setLabelFor(t_email);
        jLabel19.setText("Email");

        jLabel12.setDisplayedMnemonic('l');
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setLabelFor(t_lugar_boda);
        jLabel12.setText("Formato: dd/MM/yyyy - HH:mm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_lugar_boda, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_fecha_contacto_invitados, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(t_fecha_hora_boda, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(647, 647, 647))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_lugar_boda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_fecha_hora_boda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_fecha_contacto_invitados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lb_error.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu_navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lb_boda, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(454, 454, 454))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_boda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(100, 100, 100)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_m_editar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_editar_clienteActionPerformed
}//GEN-LAST:event_b_m_editar_clienteActionPerformed

    private void b_m_facturar_otro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_facturar_otro_clienteActionPerformed
}//GEN-LAST:event_b_m_facturar_otro_clienteActionPerformed

    private void b_m_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_cancelarActionPerformed
        accionCancelar();
    }//GEN-LAST:event_b_m_cancelarActionPerformed

    private void b_m_informacion_extraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_informacion_extraActionPerformed
    }//GEN-LAST:event_b_m_informacion_extraActionPerformed

    private void b_m_confirmar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_confirmar_clienteActionPerformed
}//GEN-LAST:event_b_m_confirmar_clienteActionPerformed

    private void b_m_menu_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_menu_principalActionPerformed
        if (b_m_menu_principal.isEnabled()) {
            log.info("MENÚ PRINCIPAL");
            ventana_padre.mostrarMenu();
        }
}//GEN-LAST:event_b_m_menu_principalActionPerformed

    private void b_m_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_salvarActionPerformed
        accionReservar();


    }//GEN-LAST:event_b_m_salvarActionPerformed

    private void t_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_telefonoActionPerformed
    }//GEN-LAST:event_t_telefonoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_confirmar_cliente;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_editar_cliente;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_facturar_otro_cliente;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_informacion_extra;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_menu_principal;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l_apellidos_novia;
    private javax.swing.JLabel l_apellidos_novio;
    private javax.swing.JLabel l_cedula_novia;
    private javax.swing.JLabel l_cedula_novio;
    private javax.swing.JLabel l_nombre_novia;
    private javax.swing.JLabel l_nombre_novio;
    private javax.swing.JLabel lb_boda;
    private javax.swing.JLabel lb_error;
    private javax.swing.JPanel menu_navegacion;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_email;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_fecha_contacto_invitados;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_fecha_hora_boda;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_lugar_boda;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_telefono;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciaVista() {
        log.debug("iniciaVista()");
        // Aquí iniciaVista ha de recibir el objeto del Plan noivios        
        manejador = PlanNovioDatosAdicionales.inicia();
        
        reseteaFormulario();
        // Lectura de los datos del novio y la novia
        PlanNovioDatosAdicionales.estableceDatosNovios(l_nombre_novia, l_apellidos_novia, l_cedula_novia, l_nombre_novio, l_apellidos_novio, l_cedula_novio, lb_boda);

        if (manejador.getPlanNovio().getModo() == PlanNovioOBJ.MODO_MODIFICANDO_PLAN) {
            // MODO MODIFICANDO
            PlanNovioDatosAdicionales.estableceDatosAdicionales( t_lugar_boda, t_fecha_hora_boda, t_fecha_contacto_invitados, t_telefono, t_email);
            b_m_salvar.setText("<html><center>Guardar<br/>Cambios<br/> F2</center></html>");
            b_m_cancelar.setText("<html><center>Cancelar<br/> F3</center></html>");
            b_m_cancelar.setEnabled(true);

        }
        else {
            // MODO RESERVANDO
            b_m_salvar.setText("<html><center>Reservar <br/> F2</center></html>");
            b_m_cancelar.setText("");
            b_m_cancelar.setEnabled(false);
        }

        iniciaFoco();
    }

    @Override
    public void iniciaFoco() {
        t_lugar_boda.requestFocus();
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }

    private void inicializarValidacion() {
        
        t_lugar_boda.addValidador(new ValidadorObligatoriedad(), this);
        t_lugar_boda.addValidador(new ValidadorTexto(400), this);
        // validador de fecha/hora
        t_fecha_hora_boda.addValidador(new ValidadorObligatoriedad(), this);
        t_fecha_hora_boda.addValidador(new ValidadorFechaHora(), this);
        
        t_fecha_contacto_invitados.addValidador(new ValidadorFecha2(), this);
        t_telefono.addValidador(new ValidadorTelefono(), this);
        t_telefono.addValidador(new ValidadorBigInteger(), this);
        t_email.addValidador(new ValidadorEmail(), this);
    }

    private void inicializarFormulario() {
        formulario = new LinkedList<IValidableForm>();

        formulario.add(t_lugar_boda);
        formulario.add(t_fecha_hora_boda);
        formulario.add(t_fecha_contacto_invitados);
        formulario.add(t_telefono);
        formulario.add(t_email);
        
    }

    private void accionReservar() {
        try {
            log.debug("accionReservar()");
            log.debug("-- Validación");
            for (IValidableForm ivf : formulario) {
                ivf.validar();
            }
            manejador.establecerDatosAdicionales( t_lugar_boda, t_fecha_hora_boda, t_fecha_contacto_invitados, t_telefono, t_email);

            if (manejador.getPlanNovio().getModo() == PlanNovioOBJ.MODO_MODIFICANDO_PLAN) {
                // MODO MODIFICANDO
                log.debug("-- Modificando Plan");
                manejador.modificaPlan();
            }
            else {
                // MODO CREACION
                log.debug("-- Creando Plan");
                manejador.crearPlan();
            }

            ventana_padre.irMostrarPlanNovio();
        }
        catch (PlanNovioException ex) {
            log.error(ex.getMessage());
            addError(new ValidationFormException("Error guardando datos del Plan"));
        }
        catch (ValidationFormException ex) {
            lb_error.setText(ex.getMessage());
            log.debug("Errores de validación en el formulario");
            addError(ex);
        }
        catch (Exception e){
            log.error("Error guardando datos del plan: "+e.getMessage(),e);
        }
    }

    private void addFunctionKeys() {

        log.info("Función de acciones de teclado");
        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionReservar();

            }
        };
        addHotKey(f2, "DatosPNF2", listenerf2);
        
        KeyStroke f3 = KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0);
        Action listenerf3 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCancelar();

            }
        };
        addHotKey(f3, "DatosPNF3", listenerf3);

        KeyStroke f12 = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        Action listenerf12 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_m_menu_principalActionPerformed(ae);
            }
        };
        addHotKey(f12, "IdentClientF12", listenerf12);
    }

    private void accionCancelar() {
        if (b_m_cancelar.isEnabled()) {
            // Hasta el momento, a cancelar solo se accede desde el modo modificar Plan
            ventana_padre.irMostrarPlanNovio();
        }
    }

    private void reseteaFormulario() {
        deshabilitaFormulario();
        t_lugar_boda.setText("");
        t_fecha_hora_boda.setText("");
        t_fecha_contacto_invitados.setText("");
        t_email.setText("");
        t_telefono.setText("");
        habilitaFormulario();
    }

    private void deshabilitaFormulario() {
        for(IValidableForm ivf: formulario){
            ivf.setValidacionHabilitada(false);
        }
    }
    private void habilitaFormulario() {
        for(IValidableForm ivf: formulario){
            ivf.setValidacionHabilitada(true);
        }
    }

    private void addFunctionsKeys() {
        
        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                accionReservar();
            }
        };
        addHotKey(f2, "DatPlanF2PlanNovio", listenerf2);
        
        KeyStroke f3 = KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0);
        Action listenerf3 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }
        };
        addHotKey(f3, "DatPlanF3PlanNovio", listenerf3);
        
                // ACCIÓN PARA MENU
        KeyStroke f12 = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        Action listenerf12 = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                b_m_menu_principalActionPerformed(ae);
            }
        };
        addHotKey(f12, "DatPlanF12", listenerf12);
        
        
    }
}
