/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JReservacionesLiquidacionParcial.java
 *
 * Created on 28-sep-2011, 13:18:52
 */
package com.comerzzia.jpos.gui.reservaciones.plannovios;
import com.comerzzia.jpos.entity.db.AbonoPlanNovio;
import com.comerzzia.jpos.entity.db.ArticuloPlanNovio;

import com.comerzzia.jpos.entity.services.reservaciones.plannovio.PlanNovioMostrar;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.reservaciones.plannovios.modelos.LiquidacionPlanCellRenderer;
import com.comerzzia.jpos.gui.reservaciones.plannovios.modelos.LiquidacionPlanTableModel;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.jpos.servicios.reservaciones.plannovio.PlanNovioException;
import es.mpsistemas.util.log.Logger;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class JPlanLiquidacionParcial extends JVentanaDialogo implements IVista {

    private static final Logger log = Logger.getMLogger(JPlanLiquidacionParcial.class);
    private JDialog contenedor;
    private boolean cancelado = false;
    PlanNovioMostrar manejador;


    /** Creates new form JReservacionesLiquidacionParcial */
    public JPlanLiquidacionParcial() {
        initComponents();
        registraEventoEnterBoton();
        registrarEventoBloqueoAplicacion();
        crearAccionFocoTabla(this, tb_articulos,  KeyEvent.VK_T, InputEvent.CTRL_MASK);
        cancelado = true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_articulos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        jLabel2 = new javax.swing.JLabel();
        t_total_abonado = new javax.swing.JTextField();
        t_articulos_seleccionados = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_restante_abonos = new javax.swing.JTextField();
        lb_error = new javax.swing.JLabel();

        tb_articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_articulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_articulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_articulosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb_articulos);

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, 18));
        jLabel1.setText("Remate Parcial");

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(b_ok.getFont().deriveFont((float)15));
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(b_cancelar.getFont().deriveFont((float)15));
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Total abonos en este local: ");

        t_total_abonado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        t_total_abonado.setEnabled(false);

        t_articulos_seleccionados.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        t_articulos_seleccionados.setEnabled(false);

        jLabel3.setText("Total artículos seleccionados:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setText("Abonos disponibles en este local:");

        t_restante_abonos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        t_restante_abonos.setEnabled(false);

        lb_error.setForeground(new java.awt.Color(255, 0, 51));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t_total_abonado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(t_articulos_seleccionados)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(t_restante_abonos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(t_total_abonado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(t_articulos_seleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(t_restante_abonos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Remate Parcial");
    }// </editor-fold>//GEN-END:initComponents

private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
    log.info("Acción Aceptar");
    cancelado = false;
    contenedor.setVisible(false);

}//GEN-LAST:event_b_okActionPerformed

private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
    log.info("Acción Cancelar");
    manejador.estableceArticulosSeleccionadosComoNoComprados();
    cancelado = true;
    contenedor.setVisible(false);
}//GEN-LAST:event_b_cancelarActionPerformed

private void tb_articulosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_articulosKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        int indiceSeleccionado = -1;
        try {
            indiceSeleccionado = tb_articulos.getSelectedRow();
            manejador.accionSeleccionaArticulo(indiceSeleccionado);
            lb_error.setText("");
        }
        catch (PlanNovioException e) {
            lb_error.setText(e.getMessage());
        }
        t_articulos_seleccionados.setText(manejador.getSeleccionados().toString());
        t_restante_abonos.setText(manejador.getRestante().toString());
        refrescarTabla(indiceSeleccionado);
    }
    else if (evt.getKeyCode() == KeyEvent.VK_TAB && evt.isShiftDown()) {
        tb_articulos.transferFocusBackward();
    }
    else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
        tb_articulos.transferFocus();
    }
}//GEN-LAST:event_tb_articulosKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_error;
    private javax.swing.JTextField t_articulos_seleccionados;
    private javax.swing.JTextField t_restante_abonos;
    private javax.swing.JTextField t_total_abonado;
    private javax.swing.JTable tb_articulos;
    // End of variables declaration//GEN-END:variables

    public List<ArticuloPlanNovio> getArticulosSeleccionados() {
        return manejador.getPlanNovio().getArticulosSeleccionados();
    }

    public JDialog getContenedor() {
        return contenedor;
    }

    public void setContenedor(JDialog contenedor) {
        this.contenedor = contenedor;
    }

    private void refrescarTabla(final int indiceSeleccionado) {
        if (manejador.getPlanNovio().getArticulosSeleccionados().isEmpty()) {
            b_ok.setEnabled(false);
        }
        else {
            b_ok.setEnabled(true);
        }
        LiquidacionPlanTableModel modelo = new LiquidacionPlanTableModel(manejador.getPlanNovio().getArticulosNoComprados());
        tb_articulos.setModel(modelo);
        if (tb_articulos.getRowCount() >= 0) {
            ListSelectionModel selectionModel = tb_articulos.getSelectionModel();
            
            SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        if (indiceSeleccionado >= 0) {
                            tb_articulos.addRowSelectionInterval(indiceSeleccionado, indiceSeleccionado);
                        }
                    }
                });
            
            
            tb_articulos.requestFocus();
        }
        else {
            b_cancelar.requestFocus();
        }
    }

    @Override
    public void iniciaVista() {
        manejador = PlanNovioMostrar.getIstance();
        cancelado = true;
        // Iría en constructor pero esta dando problemas         
        manejador.inicializaLiquidacion();

        //Calcular el valor que puede utilizar de ese local
        BigDecimal totalAbonoLocal = BigDecimal.ZERO;
        for(AbonoPlanNovio abonoPlanNovio : manejador.getPlanNovio().getPlan().getAbonoPlanNovioList()){
            if(abonoPlanNovio.getAbonoPlanNovioPK().getCodAlmAbono().equals(Sesion.getTienda().getCodalm()) &&
                    (abonoPlanNovio.getEstadoLiquidacion() == null || !abonoPlanNovio.getEstadoLiquidacion().equals("L"))){
                totalAbonoLocal = totalAbonoLocal.add(abonoPlanNovio.getCantidadConDcto());
            }
        }
        BigDecimal porAbonar = totalAbonoLocal.subtract(manejador.getPlanNovio().getPlan().getComprado());
        t_total_abonado.setText(totalAbonoLocal.toString());
        t_restante_abonos.setText(porAbonar.toString());
        t_articulos_seleccionados.setText(manejador.getSeleccionados().toString());

        tb_articulos.setDefaultRenderer(Object.class, new LiquidacionPlanCellRenderer());
        refrescarTabla(-1);

        //List<ReservaArticulo> articulosNoComprados, BigDecimal totalAbonado
        tb_articulos.requestFocus();
    }
   /*     t_total_abonado.setText(manejador.getPlanNovio().getPlan().getAbonadoConDto().toString());
        t_restante_abonos.setText(manejador.getRestante().toString());
        t_articulos_seleccionados.setText(manejador.getSeleccionados().toString());

        tb_articulos.setDefaultRenderer(Object.class, new LiquidacionPlanCellRenderer());
        refrescarTabla(-1);

        //List<ReservaArticulo> articulosNoComprados, BigDecimal totalAbonado
        tb_articulos.requestFocus();
    }*/

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
    }

    public boolean isCancelado() {
        return cancelado;
    }

    public void setCancelado(boolean cancelado) {
        this.cancelado = cancelado;
    }

    @Override
    public void accionCancelar() {
        b_cancelarActionPerformed(null);
    }

    @Override
    public void iniciaFoco() {
        log.info("Iniciando Foco");
        tb_articulos.requestFocus();
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

    void reseteaArticulosSeleccionados() {
        manejador.estableceArticulosSeleccionadosComoNoComprados();
    }
}
