/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JStock.java
 *
 * Created on 28-nov-2012, 16:55:32
 */
package com.comerzzia.jpos.gui.stock;

import com.comerzzia.jpos.entity.db.Articulos;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.stock.modelos.StockCellRenderer;
import com.comerzzia.jpos.gui.stock.modelos.StockTableModel;
import com.comerzzia.jpos.servicios.core.permisos.Operaciones;
import com.comerzzia.jpos.servicios.core.permisos.SinPermisosException;
import com.comerzzia.jpos.servicios.stock.StockException;
import com.comerzzia.jpos.servicios.stock.StockManager;
import es.mpsistemas.util.log.Logger;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.ListSelectionModel;

/**
 *
 * @author MGRI
 */
public class JStock extends JVentanaDialogo {

    private static final Logger log = Logger.getMLogger(JVentanaDialogo.class);
    StockManager manejador = new StockManager();
    /** Creates new form JStock */
    public JStock() {
        initComponents(); 
        manejador = StockManager.getInstance();     
        tb_listaStock.setDefaultRenderer(Object.class,new StockCellRenderer());        
        crearAccionFocoTabla(this, tb_listaStock, KeyEvent.VK_T, InputEvent.CTRL_MASK);   
        registraEventoEnterBoton();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_articulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_listaStock = new javax.swing.JTable();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_otros_locales = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        lb_error = new javax.swing.JLabel();

        lb_articulo.setFont(lb_articulo.getFont().deriveFont(lb_articulo.getFont().getStyle() | java.awt.Font.BOLD, lb_articulo.getFont().getSize()+2));
        lb_articulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_articulo.setText("Articulo");

        tb_listaStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tb_listaStockFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_listaStockFocusLost(evt);
            }
        });
        tb_listaStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_listaStockKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_listaStock);

        b_cancelar.setMnemonic('c');
        b_cancelar.setText("Cancelar");
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_otros_locales.setMnemonic('D');
        b_otros_locales.setText("Desglose Locales");
        b_otros_locales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_otros_localesActionPerformed(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(255, 0, 0));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_error.setText("Mensaje de error al consultar stock");
        lb_error.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b_otros_locales, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(lb_articulo, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lb_articulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_otros_locales, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        b_otros_locales.getAccessibleContext().setAccessibleName("Desglose Locales");
    }// </editor-fold>//GEN-END:initComponents

    private void tb_listaStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaStockFocusGained
        if (tb_listaStock.getRowCount() >= 0) {
            ListSelectionModel selectionModel = tb_listaStock.getSelectionModel();
            selectionModel.setSelectionInterval(0, 0);
        }
}//GEN-LAST:event_tb_listaStockFocusGained

    private void tb_listaStockFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaStockFocusLost
        
}//GEN-LAST:event_tb_listaStockFocusLost

    private void tb_listaStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_listaStockKeyPressed
        if (evt.getKeyChar() == '\n') {
            
        } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            b_otros_locales.requestFocus();
        }
    }//GEN-LAST:event_tb_listaStockKeyPressed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
       accionCancelar();
}//GEN-LAST:event_b_cancelarActionPerformed

    private void b_otros_localesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_otros_localesActionPerformed
       accionOtrosLocales();               
    }//GEN-LAST:event_b_otros_localesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_otros_locales;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_articulo;
    private javax.swing.JLabel lb_error;
    private javax.swing.JTable tb_listaStock;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
        lb_error.setText("");
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
    
    public void iniciaVista(){    
        limpiarFormulario();  
        
        try{
            manejador.accionConsultarStockTotal();
            refrescaTabla(true);
        }
        catch (StockException e){
            log.error(e.getMessage());
        }
        catch(Exception e){
            log.error("No se pudo consultar el Stock");
        }
        
        lb_articulo.setText(manejador.getNombreArticulo());
    }

    private void refrescaTabla(boolean mostrarBloqueo) {
        tb_listaStock.setModel(new StockTableModel(manejador.getListaStock(), mostrarBloqueo));
    }

    public void setArticuloBuscado(Articulos articulo) {
        manejador.setArticuloBuscado(articulo);
    }

    public void setArticuloBuscado(Vector vectorArt) {
        log.debug("setArticuloBuscado() - establecemos el articulo buscado");
        Articulos art = new Articulos();
        art.setCodart((String)vectorArt.get(0));
        art.setDesart((String)vectorArt.get(1));
        manejador.setArticuloBuscado(art);
    }

    private void accionOtrosLocales() {
        contenedor.setVisible(false);
        try{
            lb_error.setText("");   
            // Pedimos autorización
            String codAdministrador = JPrincipal.getInstance().compruebaAutorizacion(Operaciones.STOCK, "Necesitas permisos para ver el stock");
            manejador.accionConsultaStockOtrosLocales();
            refrescaTabla(false);
        }
        catch (StockException e){
            log.error(e.getMessage());
        }
        catch (SinPermisosException ex) {
            log.debug("No se tiene permisos para añadir el artículo con falta de stock.");
        }
        catch(Exception e){
            log.error("No se pudo consultar el Stock");
        }
        contenedor.setVisible(true);
    }

}
