/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JAutorizacionTarjeta.java
 *
 * Created on 04-sep-2012, 16:01:29
 */
package com.comerzzia.jpos.gui.bancos;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorBigInteger;
import com.comerzzia.jpos.gui.validation.ValidadorNumeroSoloCeros;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.pagos.credito.PagoCredito;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;

/**
 *
 * @author MGRI
 */
public class JAutorizacionNumTarjeta extends JVentanaDialogo implements IViewerValidationFormError {

    private String numeroAutorizacion = "";
    private String tipoAutorizacion = "";
    private PagoCredito pagoCredito;

    /** Creates new form JAutorizacionTarjeta */
    public JAutorizacionNumTarjeta() {
        initComponents();
        
        addFunctionsKeys();
        registraEventoEnterBoton();
        t_numero_autorizacion.addValidador(new ValidadorObligatoriedad(), this);
        t_numero_autorizacion.addValidador(new ValidadorBigInteger(), this);
        t_numero_autorizacion.addValidador(new ValidadorNumeroSoloCeros(), this);
        t_numero_autorizacion.setValidacionHabilitada(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_numero_autorizacion = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        b_ok2 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        lb_error = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_tipo_autorizacion = new javax.swing.JComboBox();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
        jLabel1.setText("Pago con Tarjeta de Crédito");

        jLabel2.setDisplayedMnemonic('N');
        jLabel2.setLabelFor(t_numero_autorizacion);
        jLabel2.setText("Número de autorización:");

        t_numero_autorizacion.setNextFocusableComponent(c_tipo_autorizacion);

        b_ok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok2.setMnemonic('a');
        b_ok2.setText("Aceptar");
        b_ok2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ok2ActionPerformed(evt);
            }
        });

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(204, 0, 0));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setDisplayedMnemonic('T');
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setLabelFor(c_tipo_autorizacion);
        jLabel3.setText("Tipo Autorización:");

        jLabel4.setFont(jLabel4.getFont().deriveFont(jLabel4.getFont().getStyle() & ~java.awt.Font.BOLD));
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Descripcion tarjeta");

        c_tipo_autorizacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automática", "Manual" }));
        c_tipo_autorizacion.setNextFocusableComponent(b_ok2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(c_tipo_autorizacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b_ok2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_numero_autorizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_numero_autorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(c_tipo_autorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_ok2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ok2ActionPerformed
        accionAceptar();
    }//GEN-LAST:event_b_ok2ActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.listenerList = null;
        limpiarFormulario();        
        getContenedor().setVisible(false);            
        
}//GEN-LAST:event_b_cancelarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok2;
    private javax.swing.JComboBox c_tipo_autorizacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_autorizacion;
    // End of variables declaration//GEN-END:variables

    
    public void iniciaVista(PagoCredito pago){
        this.pagoCredito = pago;
        limpiarFormulario();
        t_numero_autorizacion.requestFocus();
        jLabel2.setText("Número de autorización de "+pago.getMedioPagoActivo().getDesMedioPago()+":");
    }
    
    @Override
    public void accionAceptar() {
        try {
            t_numero_autorizacion.validar();
            numeroAutorizacion = t_numero_autorizacion.getText().trim();
            tipoAutorizacion = c_tipo_autorizacion.getSelectedItem().toString();
            pagoCredito.setCodigoValidacionManual(numeroAutorizacion);
            if(tipoAutorizacion.equals("Automática")){
                pagoCredito.setTipoValidacionManual("A");
            } else {
                pagoCredito.setTipoValidacionManual("M");
            }
            String resultado = pagoCredito.validarAutorizacionManual();
            if (resultado != null){
                pagoCredito.setCodigoValidacionManual(null);
                lb_error.setText(resultado);
                t_numero_autorizacion.requestFocus(true);
                return;
            }
            pagoCredito.setValidadoManual(true);
            contenedor.setVisible(false);
        }
        catch (ValidationFormException ex) {
            addError(ex);
        }
    }

    @Override
    public void limpiarFormulario() {
        numeroAutorizacion ="";
        tipoAutorizacion ="";
        t_numero_autorizacion.setText("");
        c_tipo_autorizacion.setSelectedIndex(0);
        lb_error.setText("");
        jLabel4.setText("");
    }

    public String getNumeroAutorizacion() {
        return numeroAutorizacion;
    }

    public void setNumeroAutorizacion(String numeroAutorizacion) {
        this.numeroAutorizacion = numeroAutorizacion;
    }

    public String getTipoAutorizacion() {
        return tipoAutorizacion;
    }

    public void setTipoAutorizacion(String tipoAutorizacion) {
        this.tipoAutorizacion = tipoAutorizacion;
    }
    
    public void iniciaFoco(){
        t_numero_autorizacion.requestFocus();
    }
    
    private void addFunctionsKeys() {        
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
                
    }
        
    @Override
    public void accionLeerTarjetaVD() {
    }    
    
}
