/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JAutorizacionTarjeta.java
 *
 * Created on 04-sep-2012, 16:01:29
 */
package com.comerzzia.jpos.gui.bancos;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.validation.IValidableForm;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorBigInteger;
import com.comerzzia.jpos.gui.validation.ValidadorEntero;
import com.comerzzia.jpos.gui.validation.ValidadorFechaAnioMesValida;
import com.comerzzia.jpos.gui.validation.ValidadorNumeroSoloCeros;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidadorTexto;
import com.comerzzia.jpos.gui.validation.ValidationException;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.mediospago.tarjetas.TarjetaCredito;
import com.comerzzia.jpos.servicios.pagos.credito.PagoCredito;
import com.comerzzia.jpos.servicios.pagos.credito.PagoCreditoSK;
import com.comerzzia.jpos.util.enums.EnumTipoPagoManual;
import com.comerzzia.util.Constantes;
import es.mpsistemas.util.log.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.KeyStroke;

/**
 *
 * @author MGRI
 */
public class JAutorizacionTarjeta extends JVentanaDialogo implements IViewerValidationFormError {
    
    private static final Logger log = Logger.getMLogger(JAutorizacionTarjeta.class);
    private String numeroAutorizacion = "";
    private PagoCredito pagoCredito;
    private String caducidad;
    private String cvv;
    private String numeroTarjeta;
    private boolean ventaManual;
    private ButtonGroup grupoRadio ;
    
    private List<IValidableForm> formularioFacturacion;

    /**
     * Creates new form JAutorizacionTarjeta
     */
    public JAutorizacionTarjeta() {
        
        initComponents();
        log.debug("initComponents() - Inicializando campos");
        addFunctionsKeys();
        registraEventoEnterBoton();
        inicializaValidacion();
        creaFormularioCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_numero_autorizacion = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        b_ok2 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_cancelar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        lb_error = new javax.swing.JLabel();
        lb_num_tarjeta = new javax.swing.JLabel();
        t_tarjeta_credito = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_fecha_caducidad = new javax.swing.JLabel();
        t_fecha_caducidad = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel4 = new javax.swing.JLabel();
        lb_cod_seguridad = new javax.swing.JLabel();
        t_cod_seguridad = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lblNombeTarjeta = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lb_num_autoriizacion = new javax.swing.JLabel();
        t_numero_lote = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_lote = new javax.swing.JLabel();
        rad_pos_movil = new javax.swing.JRadioButton();
        rad_data_link = new javax.swing.JRadioButton();
        rad_manual = new javax.swing.JRadioButton();
        lb_num_orden = new javax.swing.JLabel();
        t_num_orden_emi = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_num_orden_ven = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_numero_orden = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();

        setMaximumSize(new java.awt.Dimension(32800, 32800));
        setPreferredSize(new java.awt.Dimension(550, 350));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+2));
        jLabel1.setText("Pago Manual con Tarjeta de Crédito");

        t_numero_autorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_numero_autorizacionActionPerformed(evt);
            }
        });
        t_numero_autorizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_autorizacionKeyTyped(evt);
            }
        });

        b_ok2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok2.setMnemonic('a');
        b_ok2.setText("Aceptar");
        b_ok2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ok2ActionPerformed(evt);
            }
        });

        b_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/cancelar.png"))); // NOI18N
        b_cancelar.setText("Cancelar");
        b_cancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(204, 0, 0));

        lb_num_tarjeta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_num_tarjeta.setText("<html>Número de tarjeta:</html>");

        t_tarjeta_credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_tarjeta_creditoActionPerformed(evt);
            }
        });
        t_tarjeta_credito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_tarjeta_creditoKeyTyped(evt);
            }
        });

        lb_fecha_caducidad.setText("Fecha de Caducidad:");

        t_fecha_caducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_fecha_caducidadActionPerformed(evt);
            }
        });
        t_fecha_caducidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_fecha_caducidadKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("(AAMM)");

        lb_cod_seguridad.setText("Cod. Seguridad:");

        t_cod_seguridad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cod_seguridadKeyTyped(evt);
            }
        });

        lblNombeTarjeta.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        lblNombeTarjeta.setText(" ");

        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lb_num_autoriizacion.setText("Número de autorización:");
        lb_num_autoriizacion.setMaximumSize(new java.awt.Dimension(113, 35));
        lb_num_autoriizacion.setMinimumSize(new java.awt.Dimension(113, 35));
        lb_num_autoriizacion.setPreferredSize(new java.awt.Dimension(113, 35));

        t_numero_lote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_loteKeyTyped(evt);
            }
        });

        lb_lote.setText("Lote:");
        lb_lote.setMaximumSize(new java.awt.Dimension(113, 35));
        lb_lote.setMinimumSize(new java.awt.Dimension(113, 35));
        lb_lote.setPreferredSize(new java.awt.Dimension(113, 35));

        rad_pos_movil.setText("Pos móvil");
        rad_pos_movil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_pos_movilActionPerformed(evt);
            }
        });

        rad_data_link.setText("Datalink");
        rad_data_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_data_linkActionPerformed(evt);
            }
        });

        rad_manual.setText("Manual");
        rad_manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_manualActionPerformed(evt);
            }
        });

        lb_num_orden.setText("Número de orden");
        lb_num_orden.setToolTipText("");

        t_num_orden_emi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_num_orden_emiActionPerformed(evt);
            }
        });
        t_num_orden_emi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_num_orden_emiKeyTyped(evt);
            }
        });

        t_num_orden_ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_num_orden_venActionPerformed(evt);
            }
        });
        t_num_orden_ven.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_num_orden_venKeyTyped(evt);
            }
        });

        t_numero_orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_numero_ordenActionPerformed(evt);
            }
        });
        t_numero_orden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_ordenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombeTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(rad_data_link)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad_pos_movil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rad_manual))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_num_orden)
                            .addComponent(lb_num_autoriizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_lote, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_num_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_fecha_caducidad))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_numero_lote, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_numero_autorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(t_num_orden_ven, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_num_orden_emi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(t_numero_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t_tarjeta_credito, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t_fecha_caducidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lb_cod_seguridad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_cod_seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_ok2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(b_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombeTarjeta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rad_data_link)
                    .addComponent(rad_manual)
                    .addComponent(rad_pos_movil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_num_orden)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_numero_autorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_num_autoriizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t_num_orden_emi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t_numero_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(t_num_orden_ven, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_numero_lote, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_lote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_tarjeta_credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_num_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_fecha_caducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lb_fecha_caducidad)
                    .addComponent(lb_cod_seguridad)
                    .addComponent(t_cod_seguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_ok2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ok2ActionPerformed
        accionAceptar();
    }//GEN-LAST:event_b_ok2ActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.listenerList = null;
        limpiarFormulario();
        getContenedor().setVisible(false);
        

}//GEN-LAST:event_b_cancelarActionPerformed

    private void t_fecha_caducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_fecha_caducidadActionPerformed

}//GEN-LAST:event_t_fecha_caducidadActionPerformed

    private void t_tarjeta_creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_tarjeta_creditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_tarjeta_creditoActionPerformed

    private void t_tarjeta_creditoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_tarjeta_creditoKeyTyped
        int maxLength = 16;
        if (t_tarjeta_credito.getText().length() >= maxLength) {
            evt.consume();
        }
    }//GEN-LAST:event_t_tarjeta_creditoKeyTyped

    private void t_fecha_caducidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_fecha_caducidadKeyTyped
        int maxLength = 4;
        if (t_fecha_caducidad.getText().length() >= maxLength) {
            evt.consume();
        }
    }//GEN-LAST:event_t_fecha_caducidadKeyTyped

    private void t_cod_seguridadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_seguridadKeyTyped
        int maxLength = 4;
        if (t_cod_seguridad.getText().length() >= maxLength) {
            evt.consume();
        }
    }//GEN-LAST:event_t_cod_seguridadKeyTyped

    private void t_numero_autorizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_autorizacionKeyTyped
        int maxLength = 6;
        if (t_numero_autorizacion.getText().length() >= maxLength) {
            evt.consume();
        }
    }//GEN-LAST:event_t_numero_autorizacionKeyTyped

    private void t_numero_loteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_loteKeyTyped
        int maxLength = 6;
        if (t_numero_lote.getText().length() >= maxLength) {
            evt.consume();
        }
    }//GEN-LAST:event_t_numero_loteKeyTyped

    private void t_numero_autorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_numero_autorizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_numero_autorizacionActionPerformed

    private void rad_pos_movilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_pos_movilActionPerformed
        visibleCampos();
    }//GEN-LAST:event_rad_pos_movilActionPerformed

    private void rad_data_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_data_linkActionPerformed
        visibleCampos();
    }//GEN-LAST:event_rad_data_linkActionPerformed

    private void rad_manualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_manualActionPerformed
        visibleCampos();
    }//GEN-LAST:event_rad_manualActionPerformed

    private void t_num_orden_emiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_num_orden_emiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_num_orden_emiActionPerformed

    private void t_num_orden_emiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_num_orden_emiKeyTyped
        int maxLength = 3;
        if (t_num_orden_emi.getText().length() >= maxLength) {
            evt.consume();
        }
    }//GEN-LAST:event_t_num_orden_emiKeyTyped

    private void t_num_orden_venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_num_orden_venActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_num_orden_venActionPerformed

    private void t_num_orden_venKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_num_orden_venKeyTyped
        int maxLength = 3;
        if (t_num_orden_ven.getText().length() >= maxLength) {
            evt.consume();
        }
    }//GEN-LAST:event_t_num_orden_venKeyTyped

    private void t_numero_ordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_numero_ordenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_numero_ordenActionPerformed

    private void t_numero_ordenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_ordenKeyTyped
       int maxLength = 9;
        if (t_numero_orden.getText().length() >= maxLength) {
            evt.consume();
        }
    }//GEN-LAST:event_t_numero_ordenKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_cancelar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_cod_seguridad;
    private javax.swing.JLabel lb_error;
    private javax.swing.JLabel lb_fecha_caducidad;
    private javax.swing.JLabel lb_lote;
    private javax.swing.JLabel lb_num_autoriizacion;
    private javax.swing.JLabel lb_num_orden;
    private javax.swing.JLabel lb_num_tarjeta;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombeTarjeta;
    private javax.swing.JRadioButton rad_data_link;
    private javax.swing.JRadioButton rad_manual;
    private javax.swing.JRadioButton rad_pos_movil;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_cod_seguridad;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_fecha_caducidad;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_num_orden_emi;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_num_orden_ven;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_autorizacion;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_lote;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_orden;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_tarjeta_credito;
    // End of variables declaration//GEN-END:variables

    public void iniciaVista(PagoCredito pago, String mensaje, boolean ventaManual) {
        this.pagoCredito = pago;
        this.ventaManual = ventaManual;
        this.grupoRadio = new ButtonGroup();
        t_numero_autorizacion.requestFocus();
        limpiarFormulario();
        
        if (pagoCredito != null) {
            if (pagoCredito.getTarjetaCredito() != null && pagoCredito.getTarjetaCredito().getMedioPago() != null) {
                lblNombeTarjeta.setText(pagoCredito.getTarjetaCredito().getMedioPago().getDesMedioPago());
            }
        }
        if (mensaje != null) {
            lblMensaje.setText(mensaje);
        } else {
            lblMensaje.setText("");
        }
        if (pago instanceof PagoCreditoSK) {
            t_cod_seguridad.setVisible(false);
            lb_cod_seguridad.setVisible(false);
            t_cod_seguridad.setValidacionHabilitada(false);
        } else {
            t_cod_seguridad.setVisible(true);
            lb_cod_seguridad.setVisible(true);
            t_cod_seguridad.setValidacionHabilitada(true);
            
        }
        if (pagoCredito.getTarjetaCredito() != null && pagoCredito.getTarjetaCredito().getNumero() != null
                && !pagoCredito.getTarjetaCredito().getNumero().contains("X")) {
            t_tarjeta_credito.setText(pagoCredito.getTarjetaCredito().getNumero());
        }
        
        if (ventaManual) {
            visualizacionManual();
        } else {
            visualizacionAutomática();
        }
        
    }
    
    private void inicializaValidacion() {
        
        t_numero_autorizacion.addValidador(new ValidadorObligatoriedad(), this);
        t_numero_autorizacion.addValidador(new ValidadorBigInteger(), this);
        t_numero_autorizacion.addValidador(new ValidadorNumeroSoloCeros(), this);
        t_numero_autorizacion.setValidacionHabilitada(true);
        
        t_tarjeta_credito.addValidador(new ValidadorObligatoriedad(), this);
        t_tarjeta_credito.addValidador(new ValidadorTexto(14, 16), this);
        t_tarjeta_credito.addValidador(new ValidadorBigInteger(), this);
        t_tarjeta_credito.addValidador(new ValidadorNumeroSoloCeros(), this);
        t_tarjeta_credito.setValidacionHabilitada(true);
        
        t_fecha_caducidad.addValidador(new ValidadorObligatoriedad(), this);
        t_fecha_caducidad.addValidador(new ValidadorTexto(4), this);
        t_fecha_caducidad.addValidador(new ValidadorFechaAnioMesValida(true), this);
        t_fecha_caducidad.setValidacionHabilitada(true);
        
        t_numero_lote.addValidador(new ValidadorObligatoriedad(), this);
        t_numero_lote.addValidador(new ValidadorBigInteger(), this);
        t_numero_lote.addValidador(new ValidadorTexto(6), this);
        t_numero_lote.addValidador(new ValidadorNumeroSoloCeros(), this);
        t_numero_lote.setValidacionHabilitada(true);
        
        if (!(pagoCredito instanceof PagoCreditoSK)) {
            t_cod_seguridad.addValidador(new ValidadorObligatoriedad(), this);
            t_cod_seguridad.addValidador(new ValidadorTexto(3, 4), this);
            t_cod_seguridad.addValidador(new ValidadorEntero(), this);
            t_cod_seguridad.setValidacionHabilitada(true);
        }
        
        t_num_orden_emi.addValidador(new ValidadorObligatoriedad(), this);
        t_num_orden_emi.addValidador(new ValidadorBigInteger(), this);
        t_num_orden_emi.addValidador(new ValidadorTexto(3, 3), this);
        t_num_orden_emi.addValidador(new ValidadorNumeroSoloCeros(), this);
        t_num_orden_emi.setValidacionHabilitada(true);
        
        t_num_orden_ven.addValidador(new ValidadorObligatoriedad(), this);
        t_num_orden_ven.addValidador(new ValidadorBigInteger(), this);
        t_num_orden_ven.addValidador(new ValidadorTexto(3, 3), this);
        t_num_orden_ven.addValidador(new ValidadorNumeroSoloCeros(), this);
        t_num_orden_ven.setValidacionHabilitada(true);
        
        t_numero_orden.addValidador(new ValidadorObligatoriedad(), this);
        t_numero_orden.addValidador(new ValidadorBigInteger(), this);
        t_numero_orden.addValidador(new ValidadorTexto(9, 9), this);
        t_numero_orden.addValidador(new ValidadorNumeroSoloCeros(), this);
        t_numero_orden.setValidacionHabilitada(true);
        
    }
    
    private void visualizacionManual() {
        
        rad_data_link.setSelected(true);
        rad_pos_movil.setVisible(true);
        rad_data_link.setVisible(true);
        rad_manual.setVisible(true);
        grupoRadio.add(rad_data_link);
        grupoRadio.add(rad_pos_movil);
        grupoRadio.add(rad_manual);
        t_numero_lote.setVisible(true);
        lb_lote.setVisible(true);
        
        visibleCampos();
        
    }
    
    private void visualizacionAutomática() {
        
        t_numero_autorizacion.setVisible(true);
        lb_num_autoriizacion.setVisible(true);
        t_tarjeta_credito.setVisible(true);
        lb_num_tarjeta.setVisible(true);
        t_cod_seguridad.setEnabled(true);
        t_fecha_caducidad.setEnabled(true);
        
        rad_data_link.setSelected(false);
        rad_pos_movil.setSelected(false);
        rad_manual.setSelected(false);
        rad_pos_movil.setVisible(false);
        rad_data_link.setVisible(false);
        rad_manual.setVisible(false);
        t_numero_lote.setVisible(false);
        lb_lote.setVisible(false);
        lb_num_orden.setVisible(false);
        t_numero_orden.setVisible(false);
        t_num_orden_emi.setVisible(false);
        t_num_orden_ven.setVisible(false);
        
    }
    
    private void visibleCampos() {
        
        boolean muestraLote = true;
        boolean muestraTarjeta = true;
        boolean muestraOrden = true;
        String fechaDefecto = "";
        String codigoDefecto = "";
        t_num_orden_emi.setText("");
        t_num_orden_ven.setText("");
        t_numero_orden.setText("");
        
        if (rad_pos_movil.isSelected()) {
            muestraOrden = false;
        } else if (rad_data_link.isSelected()) {
            muestraLote = false;
            muestraTarjeta = false;
            muestraOrden = true;
            fechaDefecto = Constantes.VALOR_DEFECTO_FECHA_TARJETA;
            codigoDefecto = Constantes.VALOR_DEFECTO_CCV;
        } else if (rad_manual.isSelected()) {
            muestraLote = false;
            muestraOrden = false;
        }
        
        lb_lote.setVisible(muestraLote);
        t_numero_lote.setVisible(muestraLote);
        t_tarjeta_credito.setVisible(muestraTarjeta);
        lb_num_tarjeta.setVisible(muestraTarjeta);
        t_cod_seguridad.setEnabled(muestraTarjeta);
        t_cod_seguridad.setEnabled(muestraTarjeta);
        t_fecha_caducidad.setEnabled(muestraTarjeta);
        t_fecha_caducidad.setText(fechaDefecto);
        t_cod_seguridad.setText(codigoDefecto);
        t_numero_orden.setVisible(muestraOrden);
        lb_num_orden.setVisible(muestraOrden);
        t_num_orden_emi.setVisible(muestraOrden);
        t_num_orden_ven.setVisible(muestraOrden);
        lb_num_autoriizacion.setVisible(!muestraOrden);
        t_numero_autorizacion.setVisible(!muestraOrden);
        
    }
    
    @Override
    public void accionAceptar() {
        log.debug("accionAceptar() - Botón Aceptar pulsado");
        try {
            
            if (ventaManual) {
                EnumTipoPagoManual enumTipoPagoManual = null;
                if (rad_pos_movil.isSelected()) {
                    enumTipoPagoManual = EnumTipoPagoManual.POS_MOVIL;
                    pagoCredito.setNumeroLoteManual(t_numero_lote.getText().trim());
                } else if (rad_data_link.isSelected()) {
                    enumTipoPagoManual = EnumTipoPagoManual.DATA_LINK;
                    setNumeroTarjeta(t_num_orden_ven.getText().trim()+t_num_orden_emi.getText().trim()+t_numero_orden.getText().trim());
                    t_numero_autorizacion.setText(t_numero_orden.getText().trim().substring(3));
                    t_tarjeta_credito.setText(getNumeroTarjeta());
                    pagoCredito.setNumeroLoteManual(Constantes.VALOR_DEFECTO_LOTE_MANUAL);
                }
                pagoCredito.setTipoPagoManual(enumTipoPagoManual);
            }
            
            numeroAutorizacion = t_numero_autorizacion.getText().trim();
            log.debug("accionAceptar() - Autorizacion ingresada por pantalla: "+ t_numero_autorizacion.getText().trim());
            
            validarFormulario();
            pagoCredito.setCodigoValidacionManual(numeroAutorizacion);
            pagoCredito.setCvv(getCvv());
            pagoCredito.setFechaCaducidad(getCaducidad());
            
            if (pagoCredito instanceof PagoCreditoSK && pagoCredito.getTarjetaCredito() != null) {
                pagoCredito.getTarjetaCredito().setNumero(getNumeroTarjeta());
            } else {
                TarjetaCredito tarjeta = new TarjetaCredito(
                        getNumeroTarjeta(), getCaducidad(), getCvv()
                );
                tarjeta.setMedioPago(pagoCredito.getTarjetaCredito().getMedioPago());
                pagoCredito.setTarjetaCredito(tarjeta);
            }
            
            String resultado = pagoCredito.validarAutorizacionManual();
            
            if (resultado == null) {
                contenedor.setVisible(false);
            } else {
                pagoCredito.setCodigoValidacionManual(null);
                lb_error.setText(resultado);
            }
            pagoCredito.setUidFacturacion(null);
        } catch (ValidationException ex) {
            log.debug("accionAceptar() - Excepción de validación: " + ex.getMessage());
        }
    }
    
    @Override
    public void limpiarFormulario() {
        log.debug("limpiarFormulario() - limpiando formulario");
        for (IValidableForm e : formularioFacturacion) {
            e.setValidacionHabilitada(false);
        }
        numeroAutorizacion = "";
        t_numero_autorizacion.setText("");
        //jLabel2.setText("");
        lb_error.setText("");
        t_tarjeta_credito.setText("");
        t_fecha_caducidad.setText("");
        t_cod_seguridad.setText("");
        t_numero_lote.setText("");
        t_num_orden_emi.setText("");
        t_num_orden_ven.setText("");
        t_numero_orden.setText("");
        
        iniciaFoco();
        for (IValidableForm e : formularioFacturacion) {
            e.setValidacionHabilitada(true);
        }
    }
    
    private void creaFormularioCliente() {
        formularioFacturacion = new LinkedList<IValidableForm>();
        formularioFacturacion.add(t_numero_autorizacion);
        formularioFacturacion.add(t_tarjeta_credito);
        formularioFacturacion.add(t_fecha_caducidad);
        formularioFacturacion.add(t_cod_seguridad);
    }
    
    public String getNumeroAutorizacion() {
        return numeroAutorizacion;
    }
    
    public void setNumeroAutorizacion(String numeroAutorizacion) {
        this.numeroAutorizacion = numeroAutorizacion;
    }
    
    public void iniciaFoco() {
        if(ventaManual){
            rad_data_link.requestFocus();
        }else{
            t_numero_autorizacion.requestFocus();
        }
    }
    
    private void addFunctionsKeys() {
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {
            
            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
    }
    
    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }
    
    @Override
    public void clearError() {
        lb_error.setText("");
        
    }
    
    @Override
    public void accionLeerTarjetaVD() {
    }
    
    private void validarFormulario() throws ValidationException {
        for (IValidableForm e : formularioFacturacion) {
            try {
                e.validar();
                validarTarjeta();
            } catch (ValidationFormException ex) {
                log.debug("validarFormulario() - Excepción de validación de formulario: " + ex.getMessage());
                addError(ex);
                throw new ValidationException(ex.getMessage());
            }
        }
        //si pasa las validaciones seteamos los valores 
        setNumeroTarjeta(t_tarjeta_credito.getText().trim());
        setCaducidad(t_fecha_caducidad.getText().trim());
        setCvv(t_cod_seguridad.getText().trim());
    }
    
    private void validarTarjeta() throws ValidationException {
        if (pagoCredito != null) {
            if (pagoCredito.getTarjetaCredito().getMedioPago().isTarjetaCredito()) {
                if (!(ventaManual && rad_data_link.isSelected())) {
                    boolean binTarjeta = false;
                    int cont = 6;
                    do {
                        binTarjeta = pagoCredito.getTarjetaCredito().getMedioPago().getBines().contains(t_tarjeta_credito.getText().substring(0, cont));
                        cont--;
                        if (cont == 0) {
                            break;
                        }
                    } while (!binTarjeta);
                    if (!binTarjeta) {
                        lb_error.setText("El numero tarjeta no pertenece al medio de pago seleccionado ");
                        t_tarjeta_credito.requestFocus();
                        throw new ValidationException("tarjeta invalida");
                    } else {
                        lb_error.setText("");
                    }
                }
            }
        }
    }
    
    public String getCaducidad() {
        return caducidad;
    }
    
    public void setCaducidad(String caducidad) {
        this.caducidad = caducidad;
    }
    
    public String getCvv() {
        return cvv;
    }
    
    public void setCvv(String cvv) {
        this.cvv = cvv;
    }
    
    public String getNumeroTarjeta() {
        return numeroTarjeta;
    }
    
    public void setNumeroTarjeta(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }
}
