/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JBancos.java
 *
 * Created on 04-sep-2012, 11:53:35
 */
package com.comerzzia.jpos.gui.bancos;

import com.comerzzia.jpos.gui.bancos.modelos.BancosTableCellRenderer;
import com.comerzzia.jpos.gui.bancos.modelos.BancosTableModel;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.servicios.pagos.credito.PagoCredito;
import com.comerzzia.util.swing.acciones.Acciones;
import java.awt.KeyboardFocusManager;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MGRI
 */
public class JBancos extends JVentanaDialogo {

    /** Creates new form JBancos */
    public JBancos() {
        initComponents();
        Border empty = new EmptyBorder(0, 0, 0, 0);
        js_banco.setViewportBorder(empty);
        tb_bancos.setBorder(empty);
        js_banco.getViewport().setOpaque(false);
        tb_bancos.setDefaultRenderer(Object.class, new BancosTableCellRenderer());
        
        Set<KeyStroke> strokes = new HashSet<KeyStroke>(Arrays.asList(KeyStroke.getKeyStroke("pressed TAB")));
        tb_bancos.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, strokes);
        strokes = new HashSet<KeyStroke>(Arrays.asList(KeyStroke.getKeyStroke("shift pressed TAB")));
        tb_bancos.setFocusTraversalKeys(KeyboardFocusManager.BACKWARD_TRAVERSAL_KEYS, strokes);
    
        addFunctionsKeys();
        registraEventoEnterBoton();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        js_banco = new javax.swing.JScrollPane();
        tb_bancos = new javax.swing.JTable();
        b_aceptar = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+4));
        jLabel1.setText("Información Bancaria");

        js_banco.setBackground(new java.awt.Color(255, 255, 255));
        js_banco.setOpaque(true);

        tb_bancos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_bancos.setOpaque(false);
        js_banco.setViewportView(tb_bancos);

        b_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_aceptar.setMnemonic('a');
        b_aceptar.setText("Aceptar");
        b_aceptar.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(js_banco, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(js_banco, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_aceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_aceptarActionPerformed
         accionAceptar();
}//GEN-LAST:event_b_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane js_banco;
    private javax.swing.JTable tb_bancos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        contenedor.setVisible(false);
    }

    @Override
    public void limpiarFormulario() {
        
    }
    
    public void iniciaVista(PagoCredito pago){    
            tb_bancos.setModel(new BancosTableModel(pago.getMedioPagoActivo().getBancos(), pago.getCodEstablecimiento()));
            setTamanosTabla();
            b_aceptar.requestFocus();
            
    }

    private void setTamanosTabla() {
        tb_bancos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);        
        tb_bancos.getColumnModel().getColumn(0).setPreferredWidth(304);
        tb_bancos.getColumnModel().getColumn(1).setPreferredWidth(100);
        tb_bancos.getColumnModel().getColumn(2).setPreferredWidth(100);
        tb_bancos.getColumnModel().getColumn(3).setPreferredWidth(172);
    }

    private void addFunctionsKeys() {
        
        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionAceptar();
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
        // Acción de acceso a Tabla
        Acciones.crearAccionFocoTabla(this, tb_bancos);
    }
    
        
    @Override
    public void accionLeerTarjetaVD() {
    }

}
