/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JValor.java
 *
 * Created on 30-ago-2011, 12:20:37
 */
package com.comerzzia.jpos.gui.components;

import com.comerzzia.jpos.gui.IVentanaDialogo;

/**
 *
 * @author MGRI
 */
public class JValor extends JVentanaDialogo implements IVentanaDialogo {

    /** Creates new form JValor */
    public JValor() {
        initComponents();
    }
    
    public String getValor(){
        return this.t_valor.getText();
    }
    
    public void setTexto(String texto){
        this.lb_key.setText(texto);
        this.t_valor.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t_valor = new javax.swing.JTextField();
        lb_key = new javax.swing.JLabel();

        lb_key.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_key.setText("Importe :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lb_key, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_key))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_key;
    private javax.swing.JTextField t_valor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        cerrarVentana();
    }

    @Override
    public void limpiarFormulario() {
        
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
}
