/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JContadores.java
 *
 * Created on 25-ene-2012, 9:27:33
 */
package com.comerzzia.jpos.gui.respaldo;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorEntero;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.core.contadores.ContadorException;
import com.comerzzia.jpos.servicios.core.contadores.caja.ServicioContadoresCaja;
import es.mpsistemas.util.log.Logger;

/**
 *
 * @author MGRI
 */
public class JContadores extends JVentanaDialogo implements IViewerValidationFormError{
    
    private static final Logger log = Logger.getMLogger(JContadores.class);
    
    /** Creates new form JContadores */
    public JContadores() {
        initComponents();
        
        t_contador_ticket.addValidador(new ValidadorEntero(new Integer(0), Integer.MAX_VALUE), this);
        t_contador_nota_credito.addValidador(new ValidadorEntero(new Integer(0), Integer.MAX_VALUE), this);
    }
    
    public void iniciaVista(){
        try {
            t_contador_ticket.setText(ServicioContadoresCaja.obtenerContadorFactura().toString());
            t_contador_nota_credito.setText(ServicioContadoresCaja.obtenerContadorNotaCredito().toString());
            
        }
        catch (ContadorException ex) {
            lb_error.setText("Error leyendo los contadores de la aplicación");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        t_contador_ticket = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_contador_nota_credito = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_error = new javax.swing.JLabel();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getSize()+6f));
        jLabel1.setText("Contadores:");

        jLabel2.setText("NOTA DE CRÉDITO:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setText("FACTURAS:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lb_error.setFont(new java.awt.Font("Comic Sans MS", 1, 10));
        lb_error.setForeground(new java.awt.Color(255, 51, 0));

        b_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/aceptar.png"))); // NOI18N
        b_ok.setMnemonic('a');
        b_ok.setText("Aceptar");
        b_ok.setFont(new java.awt.Font("Tahoma", 0, 18));
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        jLabel4.setFont(jLabel4.getFont());
        jLabel4.setText("<html>Compruebe que el valor coincide con el anterior <br> número que el indicado en el recibo preimpreso</tml>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_contador_nota_credito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_contador_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_contador_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_contador_nota_credito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        
        accionAceptar();
    }//GEN-LAST:event_b_okActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_contador_nota_credito;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_contador_ticket;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
        

        
        try {
            log.info("Acción Aceptar");
            // Actualizamos los contadores
            t_contador_ticket.validar();
            t_contador_nota_credito.validar();
            
            Long contFactura = Long.valueOf(t_contador_ticket.getText());
            Long contNotaCredito = Long.valueOf(t_contador_nota_credito.getText());
            ServicioContadoresCaja.actualizarContadorFactura(contFactura);
            ServicioContadoresCaja.actualizarContadorNotaCredito(contNotaCredito);
            
            cerrarVentanaDialogo();
        }
        catch (ValidationFormException ex) {
            lb_error.setText(ex.getMessage());
        }
        catch (ContadorException ex) {
            //log.error("Error estableciendo contadores : (Ticket)"+contadores.getContadorTicket()+" (NC)"+contadoresFrm.getContadorNotaCredito());
            log.error("Error estableciendo contadores ");
            lb_error.setText("Error estableciendo contadores");
        }
        catch (Exception ex){
            log.error("Error estableciendo contadores ",ex);
            lb_error.setText("Error estableciendo contadores");
        }
    }

    @Override
    public void cerrarVentana() {
        // Sobreescribimos para que no se pueda cerrar la ventana sin pulsar aceptar
    }
    
    public void cerrarVentanaDialogo() {
        super.cerrarVentana();
    }
    
    @Override
    public void limpiarFormulario() {
        
    }

    @Override
    public void addError(ValidationFormException e) {
        this.lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        this.lb_error.setText("");
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
}
