/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JErrorArranque.java
 *
 * Created on 25-ene-2012, 14:23:22
 */
package com.comerzzia.jpos.gui.respaldo;

import com.comerzzia.util.shell.ComandoS;
import com.comerzzia.util.shell.ComandoSException;
import es.mpsistemas.util.log.Logger;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author MGRI
 */
public class JErrorArranque extends javax.swing.JPanel {

    private static final Logger log = Logger.getMLogger(JErrorArranque.class);
    private static boolean modoRespaldo = false;
    /** Creates new form JErrorArranque */
    public JErrorArranque() {
        initComponents();
        
         URL myurl;
        
        myurl= this.getClass().getResource("/com/comerzzia/jpos/imagenes/iconos/iconoTransparente.gif");
        ImageIcon icon=new ImageIcon(myurl);
        
        dialog_confirm.setIconImage(icon.getImage());
        
        if (!modoRespaldo){
            b_respaldo.setEnabled(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_confirm = new javax.swing.JDialog();
        p_confirmacion = new com.comerzzia.jpos.gui.JConfirmacion();
        jLabel1 = new javax.swing.JLabel();
        b_respaldo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        l_error = new javax.swing.JLabel();

        dialog_confirm.setMinimumSize(new java.awt.Dimension(560, 180));
        dialog_confirm.setModal(true);
        dialog_confirm.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                dialog_confirmWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        p_confirmacion.setMaximumSize(new java.awt.Dimension(530, 180));
        p_confirmacion.setMinimumSize(new java.awt.Dimension(530, 180));
        p_confirmacion.setPreferredSize(new java.awt.Dimension(530, 180));

        javax.swing.GroupLayout dialog_confirmLayout = new javax.swing.GroupLayout(dialog_confirm.getContentPane());
        dialog_confirm.getContentPane().setLayout(dialog_confirmLayout);
        dialog_confirmLayout.setHorizontalGroup(
            dialog_confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_confirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        dialog_confirmLayout.setVerticalGroup(
            dialog_confirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_confirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        jLabel1.setText("Error en el arranqe de Comerzzia JPOS");

        b_respaldo.setText("Lanzar Aplicación en Modo Respaldo");
        b_respaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_respaldoActionPerformed(evt);
            }
        });

        jLabel2.setText("Consulte el log para mas información.");

        l_error.setForeground(new java.awt.Color(204, 0, 0));
        l_error.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_respaldo)
                    .addComponent(l_error, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(b_respaldo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_error, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_respaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_respaldoActionPerformed
    try {
        
        if (crearVentanaConfirmacion("La acción arrancará la aplicación en modo de Respaldo. Esta operación debe estar autorizada por el administrador.¿Desea seguir ejecutando la acción?", "Sí", "No")){
            if (crearVentanaConfirmacion("Responda afirmativamente si desea arrancar el modo Respaldo. Confirme con el administrador que se desea realizar esta operación", "Sí", "No")){
                ComandoS.arrancaReserva();                   
                this.tryToClose();
            }
        }
    }
    catch (ComandoSException ex) {
        log.error("Error Ejecutando Comando de apertura de reserva", ex);
        //ventana_padre.crearError("Error Ejecutando Comando de apertura de reserva");
    }
    }//GEN-LAST:event_b_respaldoActionPerformed

    private void dialog_confirmWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialog_confirmWindowGainedFocus
        p_confirmacion.iniciaVista();
}//GEN-LAST:event_dialog_confirmWindowGainedFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_respaldo;
    private javax.swing.JDialog dialog_confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l_error;
    private com.comerzzia.jpos.gui.JConfirmacion p_confirmacion;
    // End of variables declaration//GEN-END:variables

    void iniciaVista() {
        
    }

    void tryToClose() {
        SwingUtilities.getWindowAncestor(this).dispose();
        System.exit(0);
    }

    void activaBotonRespaldo() {
        modoRespaldo = true;
        b_respaldo.setEnabled(true);
        
    }
    
    void desactivaBotonRespaldo() {
        modoRespaldo = false;
        b_respaldo.setEnabled(false);
        
    }
    
    
    
    
    public boolean crearVentanaConfirmacion(String texto,String textoConfirmacion,String textoCancelacion) {
        log.info("Crear Ventana de Confirmación");
        boolean res = false;
        p_confirmacion.setContenedor(dialog_confirm);
        p_confirmacion.setDesError(texto);
        p_confirmacion.cambiaTextoBotones(textoConfirmacion,textoCancelacion);
        dialog_confirm.setModal(true);
        dialog_confirm.setLocationRelativeTo(null);
        p_confirmacion.requestFocus();
        dialog_confirm.setVisible(true);
        //dialog_error.setSize(450, 100);
        
                
        res = p_confirmacion.isAceptado();
        return res;
    }
    
    public void addError(String error){
        l_error.setText(error);
    }

    void ocultaBotonRespaldo() {
        b_respaldo.setEnabled(false);
        b_respaldo.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
    }
}
