/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JNuevaGuiaRemision.java
 *
 * Created on 12-dic-2012, 11:51:42
 */
package com.comerzzia.jpos.gui.guiasremision;

import com.comerzzia.jpos.entity.db.Almacen;
import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.gui.guiasremision.modelos.ArticulosGuiaRemisionCellRenderer;
import com.comerzzia.jpos.gui.guiasremision.modelos.ArticulosGuiaRemisionTableModel;
import com.comerzzia.jpos.gui.validation.IFormTipoIdentificacion;
import com.comerzzia.jpos.gui.validation.IValidableForm;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorCedulaRuc;
import com.comerzzia.jpos.gui.validation.ValidadorCelularEcuador;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidadorTexto;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.guiasremision.GuiaRemisionException;
import com.comerzzia.jpos.servicios.guiasremision.GuiasRemisionManager;
import com.comerzzia.jpos.servicios.login.Sesion;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import es.mpsistemas.util.log.Logger;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author MGRI
 */
public class JNuevaGuiaRemision2 extends JPanelImagenFondo implements IVista, IViewerValidationFormError, IFormTipoIdentificacion {

    private static Logger log = Logger.getMLogger(JNuevaGuiaRemision2.class);
    public static int TIPO_FACTURA = 1 ;    
    private static GuiasRemisionManager manejador;
    private static final long serialVersionUID = 1L;
    private List<IValidableForm> formulario;

    /** Creates new form JNuevaGuiaRemision */
    public JNuevaGuiaRemision2() {
              
        
        initComponents();        
        
        // Imagen de fondo
        String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
        try {
            URL myurl2 = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_guia_remision.png");
            this.setImagenFondo((Image) ImageIO.read(new File(myurl2.getPath())));
        }
        catch (IOException ex) {
            log.error("No se pudo cargar la imagen de fondo de guía de remisión");
        }
        catch (Exception e) {
            log.error("No se pudo cargar la imagen de fondo de guía de remisión: " + e.getMessage(), e);
        }
        
        // Tabla transparente
        Border empty = new EmptyBorder(0, 0, 0, 0);
        js_tb_articulos.setViewportBorder(empty);
        tb_articulos.setBorder(empty);
        js_tb_articulos.getViewport().setOpaque(false);
        
        registraEventoEnterBoton();
        registrarEventoBloqueoAplicacion();
        registrarEventosBotones();   
        crearAccionFocoTabla(this, tb_articulos, KeyEvent.VK_T, InputEvent.CTRL_MASK);

        manejador = GuiasRemisionManager.getInstance();
        
        // registrar acciones de teclado
             

        //registrar validación:
        inicializarValidacion();

        // Renderer de la tabla (en iniciaVista)

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        bg_tipo_documento = new javax.swing.ButtonGroup();
        tiendasKeySelectionManager1 = new com.comerzzia.jpos.gui.modelos.TiendasKeySelectionManager();
        tiendasListRenderer1 = new com.comerzzia.jpos.gui.modelos.TiendasListRenderer();
        sesion1 = new com.comerzzia.jpos.servicios.login.Sesion();
        sesion1.listaTiendas = new ArrayList();
        sesion1.listaTiendas.add(Sesion.getTienda().getAlmacen());
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l_codigo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        l_motivos_traslado = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t_nombreDestinatario = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_numeroCedulaDestinatario = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_ciudadDestinatario = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_DireccionLlegadaDestinatario = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_bienesTransportados = new com.comerzzia.jpos.gui.components.form.JTextAreaForm();
        l_tienda_origen = new javax.swing.JComboBox();
        menu_navegacion = new javax.swing.JPanel();
        b_volver = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_menu_principal = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_ok = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        t_nombreTransportista = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_cedulaTransportista = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_ciudadTransportista = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jPanel5 = new javax.swing.JPanel();
        js_tb_articulos = new javax.swing.JScrollPane();
        tb_articulos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código:");

        l_codigo.setText("[CÓDIGO]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_codigo))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setOpaque(false);

        jLabel5.setDisplayedMnemonic('m');
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setLabelFor(l_motivos_traslado);
        jLabel5.setText("Motivo de Traslado:");

        l_motivos_traslado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ventas", "Compras", "Consignación", "Devolución", "Traslado entre establecimientos de una misma empresa", "Traslado por emisor itinerante de comprobantes de venta", "Importación", "Otros no incluidos en los puntos anteriores" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_motivos_traslado, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(498, 498, 498))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(l_motivos_traslado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setOpaque(false);

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel3.setText("Destinatario:");

        jLabel4.setDisplayedMnemonic('n');
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setLabelFor(t_nombreDestinatario);
        jLabel4.setText("Nombre:");

        jLabel6.setDisplayedMnemonic('e');
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setLabelFor(t_numeroCedulaDestinatario);
        jLabel6.setText("Número de Cédula:");

        jLabel7.setDisplayedMnemonic('p');
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setLabelFor(l_tienda_origen);
        jLabel7.setText("Punto de partida:");

        jLabel8.setDisplayedMnemonic('c');
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setLabelFor(t_ciudadDestinatario);
        jLabel8.setText("Ciudad:");

        jLabel9.setDisplayedMnemonic('d');
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setLabelFor(t_DireccionLlegadaDestinatario);
        jLabel9.setText("Destino (Punto de llegada):");

        jLabel10.setDisplayedMnemonic('b');
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setLabelFor(t_bienesTransportados);
        jLabel10.setText("Observaciones:");

        jScrollPane1.setMaximumSize(new java.awt.Dimension(234, 94));

        t_bienesTransportados.setColumns(20);
        t_bienesTransportados.setRows(5);
        jScrollPane1.setViewportView(t_bienesTransportados);

        l_tienda_origen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        l_tienda_origen.setKeySelectionManager(tiendasKeySelectionManager1);
        l_tienda_origen.setRenderer(tiendasListRenderer1);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${listaTiendas}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, sesion1, eLProperty, l_tienda_origen);
        bindingGroup.addBinding(jComboBoxBinding);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_tienda_origen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_nombreDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(t_numeroCedulaDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t_ciudadDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_DireccionLlegadaDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_nombreDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_numeroCedulaDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(l_tienda_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t_ciudadDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(t_DireccionLlegadaDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_navegacion.setBackground(new java.awt.Color(255, 255, 255));
        menu_navegacion.setOpaque(false);

        b_volver.setText("<html><center>Volver <br/> F2</center></html>");
        b_volver.setActionCommand("Identificar Cliente F3");
        b_volver.setMargin(new java.awt.Insets(0, -3, 0, 0));
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });

        b_m_menu_principal.setText("<html><center>Menú Principal <br/>F12</center></html>");
        b_m_menu_principal.setNextFocusableComponent(l_motivos_traslado);
        b_m_menu_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_menu_principalActionPerformed(evt);
            }
        });

        b_ok.setText("<html><center>Guardar <br/> F8</center></html>");
        b_ok.setActionCommand("Identificar Cliente F3");
        b_ok.setMargin(new java.awt.Insets(0, -3, 0, 0));
        b_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_navegacionLayout = new javax.swing.GroupLayout(menu_navegacion);
        menu_navegacion.setLayout(menu_navegacionLayout);
        menu_navegacionLayout.setHorizontalGroup(
            menu_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_navegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_m_menu_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        menu_navegacionLayout.setVerticalGroup(
            menu_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_navegacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menu_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b_ok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_m_menu_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setOpaque(false);

        jLabel11.setFont(jLabel11.getFont().deriveFont(jLabel11.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel11.setText("Persona Encargada del transporte:");

        jLabel12.setDisplayedMnemonic('o');
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setLabelFor(t_nombreTransportista);
        jLabel12.setText("Nombre:");

        jLabel13.setDisplayedMnemonic('r');
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setLabelFor(t_cedulaTransportista);
        jLabel13.setText("Número de Cédula:");

        jLabel15.setDisplayedMnemonic('i');
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setLabelFor(t_ciudadTransportista);
        jLabel15.setText("Ciudad:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_nombreTransportista, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                .addComponent(t_cedulaTransportista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(t_ciudadTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(t_nombreTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_cedulaTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_ciudadTransportista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jPanel5.setOpaque(false);

        tb_articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_articulos.setOpaque(false);
        tb_articulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_articulos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_articulosKeyPressed(evt);
            }
        });
        js_tb_articulos.setViewportView(tb_articulos);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_tb_articulos, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(js_tb_articulos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void b_m_menu_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_menu_principalActionPerformed
        if (b_m_menu_principal.isEnabled()) {
            log.info("MENÚ PRINCIPAL");
            deshabilitarFormulario();
            JPrincipal.getInstance().mostrarMenu();
        }
}//GEN-LAST:event_b_m_menu_principalActionPerformed

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        deshabilitarFormulario();
        if (JPrincipal.getInstance().crearVentanaConfirmacion("Se perderán los datos de la pantalla actual. ¿Desea proceder?")){
            accionVolver();
        }
        else{
            habilitarFormulario();
        }

    }//GEN-LAST:event_b_volverActionPerformed

    private void tb_articulosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_articulosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                manejador.accionSeleccionaArticulo(tb_articulos.getSelectedRow());
            }
            catch (Exception e) {
                addError(new ValidationFormException(e.getMessage()));
            }
            refrescarTabla();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_TAB && evt.isShiftDown()) {
            tb_articulos.transferFocusBackward();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            tb_articulos.transferFocus();
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F2){
             b_volverActionPerformed(null);
        }
        else if (evt.getKeyCode() == KeyEvent.VK_F8){
                accionGuardar();
        }       
        
}//GEN-LAST:event_tb_articulosKeyPressed

    private void b_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_okActionPerformed
        accionGuardar();
    }//GEN-LAST:event_b_okActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_menu_principal;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_ok;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_volver;
    private javax.swing.ButtonGroup bg_tipo_documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane js_tb_articulos;
    private javax.swing.JLabel l_codigo;
    private javax.swing.JComboBox l_motivos_traslado;
    private javax.swing.JComboBox l_tienda_origen;
    private javax.swing.JPanel menu_navegacion;
    private com.comerzzia.jpos.servicios.login.Sesion sesion1;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_DireccionLlegadaDestinatario;
    private com.comerzzia.jpos.gui.components.form.JTextAreaForm t_bienesTransportados;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_cedulaTransportista;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_ciudadDestinatario;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_ciudadTransportista;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_nombreDestinatario;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_nombreTransportista;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numeroCedulaDestinatario;
    private javax.swing.JTable tb_articulos;
    private com.comerzzia.jpos.gui.modelos.TiendasKeySelectionManager tiendasKeySelectionManager1;
    private com.comerzzia.jpos.gui.modelos.TiendasListRenderer tiendasListRenderer1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public void iniciaVista() {

        cargarDatosFormulario();
        // iniciar foco
        iniciaFoco();
        tb_articulos.setDefaultRenderer(Object.class, new ArticulosGuiaRemisionCellRenderer());
        refrescarTabla();
        inicializarValidacion();
        iniciaFoco();
        habilitarFormulario();
        
    }

    private void inicializarValidacion() {
        formulario = new ArrayList();

        t_ciudadDestinatario.addValidador(new ValidadorObligatoriedad(), this);        
        t_nombreDestinatario.addValidador(new ValidadorObligatoriedad(), this);
        t_numeroCedulaDestinatario.addValidador(new ValidadorObligatoriedad(), this);
        t_DireccionLlegadaDestinatario.addValidador(new ValidadorObligatoriedad(), this);
        t_bienesTransportados.addValidador(new ValidadorObligatoriedad(), this);

        if (!Sesion.getDatosConfiguracion().isModoDesarrollo()){
            t_cedulaTransportista.addValidador(new ValidadorCedulaRuc(this), this);
            t_numeroCedulaDestinatario.addValidador(new ValidadorCedulaRuc(this), this);
        }
        
        //TODO: GUIA REMISION - Añadir Validadores de Longitud cuando sepamos tamaño de campos 
        t_ciudadDestinatario.addValidador(new ValidadorTexto(100), this);        
        t_nombreDestinatario.addValidador(new ValidadorTexto(100), this);
        t_numeroCedulaDestinatario.addValidador(new ValidadorTexto(20), this);
        t_DireccionLlegadaDestinatario.addValidador(new ValidadorTexto(100), this);        
        t_bienesTransportados.addValidador(new ValidadorTexto(400), this);
        t_nombreTransportista.addValidador(new ValidadorTexto(100), this);
        t_cedulaTransportista.addValidador(new ValidadorTexto(20), this);
        t_ciudadTransportista.addValidador(new ValidadorTexto(100), this);
        
        formulario.add(t_ciudadDestinatario);
        formulario.add(t_nombreDestinatario);
        formulario.add(t_numeroCedulaDestinatario);
        formulario.add(t_DireccionLlegadaDestinatario);
        formulario.add(t_bienesTransportados);
        formulario.add(t_nombreTransportista);
        formulario.add(t_cedulaTransportista);
        formulario.add(t_ciudadTransportista);
    }

    @Override
    public void addError(ValidationFormException e) {
        JPrincipal.getInstance().crearError(e.getMessage());
    }

    @Override
    public void clearError() {
    }

    @Override
    public void iniciaFoco() {
        l_motivos_traslado.requestFocus();
    }

    private void refrescarTabla() {
        //TODO: GUIA REMISION - Hay que refrescar la tabla para representar el estado en el que esta la línea //Seleccionada o no
        int posicion =-1;

        if (manejador.getGuiaRemision().isTipoFactura() &&  manejador.getLineas().isEmpty()) {
            b_ok.setEnabled(false);           
        }
        else {
            b_ok.setEnabled(true);
        }

        if (tb_articulos.isFocusOwner()){
            ListSelectionModel selectionModel = tb_articulos.getSelectionModel();
            posicion = selectionModel.getMaxSelectionIndex();
        }
        
        ArticulosGuiaRemisionTableModel modelo = new ArticulosGuiaRemisionTableModel(manejador.getLineas());
        tb_articulos.setModel(modelo);
        if (tb_articulos.isFocusOwner()){
            ListSelectionModel selectionModel = tb_articulos.getSelectionModel();
            selectionModel.setSelectionInterval(posicion, posicion);    
        }     
    }

    private void accionVolver() {
        GuiasRemisionManager.setAccionVolver(true);
        JPrincipal.getInstance().irPantallaGuiaRemision();
    }

    private void cargarDatosFormulario() {
        l_codigo.setText(manejador.getIdentificador());
        l_tienda_origen.setSelectedItem(new Almacen(manejador.getGuiaRemision().getCodalm()));
        
        limpiarFormulario();
        
        if (manejador.getGuiaRemision().getDestNombre()!=null){
            t_nombreDestinatario.setText(manejador.getGuiaRemision().getDestNombre());
        }
        if (manejador.getGuiaRemision().getDestCedula()!=null){
            t_numeroCedulaDestinatario.setText(manejador.getGuiaRemision().getDestCedula()); 
        }        
        if (manejador.getGuiaRemision().getDestDireccion()!=null){
            t_DireccionLlegadaDestinatario.setText(manejador.getGuiaRemision().getDestDireccion()); 
        }
        if (manejador.getGuiaRemision().getCodalm()!=null){
            l_tienda_origen.setSelectedItem(new Almacen(manejador.getGuiaRemision().getCodalm()));             
        }
  
    }

    private void limpiarFormulario() {
        
        t_bienesTransportados.setText("");
        t_cedulaTransportista.setText("");
        t_ciudadDestinatario.setText("");
        t_ciudadTransportista.setText("");
        t_DireccionLlegadaDestinatario.setText("");
        t_nombreDestinatario.setText("");
        t_nombreTransportista.setText("");
        t_numeroCedulaDestinatario.setText("");
        
        l_motivos_traslado.setSelectedIndex(0);        
    }

    private void accionGuardar() {
        try {
            log.debug("Seleccionada Acción Guardar Guía de Remisión");
            // Validar los datos del formulario               
            for (IValidableForm val : formulario) {
                val.validar();
            }
            log.debug("Formulario validado satisfactoriamente");
            // Guardamos los datos
            manejador.getGuiaRemision().setMotivoTraslado((String)l_motivos_traslado.getSelectedItem());
            manejador.getGuiaRemision().setDestNombre(t_nombreDestinatario.getText());
            manejador.getGuiaRemision().setDestCedula(t_numeroCedulaDestinatario.getText());
            manejador.getGuiaRemision().setDestCiudad(t_ciudadDestinatario.getText());
            manejador.getGuiaRemision().setDestDireccion(t_DireccionLlegadaDestinatario.getText());
            manejador.getGuiaRemision().setDestCodalm(((Almacen)l_tienda_origen.getSelectedItem()).getCodalm());
            manejador.getGuiaRemision().setBienesTransportados(t_bienesTransportados.getText());
            manejador.getGuiaRemision().setTransNombre(t_nombreTransportista.getText());
            manejador.getGuiaRemision().setTransCedula(t_cedulaTransportista.getText());
            manejador.getGuiaRemision().setTransDireccion(t_ciudadTransportista.getText());
            
            manejador.accionGuardar();
            JPrincipal.getInstance().crearConfirmacion("Guía de Remisión Guardada");
            JPrincipal.getInstance().showView(JPrincipal.VISTA_INICIO);
        }
        catch (GuiaRemisionException ex) {
            addError(new ValidationFormException(ex.getMessage()));
        }
        catch (ValidationFormException ex) {
            addError(ex);
        }
        catch (Exception ex) {
            log.error(" accionGuardar() - "+ex.getMessage(),ex);
            addError(new ValidationFormException("Error guardando guia de remisión"));
        }
        
    }

    private void registrarEventosBotones() {
        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_volverActionPerformed(null);
            }
        };
        addHotKey(f2, "IdentClientF2", listenerf2);

        KeyStroke f8 = KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0);
        Action listenerf8b = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionGuardar();

            }
        };
        addHotKey(f8, "IdentClientF8b", listenerf8b);


        KeyStroke f12 = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        Action listenerf12 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_m_menu_principalActionPerformed(ae);
            }
        };
        addHotKey(f12, "IdentClientF9", listenerf12);
    }

    private void accionCancelar() {
        JPrincipal.getInstance().showViewMenuVentas();
    }


    
    private void deshabilitarFormulario() {
        for(IValidableForm ivf:formulario){
            ivf.setValidacionHabilitada(false);
        }
    }
    
    private void habilitarFormulario() {
        for(IValidableForm ivf:formulario){
            ivf.setValidacionHabilitada(true);
        }
    }

    @Override
    public String getTipoIdentificacion() {
        return "CED";
    }
}
