/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JNuevaGuiaRemision.java
 *
 * Created on 12-dic-2012, 11:51:42
 */
package com.comerzzia.jpos.gui.guiasremision;

import com.comerzzia.jpos.gui.IVista;
import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JPanelImagenFondo;
import com.comerzzia.jpos.gui.validation.IValidableForm;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorFecha;
import com.comerzzia.jpos.gui.validation.ValidadorObligatoriedad;
import com.comerzzia.jpos.gui.validation.ValidadorTexto;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.guiasremision.GuiasRemisionManager;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import es.mpsistemas.util.fechas.Fecha;
import es.mpsistemas.util.log.Logger;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.AbstractButton;
import javax.swing.Action;
import javax.swing.KeyStroke;

/**
 *
 * @author MGRI
 */
public class JNuevaGuiaRemision extends JPanelImagenFondo implements IVista, IViewerValidationFormError {

    private static Logger log = Logger.getMLogger(JNuevaGuiaRemision.class);
    private static GuiasRemisionManager manejador;
    private List<IValidableForm> formulario;

    /** Creates new form JNuevaGuiaRemision */
    public JNuevaGuiaRemision() {     
        initComponents();
        
        // Imagen de fondo
        String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
        try {
            URL myurl2 = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_guia_remision.png");
            this.setImagenFondo((Image) ImageIO.read(new File(myurl2.getPath())));
        }
        catch (IOException ex) {
            log.error("No se pudo cargar la imagen de fondo de guía de remisión");
        }
        catch (Exception e) {
            log.error("No se pudo cargar la imagen de fondo de guía de remisión: " + e.getMessage(), e);
        }
        
        registraEventoEnterBoton();
        registrarEventoBloqueoAplicacion();
        registrarEventosBotones();
        manejador = GuiasRemisionManager.getInstance();


        // registrar acciones de teclado

        //registrar validación:
        inicializarValidacion();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_tipo_documento = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        l_codigo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        t_fecha_inicioTraslado = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_fecha_fin_traslado = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_codigo_local1 = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_codigo_local2 = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel9 = new javax.swing.JLabel();
        t_numero_orden_salida = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_numero_transferencia = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t_numero_orden_despacho = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t_numero_pedido = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        t_documentoImpreso = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        menu_navegacion = new javax.swing.JPanel();
        b_m_salvar = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_m_menu_principal = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_volver = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código:");

        l_codigo.setText("[CÓDIGO]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_codigo))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setOpaque(false);

        jLabel3.setDisplayedMnemonic('i');
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setLabelFor(t_fecha_inicioTraslado);
        jLabel3.setText("Fecha Inicio Traslado:");

        jLabel4.setDisplayedMnemonic('f');
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setLabelFor(t_fecha_fin_traslado);
        jLabel4.setText("Fecha Fin Traslado:");

        jLabel5.setDisplayedMnemonic('t');
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setLabelFor(jRadioButton1);
        jLabel5.setText("Tipo de Documento:");

        bg_tipo_documento.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setLabel("(1) Factura / Pendiente de Entrega");
        jRadioButton1.setName("1"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        t_fecha_inicioTraslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_fecha_inicioTrasladoActionPerformed(evt);
            }
        });

        bg_tipo_documento.add(jRadioButton3);
        jRadioButton3.setText("(10) Pedido de Transferencia ");
        jRadioButton3.setName("10"); // NOI18N

        bg_tipo_documento.add(jRadioButton4);
        jRadioButton4.setText("(13) Guía de despacho Técnico ");
        jRadioButton4.setName("13"); // NOI18N

        bg_tipo_documento.add(jRadioButton7);
        jRadioButton7.setText("(61) Orden de Salida ");
        jRadioButton7.setName("61"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_fecha_fin_traslado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_fecha_inicioTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                .addGap(320, 320, 320))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(t_fecha_inicioTraslado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_fecha_fin_traslado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addGap(21, 21, 21))
        );

        jPanel3.setOpaque(false);

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getStyle() | java.awt.Font.BOLD));
        jLabel6.setText("Datos del Comprobante de Venta:");

        jLabel7.setDisplayedMnemonic('n');
        jLabel7.setLabelFor(t_documentoImpreso);
        jLabel7.setText("Número de documento impreso:");

        jLabel8.setDisplayedMnemonic('l');
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setLabelFor(t_codigo_local1);
        jLabel8.setText("<html>Código <u>L</u>ocal:<br>Origen</html>");

        jLabel9.setDisplayedMnemonic('o');
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setLabelFor(t_codigo_local2);
        jLabel9.setText("<html>Códig<u>o</u> Local:<br>Destino</html>");

        jLabel10.setDisplayedMnemonic('r');
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setLabelFor(t_numero_transferencia);
        jLabel10.setText("<html>Número de t<u>r</u>ansferencia:</html>");

        jLabel11.setDisplayedMnemonic('s');
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setLabelFor(t_numero_orden_salida);
        jLabel11.setText("<html>Número de orden de <u>s</u>alida:</html>");

        jLabel12.setDisplayedMnemonic('p');
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setLabelFor(t_numero_pedido);
        jLabel12.setText("<html>Número de <u>p</u>edido:</html>");

        jLabel13.setDisplayedMnemonic('d');
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setLabelFor(t_numero_orden_despacho);
        jLabel13.setText("<html>Número de orden de <u>d</u>espacho:</html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_documentoImpreso, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_codigo_local2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_codigo_local1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_numero_orden_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_numero_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_numero_orden_despacho, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_numero_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(t_documentoImpreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_codigo_local1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_numero_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_numero_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_codigo_local2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_numero_orden_salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_numero_orden_despacho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        menu_navegacion.setBackground(new java.awt.Color(255, 255, 255));
        menu_navegacion.setOpaque(false);

        b_m_salvar.setText("<html><center>Continuar <br/> F8</center></html>");
        b_m_salvar.setActionCommand("Identificar Cliente F3");
        b_m_salvar.setMargin(new java.awt.Insets(0, -3, 0, 0));
        b_m_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_salvarActionPerformed(evt);
            }
        });

        b_m_menu_principal.setText("<html><center>Menú Principal <br/>F12</center></html>");
        b_m_menu_principal.setNextFocusableComponent(t_fecha_inicioTraslado);
        b_m_menu_principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_m_menu_principalActionPerformed(evt);
            }
        });

        b_volver.setText("<html><center>Cancelar <br/> F2</center></html>");
        b_volver.setActionCommand("Identificar Cliente F3");
        b_volver.setMargin(new java.awt.Insets(0, -3, 0, 0));
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_navegacionLayout = new javax.swing.GroupLayout(menu_navegacion);
        menu_navegacion.setLayout(menu_navegacionLayout);
        menu_navegacionLayout.setHorizontalGroup(
            menu_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_navegacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_m_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_m_menu_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        menu_navegacionLayout.setVerticalGroup(
            menu_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_navegacionLayout.createSequentialGroup()
                .addGroup(menu_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_navegacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b_m_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(b_m_menu_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu_navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(menu_navegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void t_fecha_inicioTrasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_fecha_inicioTrasladoActionPerformed
    }//GEN-LAST:event_t_fecha_inicioTrasladoActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void b_m_menu_principalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_menu_principalActionPerformed
        if (b_m_menu_principal.isEnabled()) {
            log.info("MENÚ PRINCIPAL");
            deshabilitarFormulario();
            JPrincipal.getInstance().mostrarMenu();
        }
}//GEN-LAST:event_b_m_menu_principalActionPerformed

    private void b_m_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_m_salvarActionPerformed
        accionPasoSiguiente();

    }//GEN-LAST:event_b_m_salvarActionPerformed

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        accionCancelar();
    }//GEN-LAST:event_b_volverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_menu_principal;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_m_salvar;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_volver;
    private javax.swing.ButtonGroup bg_tipo_documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JLabel l_codigo;
    private javax.swing.JPanel menu_navegacion;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_codigo_local1;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_codigo_local2;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_documentoImpreso;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_fecha_fin_traslado;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_fecha_inicioTraslado;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_orden_despacho;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_orden_salida;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_pedido;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_transferencia;
    // End of variables declaration//GEN-END:variables

    @Override
    public void iniciaVista() {
        try {
            // iniciar foco
            t_fecha_inicioTraslado.requestFocus();
            
            cargarDatosFormulario();
            iniciaFoco();
            habilitarFormulario();
            iniciaFoco();
        }
        catch (ValidationFormException ex) {
            accionCancelar();
            JPrincipal.getInstance().crearError(ex.getMessage());
        }

    }

    private void accionPasoSiguiente() {
        try {
            // Validar los datos del formulario               
            for (IValidableForm val : formulario) {
                val.validar();
            }
            
            int indiceSeleccionado = 0;
            
            if (jRadioButton3.isSelected()){
                indiceSeleccionado = 10;
            }
            else if (jRadioButton4.isSelected()){
                indiceSeleccionado = 13;
            }
            else if (jRadioButton7.isSelected()){
                indiceSeleccionado = 61;
            }
            else if (jRadioButton1.isSelected()){
                indiceSeleccionado = 1;
            }

            //Una de las formas en que será posible pasar a la siguiente pantalla es habiéndo ingresado una factura
            manejador.limpiarDatosGR();
            
            if (jRadioButton1.isSelected()) {
                if (t_documentoImpreso.getText().isEmpty()) {
                    addError(new ValidationFormException("No ha introducido un número de documento"));
                    t_documentoImpreso.requestFocus();
                }
                else {  
                    manejador.setParametrosGuiaRemision(t_fecha_inicioTraslado.getText(),
                            t_fecha_fin_traslado.getText(),
                            t_documentoImpreso.getText(),
                            t_codigo_local1.getText(),
                            t_codigo_local2.getText(),
                            t_numero_orden_despacho.getText(),
                            t_numero_orden_salida.getText(),
                            t_numero_pedido.getText(),
                            t_numero_transferencia.getText(),
                            indiceSeleccionado
                            );
                            
                    // Consultamos si hay un ticket con lineas de envío a domicilio
                    // Si no hay ticket o no hay lineas devolveremos sendas excepciones
                    //TODO ¿Comprobamos que el ticket este en BD?    
                    manejador.consultaTicket(); // este método ya cambia la pantalla si tiene exito
                }
            }
            else{
                manejador.reseteaListaLineas();
                //TODO [GUIAS REMISION] : Controlar validaciones de campos requeridos para otros tipos de documentos
                // Actualmente no se podran crear estas guias porque debe haber por lo menos una línea seleccionada.
                
               
                manejador.setParametrosGuiaRemision(t_fecha_inicioTraslado.getText(),
                            t_fecha_fin_traslado.getText(),
                            t_documentoImpreso.getText(),
                            t_codigo_local1.getText(),
                            t_codigo_local2.getText(),
                            t_numero_orden_despacho.getText(),
                            t_numero_orden_salida.getText(),
                            t_numero_pedido.getText(),
                            t_numero_transferencia.getText(),
                            indiceSeleccionado);
                JPrincipal.getInstance().irPantallaGuiaRemision2();
            }

        }
        catch (ValidationFormException ex) {
            addError(ex);
        }
        // Se consultará el ticket para saber que artículos serán los que vamos a trasladar
    }

    private void inicializarValidacion() {
        formulario = new ArrayList();

        Fecha fechaMin = new Fecha();
        fechaMin.sumaDias(-1);
        
        t_fecha_inicioTraslado.addValidador(new ValidadorFecha(fechaMin.getDate(), null), this);
        t_fecha_fin_traslado.addValidador(new ValidadorFecha(fechaMin.getDate(), null), this);
        t_fecha_inicioTraslado.addValidador(new ValidadorObligatoriedad(), this);
        t_fecha_fin_traslado.addValidador(new ValidadorObligatoriedad(), this);
              
        //Validadores de longitud
        t_documentoImpreso.addValidador(new ValidadorTexto(20), this);
        t_numero_orden_despacho.addValidador(new ValidadorTexto(10), this);
        t_numero_orden_salida.addValidador(new ValidadorTexto(10), this);
        t_numero_pedido.addValidador(new ValidadorTexto(10), this);
        t_numero_transferencia.addValidador(new ValidadorTexto(10), this);
        t_codigo_local2.addValidador(new ValidadorTexto(3), this);
        t_codigo_local1.addValidador(new ValidadorTexto(3), this);
          
        formulario.add(t_fecha_inicioTraslado);
        formulario.add(t_fecha_fin_traslado);
        formulario.add(t_documentoImpreso);
        formulario.add(t_numero_orden_despacho);
        formulario.add(t_numero_orden_salida);
        formulario.add(t_numero_pedido);
        formulario.add(t_numero_transferencia);
        formulario.add(t_codigo_local2);
        formulario.add(t_codigo_local1);
    }

    @Override
    public void addError(ValidationFormException e) {
        JPrincipal.getInstance().crearError(e.getMessage());
    }

    @Override
    public void clearError() {
    }

    @Override
    public void iniciaFoco() {
        t_fecha_inicioTraslado.requestFocus();
    }

    private void cargarDatosFormulario() throws ValidationFormException {
        if (!GuiasRemisionManager.isAccionVolver()) {
            // limpiamos el formulario
            limpiarFormulario();
        }
        else {
            // recuperamos el formulario
            recuperarFormulario();

        }
    }

    private void limpiarFormulario() throws ValidationFormException {
        manejador.establecerCodigoGR();
        
        t_fecha_inicioTraslado.setText("");
        t_fecha_fin_traslado.setText("");
        t_numero_orden_despacho.setText("");
        t_numero_orden_salida.setText("");
        t_numero_pedido.setText("");
        t_numero_transferencia.setText("");
        t_codigo_local2.setText("");
        t_codigo_local1.setText("");
        t_documentoImpreso.setText("");
        jRadioButton1.setSelected(true);
        l_codigo.setText(manejador.getIdentificador());
    }

    private void recuperarFormulario() {
        t_fecha_inicioTraslado.setText(manejador.getFechaInicioTrasladoStr());
        t_fecha_fin_traslado.setText(manejador.getFechaFinTrasladoStr());
 /*       t_numero_orden_despacho.setText(manejador.getNumeroOrdenDespacho());
        t_numero_orden_salida.setText(manejador.getNumeroOrdenSalida());
        t_numero_pedido.setText(manejador.getNumeroPedido());
        t_numero_transferencia.setText(manejador.getNumeroTransferencia());*/
        t_codigo_local1.setText(manejador.getCodigoLocal1());
        t_codigo_local2.setText(manejador.getCodigoLocal2());
        t_documentoImpreso.setText(manejador.getNumeroDocumentoImpreso());
        l_codigo.setText(manejador.getIdentificador());
        switch (manejador.getGuiaRemision().getTipoDocumento()) {
            case (1):
                 jRadioButton1.setSelected(true);
                break;            
            case (10):
                 jRadioButton3.setSelected(true);
                break;
            case (13):
                 jRadioButton4.setSelected(true);
                 break; 
            case (61):
                 jRadioButton7.setSelected(true);
                 break;
            default:
                ;
        }
        GuiasRemisionManager.setAccionVolver(false);
        
    }

    private void registrarEventosBotones() {
        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }
            
        };
        addHotKey(f2, "IdentClientF2", listenerf2);

        KeyStroke f8 = KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0);
        Action listenerf8 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionPasoSiguiente();

            }
        };
        addHotKey(f8, "IdentClientF5", listenerf8);

        KeyStroke f12 = KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0);
        Action listenerf12 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                b_m_menu_principalActionPerformed(ae);

            }
        };
        addHotKey(f12, "IdentClientF9", listenerf12);
    }
    
    private void accionCancelar() {
       //deshabilitamos validación porque podría pasar qe no dejase ir el foco de un campo requerido
     deshabilitarFormulario();
        if (JPrincipal.getInstance().crearVentanaConfirmacion("¿Desea cancelar la creación de guía de remisión?")){
            JPrincipal.getInstance().showViewMenuVentas();
       }
        else{
            habilitarFormulario();
        }
    }

    private void deshabilitarFormulario() {
        for(IValidableForm ivf:formulario){
            ivf.setValidacionHabilitada(false);
        }
    }
    
    private void habilitarFormulario() {
        for(IValidableForm ivf:formulario){
            ivf.setValidacionHabilitada(true);
        }
    }
}
