/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JBuscarLetrasCambio.java
 *
 * Created on 02-oct-2012, 13:08:05
 */
package com.comerzzia.jpos.gui.bonoEfectivo;

import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.bonoEfectivo.modelos.BonoEfectivoCambioCellRenderer;
import com.comerzzia.jpos.gui.bonoEfectivo.modelos.BonoEfectivoCambioTableModel;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.credito.JOperacionesTarjeta;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.bonoEfectivo.BonoEfectivoCambioException;
import com.comerzzia.jpos.servicios.bonoEfectivo.BonoEfectivoManager;
import es.mpsistemas.util.log.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;

/**
 *
 * @author MGRI
 */
public class JConsultaBonoEfectivo extends JVentanaDialogo implements IViewerValidationFormError {

    protected static Logger log = Logger.getMLogger(JConsultaBonoEfectivo.class);
    public static BonoEfectivoManager manejador;
    private static final long serialVersionUID = 1L;
    private JPrincipal ventana_padre = null;

    /**
     * Creates new form JBuscarLetrasCambio
     */
    public JConsultaBonoEfectivo() {
        initComponents();
        registraEventoEnterBoton();
        crearAccionFocoTabla(this, tb_listaFacturas, KeyEvent.VK_T, InputEvent.CTRL_MASK);
        manejador = BonoEfectivoManager.getInstance();
        tb_listaFacturas.setDefaultRenderer(Object.class, new BonoEfectivoCambioCellRenderer());
        addFunctionsKeys();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        t_numero_cedula = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_error = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_listaFacturas = new javax.swing.JTable();
        b_volver1 = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+7));
        jLabel1.setText("CONSULTA DE BONO EFECTIVO");

        jLabel4.setDisplayedMnemonic('c');
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setLabelFor(t_numero_cedula);
        jLabel4.setText("Nro. Cédula:");

        t_numero_cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_numero_cedulaActionPerformed(evt);
            }
        });
        t_numero_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_cedulaKeyTyped(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(255, 0, 0));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_error.setText("Cedula Invalida");
        lb_error.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(t_numero_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(308, 308, 308))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_numero_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        tb_listaFacturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_listaFacturas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tb_listaFacturasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_listaFacturasFocusLost(evt);
            }
        });
        tb_listaFacturas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_listaFacturasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_listaFacturas);

        b_volver1.setText("<html><center>Volver<br/>F2</center></html>");
        b_volver1.setActionCommand("<html><center> Cancelar <br>F2</center></html>");
        b_volver1.setAlignmentY(0.0F);
        b_volver1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        b_volver1.setMargin(new java.awt.Insets(2, 0, 2, 0));
        b_volver1.setMaximumSize(new java.awt.Dimension(76, 48));
        b_volver1.setMinimumSize(new java.awt.Dimension(76, 48));
        b_volver1.setPreferredSize(new java.awt.Dimension(114, 48));
        b_volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volver1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_volver1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_volver1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

//GEN-FIRST:event_tb_listaArticulosKeyPressed
 
//GEN-LAST:event_tb_listaArticulosKeyPressed
////
    private void tb_listaFacturasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_listaFacturasKeyPressed
//        if (evt.getKeyChar() == '\n') {
//            accionSeleccionaFactura();
//        } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
//            b_volver.requestFocus();
//        } else if (evt.getKeyCode() == KeyEvent.VK_F2) {
//            accionIrAtras();
//        }

    }//GEN-LAST:event_tb_listaFacturasKeyPressed

    private void tb_listaFacturasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaFacturasFocusLost
        eliminaSeleccionTabla();
    }//GEN-LAST:event_tb_listaFacturasFocusLost

    private void tb_listaFacturasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaFacturasFocusGained
        if (tb_listaFacturas.getRowCount() >= 0) {
            ListSelectionModel selectionModel = tb_listaFacturas.getSelectionModel();
            selectionModel.setSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_tb_listaFacturasFocusGained

    private void t_numero_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_cedulaKeyTyped
        if (evt.getKeyChar() == '\n') {
            accionBuscarCedula();
        }
    }//GEN-LAST:event_t_numero_cedulaKeyTyped

    private void t_numero_cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_numero_cedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_numero_cedulaActionPerformed

    private void b_volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volver1ActionPerformed
        accionCancelar();
    }//GEN-LAST:event_b_volver1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_volver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_cedula;
    private javax.swing.JTable tb_listaFacturas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
        t_numero_cedula.setText("");
        lb_error.setText("");
    }

    public void iniciaVista() {
        manejador.inicia();
        limpiarFormulario();
        inicializaValidacion();
        refrescarTabla();
        iniciaFoco();
    }

    public void recuperaVista() {
        refrescarTabla();
        lb_error.setText("");
        inicializaValidacion();
        iniciaFoco();
    }

    void iniciaFoco() {
        t_numero_cedula.requestFocus();
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

//    private void accionSeleccionaFactura() {
//        try {
//            manejador.accionSeleccionaFactura(tb_listaFacturas.getSelectedRow());
//            accionIrADetalleDeFactura();
//        } catch (BonoEfectivoCambioException e) {
//            lb_error.setText(e.getMessage());
//            return;
//        }
//    }
//    private void accionBuscarNumeroFactura() {
//        try {
//            t_numero_factura.validar();
//            if (t_numero_factura.getText().isEmpty()) {
//                lb_error.setText("Debe ingresar una caja.");
//                return;
//            }
////            if (t_numero_factura1.getText().isEmpty()) {
////                lb_error.setText("Debe ingresar un número de factura.");
////                return;
////            }           
//            manejador.accionBuscarFactura(t_numero_factura1.getText(), t_numero_factura.getText());
//            mostrarResultados();
//        } catch (LetraCambioException e) {
//            lb_error.setText(e.getMessage());
//        } catch (ValidationFormException ex) {
//            addError(ex);
//        }
//    }
    private void mostrarResultados() throws BonoEfectivoCambioException {
//        if (manejador.getListaFacturas().isEmpty()) {
//          lb_error.setText("No existen letras de cambio para la datos seleccionados");
//          refrescarTabla();
//        } else 
//        if (manejador.getbonoEfectivo().size() == 1) {
//            manejador.accionSeleccionaFactura(0);
//            accionIrADetalleDeFactura();
//        } else {
        refrescarTabla();
//        }

//        if (manejador.getListaFacturas().size() > 1) {
//            tb_listaFacturas.requestFocus();
//        }
    }

    private void addFunctionsKeys() {
        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }

        };
        addHotKey(f2, "IdentClientF2", listenerf2);
    }

    private void accionBuscarCedula() {
        lb_error.setText("");

        if (t_numero_cedula.getText().isEmpty()) {
            lb_error.setText("Debe ingresar una Cedula");
            return;
        }
        try {
            try {
                manejador.accionBuscarCedula(t_numero_cedula.getText());
            } catch (BonoEfectivoCambioException ex) {
                java.util.logging.Logger.getLogger(JConsultaBonoEfectivo.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrarResultados();
        } catch (BonoEfectivoCambioException e) {
            lb_error.setText(e.getMessage());
        }
    }

    private void refrescarTabla() {
        tb_listaFacturas.setModel(new BonoEfectivoCambioTableModel(manejador.getbonoEfectivo()));
    }

    private void accionIrADetalleDeFactura() {
        contenedor.setVisible(false);
        JOperacionesTarjeta.crearVentanaPagarLetra();
        limpiarFormulario();

    }

    private void eliminaSeleccionTabla() {
        ListSelectionModel selectionModel = tb_listaFacturas.getSelectionModel();
        selectionModel.clearSelection();
    }

    private void accionIrAtras() {
        cerrarVentana();
        JPrincipal.getInstance().crearVentanaMenuTarjetas();
    }

    private void inicializaValidacion() {
        //     t_numero_factura.addValidador(new ValidadorTexto(3, true), this);
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }
}
