/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JReimpresion.java
 *
 * Created on 11-mar-2014, 18:02:41
 */
package com.comerzzia.jpos.gui.reimpresion;

import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.JSolicitarAutorizacionVentana;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.persistencia.print.documentos.DocumentosBean;
import com.comerzzia.jpos.servicios.core.permisos.Operaciones;
import com.comerzzia.jpos.servicios.core.permisos.SinPermisosException;
import com.comerzzia.jpos.servicios.core.variables.Variables;

import es.mpsistemas.util.log.Logger;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.net.URL;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JDialog;
import javax.swing.KeyStroke;

/**
 *
 * @author SMLM
 */
public class JReimpresion extends JVentanaDialogo {

    private static Logger log = Logger.getMLogger(JReimpresion.class);
    private JPrincipal ventana_padre = null;
    public JSolicitarAutorizacionVentana v_dialog_autorizar;
    private static JDialog popupActivo;

    /**
     * Creates new form JReimpresion
     */
    public JReimpresion() {
        super();
        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_menu.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
            initComponents();

            v_dialog_autorizar = new JSolicitarAutorizacionVentana();
            v_dialog_autorizar.setAlwaysOnTop(true);
            preparaDimensionVentanaAutorizacion();
            v_dialog_autorizar.setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
            v_dialog_autorizar.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
            v_dialog_autorizar.setResizable(false);

            b_factura.requestFocus(true);

            // Reimpresión de Documentos
            v_reimpresion_documento.setLocationRelativeTo(null);
            p_reimpresion_documento.setContenedor(v_reimpresion_documento);
            /**
             * Reimpresión de Facturas Rd
             */
            v_reimpresion_factura.setLocationRelativeTo(null);
            p_reimpresion_factura.setContenedor(v_reimpresion_factura);

            // Menu Tipos Documento
            v_menu_tipos.setLocationRelativeTo(null);
            p_menu_tipos.setContenedor(v_menu_tipos);

            // Reimpresión de Bono
            v_reimpresion_docu_recibo.setLocationRelativeTo(null);
            p_reimpresion_docu_recibo.setContenedor(v_reimpresion_docu_recibo);

            b_pendiente_reserva.setVisible(true);
            v_pendientereserva.setLocationRelativeTo(null);
            p_pendientereserva.setContenedor(v_pendientereserva);
            b_notaCredito.setVisible(true);
            b_bono.setVisible(true);
            addFunctionKeys();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_reimpresion_documento = new javax.swing.JDialog();
        p_reimpresion_documento = new com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumento();
        v_menu_tipos = new javax.swing.JDialog();
        p_menu_tipos = new com.comerzzia.jpos.gui.reimpresion.JReimpresionMenuTipos();
        v_reimpresion_docu_recibo = new javax.swing.JDialog();
        p_reimpresion_docu_recibo = new com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumentoRecibo();
        v_reimpresion_factura = new javax.swing.JDialog();
        p_reimpresion_factura = new com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionFactura();
        v_pendientereserva = new javax.swing.JDialog();
        p_pendientereserva = new com.comerzzia.jpos.gui.reimpresion.pendientereserva.JPendienteReserva();
        jLabel7 = new javax.swing.JLabel();
        b_factura = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_notaCredito = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_reciboPago = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_reservaciones = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_giftcard = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_bono = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_planNovio = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_pendiente_reserva = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        v_reimpresion_documento.setAlwaysOnTop(true);
        v_reimpresion_documento.setMinimumSize(new java.awt.Dimension(520,380));

        p_reimpresion_documento.setToolTipText("");
        p_reimpresion_documento.setMaximumSize(new java.awt.Dimension(520,270));
        p_reimpresion_documento.setMinimumSize(new java.awt.Dimension(520,380));

        javax.swing.GroupLayout v_reimpresion_documentoLayout = new javax.swing.GroupLayout(v_reimpresion_documento.getContentPane());
        v_reimpresion_documento.getContentPane().setLayout(v_reimpresion_documentoLayout);
        v_reimpresion_documentoLayout.setHorizontalGroup(
            v_reimpresion_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_reimpresion_documentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_reimpresion_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        v_reimpresion_documentoLayout.setVerticalGroup(
            v_reimpresion_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_reimpresion_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_reimpresion_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        v_menu_tipos.setAlwaysOnTop(true);
        v_menu_tipos.setMinimumSize(new java.awt.Dimension(312, 316));

        javax.swing.GroupLayout v_menu_tiposLayout = new javax.swing.GroupLayout(v_menu_tipos.getContentPane());
        v_menu_tipos.getContentPane().setLayout(v_menu_tiposLayout);
        v_menu_tiposLayout.setHorizontalGroup(
            v_menu_tiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_menu_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        v_menu_tiposLayout.setVerticalGroup(
            v_menu_tiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_menu_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        v_reimpresion_docu_recibo.setAlwaysOnTop(true);
        v_reimpresion_docu_recibo.setMinimumSize(new java.awt.Dimension(600, 260));

        p_reimpresion_docu_recibo.setMinimumSize(new java.awt.Dimension(520, 260));
        p_reimpresion_docu_recibo.setPreferredSize(new java.awt.Dimension(570, 220));

        javax.swing.GroupLayout v_reimpresion_docu_reciboLayout = new javax.swing.GroupLayout(v_reimpresion_docu_recibo.getContentPane());
        v_reimpresion_docu_recibo.getContentPane().setLayout(v_reimpresion_docu_reciboLayout);
        v_reimpresion_docu_reciboLayout.setHorizontalGroup(
            v_reimpresion_docu_reciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_reimpresion_docu_recibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        v_reimpresion_docu_reciboLayout.setVerticalGroup(
            v_reimpresion_docu_reciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_reimpresion_docu_recibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        v_reimpresion_factura.setAlwaysOnTop(true);
        v_reimpresion_factura.setMinimumSize(new java.awt.Dimension(600,390));

        p_reimpresion_factura.setMaximumSize(new java.awt.Dimension(520,270));
        p_reimpresion_factura.setMinimumSize(new java.awt.Dimension(600,390));
        p_reimpresion_factura.setName(""); // NOI18N

        javax.swing.GroupLayout v_reimpresion_facturaLayout = new javax.swing.GroupLayout(v_reimpresion_factura.getContentPane());
        v_reimpresion_factura.getContentPane().setLayout(v_reimpresion_facturaLayout);
        v_reimpresion_facturaLayout.setHorizontalGroup(
            v_reimpresion_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(v_reimpresion_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(v_reimpresion_facturaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p_reimpresion_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        v_reimpresion_facturaLayout.setVerticalGroup(
            v_reimpresion_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(v_reimpresion_facturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(v_reimpresion_facturaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p_reimpresion_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout v_pendientereservaLayout = new javax.swing.GroupLayout(v_pendientereserva.getContentPane());
        v_pendientereserva.getContentPane().setLayout(v_pendientereservaLayout);
        v_pendientereservaLayout.setHorizontalGroup(
            v_pendientereservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_pendientereservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_pendientereserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_pendientereservaLayout.setVerticalGroup(
            v_pendientereservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, v_pendientereservaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p_pendientereserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setMaximumSize(new java.awt.Dimension(260,320));
        setMinimumSize(new java.awt.Dimension(260,320));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(-4144960,true));
        jLabel7.setText("MENÚ DE REIMPRESIONES");

        b_factura.setMnemonic('f');
        b_factura.setText("Factura ");
        b_factura.setAlignmentY(0.2F);
        b_factura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_facturaActionPerformed(evt);
            }
        });

        b_notaCredito.setMnemonic('C');
        b_notaCredito.setText("Nota de Crédito");
        b_notaCredito.setAlignmentY(0.2F);
        b_notaCredito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_notaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_notaCreditoActionPerformed(evt);
            }
        });

        b_reciboPago.setMnemonic('P');
        b_reciboPago.setText("Recibo de Pago");
        b_reciboPago.setAlignmentY(0.2F);
        b_reciboPago.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_reciboPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_reciboPagoActionPerformed(evt);
            }
        });

        b_reservaciones.setMnemonic('R');
        b_reservaciones.setText("Reservaciones");
        b_reservaciones.setAlignmentY(0.2F);
        b_reservaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_reservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_reservacionesActionPerformed(evt);
            }
        });

        b_giftcard.setMnemonic('G');
        b_giftcard.setText("Giftcard");
        b_giftcard.setAlignmentY(0.2F);
        b_giftcard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_giftcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_giftcardActionPerformed(evt);
            }
        });

        b_bono.setMnemonic('b');
        b_bono.setText("Bono Efectivo");
        b_bono.setAlignmentY(0.2F);
        b_bono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_bono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bonoActionPerformed(evt);
            }
        });

        b_planNovio.setMnemonic('N');
        b_planNovio.setText("Plan Novio");
        b_planNovio.setAlignmentY(0.2F);
        b_planNovio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_planNovio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_planNovioActionPerformed(evt);
            }
        });

        b_pendiente_reserva.setMnemonic('b');
        b_pendiente_reserva.setText("Pendiente/Reserva Cadudado");
        b_pendiente_reserva.setAlignmentY(0.2F);
        b_pendiente_reserva.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_pendiente_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pendiente_reservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(b_factura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_notaCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_reciboPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_reservaciones, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_giftcard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_bono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_planNovio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_pendiente_reserva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_notaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_reciboPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_reservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_planNovio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_giftcard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_bono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_pendiente_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_facturaActionPerformed
        crearVentanaReimpresion(DocumentosBean.FACTURA);
}//GEN-LAST:event_b_facturaActionPerformed

    private void b_notaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_notaCreditoActionPerformed
        crearVentanaReimpresion(DocumentosBean.NOTA_CREDITO);
    }//GEN-LAST:event_b_notaCreditoActionPerformed

    private void b_reciboPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_reciboPagoActionPerformed
        crearMenuReimpresionTipos(DocumentosBean.ABONO);
    }//GEN-LAST:event_b_reciboPagoActionPerformed

    private void b_reservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_reservacionesActionPerformed
        crearMenuReimpresionTipos(DocumentosBean.RESERVACION);
    }//GEN-LAST:event_b_reservacionesActionPerformed

    private void b_giftcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_giftcardActionPerformed
        crearMenuReimpresionTipos(DocumentosBean.GIFTCARD);
    }//GEN-LAST:event_b_giftcardActionPerformed

    private void b_bonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bonoActionPerformed
        crearVentanaReimpresionBono(DocumentosBean.BONO);
    }//GEN-LAST:event_b_bonoActionPerformed

    private void b_planNovioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_planNovioActionPerformed
        crearMenuReimpresionTipos(DocumentosBean.PLAN_NOVIO);
    }//GEN-LAST:event_b_planNovioActionPerformed

    private void b_pendiente_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pendiente_reservaActionPerformed
        crearVentanaPendienteReserva(DocumentosBean.PENDIENTE_RESERVA);
    }//GEN-LAST:event_b_pendiente_reservaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_bono;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_factura;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_giftcard;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_notaCredito;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_pendiente_reserva;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_planNovio;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_reciboPago;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_reservaciones;
    private javax.swing.JLabel jLabel7;
    private com.comerzzia.jpos.gui.reimpresion.JReimpresionMenuTipos p_menu_tipos;
    private com.comerzzia.jpos.gui.reimpresion.pendientereserva.JPendienteReserva p_pendientereserva;
    private com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumentoRecibo p_reimpresion_docu_recibo;
    private com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumento p_reimpresion_documento;
    private com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionFactura p_reimpresion_factura;
    private javax.swing.JDialog v_menu_tipos;
    private javax.swing.JDialog v_pendientereserva;
    private javax.swing.JDialog v_reimpresion_docu_recibo;
    private javax.swing.JDialog v_reimpresion_documento;
    private javax.swing.JDialog v_reimpresion_factura;
    // End of variables declaration//GEN-END:variables

    private void crearVentanaReimpresion(String tipo) {
        /**
         * Rd Reimpresion
         */
        if (tipo.equals(DocumentosBean.FACTURA)) {
            p_reimpresion_factura.setTipo(tipo);
            cerrarVentana();
            v_reimpresion_factura.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
            v_reimpresion_factura.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
            p_reimpresion_factura.iniciaVista();
            v_reimpresion_factura.setVisible(true);
        } else if (tipo.equals(DocumentosBean.NOTA_CREDITO)) {
            try {
//                Sesion.setReimpresionNC("S");
                String compruebaAutorizacion = compruebaAutorizacionReimpresionNC(Operaciones.REIMPRIMIR_NOTA_CREDITO_BONO);
                p_reimpresion_documento.setTipo(tipo);
                cerrarVentana();
                v_reimpresion_documento.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
                v_reimpresion_documento.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
                p_reimpresion_documento.iniciaVista();
                v_reimpresion_documento.setVisible(true);
            } catch (SinPermisosException ex) {
                java.util.logging.Logger.getLogger(JReimpresion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            p_reimpresion_documento.setTipo(tipo);
            cerrarVentana();
            v_reimpresion_documento.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
            v_reimpresion_documento.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
            p_reimpresion_documento.iniciaVista();
            v_reimpresion_documento.setVisible(true);
        }
    }

    private void crearMenuReimpresionTipos(String tipo) {
        p_menu_tipos.setTipo(tipo);
        cerrarVentana();
        v_menu_tipos.setResizable(false);
        if (!v_menu_tipos.isUndecorated()) {
            v_menu_tipos.setUndecorated(true);
        }
        v_menu_tipos.setLocationRelativeTo(null);
        v_menu_tipos.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        v_menu_tipos.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        p_menu_tipos.iniciaVista();
        v_menu_tipos.setVisible(true);
    }

    private void crearVentanaReimpresionBono(String tipo) {
        try {
            String compruebaAutorizacion = compruebaAutorizacionReimpresionNC(Operaciones.REIMPRIMIR_NOTA_CREDITO_BONO);
            p_reimpresion_docu_recibo.setTipo(tipo);
            cerrarVentana();
            v_reimpresion_docu_recibo.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
            v_reimpresion_docu_recibo.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
            p_reimpresion_docu_recibo.iniciaVista();
            v_reimpresion_docu_recibo.setVisible(true);
        } catch (SinPermisosException ex) {
            java.util.logging.Logger.getLogger(JReimpresion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     *
     * @param tipo
     */
    private void crearVentanaPendienteReserva(String tipo) {
        p_pendientereserva.setTipo(tipo);
        cerrarVentana();

        v_pendientereserva.setSize(1000, 600);
        v_pendientereserva.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        v_pendientereserva.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        p_pendientereserva.iniciaVista();
        v_pendientereserva.setVisible(true);
    }

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

    private void addFunctionKeys() {
        // ENTER EN LOS BOTONES
        addHotKey(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "EnterBotones", listenerEnter);

        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
    }

    public void iniciaFoco() {
        b_factura.requestFocus();
    }

    public String compruebaAutorizacionReimpresionNC(Byte operacion) throws SinPermisosException {
        log.debug("PERMISOS Combrobando Autorización Reimpresion Nota Credito: " + operacion);
        return crearVentanaAutorizacionNC(operacion);
    }

    public String crearVentanaAutorizacionNC(Byte operacion) throws SinPermisosException {
        log.info("PERMISOS: Creando Pantalla de Autorización");
        preparaDimensionVentanaAutorizacion();
        v_dialog_autorizar.setLocationRelativeTo(null);
        v_dialog_autorizar.setOperacionAAutorizar(operacion);
//        v_dialog_autorizar.setMensajeDefault();
        v_dialog_autorizar.setFocoInicial();
        popupActivo = v_dialog_autorizar;
        v_dialog_autorizar.setVisible(true);
        popupActivo = null;
        // Aqui esperamos a que termine la ventana modal
        return v_dialog_autorizar.autenticacionExitosa();

    }

    public void preparaDimensionVentanaAutorizacion() {
        v_dialog_autorizar.setMinimumSize(new java.awt.Dimension(370, 360)); //442
        v_dialog_autorizar.setMaximumSize(new java.awt.Dimension(370, 360));
        v_dialog_autorizar.setPreferredSize(new java.awt.Dimension(370, 360));
    }
}
