/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JReimpresionMenuTipos.java
 *
 * Created on 02-abr-2014, 13:50:32
 */
package com.comerzzia.jpos.gui.reimpresion;

import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.persistencia.print.documentos.DocumentosBean;
import com.comerzzia.jpos.servicios.core.variables.Variables;
import es.mpsistemas.util.log.Logger;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;

/**
 *
 * @author SMLM
 */
public class JReimpresionMenuTipos extends JVentanaDialogo {
    
    private static Logger log = Logger.getMLogger(JReimpresionMenuTipos.class);
    private String tipo;
    /** Creates new form JReimpresionMenuTipos */
    public JReimpresionMenuTipos() {
        super();
        try {
            String prefijo = Variables.getVariable(Variables.POS_UI_SKIN);
            URL myurl = this.getClass().getResource("/skin/" + prefijo + "/" + prefijo + "_menu.png");

            this.setImagenFondo((Image) ImageIO.read(new File(myurl.getPath())));
        }
        catch (Exception e) {
        }        
        initComponents();
        addFunctionKeys();
        
        // Reimpresión de Documentos
        v_reimpresion_documento.setLocationRelativeTo(null);
        p_reimpresion_documento.setContenedor(v_reimpresion_documento);
        
        // Reimpresión de Documentos con Abono
        v_reimpresiondocu_Abono.setLocationRelativeTo(null);
        p_reimpresiondocu_Abono.setContenedor(v_reimpresiondocu_Abono);
        
        // Reimpresion de Documentos con Recibo
        v_reimpresiondocu_Recibo.setLocationRelativeTo(null);
        p_reimpresiondocu_Recibo.setContenedor(v_reimpresiondocu_Recibo);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        v_reimpresion_documento = new javax.swing.JDialog();
        p_reimpresion_documento = new com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumento();
        v_reimpresiondocu_Abono = new javax.swing.JDialog();
        p_reimpresiondocu_Abono = new com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumentoConAbono();
        v_reimpresiondocu_Recibo = new javax.swing.JDialog();
        p_reimpresiondocu_Recibo = new com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumentoRecibo();
        b_boton2 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        l_titulo = new javax.swing.JLabel();
        b_boton1 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_boton3 = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        b_boton4 = new com.comerzzia.jpos.gui.components.form.JButtonForm();

        v_reimpresion_documento.setAlwaysOnTop(true);
        v_reimpresion_documento.setMinimumSize(new java.awt.Dimension(520,380));

        javax.swing.GroupLayout v_reimpresion_documentoLayout = new javax.swing.GroupLayout(v_reimpresion_documento.getContentPane());
        v_reimpresion_documento.getContentPane().setLayout(v_reimpresion_documentoLayout);
        v_reimpresion_documentoLayout.setHorizontalGroup(
            v_reimpresion_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_reimpresion_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_reimpresion_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_reimpresion_documentoLayout.setVerticalGroup(
            v_reimpresion_documentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_reimpresion_documentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_reimpresion_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        v_reimpresiondocu_Abono.setAlwaysOnTop(true);
        v_reimpresiondocu_Abono.setMinimumSize(new java.awt.Dimension(520,280));
        v_reimpresiondocu_Abono.setPreferredSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout v_reimpresiondocu_AbonoLayout = new javax.swing.GroupLayout(v_reimpresiondocu_Abono.getContentPane());
        v_reimpresiondocu_Abono.getContentPane().setLayout(v_reimpresiondocu_AbonoLayout);
        v_reimpresiondocu_AbonoLayout.setHorizontalGroup(
            v_reimpresiondocu_AbonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_reimpresiondocu_AbonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_reimpresiondocu_Abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        v_reimpresiondocu_AbonoLayout.setVerticalGroup(
            v_reimpresiondocu_AbonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_reimpresiondocu_AbonoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_reimpresiondocu_Abono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        v_reimpresiondocu_Recibo.setAlwaysOnTop(true);
        v_reimpresiondocu_Recibo.setMinimumSize(new java.awt.Dimension(600,280));
        v_reimpresiondocu_Recibo.setPreferredSize(new java.awt.Dimension(600, 300));

        p_reimpresiondocu_Recibo.setPreferredSize(new java.awt.Dimension(529, 275));
        p_reimpresiondocu_Recibo.setRepintarImagenFondo(false);

        javax.swing.GroupLayout v_reimpresiondocu_ReciboLayout = new javax.swing.GroupLayout(v_reimpresiondocu_Recibo.getContentPane());
        v_reimpresiondocu_Recibo.getContentPane().setLayout(v_reimpresiondocu_ReciboLayout);
        v_reimpresiondocu_ReciboLayout.setHorizontalGroup(
            v_reimpresiondocu_ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_reimpresiondocu_Recibo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        v_reimpresiondocu_ReciboLayout.setVerticalGroup(
            v_reimpresiondocu_ReciboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(v_reimpresiondocu_ReciboLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_reimpresiondocu_Recibo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        b_boton2.setAlignmentY(0.2F);
        b_boton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton2ActionPerformed(evt);
            }
        });

        l_titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        l_titulo.setForeground(new java.awt.Color(-4144960,true));
        l_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        b_boton1.setAlignmentY(0.2F);
        b_boton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton1ActionPerformed(evt);
            }
        });

        b_boton3.setAlignmentY(0.2F);
        b_boton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton3ActionPerformed(evt);
            }
        });

        b_boton4.setAlignmentY(0.2F);
        b_boton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_boton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_boton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(b_boton1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(b_boton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(b_boton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(l_titulo)
                .addGap(29, 29, 29)
                .addComponent(b_boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(b_boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(b_boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(b_boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton2ActionPerformed
        if(tipo.equals(DocumentosBean.GIFTCARD)){
            crearVentanaReimpresion(DocumentosBean.GIFTCARD);
        }
        if(tipo.equals(DocumentosBean.ABONO)){
            crearVentanaReimpresion(DocumentosBean.LETRA_ABONO);
        }
        if(tipo.equals(DocumentosBean.RESERVACION)){
            crearVentanaReimpresionConAbono(DocumentosBean.ABONO_RESERVA);
        }
        if(tipo.equals(DocumentosBean.PLAN_NOVIO)){
            crearVentanaReimpresionConAbono(DocumentosBean.ABONO_PLAN_NOVIO);
        }
}//GEN-LAST:event_b_boton2ActionPerformed

    private void b_boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton1ActionPerformed
        if(tipo.equals(DocumentosBean.GIFTCARD)){
            crearVentanaReimpresion(DocumentosBean.GIFTCARD);
        }
        if(tipo.equals(DocumentosBean.ABONO)){
            crearVentanaReimpresion(DocumentosBean.CREDITO_ABONO);
        }
        if(tipo.equals(DocumentosBean.RESERVACION)){
            crearVentanaReimpresionRecibo(DocumentosBean.RESERVACION);
        }     
        if(tipo.equals(DocumentosBean.PLAN_NOVIO)) {
            crearVentanaReimpresionRecibo(DocumentosBean.PLAN_NOVIO);
        }
    }//GEN-LAST:event_b_boton1ActionPerformed

    private void b_boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton3ActionPerformed
        if(tipo.equals(DocumentosBean.RESERVACION)){
            crearVentanaReimpresionRecibo(DocumentosBean.LIQUIDACION_RE);
        }
        if(tipo.equals(DocumentosBean.PLAN_NOVIO)){
            crearVentanaReimpresionRecibo(DocumentosBean.LIQUIDACION_PN);
        }        
        if(tipo.equals(DocumentosBean.GIFTCARD)){
            crearVentanaReimpresion(DocumentosBean.GIFTCARD_P);
        }
    }//GEN-LAST:event_b_boton3ActionPerformed

    private void b_boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_boton4ActionPerformed
        if(tipo.equals(DocumentosBean.RESERVACION)){
            crearVentanaReimpresionRecibo(DocumentosBean.BONO_RESERVA);
        }      
    }//GEN-LAST:event_b_boton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton1;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton2;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton3;
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_boton4;
    private javax.swing.JLabel l_titulo;
    private com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumento p_reimpresion_documento;
    private com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumentoConAbono p_reimpresiondocu_Abono;
    private com.comerzzia.jpos.gui.reimpresion.tipos.JReimpresionDocumentoRecibo p_reimpresiondocu_Recibo;
    private javax.swing.JDialog v_reimpresion_documento;
    private javax.swing.JDialog v_reimpresiondocu_Abono;
    private javax.swing.JDialog v_reimpresiondocu_Recibo;
    // End of variables declaration//GEN-END:variables
   
    private void crearVentanaReimpresion(String tipo) {
        cerrarVentana();
        p_reimpresion_documento.setTipo(tipo);
        v_reimpresion_documento.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        v_reimpresion_documento.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);        
        p_reimpresion_documento.iniciaVista();
        v_reimpresion_documento.setVisible(true);  
    }
    
    private void crearVentanaReimpresionConAbono(String tipo) {
        cerrarVentana();
        p_reimpresiondocu_Abono.setTipo(tipo);
        v_reimpresiondocu_Abono.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        v_reimpresiondocu_Abono.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);        
        p_reimpresiondocu_Abono.iniciaVista();
        v_reimpresiondocu_Abono.setVisible(true);          
    }
    
    private void crearVentanaReimpresionRecibo(String tipo) {
        cerrarVentana();
        p_reimpresiondocu_Recibo.setTipo(tipo);
        v_reimpresiondocu_Recibo.setModalityType(Dialog.ModalityType.TOOLKIT_MODAL);
        v_reimpresiondocu_Recibo.setModalExclusionType(Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);        
        p_reimpresiondocu_Recibo.iniciaVista();
        v_reimpresiondocu_Recibo.setVisible(true);           
    }
    
    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
    }

    @Override
    public void accionLeerTarjetaVD() {
    }
    
    public void iniciaVista(){
        if(tipo.equals(DocumentosBean.GIFTCARD)){
            l_titulo.setText("REIMPRESIONES DE GIFTCARD");
            b_boton1.setText("Recibo de Compra");
            b_boton1.setMnemonic('C');
            b_boton2.setText("Recibo de Recarga");
            b_boton2.setMnemonic('R');
            b_boton3.setText("Recibo de Uso");
            b_boton3.setMnemonic('U');
            b_boton3.setVisible(true);
            b_boton4.setVisible(false);
        }
        if(tipo.equals(DocumentosBean.ABONO)){
            l_titulo.setText("REIMPRESIONES DE RECIBO DE PAGO");
            b_boton1.setText("Recibo Pago Crédito Propio");
            b_boton1.setMnemonic('P');
            b_boton2.setText("Recibo Pago Crédito Temporal");
            b_boton2.setMnemonic('T');
            b_boton3.setVisible(false);
            b_boton4.setVisible(false);          
        }
        if(tipo.equals(DocumentosBean.RESERVACION)){
            l_titulo.setText("REIMPRESIONES DE RESERVACIONES");
            b_boton1.setText("Recibo de Creación");
            b_boton1.setMnemonic('C');
            b_boton2.setText("Recibo Abono");
            b_boton2.setMnemonic('A');
            b_boton3.setText("Recibo Liquidación/Anulación");
            b_boton3.setMnemonic('L');
            b_boton3.setVisible(true);
            b_boton4.setText("Bono Anulación/Liquidación");
            b_boton4.setMnemonic('B');
            b_boton4.setVisible(true);
        }
        if(tipo.equals(DocumentosBean.PLAN_NOVIO)){
            l_titulo.setText("REIMPRESIONES DE PLAN NOVIO");
            b_boton1.setText("Recibo de Creación");
            b_boton1.setMnemonic('C');
            b_boton2.setText("Recibo Abono");
            b_boton2.setMnemonic('A');
            b_boton3.setText("Recibo Liquidación");
            b_boton3.setMnemonic('L');
            b_boton3.setVisible(true);
            b_boton4.setVisible(false);
        }
        b_boton1.requestFocus();
    }
    
    private void addFunctionKeys() {
        // ENTER EN LOS BOTONES
        addHotKey(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "EnterBotones", listenerEnter);

        KeyStroke esc = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action listeneresc = new AbstractAction() {

            @Override
            public void actionPerformed(ActionEvent ae) {
                accionCancelar();
            }
        };
        addHotKey(esc, "IdentClientesc", listeneresc);
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    public void iniciaFoco() {
        b_boton1.requestFocus();
    }
}
