/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JBuscarLetrasCambio.java
 *
 * Created on 02-oct-2012, 13:08:05
 */
package com.comerzzia.jpos.gui.credito.letras;

import com.comerzzia.jpos.gui.JPrincipal;
import com.comerzzia.jpos.gui.components.JVentanaDialogo;
import com.comerzzia.jpos.gui.credito.JOperacionesTarjeta;
import com.comerzzia.jpos.gui.credito.letras.modelos.FacturasCambioCellRenderer;
import com.comerzzia.jpos.gui.credito.letras.modelos.FacturasCambioTableModel;
import com.comerzzia.jpos.gui.validation.IViewerValidationFormError;
import com.comerzzia.jpos.gui.validation.ValidadorTexto;
import com.comerzzia.jpos.gui.validation.ValidationFormException;
import com.comerzzia.jpos.servicios.letras.LetraCambioException;
import com.comerzzia.jpos.servicios.letras.LetraCambioManager;
import es.mpsistemas.util.log.Logger;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;

/**
 *
 * @author MGRI
 */
public class JBuscarLetrasCambio extends JVentanaDialogo implements IViewerValidationFormError {

    protected static Logger log = Logger.getMLogger(JBuscarLetrasCambio.class);
    public static LetraCambioManager manejador;
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form JBuscarLetrasCambio
     */
    public JBuscarLetrasCambio() {
        initComponents();
        registraEventoEnterBoton();
        crearAccionFocoTabla(this, tb_listaFacturas, KeyEvent.VK_T, InputEvent.CTRL_MASK);
        manejador = LetraCambioManager.getInstance();
        tb_listaFacturas.setDefaultRenderer(Object.class, new FacturasCambioCellRenderer());
        addFunctionsKeys();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        t_numero_factura1 = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_numero_cedula = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        lb_error = new javax.swing.JLabel();
        l_fecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_numero_factura = new com.comerzzia.jpos.gui.components.form.JTextFieldForm();
        jLabel5 = new javax.swing.JLabel();
        b_volver = new com.comerzzia.jpos.gui.components.form.JButtonForm();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_listaFacturas = new javax.swing.JTable();

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+7));
        jLabel1.setText("CONSULTA DE SALDO DE CRÉDITO TEMPORAL");

        t_numero_factura1.setNextFocusableComponent(t_numero_cedula);
        t_numero_factura1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_factura1KeyTyped(evt);
            }
        });

        jLabel3.setDisplayedMnemonic('f');
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setLabelFor(t_numero_factura);
        jLabel3.setText("Nro. Factura:");

        jLabel4.setDisplayedMnemonic('c');
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setLabelFor(t_numero_cedula);
        jLabel4.setText("Nro. Cédula:");

        t_numero_cedula.setNextFocusableComponent(b_volver);
        t_numero_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_cedulaKeyTyped(evt);
            }
        });

        lb_error.setForeground(new java.awt.Color(255, 0, 0));
        lb_error.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_error.setText("Tarjeta de identificación incorrecta");
        lb_error.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        l_fecha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        l_fecha.setText("27-AGO-2012");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Fecha:");

        t_numero_factura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_numero_factura.setNextFocusableComponent(t_numero_factura1);
        t_numero_factura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_facturaKeyTyped(evt);
            }
        });

        jLabel5.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t_numero_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(t_numero_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel5)
                                    .addGap(8, 8, 8)
                                    .addComponent(t_numero_factura1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(47, 47, 47)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(l_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238)))
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(l_fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_numero_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_numero_factura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_numero_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_error, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        b_volver.setText("<html><center>Volver <br/>F2</center></html>");
        b_volver.setNextFocusableComponent(t_numero_factura);
        b_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_volverActionPerformed(evt);
            }
        });

        tb_listaFacturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_listaFacturas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tb_listaFacturasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tb_listaFacturasFocusLost(evt);
            }
        });
        tb_listaFacturas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_listaFacturasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_listaFacturas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(b_volver, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_volver, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_volverActionPerformed
        if (b_volver.isEnabled()) {
            accionIrAtras();
        }
}//GEN-LAST:event_b_volverActionPerformed

//GEN-FIRST:event_tb_listaArticulosKeyPressed
 
//GEN-LAST:event_tb_listaArticulosKeyPressed

    private void tb_listaFacturasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_listaFacturasKeyPressed
        if (evt.getKeyChar() == '\n') {
            accionSeleccionaFactura();
        } else if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            b_volver.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_F2) {
            accionIrAtras();
        }

    }//GEN-LAST:event_tb_listaFacturasKeyPressed

    private void tb_listaFacturasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaFacturasFocusLost
        eliminaSeleccionTabla();
    }//GEN-LAST:event_tb_listaFacturasFocusLost

    private void tb_listaFacturasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tb_listaFacturasFocusGained
        if (tb_listaFacturas.getRowCount() >= 0) {
            ListSelectionModel selectionModel = tb_listaFacturas.getSelectionModel();
            selectionModel.setSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_tb_listaFacturasFocusGained

    private void t_numero_facturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_facturaKeyTyped
        if (evt.getKeyChar() == '\n') {
            accionBuscarNumeroFactura();
        }
    }//GEN-LAST:event_t_numero_facturaKeyTyped

    private void t_numero_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_cedulaKeyTyped
        if (evt.getKeyChar() == '\n') {
            accionBuscarCedula();
        }
    }//GEN-LAST:event_t_numero_cedulaKeyTyped

    private void t_numero_factura1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_factura1KeyTyped
        if (evt.getKeyChar() == '\n') {
            accionBuscarNumeroFactura();
        }
    }//GEN-LAST:event_t_numero_factura1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.comerzzia.jpos.gui.components.form.JButtonForm b_volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l_fecha;
    private javax.swing.JLabel lb_error;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_cedula;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_factura;
    private com.comerzzia.jpos.gui.components.form.JTextFieldForm t_numero_factura1;
    private javax.swing.JTable tb_listaFacturas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void accionAceptar() {
    }

    @Override
    public void limpiarFormulario() {
        t_numero_cedula.setText("");
        t_numero_factura.setText("");
        t_numero_factura1.setText("");
        lb_error.setText("");
        l_fecha.setText(formateadorFechaCorta.format(new Date()));
    }

    public void iniciaVista() {
        t_numero_factura.setValidacionHabilitada(false);
        manejador.inicia();
        limpiarFormulario();
        accionBuscarLetras();
        inicializaValidacion();
        refrescarTabla();
        iniciaFoco();
        t_numero_factura.setValidacionHabilitada(true);
    }

    public void recuperaVista() {
        refrescarTabla();
        lb_error.setText("");
        inicializaValidacion();
        iniciaFoco();
    }

    void iniciaFoco() {
        t_numero_factura.requestFocus();
    }

    @Override
    public void accionLeerTarjetaVD() {
    }

    private void accionSeleccionaFactura() {
        try {
            manejador.accionSeleccionaFactura(tb_listaFacturas.getSelectedRow());
            accionIrADetalleDeFactura();
        } catch (LetraCambioException e) {
            lb_error.setText(e.getMessage());
            return;
        }
    }

    private void accionBuscarNumeroFactura() {
        try {
            t_numero_factura.validar();
            if (t_numero_factura.getText().isEmpty()) {
                lb_error.setText("Debe ingresar una caja.");
                return;
            }
//            if (t_numero_factura1.getText().isEmpty()) {
//                lb_error.setText("Debe ingresar un número de factura.");
//                return;
//            }           
            manejador.accionBuscarFactura(t_numero_factura1.getText(), t_numero_factura.getText());
            mostrarResultados();
        } catch (LetraCambioException e) {
            lb_error.setText(e.getMessage());
        } catch (ValidationFormException ex) {
            addError(ex);
        }
    }
    
     private void accionBuscarLetras() {
        try {
            manejador.accionBuscarLetras();
            mostrarResultados();
        } catch (LetraCambioException e) {
            lb_error.setText(e.getMessage());
        }
    }

    private void mostrarResultados() throws LetraCambioException {
//        if (manejador.getListaFacturas().isEmpty()) {
//          lb_error.setText("No existen letras de cambio para la datos seleccionados");
//          refrescarTabla();
//        } else 
        if (manejador.getListaFacturas().size() == 1) {
            manejador.accionSeleccionaFactura(0);
            accionIrADetalleDeFactura();
        } else {
            refrescarTabla();
        }

        if (manejador.getListaFacturas().size() > 1) {
            tb_listaFacturas.requestFocus();
        }
    }

    private void accionBuscarCedula() {
        lb_error.setText("");
        t_numero_factura1.setText("");
        t_numero_factura.setText("");

        if (t_numero_cedula.getText().isEmpty()) {
            lb_error.setText("Debe ingresar una Cedula");
            return;
        }
        try {
            manejador.accionBuscarCedula(t_numero_cedula.getText());
            mostrarResultados();
        } catch (LetraCambioException e) {
            lb_error.setText(e.getMessage());
        }
    }

    private void refrescarTabla() {
        tb_listaFacturas.setModel(new FacturasCambioTableModel(manejador.getListaFacturas()));
    }

    private void accionIrADetalleDeFactura() {
        contenedor.setVisible(false);
        JOperacionesTarjeta.crearVentanaPagarLetra();
        limpiarFormulario();

    }

    private void addFunctionsKeys() {
        KeyStroke f2 = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        Action listenerf2 = new AbstractAction() {

            public void actionPerformed(ActionEvent ae) {

                b_volverActionPerformed(ae);
            }
        };
        addHotKey(f2, "IdentClientF12", listenerf2);
    }

    private void eliminaSeleccionTabla() {
        ListSelectionModel selectionModel = tb_listaFacturas.getSelectionModel();
        selectionModel.clearSelection();
    }

    private void accionIrAtras() {
        cerrarVentana();
        JPrincipal.getInstance().crearVentanaMenuTarjetas();
    }

    private void inicializaValidacion() {
        t_numero_factura.addValidador(new ValidadorTexto(3, true), this);
    }

    @Override
    public void addError(ValidationFormException e) {
        lb_error.setText(e.getMessage());
    }

    @Override
    public void clearError() {
        lb_error.setText("");
    }
}
